/**
 * Renders the curated Master Gap Ledger (`docs/master-gap-ledger.source.ts`) to
 * `docs/generated/master-gap-ledger.{json,md}`. Run via `npm run gap:ledger`;
 * the outputs are committed and guarded by check:generated-docs.
 */

import { writeFileSync } from 'node:fs';
import path from 'node:path';

import {
  MASTER_GAP_LEDGER,
  type GapLedgerItem,
  type LedgerStatus,
} from '../../docs/master-gap-ledger.source';

const projectRoot = process.cwd();
const generatedAt = new Date().toISOString();

const STATUS_ORDER: LedgerStatus[] = ['done', 'in-progress', 'pending', 'missing', 'blocked'];
const PHASE_TITLES: Record<number, string> = {
  0: 'Phase 0 — Ground truth & instruments',
  1: 'Phase 1 — Denominator A (content)',
  2: 'Phase 2 — Architecture spine (RFC 003)',
  3: 'Phase 3 — Denominator B (engine-math wiring)',
  4: 'Phase 4 — Cross-system parity & UX',
  5: 'Phase 5 — Production hardening',
  6: 'Phase 6 — Roadmap expansions',
  7: 'Phase 7 — Release',
};

function countBy<K extends string>(items: readonly GapLedgerItem[], key: (i: GapLedgerItem) => K) {
  const out: Record<string, number> = {};
  for (const item of items) {
    const k = key(item);
    out[k] = (out[k] ?? 0) + 1;
  }
  return out;
}

const byStatus = countBy(MASTER_GAP_LEDGER, (i) => i.status);
const byPhase = countBy(MASTER_GAP_LEDGER, (i) => String(i.phase));
const byTrack = countBy(MASTER_GAP_LEDGER, (i) => i.track);
const launchBlockers = MASTER_GAP_LEDGER.filter((i) => i.tags.includes('launch-blocker'));
const legalBlocking = MASTER_GAP_LEDGER.filter((i) => i.tags.includes('legal-blocking'));

const summary = {
  total: MASTER_GAP_LEDGER.length,
  byStatus,
  byPhase,
  byTrack,
  launchBlockers: launchBlockers.map((i) => ({ id: i.id, status: i.status, title: i.title })),
  legalBlocking: legalBlocking.map((i) => ({ id: i.id, status: i.status, title: i.title })),
};

// ── JSON ────────────────────────────────────────────────────────────────────
const json = { generatedAt, summary, items: MASTER_GAP_LEDGER };
writeFileSync(
  path.join(projectRoot, 'docs/generated/master-gap-ledger.json'),
  `${JSON.stringify(json, null, 2)}\n`,
  'utf8'
);

// ── Markdown ──────────────────────────────────────────────────────────────────
function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

const lines: string[] = [];
lines.push('# Master Gap Ledger');
lines.push('');
lines.push(
  '_Source: `docs/master-gap-ledger.source.ts` — regenerate with `npm run gap:ledger`; do not edit this file by hand._'
);
lines.push(`_Generated: ${generatedAt}_`);
lines.push('');
lines.push(
  'The authoritative per-phase work-list toward the two-denominator, hardened, ' +
    'doc-true product. Status is conservative — `done` requires an artifact the ' +
    'producer cannot edit (a gate, a generated number, a committed diff).'
);
lines.push('');

lines.push('## Summary');
lines.push('');
lines.push(`- **Items:** ${summary.total}`);
lines.push(
  `- **By status:** ${STATUS_ORDER.filter((s) => byStatus[s])
    .map((s) => `${s} ${byStatus[s]}`)
    .join(' · ')}`
);
lines.push(
  `- **Launch-blockers:** ${launchBlockers.length} (${launchBlockers.filter((i) => i.status === 'done').length} done)`
);
lines.push('');
lines.push('### Launch-blocker pack');
lines.push('');
lines.push('| Status | Item |');
lines.push('| --- | --- |');
for (const item of launchBlockers) {
  lines.push(`| ${item.status} | ${escapeCell(item.title)} |`);
}
lines.push('');

const phases = [...new Set(MASTER_GAP_LEDGER.map((i) => i.phase))].sort((a, b) => a - b);
for (const phase of phases) {
  const phaseItems = MASTER_GAP_LEDGER.filter((i) => i.phase === phase).sort(
    (a, b) => STATUS_ORDER.indexOf(a.status) - STATUS_ORDER.indexOf(b.status)
  );
  lines.push(`## ${PHASE_TITLES[phase] ?? `Phase ${phase}`}`);
  lines.push('');
  lines.push('| Status | Track | Item | Detail | Tags |');
  lines.push('| --- | --- | --- | --- | --- |');
  for (const item of phaseItems) {
    lines.push(
      `| ${item.status} | ${item.track} | ${escapeCell(item.title)} | ${escapeCell(item.detail)} | ${item.tags.join(', ')} |`
    );
  }
  lines.push('');
}

writeFileSync(
  path.join(projectRoot, 'docs/generated/master-gap-ledger.md'),
  `${lines.join('\n')}\n`,
  'utf8'
);

console.log(
  `Master Gap Ledger regenerated: ${summary.total} items ` +
    `(${byStatus.done ?? 0} done, ${launchBlockers.length} launch-blockers).`
);
