// GENERATED by scripts/encode-pf2e-backgrounds.mjs from Pf2eToolsOrg/Pf2eTools
// (Core Rulebook backgrounds, OGL — source:"CRB"; see docs/srd-sources.md).
// Genuine sourced backgrounds, NOT placeholders. Hand-written backgrounds in
// index.ts win on name match. Regenerate with:
//   node scripts/encode-pf2e-backgrounds.mjs

import type { Pf2eBackgroundDefinition } from '../../../../types/character-options/pf2eBackgrounds';

export const srdPf2eGeneratedBackgrounds: Pf2eBackgroundDefinition[] = [
  {
    id: 'pf2e-bg-animal-whisperer',
    name: 'Animal Whisperer',
    source: 'Core Rulebook',
    description:
      'You have always felt a connection to animals, and it was only a small leap to learn to train them. As you travel, you continuously encounter different creatures, befriending them along the way.',
    abilityBoosts: {
      options: ['wis', 'cha'],
      label: 'Wisdom or Charisma, plus one free',
    },
    skillTraining: 'nature',
    loreTraining: {
      options: ['plains-lore', 'swamp-lore'],
      label: 'A Lore skill such as Plains Lore or Swamp Lore',
    },
    feat: {
      id: 'train-animal',
      name: 'Train Animal',
      type: 'skill',
      description: 'Granted by the Animal Whisperer background.',
    },
  },
  {
    id: 'pf2e-bg-artisan',
    name: 'Artisan',
    source: 'Core Rulebook',
    description:
      "As an apprentice, you practiced a particular form of building or crafting, developing specialized skill. You might have been a blacksmith's apprentice toiling over the forge for countless hours, a young tailor sewing garments of all kinds, or a shipwright shaping the hulls of ships.",
    abilityBoosts: {
      options: ['str', 'int'],
      label: 'Strength or Intelligence, plus one free',
    },
    skillTraining: 'crafting',
    loreTraining: 'guild-lore',
    feat: {
      id: 'specialty-crafting',
      name: 'Specialty Crafting',
      type: 'skill',
      description: 'Granted by the Artisan background.',
    },
  },
  {
    id: 'pf2e-bg-barrister',
    name: 'Barrister',
    source: 'Core Rulebook',
    description:
      "Piles of legal manuals, stern teachers, and experience in the courtroom have instructed you in legal matters. You're capable of mounting a prosecution or defense in court, and you tend to keep abreast of local laws, as you never can tell when you might need to know them on short notice.",
    abilityBoosts: {
      options: ['int', 'cha'],
      label: 'Intelligence or Charisma, plus one free',
    },
    skillTraining: 'diplomacy',
    loreTraining: 'legal-lore',
    feat: {
      id: 'group-impression',
      name: 'Group Impression',
      type: 'skill',
      description: 'Granted by the Barrister background.',
    },
  },
  {
    id: 'pf2e-bg-bounty-hunter',
    name: 'Bounty Hunter',
    source: 'Core Rulebook',
    description:
      'Bringing in lawbreakers lined your pockets. Maybe you had an altruistic motive and sought to bring in criminals to make the streets safer, or maybe the coin was motivation enough. Your techniques for hunting down criminals transfer easily to the life of an adventurer.',
    abilityBoosts: {
      options: ['str', 'wis'],
      label: 'Strength or Wisdom, plus one free',
    },
    skillTraining: 'survival',
    loreTraining: 'legal-lore',
    feat: {
      id: 'experienced-tracker',
      name: 'Experienced Tracker',
      type: 'skill',
      description: 'Granted by the Bounty Hunter background.',
    },
  },
  {
    id: 'pf2e-bg-charlatan',
    name: 'Charlatan',
    source: 'Core Rulebook',
    description:
      "You traveled from place to place, peddling false fortunes and snake oil in one town, pretending to be royalty in exile to seduce a wealthy heir in the next. Becoming an adventurer might be your next big scam or an attempt to put your talents to use for a greater cause. Perhaps it's a bit of both, as you realize that after pretending to be a hero, you've become the mask.",
    abilityBoosts: {
      options: ['int', 'cha'],
      label: 'Intelligence or Charisma, plus one free',
    },
    skillTraining: 'deception',
    loreTraining: 'underworld-lore',
    feat: {
      id: 'charming-liar',
      name: 'Charming Liar',
      type: 'skill',
      description: 'Granted by the Charlatan background.',
    },
  },
  {
    id: 'pf2e-bg-detective',
    name: 'Detective',
    source: 'Core Rulebook',
    description:
      'You solved crimes as a police inspector or took jobs for wealthy clients as a private investigator. You might have become an adventurer as part of your next big mystery, but likely it was due to the consequences or aftermath of a prior case.',
    abilityBoosts: {
      options: ['int', 'wis'],
      label: 'Intelligence or Wisdom, plus one free',
    },
    skillTraining: 'society',
    loreTraining: 'underworld-lore',
    feat: {
      id: 'streetwise',
      name: 'Streetwise',
      type: 'skill',
      description: 'Granted by the Detective background.',
    },
  },
  {
    id: 'pf2e-bg-entertainer',
    name: 'Entertainer',
    source: 'Core Rulebook',
    description:
      'Through an education in the arts or sheer dogged practice, you learned to entertain crowds. You might have been an actor, a dancer, a musician, a street magician, or any other sort of performer.',
    abilityBoosts: {
      options: ['dex', 'cha'],
      label: 'Dexterity or Charisma, plus one free',
    },
    skillTraining: 'performance',
    loreTraining: 'theater-lore',
    feat: {
      id: 'fascinating-performance',
      name: 'Fascinating Performance',
      type: 'skill',
      description: 'Granted by the Entertainer background.',
    },
  },
  {
    id: 'pf2e-bg-field-medic',
    name: 'Field Medic',
    source: 'Core Rulebook',
    description:
      'In the chaotic rush of battle, you learned to adapt to rapidly changing conditions as you administered to battle casualties.',
    abilityBoosts: {
      options: ['con', 'wis'],
      label: 'Constitution or Wisdom, plus one free',
    },
    skillTraining: 'medicine',
    loreTraining: 'warfare-lore',
    feat: {
      id: 'battle-medicine',
      name: 'Battle Medicine',
      type: 'skill',
      description: 'Granted by the Field Medic background.',
    },
  },
  {
    id: 'pf2e-bg-fortune-teller',
    name: 'Fortune Teller',
    source: 'Core Rulebook',
    description:
      'The strands of fate are clear to you, as you have learned many traditional forms by which laypeople can divine the future.',
    abilityBoosts: {
      options: ['int', 'cha'],
      label: 'Intelligence or Charisma, plus one free',
    },
    skillTraining: 'occultism',
    loreTraining: 'fortune-telling-lore',
    feat: {
      id: 'oddity-identification',
      name: 'Oddity Identification',
      type: 'skill',
      description: 'Granted by the Fortune Teller background.',
    },
  },
  {
    id: 'pf2e-bg-gambler',
    name: 'Gambler',
    source: 'Core Rulebook',
    description:
      'The thrill of the win drew you into games of chance. This might have been a lucrative sideline that paled in comparison to the real risks of adventuring, or you might have fallen on hard times due to your gambling and pursued adventuring as a way out of a spiral.',
    abilityBoosts: {
      options: ['dex', 'cha'],
      label: 'Dexterity or Charisma, plus one free',
    },
    skillTraining: 'deception',
    loreTraining: 'games-lore',
    feat: {
      id: 'lie-to-me',
      name: 'Lie to Me',
      type: 'skill',
      description: 'Granted by the Gambler background.',
    },
  },
  {
    id: 'pf2e-bg-gladiator',
    name: 'Gladiator',
    source: 'Core Rulebook',
    description: 'The bloody games of the arena taught you the art of combat.',
    abilityBoosts: {
      options: ['str', 'cha'],
      label: 'Strength or Charisma, plus one free',
    },
    skillTraining: 'performance',
    loreTraining: 'gladiatorial-lore',
    feat: {
      id: 'impressive-performance',
      name: 'Impressive Performance',
      type: 'skill',
      description: 'Granted by the Gladiator background.',
    },
  },
  {
    id: 'pf2e-bg-hermit',
    name: 'Hermit',
    source: 'Core Rulebook',
    description:
      'In an isolated place—like a cave, remote oasis, or secluded mansion—you lived a life of solitude. Adventuring might represent your first foray out among other people in some time.',
    abilityBoosts: {
      options: ['con', 'int'],
      label: 'Constitution or Intelligence, plus one free',
    },
    skillTraining: {
      options: ['nature', 'occultism'],
      label: 'Nature or Occultism',
    },
    loreTraining: {
      options: ['cave-lore', 'desert-lore'],
      label: 'A Lore skill such as Cave Lore or Desert Lore',
    },
    feat: {
      id: 'dubious-knowledge',
      name: 'Dubious Knowledge',
      type: 'skill',
      description: 'Granted by the Hermit background.',
    },
  },
  {
    id: 'pf2e-bg-hunter',
    name: 'Hunter',
    source: 'Core Rulebook',
    description:
      'You stalked and took down animals and other creatures of the wild. Skinning animals, harvesting their flesh, and cooking them were also part of your training, all of which can give you useful resources while you adventure.',
    abilityBoosts: {
      options: ['dex', 'wis'],
      label: 'Dexterity or Wisdom, plus one free',
    },
    skillTraining: 'survival',
    loreTraining: 'tanning-lore',
    feat: {
      id: 'survey-wildlife',
      name: 'Survey Wildlife',
      type: 'skill',
      description: 'Granted by the Hunter background.',
    },
  },
  {
    id: 'pf2e-bg-martial-disciple',
    name: 'Martial Disciple',
    source: 'Core Rulebook',
    description:
      'You dedicated yourself to intense training and rigorous study to become a great warrior. The school you attended might have been a traditionalist monastery, an elite military academy, or the local branch of a prestigious mercenary organization.',
    abilityBoosts: {
      options: ['str', 'dex'],
      label: 'Strength or Dexterity, plus one free',
    },
    skillTraining: {
      options: ['acrobatics', 'athletics'],
      label: 'Acrobatics or Athletics',
    },
    loreTraining: 'warfare-lore',
    feat: {
      id: 'cat-fall',
      name: 'Cat Fall or Quick Jump',
      type: 'skill',
      description: 'Granted by the Martial Disciple background (depending on your chosen skill).',
    },
  },
  {
    id: 'pf2e-bg-merchant',
    name: 'Merchant',
    source: 'Core Rulebook',
    description:
      'In a dusty shop, market stall, or merchant caravan, you bartered wares for coin and trade goods. The skills you picked up still apply in the adventuring life, in which a good deal on a suit of armor could prevent your death.',
    abilityBoosts: {
      options: ['int', 'cha'],
      label: 'Intelligence or Charisma, plus one free',
    },
    skillTraining: 'diplomacy',
    loreTraining: 'mercantile-lore',
    feat: {
      id: 'bargain-hunter',
      name: 'Bargain Hunter',
      type: 'skill',
      description: 'Granted by the Merchant background.',
    },
  },
  {
    id: 'pf2e-bg-miner',
    name: 'Miner',
    source: 'Core Rulebook',
    description:
      "You earned a living wrenching precious minerals from the lightless depths of the earth. Adventuring might have seemed lucrative or glamorous compared to this backbreaking labor—and if you have to head back underground, this time you plan to do so armed with a real weapon instead of a miner's pick.",
    abilityBoosts: {
      options: ['str', 'wis'],
      label: 'Strength or Wisdom, plus one free',
    },
    skillTraining: 'survival',
    loreTraining: 'mining-lore',
    feat: {
      id: 'terrain-expertise',
      name: 'Terrain Expertise',
      type: 'skill',
      description: 'Granted by the Miner background.',
    },
  },
  {
    id: 'pf2e-bg-nomad',
    name: 'Nomad',
    source: 'Core Rulebook',
    description:
      'Traveling far and wide, you picked up basic tactics for surviving on the road and in unknown lands, getting by with few supplies and even fewer comforts. As an adventurer, you travel still, often into even more dangerous places.',
    abilityBoosts: {
      options: ['con', 'wis'],
      label: 'Constitution or Wisdom, plus one free',
    },
    skillTraining: 'survival',
    loreTraining: {
      options: ['desert-lore', 'swamp-lore'],
      label: 'A Lore skill such as Desert Lore or Swamp Lore',
    },
    feat: {
      id: 'assurance',
      name: 'Assurance',
      type: 'skill',
      description: 'Granted by the Nomad background.',
    },
  },
  {
    id: 'pf2e-bg-prisoner',
    name: 'Prisoner',
    source: 'Core Rulebook',
    description:
      'You might have been imprisoned for crimes (whether you were guilty or not), or enslaved for some part of your upbringing.',
    abilityBoosts: {
      options: ['str', 'con'],
      label: 'Strength or Constitution, plus one free',
    },
    skillTraining: 'stealth',
    loreTraining: 'underworld-lore',
    feat: {
      id: 'experienced-smuggler',
      name: 'Experienced Smuggler',
      type: 'skill',
      description: 'Granted by the Prisoner background.',
    },
  },
  {
    id: 'pf2e-bg-tinker',
    name: 'Tinker',
    source: 'Core Rulebook',
    description:
      "Creating all sorts of minor inventions scratches your itch for problem-solving. Your engineering skills take a particularly creative bent, and no one know what you'll come up with next.",
    abilityBoosts: {
      options: ['dex', 'int'],
      label: 'Dexterity or Intelligence, plus one free',
    },
    skillTraining: 'crafting',
    loreTraining: 'engineering-lore',
    feat: {
      id: 'specialty-crafting',
      name: 'Specialty Crafting',
      type: 'skill',
      description: 'Granted by the Tinker background.',
    },
  },
];
