// GENERATED by scripts/encode-dh-environments.mjs from
// Batres3/daggerheart-srd (Daggerheart SRD 1.0, DPCGL — see
// docs/srd-sources.md). Regenerate per the script header.

import { DaggerheartEnvironment } from './index';

export const daggerheartTier4Environments: DaggerheartEnvironment[] = [
  {
    id: 'chaos-realm',
    name: 'Chaos Realm',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    type: 'Traversal',
    description: 'An otherworldly space where the laws of reality are unstable and dangerous.',
    impulses: 'Annihilate certainty, consume power, defy logic',
    difficulty: 20,
    potentialAdversaries: 'Outer Realms Monstrosities (Abomination, Corruptor, Thrall)',
    features: [
      {
        name: 'Impossible Architecture - Passive',
        description:
          'Up is down, down is right, right is a stairway. Gravity and directionality themselves are in flux, and any attempt to move through this realm is an odyssey unto itself, requiring a Progress Countdown (8). On a failure, a PC must mark a Stress in addition to the roll’s other consequences.\\n\\n  *What does it feel like to move in a space so alien to the Mortal Realm? What landmark or point do you fixate on to maintain your balance? What bizarre landmarks do you traverse on your journey?*',
      },
      {
        name: 'Everything You Are This Place Will Take from You - Action',
        description:
          'Countdown (Loop 14). Activate the countdown. When it triggers, all PCs must succeed on a Presence Reaction Roll or their highest trait is temporarily reduced by 1d4 unless they mark a number of Stress equal to its value. Any lost trait points are regained if the PC critically succeeds or escapes the Chaos Realm.\\n\\n  *How does this place try to steal from you that which makes you legendary? What does it feel like to have this power taken from you?*',
      },
      {
        name: 'Unmake - Action',
        description:
          'On a failure, they take 4d10 direct magic damage. On a success, they must mark a Stress.\\n\\n  *What glimpse of other worlds do you catch while this place tries to unmake you? What core facet of your personality does the unmaking try to erase?*',
      },
      {
        name: 'Outer Realms Predators - Action',
        description:
          'Spend a Fear to summon an Outer Realms Abomination, an Outer Realms Corruptor, and 2d6 Outer Realms Thralls, who appear at Close range of a chosen PC in defiance of logic and causality. Immediately spotlight one of these adversaries, and you can spend an additional Fear to automatically succeed on that adversary’s standard attack.\\n\\n  *What half-consumed remnants of the shattered soul do these monstrosities cast aside in pursuit of living flesh? What jagged reflections of former personhood do you catch between moments of unquenching malice?*',
      },
      {
        name: 'Disorienting Reality - Reaction',
        description:
          'On a result with Fear, you can ask the PC to describe which of their fears the Chaos Realm evokes as a vision of reality unmakes and reconstitutes itself to the PC. The PC loses a Hope. If it is their last Hope, you gain a Fear.\\n\\n  *What moment do they see? If it’s a memory, how is it usurped by this place? How hard will it be to hold on to the real memory?*',
      },
    ],
  },
  {
    id: 'divine-usurpation',
    name: 'Divine Usurpation',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    type: 'Event',
    description:
      'A massive ritual designed to breach the gates of the Hallows Above and unseat the New Gods themselves.',
    impulses: 'Collect power, overawe, silence dissent',
    difficulty: 20,
    potentialAdversaries:
      'Arch-Necromancer, Fallen Shock Troops, Mortal Hunter, Oracle of Doom, Perfected Zombie',
    features: [
      {
        name: 'Final Preparations - Passive',
        description:
          'When the environment first takes the spotlight, designate one adversary as the Usurper seeking to overthrow the gods. Activate a Long-Term Countdown (8) as the Usurper assembles what they need to conduct the ritual. When it triggers, spotlight this environment to use the “Beginning of the End” feature. While this environment remains in play, you can hold up to 15 Fear.\\n\\n  *What does the Usurper still require: The heart of a High Seraph? The last notes of an ancient vignette? The loyalty of two archenemies? The heartbroken tears of a pure soul?*',
      },
      {
        name: 'Divine Blessing - Passive',
        description:
          'When a PC critically succeeds, they can spend 2 Hope to refresh an ability normally limited by uses (such as once per rest, once per session).\\n\\n  *What god favors you as you fight against this usurpation? How does your renewed power reflect their influence?*',
      },
      {
        name: 'Defiers Abound - Action',
        description:
          'Spend 2 Fear to summon 1d4+2 Fallen Shock Troops that appear within Close range of the Usurper to assist their divine siege. Immediately spotlight the Shock Troops to use a “Group Attack” action.\\n\\n  *Which High Fallen do these troops serve? Which god’s flesh do they wish to feast upon?*',
      },
      {
        name: 'Godslayer - Action',
        description:
          'If the Divine Siege Countdown (see “Beginning of the End”) has triggered, you can spend 3 Fear to describe the Usurper slaying one of the gods of the Hallows Above, feasting upon their power and growing stronger. The Usurper clears 2 HP. Increase their Difficulty, damage, attack modifier, or give them a new feature from the slain god.\\n\\n  *Which god meets their end? What are their last words? How does the Usurper’s new stolen power manifest?*',
      },
      {
        name: 'Beginning of the End - Reaction',
        description:
          'When the “Final Preparations” long-term countdown triggers, the Usurper begins hammering on the gates of the Hallows themselves. Activate a Divine Siege Countdown (10). Spotlight the Usurper to describe the Usurper’s assault and tick down this countdown by 1. If the Usurper takes Major or greater damage, tick up the countdown by 1. When it triggers, the Usurper shatters the barrier between the Mortal Realm and the Hallows Above to slay the gods and take their place. You gain a Fear for each unmarked HP the Usurper has. You can immediately use the “Godslayer” feature without spending Fear to make an additional GM move.\\n\\n  *How does the Mortal Realm writhe as the natural order is violated? What mortals witness this blasphemy from afar?*',
      },
      {
        name: 'Ritual Nexus - Reaction',
        description:
          'On any failure with Fear against the Usurper, the PC must mark 1d4 Stress from the backlash of magical power.\\n\\n  *What visions of failures past torment you as your efforts fall short? How are these memories twisted by the Usurper?*',
      },
    ],
  },
  {
    id: 'imperial-court',
    name: 'Imperial Court',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    type: 'Social',
    description:
      'The dazzling mansion of a powerful empire, lavishly appointed with stolen treasures.',
    impulses:
      'Justify and perpetuate imperial rule, seduce rivals with promises of power and comfort',
    difficulty: 20,
    potentialAdversaries: 'Bladed Guard, Courtesan, Knight of the Realm, Monarch, Spy',
    features: [
      {
        name: 'All Roads Lead Here - Passive',
        description:
          'While in the Imperial Court, a PC has disadvantage on Presence Rolls made to take actions that don’t fit the imperial way of life or support the empire’s dominance.\\n\\n  *How does the way language is used make even discussing alternative ways of living difficult? What obvious benefits for loyalty create friction when you try to discuss alternatives?*',
      },
      {
        name: 'Rival Vassals - Passive',
        description:
          'The PCs can find imperial subjects, vassals, and supplicants in the court, each vying for favor, seeking proximity to power, exchanging favors for loyalty, and elevating their status above others. Some might be desperate to undermine their rivals, while others might even be open to discussions that verge on sedition.\\n\\n  *How do they benefit from vassalage, and what has it cost them? What exploitation drives them to consider opposing the unstoppable?*',
      },
      {
        name: 'The Gravity of Empire - Action',
        description:
          'Spend a Fear to present a PC with a golden opportunity or offer to satisfy a major goal in exchange for obeying or supporting the empire. The target must make a Presence Reaction Roll. On a failure, they must mark all their Stress or accept the offer. If they have already marked all their Stress, they must reduce their Stress track by 1d4. On a success, they must mark 1d4 Stress as they’re taxed by temptation.\\n\\n  *What do the PCs want so desperately they might consider throwing in with this ruthless power? How did imperial agents learn the PC’s greatest desires?*',
      },
      {
        name: 'Imperial Decree - Action',
        description:
          'Spend a Fear to tick down a long-term countdown related to the empire’s agenda by 1d4. If this triggers the countdown, a proclamation related to the agenda is announced at court as the plan is executed.\\n\\n  *What display of power or transfer of wealth was needed to expedite this plan? Whose lives were disrupted or upended to make this happen?*',
      },
      {
        name: 'Eyes Everywhere - Reaction',
        description:
          'On a result with Fear, you can spend a Fear to have someone loyal to the empire overhear seditious talk within the court. A PC must succeed on an Instinct Reaction Roll to notice that the group has been overheard so they can try to intercept the witness before the PCs are exposed.\\n\\n  *How has the empire compromised this witness? Why is their first impulse to protect the empire, even if doesn’t treat them well?*',
      },
    ],
  },
  {
    id: 'necromancer-s-ossuary',
    name: "Necromancer's Ossuary",
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    type: 'Exploration',
    description:
      'A dusty crypt with a library, twisting corridors, and abundant sarcophagi; spattered with the blood of ill-fated invaders.',
    impulses:
      'Confound intruders, delve into secrets best left buried, manifest unlife, unleash a tide of undead',
    difficulty: 19,
    potentialAdversaries: 'Arch-Necromancer’s Host (Perfected Zombie, Zombie Legion)',
    features: [
      {
        name: 'No Place for the Living - Passive',
        description:
          'A feature or action that clears HP requires spending a Hope to use. If it already costs Hope, a PC must spend an additional Hope.\\n\\n  *What does it feel like to try to heal in a place so antithetical to life?*',
      },
      {
        name: 'Centuries of Knowledge - Passive',
        description:
          'A PC can investigate the library and laboratory and make a Knowledge Roll to learn information related to arcana, local history, and the Necromancer’s plans.\\n\\n  *What are the names of the tomes? What project is the necromancer working on and what does it communicate about their plans?*',
      },
      {
        name: 'Skeletal Burst - Action',
        description:
          'All targets within Close range of a point you choose in this environment must succeed on an Agility Reaction Roll or take 4d8+8 physical damage from bone shrapnel as part of the ossuary detonates around them.\\n\\n  *What ancient skeletal architecture is destroyed? What bones stick in your armor?*',
      },
      {
        name: 'Aura of Death - Action',
        description:
          'Once per scene, roll a d4. Each undead within Far range of the Necromancer can clear HP and Stress equal to the result rolled. The undead can choose how that total number is divided between HP and Stress.\\n\\n  *How does the power manifest? Do the undead look more lifelike or, paradoxically, are they more decayed but vigorous?*',
      },
      {
        name: 'They Just Keep Coming! - Action',
        description:
          'Spend a Fear to summon 1d6 Rotted Zombies, two Perfected Zombies, or a Zombie Legion, who appear at Close range of a chosen PC.\\n\\n  *Who were these people before they became the necromancer’s pawns? What vestiges of those lives remain for the heroes to see?*',
      },
    ],
  },
];
