// GENERATED by scripts/encode-dh-environments.mjs from
// Batres3/daggerheart-srd (Daggerheart SRD 1.0, DPCGL — see
// docs/srd-sources.md). Regenerate per the script header.

import { DaggerheartEnvironment } from './index';

export const daggerheartTier2Environments: DaggerheartEnvironment[] = [
  {
    id: 'cult-ritual',
    name: 'Cult Ritual',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    type: 'Event',
    description:
      'A fallen cult assembles around a sigil of the defeated gods and a bonfire that burns a sickly shade of green.',
    impulses: 'Profane the land, unite the Mortal Realm with the Circles Below',
    difficulty: 14,
    potentialAdversaries:
      'Cult of the Fallen (Cult Adept, Cult Fang, Cult Initiate, Secret-Keeper)',
    features: [
      {
        name: 'Desecrated Ground - Passive',
        description:
          'Cultists dedicated this place to the Fallen Gods, and their foul influence seeps into it. Reduce the PCs’ Hope Die to a d10 while in this environment. The desecration can be removed with a Progress Countdown (6).\\n\\n  *How do the PCs first notice that something is wrong about this place? What fears resurface while hope is kept at bay?*',
      },
      {
        name: 'Blasphemous Might - Action',
        description:
          'A portion of the ritual’s power is diverted into a cult member to fight off interlopers. Choose one adversary to become Imbued with terrible magic until the scene ends or they’re defeated. An Imbued adversary immediately takes the spotlight and gains one of the following benefits, or all three if you spend a Fear:\\n\\n  - They gain advantage on all attacks.\\n  - They deal an extra 1d10 damage on a successful attack.\\n  - They gain the following feature:\\n    Relentless (2) - Passive: This adversary can be spotlighted multiple times per GM turn. Spend Fear as usual to spotlight them.\\n\\n  *How does the enemy change in appearance? What fears do their blows bring to the surface?*',
      },
      {
        name: 'The Summoning - Reaction',
        description:
          'Countdown (6). When the PCs enter the scene or the cult begins the ritual to summon a demon, activate the countdown. Designate one adversary to lead the ritual. The countdown ticks down when a PC rolls with Fear. When it triggers, summon a Minor Demon within Very Close range of the ritual’s leader. If the leader is defeated, the countdown ends with no effect as the ritual fails.\\n\\n  *What will the cult do with this leashed demon if they succeed? What will they try to summon next?*',
      },
      {
        name: 'Complete the Ritual - Reaction',
        description:
          'If the ritual’s leader is targeted by an attack or spell, an ally within Very Close range of them can mark a Stress to be targeted by that attack or spell instead.\\n\\n  *What does it feel like to see such devotion turned to the pursuit of fear and domination?*',
      },
    ],
  },
  {
    id: 'hallowed-temple',
    name: 'Hallowed Temple',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    type: 'Social',
    description:
      'A bustling yet well-kept temple that provides healing and hosts regular services, overseen by a priest or seraph.',
    impulses:
      'Connect the Mortal Realm with the Hallows Above, display the power of the divine, provide aid and succor to the faithful',
    difficulty: 13,
    potentialAdversaries: 'Guards (Archer Guard, Bladed Guard, Head Guard)',
    features: [
      {
        name: 'A Place of Healing - Passive',
        description:
          'A PC who takes a rest in the Hallowed Temple automatically clears all HP.\\n\\n  *What does the incense smell like? What kinds of songs do the acolytes sing?*',
      },
      {
        name: 'Divine Guidance - Passive',
        description:
          'A PC who prays to a deity while in the Hallowed Temple can make an Instinct Roll to receive answers. If the god they beseech isn’t welcome in this temple, roll this made with disadvantage.\\n\\n  - Critical Success: The PC gains clear information. Additionally, they gain 1d4 Hope, which can be distributed between the party if they share the vision and guidance they received.\\n  - Success with Hope: The PC receives clear information.\\n  - Success with Fear: The PC receives brief flashes of insight and an emotional impression conveying an answer.\\n  - Any Failure: The PC receives only vague flashes. They can mark a Stress to receive one clear image without context.\\n\\n  *What does it feel like as you are touched by this vision? What feeling lingers after the images have passed?*',
      },
      {
        name: 'Restless Hope - Reaction',
        description:
          'Once per scene, each PC can mark a Stress to turn a result with Fear into a result with Hope.\\n\\n  *What emotions or memories do you connect with when fear presses in?*',
      },
      {
        name: 'Divine Censure - Reaction',
        description:
          'When the PCs have trespassed, blasphemed, or offended the clergy, you can spend a Fear to summon a High Seraph and 1d4 Bladed Guards within Close range of the senior priest to reinforce their will.\\n\\n  *What symbols or icons do they bear that signal they are anointed agents of the divinity? Who leads the group and what led them to this calling?*',
      },
    ],
  },
  {
    id: 'haunted-city',
    name: 'Haunted City',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    type: 'Exploration',
    description: 'An abandoned city populated by the restless spirits of eras past.',
    impulses: 'Misdirect and disorient, replay apocalypses both public and personal',
    difficulty: 14,
    potentialAdversaries:
      'Ghosts (Spectral Archer, Spectral Captain, Spectral Guardian), (ghostly versions of other adversaries (see “Ghostly Form”))',
    features: [
      {
        name: 'Buried Knowledge - Passive',
        description:
          'The city has countless mysteries to unfold. A PC who seeks knowledge about the fallen city can make an Instinct or Knowledge Roll to learn about this place and discover (potentially haunted) loot.\\n\\n  - Critical Success: Gain valuable information and a related useful item.\\n  - Success with Hope: Gain valuable information.\\n  - Success with Fear: Uncover vague or incomplete information.\\n  - Any Failure: Mark a Stress to find a lead after an exhaustive search.\\n\\n  *What secret secrets does the city contain? Why have so many ghosts lingered here? What doomed adventurers have met a bad fate here already?*',
      },
      {
        name: 'Ghostly Form - Passive',
        description:
          'Adversaries who appear here are of a ghostly form. They have resistance to physical damage and can mark a Stress to move up to Close range through solid objects.\\n\\n  *What injuries to their physical form speak to their cause of death? What unfulfilled purpose holds them in the Mortal Plane?*',
      },
      {
        name: 'Dead Ends - Action',
        description:
          'The ghosts of an earlier era manifest scenes from the past, such as a street festival, a city council, or a heist. These hauntings change the layout of the city around the PCs, blocking the way behind them, forcing a detour, or presenting them with a challenge, such as mistaking them for rival thieves during the heist.\\n\\n  *What do the ghosts want from you? What do you need from them?*',
      },
      {
        name: 'Apocalypse Then - Action',
        description:
          'Spend a Fear to manifest the echo of a past disaster that ravaged the city. Activate a Progress Countdown (5) as the disaster replays around the PCs. To complete the countdown and escape the catastrophe, the PCs must overcome threats such as rampaging fires, stampeding civilians, collapsing buildings, or crumbling streets, while recalling history and finding clues to escape the inevitable.\\n\\n  *Is this the disaster that led the city to be abandoned? What is known about this disaster, and how could that help the PCs escape?*',
      },
    ],
  },
  {
    id: 'mountain-pass',
    name: 'Mountain Pass',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    type: 'Traversal',
    description:
      'Stony peaks that pierce the clouds, with a twisting path winding its way up and over through many switchbacks.',
    impulses:
      'Exact a chilling toll in supplies and stamina, reveal magical slumber, slow down travel',
    difficulty: 15,
    potentialAdversaries:
      'Beasts (Bear, Giant Eagle, Glass Snake), Chaos Skull, Minotaur Wrecker, Mortal Hunter',
    features: [
      {
        name: 'Engraved Sigils - Passive',
        description:
          'Large markings and engravings have been made in the mountainside. A PC with a relevant background or Experience identifies them as weather magic increasing the power of the icy winds. A PC who succeeds on a Knowledge Roll can recall information about the sigils, potential information about their creators, and the knowledge of how to dispel them. If a PC critically succeeds, they recognize that the sigils are of a style created by highborne enchanters and they gain advantage on a roll to dispel the sigils.\\n\\n  *Who laid this enchantment? Are they nearby? Why did they want the weather to be more daunting?*',
      },
      {
        name: 'Avalanche - Action',
        description:
          'Spend a Fear to carve the mountain with an icy torrent, causing an avalanche. All PCs in its path must succeed on an Agility or Strength Reaction Roll or be bowled over and carried down the mountain. A PC using rope, pitons, or other climbing gear gains advantage on this roll. Targets who fail are knocked down the mountain to Far range, take 2d20 physical damage, and must mark a Stress. Targets who succeed must mark a Stress.\\n\\n  *How do the PCs try to weather the avalanche? What approach do they take to avoid being buried or hurtling down the mountainside?*',
      },
      {
        name: 'Raptor Nest - Reaction',
        description:
          'When the PCs enter the raptors’ hunting grounds, two Giant Eagles appear at Very Far range of a chosen PC, identifying the PCs as likely prey.\\n\\n  *How long has it been since the eagles last found prey? Do they have eggs in their nest, or unfledged young?*',
      },
      {
        name: 'Icy Winds - Reaction',
        description:
          'Countdown (Loop 4). When the PCs enter the mountain pass, activate the countdown. When it triggers, all characters traveling through the pass must succeed on a Strength Reaction Roll or mark a Stress. A PC wearing clothes appropriate for extreme cold gains advantage on these rolls.\\n\\n  *What parts of the PCs’ bodies go numb first? How do they try to keep warm as they press forward?*',
      },
    ],
  },
];
