// GENERATED by scripts/encode-35e-spells.mjs from olimot/srd-v3.5-md
// (SRD 3.5 core spells, OGL — see docs/srd-sources.md). Hand-written spells
// always win on name and id match; regenerate with:
// node scripts/encode-35e-spells.mjs

import { Spell } from '../../../../types/magic/spells';

export const srd35eCantrips: Spell[] = [
  {
    id: 'lullaby-35e',
    name: 'Lullaby',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/lullaby.htm',
    level: 0,
    school: 'enchantment',
    subschool: 'Compulsion',
    descriptors: ['Mind-Affecting'],
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'medium',
      feet: 100,
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    duration: {
      type: 'concentration',
      maxDuration: 'Concentration + 1 round/level (D)',
    },
    area: 'Living creatures within a 10-ft.-radius burst',
    savingThrowText: 'Will negates',
    spellResistance: true,
    concentration: true,
    ritual: false,
    description:
      'Any creature within the area that fails a Will save becomes drowsy and inattentive, taking a –5 penalty on Listen and Spot checks and a –2 penalty on Will saves against sleep effects while the lullaby is in effect. Lullaby lasts for as long as the caster concentrates, plus up to 1 round per caster level thereafter.',
    classes: ['bard'],
    levelsByClass: {
      bard: 0,
    },
  },
  {
    id: 'mage-hand-35e',
    name: 'Mage Hand',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/mageHand.htm',
    level: 0,
    school: 'transmutation',
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'close',
      feet: 25,
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    duration: {
      type: 'concentration',
      maxDuration: 'Concentration',
    },
    target: 'One nonmagical, unattended object weighing up to 5 lb.',
    savingThrowText: 'None',
    spellResistance: false,
    concentration: true,
    ritual: false,
    description:
      'You point your finger at an object and can lift it and move it at will from a distance. As a move action, you can propel the object as far as 15 feet in any direction, though the spell ends if the distance between you and the object ever exceeds the spell’s range.',
    classes: ['bard', 'sorcerer', 'wizard'],
    levelsByClass: {
      bard: 0,
      sorcerer: 0,
      wizard: 0,
    },
  },
  {
    id: 'message-35e',
    name: 'Message',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/message.htm',
    level: 0,
    school: 'transmutation',
    descriptors: ['Language-Dependent'],
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'medium',
      feet: 100,
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
      focus: true,
    },
    duration: {
      type: 'minutes-per-level',
      minutes: 10,
    },
    target: 'One creature/level',
    savingThrowText: 'None',
    spellResistance: false,
    concentration: false,
    ritual: false,
    description:
      'You can whisper messages and receive whispered replies with little chance of being overheard. You point your finger at each creature you want to receive the message. When you whisper, the whispered message is audible to all targeted creatures within range. Magical silence, 1 foot of stone, 1 inch of common metal (or a thin sheet of lead), or 3 feet of wood or dirt blocks the spell. The message does not have to travel in a straight line. It can circumvent a barrier if there is an open path between you and the subject, and the path’s entire length lies within the spell’s range. The creatures that receive the message can whisper a reply that you hear. The spell transmits sound, not meaning. It doesn’t transcend language barriers.\n\nNote: To speak a message, you must mouth the words and whisper, possibly allowing observers the opportunity to read your lips.\n\nFocus: A short piece of copper wire.',
    classes: ['bard', 'sorcerer', 'wizard'],
    levelsByClass: {
      bard: 0,
      sorcerer: 0,
      wizard: 0,
    },
  },
  {
    id: 'open-close-35e',
    name: 'Open/Close',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/openClose.htm',
    level: 0,
    school: 'transmutation',
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'close',
      feet: 25,
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
      focus: true,
    },
    duration: {
      type: 'instant',
    },
    target: 'Object weighing up to 30 lb. or portal that can be opened or closed',
    savingThrowText: 'Will negates (object)',
    spellResistance: true,
    concentration: false,
    ritual: false,
    description:
      'You can open or close (your choice) a door, chest, box, window, bag, pouch, bottle, barrel, or other container. If anything resists this activity (such as a bar on a door or a lock on a chest), the spell fails. In addition, the spell can only open and close things weighing 30 pounds or less. Thus, doors, chests, and similar objects sized for enormous creatures may be beyond this spell’s ability to affect.\n\nFocus: A brass key.',
    classes: ['bard', 'sorcerer', 'wizard'],
    levelsByClass: {
      bard: 0,
      sorcerer: 0,
      wizard: 0,
    },
  },
  {
    id: 'summon-instrument-35e',
    name: 'Summon Instrument',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/summonInstrument.htm',
    level: 0,
    school: 'conjuration',
    subschool: 'Summoning',
    castingTime: {
      type: 'rounds',
      rounds: 1,
    },
    range: {
      type: 'ranged',
      feet: 0,
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    duration: {
      type: 'minutes-per-level',
      minutes: 1,
    },
    effect: 'One summoned handheld musical instrument',
    savingThrowText: 'None',
    spellResistance: false,
    concentration: false,
    ritual: false,
    description:
      'This spell summons one handheld musical instrument of your choice. This instrument appears in your hands or at your feet (your choice). The instrument is typical for its type. Only one instrument appears per casting, and it will play only for you. You can’t summon an instrument too large to be held in two hands.',
    classes: ['bard'],
    levelsByClass: {
      bard: 0,
    },
  },
  {
    id: 'touch-of-fatigue-35e',
    name: 'Touch of Fatigue',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/touchOfFatigue.htm',
    level: 0,
    school: 'necromancy',
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'touch',
    },
    components: {
      verbal: true,
      somatic: true,
      material: true,
    },
    duration: {
      type: 'rounds-per-level',
      rounds: 1,
    },
    target: 'Creature touched',
    savingThrowText: 'Fortitude negates',
    spellResistance: true,
    concentration: false,
    ritual: false,
    description:
      'You channel negative energy through your touch, fatiguing the target. You must succeed on a touch attack to strike a target.\n\nThe subject is immediately fatigued for the spell’s duration.\n\nThis spell has no effect on a creature that is already fatigued. Unlike with normal fatigue, the effect ends as soon as the spell’s duration expires.\n\nMaterial Component: A drop of sweat.',
    classes: ['sorcerer', 'wizard'],
    levelsByClass: {
      sorcerer: 0,
      wizard: 0,
    },
  },
];
