// GENERATED by scripts/encode-35e-spells.mjs from olimot/srd-v3.5-md
// (SRD 3.5 core spells, OGL — see docs/srd-sources.md). Hand-written spells
// always win on name and id match; regenerate with:
// node scripts/encode-35e-spells.mjs

import { Spell } from '../../../../types/magic/spells';

export const srd35eLevel9Spells: Spell[] = [
  {
    id: 'crushing-hand-35e',
    name: 'Crushing Hand',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/crushingHand.htm',
    level: 9,
    school: 'evocation',
    descriptors: ['Force'],
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'personal',
    },
    components: {
      verbal: true,
      somatic: true,
      material: true,
      focus: true,
      divineFocus: true,
    },
    duration: {
      type: 'instant',
    },
    concentration: false,
    ritual: false,
    description:
      'This spell functions like interposing hand, except that the hand can interpose itself, push, or crush one opponent that you select.\n\nThe crushing hand can grapple an opponent like grasping hand does. Its grapple bonus equals your caster level + your Intelligence, Wisdom, or Charisma modifier (for a wizard, cleric, or sorcerer, respectively), +12 for the hand’s Strength score (35), +4 for being Large. The hand deals 2d6+12 points of damage (lethal, not nonlethal) on each successful grapple check against an opponent.\n\nThe crushing hand can also interpose itself as interposing hand does, or it can bull rush an opponent as forceful hand does, but at a +18 bonus.\n\nDirecting the spell to a new target is a move action.\n\nClerics who cast this spell name it for their deities.\n\nArcane Material Component: The shell of an egg.\n\nArcane Focus: A glove of snakeskin.',
    classes: ['sorcerer', 'wizard'],
    levelsByClass: {
      sorcerer: 9,
      wizard: 9,
    },
  },
  {
    id: 'dominate-monster-35e',
    name: 'Dominate Monster',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/dominateMonster.htm',
    level: 9,
    school: 'enchantment',
    subschool: 'Compulsion',
    descriptors: ['Mind-Affecting'],
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'personal',
    },
    components: {
      verbal: false,
      somatic: false,
      material: false,
    },
    duration: {
      type: 'instant',
    },
    target: 'One creature',
    concentration: false,
    ritual: false,
    description:
      'This spell functions like dominate person, except that the spell is not restricted by creature type.',
    classes: ['sorcerer', 'wizard'],
    levelsByClass: {
      sorcerer: 9,
      wizard: 9,
    },
  },
  {
    id: 'freedom-35e',
    name: 'Freedom',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/freedom.htm',
    level: 9,
    school: 'abjuration',
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'close',
      feet: 25,
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    duration: {
      type: 'instant',
    },
    target: 'One creature',
    savingThrowText: 'Will negates (harmless)',
    spellResistance: true,
    concentration: false,
    ritual: false,
    description:
      'The subject is freed from spells and effects that restrict its movement, including binding, entangle, grappling, imprisonment, maze, paralysis, petrification, pinning, sleep, slow, stunning, temporal stasis, and web. To free a creature from imprisonment or maze, you must know its name and background, and you must cast this spell at the spot where it was entombed or banished into the maze.',
    classes: ['sorcerer', 'wizard'],
    levelsByClass: {
      sorcerer: 9,
      wizard: 9,
    },
  },
  {
    id: 'hold-monster-mass-35e',
    name: 'Hold Monster, Mass',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/holdMonsterMass.htm',
    level: 9,
    school: 'enchantment',
    subschool: 'Compulsion',
    descriptors: ['Mind-Affecting'],
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'personal',
    },
    components: {
      verbal: false,
      somatic: false,
      material: false,
    },
    duration: {
      type: 'instant',
    },
    target: 'One or more creatures, no two of which can be more than 30 ft. apart',
    concentration: false,
    ritual: false,
    description:
      'This spell functions like hold person, except that it affects multiple creatures and holds any living creature that fails its Will save.',
    classes: ['sorcerer', 'wizard'],
    levelsByClass: {
      sorcerer: 9,
      wizard: 9,
    },
  },
  {
    id: 'imprisonment-35e',
    name: 'Imprisonment',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/imprisonment.htm',
    level: 9,
    school: 'abjuration',
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'touch',
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    duration: {
      type: 'instant',
    },
    target: 'Creature touched',
    savingThrowText: 'Will negates; see text',
    spellResistance: true,
    concentration: false,
    ritual: false,
    description:
      'When you cast imprisonment and touch a creature, it is entombed in a state of suspended animation (see the temporal stasis spell) in a small sphere far beneath the surface of the earth. The subject remains there unless a freedom spell is cast at the locale where the imprisonment took place. Magical search by a crystal ball, a locate object spell, or some other similar divination does not reveal the fact that a creature is imprisoned, but discern location does. A wish or miracle spell will not free the recipient, but will reveal where it is entombed. If you know the target’s name and some facts about its life, the target takes a –4 penalty on its save.',
    classes: ['sorcerer', 'wizard'],
    levelsByClass: {
      sorcerer: 9,
      wizard: 9,
    },
  },
  {
    id: 'mage-s-disjunction-35e',
    name: 'Mage’s Disjunction',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/mageSDisjunction.htm',
    level: 9,
    school: 'abjuration',
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'close',
      feet: 25,
    },
    components: {
      verbal: true,
      somatic: false,
      material: false,
    },
    duration: {
      type: 'instant',
    },
    area: 'All magical effects and magic items within a 40-ft.-radius burst',
    savingThrowText: 'Will negates (object)',
    spellResistance: false,
    concentration: false,
    ritual: false,
    description:
      'All magical effects and magic items within the radius of the spell, except for those that you carry or touch, are disjoined. That is, spells and spell-like effects are separated into their individual components (ending the effect as a dispel magic spell does), and each permanent magic item must make a successful Will save or be turned into a normal item. An item in a creature’s possession uses its own Will save bonus or its possessor’s Will save bonus, whichever is higher.\n\nYou also have a 1% chance per caster level of destroying an antimagic field. If the antimagic field survives the disjunction, no items within it are disjoined.\n\nEven artifacts are subject to disjunction, though there is only a 1% chance per caster level of actually affecting such powerful items. Additionally, if an artifact is destroyed, you must make a DC 25 Will save or permanently lose all spellcasting abilities. (These abilities cannot be recovered by mortal magic, not even miracle or wish.)\n\nNote: Destroying artifacts is a dangerous business, and it is 95% likely to attract the attention of some powerful being who has an interest in or connection with the device.',
    classes: ['sorcerer', 'wizard'],
    levelsByClass: {
      sorcerer: 9,
      wizard: 9,
    },
  },
  {
    id: 'weird-35e',
    name: 'Weird',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    sourceUrl: 'https://www.d20srd.org/srd/spells/weird.htm',
    level: 9,
    school: 'illusion',
    subschool: 'Phantasm',
    descriptors: ['Fear', 'Mind-Affecting'],
    castingTime: {
      type: 'standard',
      amount: 1,
    },
    range: {
      type: 'personal',
    },
    components: {
      verbal: false,
      somatic: false,
      material: false,
    },
    duration: {
      type: 'instant',
    },
    target: 'Any number of creatures, no two of which can be more than 30 ft. apart',
    concentration: false,
    ritual: false,
    description:
      'This spell functions like phantasmal killer, except it can affect more than one creature. Only the affected creatures see the phantasmal creatures attacking them, though you see the attackers as shadowy shapes.\n\nIf a subject’s Fortitude save succeeds, it still takes 3d6 points of damage and is stunned for 1 round. The subject also takes 1d4 points of temporary Strength damage.',
    classes: ['sorcerer', 'wizard'],
    levelsByClass: {
      sorcerer: 9,
      wizard: 9,
    },
  },
];
