// GENERATED by scripts/encode-daggerheart-adversaries.mjs from
// Batres3/daggerheart-srd (Daggerheart SRD 1.0, DPCGL — see
// docs/srd-sources.md). Regenerate per the script header.

import { DaggerheartAdversary } from '../../../../types/daggerheart';

export const daggerheartTier2Adversaries: DaggerheartAdversary[] = [
  {
    id: 'apprentice-assassin',
    name: 'Apprentice Assassin',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Minion',
    description: 'A young trainee eager to prove themselves.',
    motivesAndTactics: 'Act reckless, kill, prove their worth, show off',
    difficulty: 13,
    hitPoints: 1,
    stress: 1,
    attackModifier: -1,
    attack: {
      name: 'Thrown Dagger',
      range: 'Very Close',
      damage: '4 phy',
    },
    experience: 'Intrusion +2',
    features: [
      {
        name: 'Minion (6) - Passive',
        description:
          'The Assassin is defeated when they take any damage. For every 6 damage a PC deals to the Assassin, defeat an additional Minion within range the attack would succeed against.',
      },
      {
        name: 'Group Attack - Action',
        description:
          'Spend a Fear to choose a target and spotlight all Apprentice Assassins within Close range of them. Those Minions move into Melee range of the target and make one shared attack roll. On a success, they deal 4 physical damage each. Combine this damage.',
      },
    ],
  },
  {
    id: 'archer-squadron',
    name: 'Archer Squadron',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Horde',
    roleDetail: '(2/HP)',
    description: 'A group of trained archers bearing massive bows.',
    motivesAndTactics: 'Stick together, survive, volley fire',
    difficulty: 13,
    thresholds: {
      major: 8,
      severe: 16,
    },
    hitPoints: 4,
    stress: 3,
    attackModifier: 0,
    attack: {
      name: 'Longbow',
      range: 'Far',
      damage: '2d6+3 phy',
    },
    features: [
      {
        name: 'Horde (1d6+3) - Passive',
        description:
          'When the Squadron has marked half or more of their HP, their standard attack deals 1d6+3 physical damage instead.',
      },
      {
        name: 'Focused Volley - Action',
        description:
          'Spend a Fear to target a point within Far range. Make an attack with advantage against all targets within Close range of that point. Targets the Squadron succeeds against take 1d10+4 physical damage.',
      },
      {
        name: 'Suppressing Fire - Action',
        description:
          'Mark a Stress to target a point within Far range. Until the next roll with Fear, a creature who moves within Close range of that point must make an Agility Reaction Roll. On a failure, they take 2d6+3 physical damage. On a success, they take half damage.',
      },
    ],
  },
  {
    id: 'assassin-poisoner',
    name: 'Assassin Poisoner',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Skulk',
    description: 'A cunning scoundrel skilled in both poisons and ambushing.',
    motivesAndTactics: 'Anticipate, get paid, kill, taint food and water',
    difficulty: 14,
    thresholds: {
      major: 8,
      severe: 16,
    },
    hitPoints: 4,
    stress: 4,
    attackModifier: 3,
    attack: {
      name: 'Poisoned Throwing Dagger',
      range: 'Close',
      damage: '2d8+1 phy',
    },
    experience: 'Intrusion +2',
    features: [
      {
        name: 'Grindeloth Venom - Passive',
        description:
          'Targets who mark HP from the Assassin’s attacks are Vulnerable until they clear a HP.',
      },
      {
        name: 'Out of Nowhere - Passive',
        description: 'The Assassin has advantage on attacks if they are Hidden.',
      },
      {
        name: 'Fumigation - Action',
        description:
          'Drop a smoke bomb that fills the air within Close range with smoke, Dizzilying all targets in this area. Dizzied targets have disadvantage on their next action roll, then clear the condition.',
      },
    ],
  },
  {
    id: 'battle-box',
    name: 'Battle Box',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Solo',
    description: 'A cube-shaped construct with a different rune on each of their six sides.',
    motivesAndTactics: 'Change tactics, trample foes, wait in disguise',
    difficulty: 15,
    thresholds: {
      major: 10,
      severe: 20,
    },
    hitPoints: 8,
    stress: 6,
    attackModifier: 2,
    attack: {
      name: 'Slam',
      range: 'Melee',
      damage: '2d6+3 phy',
    },
    experience: 'Camouflage +2',
    features: [
      {
        name: 'Relentless (2) - Passive',
        description:
          'The Box can be spotlighted up to two times per turn. Spend Fear as usual to spotlight them.',
      },
      {
        name: 'Randomized Tactics - Action',
        description:
          'Mark a Stress and roll a d6. The Box uses the corresponding move: 1. Mana Beam: The Box fires a searing beam. Make an attack against a target within Far range. On a success, deal 2d10+2 magic damage. 2. Fire Jets: The Box shoots into the air, spinning and releasing jets of flame. Make an attack against all targets within Close range. Targets the Box succeeds against take 2d8 physical damage. 3. Trample: The Box rockets around erratically. Make an attack against all PCs within Close range. Targets the Box succeeds against take 1d6+5 physical damage and are Vulnerable until their next roll with Hope. 4. Shocking Gas: The Box sprays out a silver gas sparking with lightning. All targets within Close range must succeed on a Finesse Reaction Roll or mark 3 Stress. 5. Stunning Clap: The Box leaps and their sides clap, creating a concussive boom. All targets within Very Close range must succeed on a Strength Reaction Roll or become Vulnerable until the cube is defeated. 6. Psonic Whine: The Box releases a cluster of mechanical bees whose buzz rattles mortal minds. All targets within Close range must succeed on a Presence Reaction Roll or take 2d4+9 direct magic damage.',
      },
      {
        name: 'Overcharge - Reaction',
        description:
          'Before rolling damage for the Box’s attack, you can mark a Stress to add a d6 to the damage roll. Additionally, you gain a Fear.',
      },
      {
        name: 'Death Quake - Reaction',
        description:
          'When the Box marks their last HP, the magic powering them ruptures in an explosion of force. All targets within Close range must succeed on an Instinct Reaction Roll or take 2d8+1 magic damage.',
      },
    ],
  },
  {
    id: 'chaos-skull',
    name: 'Chaos Skull',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Ranged',
    description: 'A floating humanoid skull animated by scintillating magic.',
    motivesAndTactics: 'Cackle, consume magic, serve creator',
    difficulty: 15,
    thresholds: {
      major: 8,
      severe: 16,
    },
    hitPoints: 5,
    stress: 4,
    attackModifier: 2,
    attack: {
      name: 'Energy Blast',
      range: 'Close',
      damage: '2d8+3 mag',
    },
    features: [
      {
        name: 'Levitation - Passive',
        description: 'The Skull levitates several feet off the ground and can’t be Restrained.',
      },
      {
        name: 'Wards - Passive',
        description: 'The Skull is resistant to magic damage.',
      },
      {
        name: 'Magic Burst - Action',
        description:
          'Mark a Stress to make an attack against all targets within Close range. Targets the Skull succeeds against take 2d6+4 magic damage.',
      },
      {
        name: 'Siphon Magic - Action',
        description:
          'Spend a Fear to make an attack against a PC with a Spellcast trait within Very Close range. On a success, the target marks 1d4 Stress and the Skull clears that many Stress. Additionally, on a success, the Skull can immediately be spotlighted again.',
      },
    ],
  },
  {
    id: 'conscript',
    name: 'Conscript',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Minion',
    description: 'A poorly trained civilian pressed into war.',
    motivesAndTactics: 'Follow orders, gang up, survive',
    difficulty: 12,
    hitPoints: 1,
    stress: 1,
    attackModifier: 0,
    attack: {
      name: 'Spears',
      range: 'Very Close',
      damage: '6 phy',
    },
    features: [
      {
        name: 'Minion (6) - Passive',
        description:
          'The Conscript is defeated when they take any damage. For every 6 damage a PC deals to the Conscript, defeat an additional Minion within range the attack would succeed against.',
      },
      {
        name: 'Group Attack - Action',
        description:
          'Spend a Fear to choose a target and spotlight all Conscripts within Close range of them. Those Minions move into Melee range of the target and make one shared attack roll. On a success, they deal 6 physical damage each. Combine this damage.',
      },
    ],
  },
  {
    id: 'courtesan',
    name: 'Courtesan',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Social',
    description: 'An accomplished manipulator and master of the social arts.',
    motivesAndTactics: 'Entice, maneuver, secure patrons',
    difficulty: 13,
    thresholds: {
      major: 7,
      severe: 13,
    },
    hitPoints: 3,
    stress: 4,
    attackModifier: -3,
    attack: {
      name: 'Dagger',
      range: 'Melee',
      damage: '1d4+3 phy',
    },
    experience: 'Manipulation +3, Socialite +3',
    features: [
      {
        name: 'Searing Glance - Reaction',
        description:
          'When a PC within Close range makes a Presence Roll, you can mark a Stress to cast a gaze toward the aftermath. On the target’s failure, they must mark 2 Stress and are Vulnerable until the scene ends or they succeed on a social action against the Courtesan. On the target’s success, they must mark a Stress.',
      },
    ],
  },
  {
    id: 'cult-adept',
    name: 'Cult Adept',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Support',
    description: 'An experienced mage wielding shadow and fear.',
    motivesAndTactics: 'Curry favor, hinder foes, uncover knowledge',
    difficulty: 14,
    thresholds: {
      major: 9,
      severe: 18,
    },
    hitPoints: 4,
    stress: 6,
    attackModifier: 2,
    attack: {
      name: 'Rune-Covered Rod',
      range: 'Far',
      damage: '2d4+3 mag',
    },
    experience: 'Fallen Lore +2, Rituals +2',
    features: [
      {
        name: 'Enervating Blast - Action',
        description:
          'Spend a Fear to make a standard attack against a target within range. On a success, the target must mark a Stress.',
      },
      {
        name: 'Shroud of the Fallen - Action',
        description:
          'Mark a Stress to wrap an ally within Close range in a shroud of Protection until the Adept marks their last HP. While Protected, the target has resistance to all damage.',
      },
      {
        name: 'Shadow Shackles - Action',
        description:
          'Spend a Fear and choose a point within Far range. All targets within Close range of that point are Restrained in smoky chains until they break free with a successful Strength or Instinct Roll. A target Restrained by this feature must spend a Hope to make an action roll.',
      },
      {
        name: 'Fear Is Fuel - Reaction',
        description: 'Twice per scene, when a PC rolls a failure with Fear, clear a Stress.',
      },
    ],
  },
  {
    id: 'cult-fang',
    name: 'Cult Fang',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Skulk',
    description: 'A professional killer-turned-cultist.',
    motivesAndTactics: 'Capture sacrifices, isolate prey, rise in the ranks',
    difficulty: 15,
    thresholds: {
      major: 9,
      severe: 17,
    },
    hitPoints: 4,
    stress: 4,
    attackModifier: 2,
    attack: {
      name: 'Long Knife',
      range: 'Melee',
      damage: '2d8+4 phy',
    },
    features: [
      {
        name: 'Shadow’s Embrace - Passive',
        description:
          'The Fang can climb and walk on vertical surfaces. Mark a Stress to move from one shadow to another within Far range.',
      },
      {
        name: 'Pick Off the Straggler - Action',
        description:
          'Mark a Stress to cause a target within Melee range to make an Instinct Reaction Roll. On a failure, the target must mark 2 Stress and is teleported with the Fang to a shadow within Far range, making them temporarily Vulnerable. On a success, the target must mark a Stress.',
      },
    ],
  },
  {
    id: 'cult-initiate',
    name: 'Cult Initiate',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Minion',
    description: 'A low-ranking cultist in simple robes, eager to gain power.',
    motivesAndTactics: 'Follow orders, gain power, seek forbidden knowledge',
    difficulty: 13,
    hitPoints: 1,
    stress: 1,
    attackModifier: 0,
    attack: {
      name: 'Ritual Dagger',
      range: 'Melee',
      damage: '5 phy',
    },
    features: [
      {
        name: 'Minion (6) - Passive',
        description:
          'The Initiate is defeated when they take any damage. For every 6 damage a PC deals to the Initiate, defeat an additional Minion within range the attack would succeed against.',
      },
      {
        name: 'Group Attack - Action',
        description:
          'Spend a Fear to choose a target and spotlight all Cult Initiates within Close range of them. Those Minions move into Melee range of the target and make one shared attack roll. On a success, they deal 5 physical damage each. Combine this damage.',
      },
    ],
  },
  {
    id: 'demonic-hound-pack',
    name: 'Demonic Hound Pack',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Horde',
    roleDetail: '(1/HP)',
    description: 'Unnatural hounds lit from within by hellfire.',
    motivesAndTactics: 'Cause fear, consume flesh, please masters',
    difficulty: 15,
    thresholds: {
      major: 11,
      severe: 23,
    },
    hitPoints: 6,
    stress: 3,
    attackModifier: 0,
    attack: {
      name: 'Claws and Fangs',
      range: 'Melee',
      damage: '2d8+2 phy',
    },
    experience: 'Scent Tracking +3',
    features: [
      {
        name: 'Horde (2d4+1) - Passive',
        description:
          'When the Pack has marked half or more of their HP, their standard attack deals 2d4+1 physical damage instead.',
      },
      {
        name: 'Dreadhowl - Action',
        description:
          'Mark a Stress to make all targets within Very Close range lose a Hope. If a target is not able to lose a Hope, they must instead mark 2 Stress.',
      },
      {
        name: 'Momentum - Reaction',
        description: 'When the Pack makes a successful attack against a PC, you gain a Fear.',
      },
    ],
  },
  {
    id: 'electric-eels',
    name: 'Electric Eels',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Horde',
    roleDetail: '(2/HP)',
    description: 'A swarm of eels that encircle and electrocute.',
    motivesAndTactics: 'Avoid larger predators, shock prey, tear apart',
    difficulty: 14,
    thresholds: {
      major: 10,
      severe: 20,
    },
    hitPoints: 5,
    stress: 3,
    attackModifier: 0,
    attack: {
      name: 'Shocking Bite',
      range: 'Melee',
      damage: '2d6+4 phy',
    },
    features: [
      {
        name: 'Horde (2d4+1) - Passive',
        description:
          'When the Eels have marked half or more of their HP, their standard attack deals 2d4+1 physical damage instead.',
      },
      {
        name: 'Paralyzing Shock - Action',
        description:
          'Mark a Stress to make a standard attack against all targets within Very Close range. You gain a Fear for each target that marks HP.',
      },
    ],
  },
  {
    id: 'elite-soldier',
    name: 'Elite Soldier',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Standard',
    description: 'An armored squire or experienced commoner looking to advance.',
    motivesAndTactics: 'Gain glory, keep order, make alliances',
    difficulty: 15,
    thresholds: {
      major: 9,
      severe: 18,
    },
    hitPoints: 4,
    stress: 3,
    attackModifier: 1,
    attack: {
      name: 'Spear',
      range: 'Very Close',
      damage: '2d8+4 phy',
    },
    features: [
      {
        name: 'Reinforce - Action',
        description:
          'Mark a Stress to move into Melee range of an ally and make a standard attack against a target within Very Close range. On a success, deal 2d10+2 physical damage and the ally can clear a Stress.',
      },
      {
        name: 'Vassal’s Loyalty - Reaction',
        description:
          'When the Soldier is within Very Close range of a knight or other noble who would take damage, you can mark a Stress to move into Melee range of them and take the damage instead.',
      },
    ],
  },
  {
    id: 'failed-experiment',
    name: 'Failed Experiment',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Standard',
    description: 'A magical necromantic experiment gone wrong, leaving them warped and ungainly.',
    motivesAndTactics: 'Devour, hunt, track',
    difficulty: 13,
    thresholds: {
      major: 12,
      severe: 23,
    },
    hitPoints: 3,
    stress: 3,
    attackModifier: 1,
    attack: {
      name: 'Bite and Claw',
      range: 'Melee',
      damage: '2d6+5 phy',
    },
    experience: 'Copycat +3',
    features: [
      {
        name: 'Warped Fortitude - Passive',
        description: 'The Experiment is resistant to physical damage.',
      },
      {
        name: 'Overwhelm - Passive',
        description:
          'When a target the Experiment attacks has other adversaries within Very Close range, the Experiment deals double damage.',
      },
      {
        name: 'Lurching Lunge - Action',
        description:
          'Mark a Stress to spotlight the Experiment as an additional GM move instead of spending Fear.',
      },
    ],
  },
  {
    id: 'giant-beastmaster',
    name: 'Giant Beastmaster',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Leader',
    description: 'A leather-clad warrior bearing a whip and massive bow.',
    motivesAndTactics: 'Command, make a living, maneuver, pin down, protect companion animals',
    difficulty: 16,
    thresholds: {
      major: 12,
      severe: 24,
    },
    hitPoints: 6,
    stress: 5,
    attackModifier: 2,
    attack: {
      name: 'Longbow',
      range: 'Far',
      damage: '2d8+4 phy',
    },
    experience: 'Animal Handling +3',
    features: [
      {
        name: 'Two as One - Passive',
        description:
          'When the Beastmaster is spotlighted, you can also spotlight a Tier 1 animal adversary currently under their control.',
      },
      {
        name: 'Pinning Strike - Action',
        description:
          'Make a standard attack against a target. On a success, you can mark a Stress to pin them to a nearby surface. The pinned target is Restrained until they break free with a successful Finesse or Strength Roll.',
      },
      {
        name: 'Deadly Companion - Action',
        description:
          'Twice per scene, summon a Bear, Dire Wolf, or similar Tier 1 animal adversary under the Beastmaster’s control. The adversary appears at Close range and is immediately spotlighted.',
      },
    ],
  },
  {
    id: 'giant-brawler',
    name: 'Giant Brawler',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Bruiser',
    description: 'An especially muscular giant wielding a warhammer larger than a human.',
    motivesAndTactics: 'Make a living, overwhelm, slam, topple',
    difficulty: 15,
    thresholds: {
      major: 12,
      severe: 28,
    },
    hitPoints: 7,
    stress: 4,
    attackModifier: 2,
    attack: {
      name: 'Warhammer',
      range: 'Very Close',
      damage: '2d12+3 phy',
    },
    experience: 'Intrusion +2',
    features: [
      {
        name: 'Battering Ram - Action',
        description:
          'Mark a Stress to have the Brawler charge at an inanimate object within Close range they could feasibly smash (such as a wall, cart, or market stand) and destroy it. All targets within Very Close range of the object must succeed on an Agility Reaction Roll or take 2d4+3 physical damage from the shrapnel.',
      },
      {
        name: 'Bloody Reprisal - Reaction',
        description:
          'When the Brawler marks 2 or more HP from an attack within Very Close range, you can make a standard attack against the attacker. On a success, the Brawler deals 2d6+15 physical damage instead of their standard damage.',
      },
      {
        name: 'Momentum - Reaction',
        description: 'When the Brawler makes a successful attack against a PC, you gain a Fear.',
      },
    ],
  },
  {
    id: 'giant-eagle',
    name: 'Giant Eagle',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Skulk',
    description: 'A giant bird of prey with blood-stained talons.',
    motivesAndTactics: 'Hunt prey, stay mobile, strike decisively',
    difficulty: 14,
    thresholds: {
      major: 8,
      severe: 19,
    },
    hitPoints: 4,
    stress: 4,
    attackModifier: 1,
    attack: {
      name: 'Claws and Beak',
      range: 'Very Close',
      damage: '2d6+3 phy',
    },
    features: [
      {
        name: 'Flight - Passive',
        description: 'While flying, the Eagle gains a +3 bonus to their Difficulty.',
      },
      {
        name: 'Deadly Dive - Action',
        description:
          'Mark a Stress to attack a target within Far range. On a success, deal 2d10+2 physical damage and knock the target over, making them Vulnerable until they next act.',
      },
      {
        name: 'Take Off - Action',
        description:
          'Make an attack against a target within Very Close range. On a success, deal 2d4+3 physical damage and the target must succeed on an Agility Reaction Roll or become temporarily Restrained within the Eagle’s massive talons. If the target is Restrained, the Eagle immediately lifts them to the air to Very Far range above the battlefield while holding them.',
      },
      {
        name: 'Deadly Drop - Action',
        description:
          'While flying, the Eagle can drop a Restrained target they are holding. When dropped, the target is no longer Restrained but starts falling. If their fall isn’t prevented during the PCs’ next action, the target takes 2d20 physical damage when they land.',
      },
    ],
  },
  {
    id: 'giant-recruit',
    name: 'Giant Recruit',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Minion',
    description: 'A giant fighter undergoing borrowed armor.',
    motivesAndTactics: 'Batter, make a living, overwhelm, terrify',
    difficulty: 13,
    hitPoints: 1,
    stress: 2,
    attackModifier: 1,
    attack: {
      name: 'Warhammer',
      range: 'Very Close',
      damage: '5 phy',
    },
    features: [
      {
        name: 'Minion (7) - Passive',
        description:
          'The Recruit is defeated when they take any damage. For every 7 damage a PC deals to the Recruit, defeat an additional Minion within range the attack would succeed against.',
      },
      {
        name: 'Group Attack - Action',
        description:
          'Spend a Fear to choose a target and spotlight all Giant Recruits within Close range of them. Those Minions move into Melee range of the target and make one shared attack roll. On a success, they deal 5 physical damage each. Combine this damage.',
      },
    ],
  },
  {
    id: 'gorgon',
    name: 'Gorgon',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Solo',
    description:
      'A snake-headed, scaled humanoid with a gilded bow, enraged that their peace has been disturbed.',
    motivesAndTactics: 'Corner, hit-and-run, petrify, seek vengeance',
    difficulty: 15,
    thresholds: {
      major: 13,
      severe: 25,
    },
    hitPoints: 9,
    stress: 3,
    attackModifier: 4,
    attack: {
      name: 'Sinew Shortbow',
      range: 'Far',
      damage: '2d20+3 mag',
    },
    experience: 'Instinct +3',
    features: [
      {
        name: 'Relentless (2) - Passive',
        description:
          'The Gorgon can be spotlighted up to two times per GM turn. Spend Fear as usual to spotlight them.',
      },
      {
        name: 'Suneater Arrows - Passive',
        description:
          'When the Gorgon makes a successful standard attack, the target Glows until the end of the scene and can’t become Hidden. Attack rolls made against a Glowing target have advantage.',
      },
      {
        name: 'Crown of Serpents - Action',
        description:
          'Make an attack roll against a target within Melee range using the Gorgon’s protective snakes. On a success, mark Stress to deal 2d10+4 physical damage and the target must mark a Stress.',
      },
      {
        name: 'Petrifying Gaze - Reaction',
        description:
          'When the Gorgon takes damage from an attack within Close range, you can spend a Fear to force the attacker to make an Instinct Reaction Roll. On a failure, they begin to turn to stone, marking a HP and starting a Petrification Countdown (4). This countdown ticks down when the Gorgon is attacked. When it triggers, the target must make a death move. If the Gorgon is defeated, all petrification countdowns end.',
      },
      {
        name: 'Death Glare - Reaction',
        description: 'When the Gorgon makes a successful attack against a PC, you gain a Fear.',
      },
    ],
  },
  {
    id: 'juvenile-flickerfly',
    name: 'Juvenile Flickerfly',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Solo',
    description:
      'A horse-sized insect with iridescent scales and crystalline wings moving faster than the eye can see.',
    motivesAndTactics: 'Collect shiny things, hunt, swoop',
    difficulty: 14,
    thresholds: {
      major: 13,
      severe: 26,
    },
    hitPoints: 10,
    stress: 5,
    attackModifier: 3,
    attack: {
      name: 'Wing Slash',
      range: 'Very Close',
      damage: '2d10+4 phy',
    },
    features: [
      {
        name: 'Relentless (3) - Passive',
        description:
          'The Flickerfly can be spotlighted up to three times per GM turn. Spend Fear as usual to spotlight them.',
      },
      {
        name: 'Peerless Accuracy - Passive',
        description:
          'Before the Flickerfly makes an attack, roll a d6. On a result of 4 or higher, the target’s Evasion is halved against this attack.',
      },
      {
        name: 'Mind Dance - Action',
        description:
          'Mark a Stress to create a magically dazzling display that grapples the minds of nearby foes. All targets within Close range must make an Instinct Reaction Roll. For each target who failed, you gain a Fear and the Flickerfly learns one of the target’s fears.',
      },
      {
        name: 'Hallucinatory Breath - Reaction: Countdown (Loop 1d6)',
        description:
          'When the Flickerfly takes damage for the first time, activate the countdown. When it triggers, the Flickerfly breathes hallucinatory gas on all targets in front of them up to Far range. Targets must succeed on an Instinct Reaction Roll or be tormented by fearful hallucinations. Targets whose fears are known to the Flickerfly have disadvantage on this roll. Targets who fail must mark a Stress and lose a Hope.',
      },
    ],
  },
  {
    id: 'knight-of-the-realm',
    name: 'Knight of the Realm',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Leader',
    description: 'A decorated soldier with heavy armor and a powerful steed.',
    motivesAndTactics: 'Run down, seek glory, show dominance',
    difficulty: 15,
    thresholds: {
      major: 13,
      severe: 26,
    },
    hitPoints: 6,
    stress: 4,
    attackModifier: 4,
    attack: {
      name: 'Longsword',
      range: 'Melee',
      damage: '2d10+4 phy',
    },
    experience: 'Ancient Knowledge +3, High Society +2, Tactics +2',
    features: [
      {
        name: 'Chevalier - Passive',
        description:
          'While the Knight is on a mount, they gain a +2 bonus to their Difficulty. When they take Severe damage, they’re knocked from their mount and lose this benefit until they’re next spotlighted.',
      },
      {
        name: 'Heavily Armored - Passive',
        description: 'When the Knight takes physical damage, reduce it by 3.',
      },
      {
        name: 'Cavalry Charge - Action',
        description:
          'If the Knight is mounted, move up to Far range and make a standard attack against a target. On a success, deal 2d8+4 physical damage and the target must mark a Stress.',
      },
      {
        name: 'For the Realm! - Action',
        description:
          'Mark a Stress to spotlight 1d4+1 allies. Attacks they make while spotlighted in this way deal half damage.',
      },
    ],
  },
  {
    id: 'masked-thief',
    name: 'Masked Thief',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Skulk',
    description: 'A cunning thief with acrobatic skill and a flair for the dramatic.',
    motivesAndTactics: 'Evade, hide, pilfer, profit',
    difficulty: 14,
    thresholds: {
      major: 8,
      severe: 17,
    },
    hitPoints: 4,
    stress: 5,
    attackModifier: 3,
    attack: {
      name: 'Backsword',
      range: 'Melee',
      damage: '2d8+3 phy',
    },
    experience: 'Acrobatics +3',
    features: [
      {
        name: 'Quick Hands - Action',
        description:
          'Make an attack against a target within Melee range. On a success, deal 1d8+2 physical damage and the Thief steals one item or consumable from the target’s inventory.',
      },
      {
        name: 'Escape Plan - Action',
        description:
          'Mark a Stress to reveal a snare trap set anywhere on the battlefield by the Thief. All targets within Very Close range of the trap must succeed on an Agility Reaction Roll (13) or be pulled off their feet and suspended upside down. The target is Restrained and Vulnerable until they break free, ending both conditions, with a successful Finesse or Strength Roll (13).',
      },
    ],
  },
  {
    id: 'master-assassin',
    name: 'Master Assassin',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Leader',
    description: 'A seasoned killer with a threatening voice and a deadly blade.',
    motivesAndTactics: 'Ambush, get out alive, kill, prepare for all scenarios',
    difficulty: 15,
    thresholds: {
      major: 12,
      severe: 25,
    },
    hitPoints: 7,
    stress: 5,
    attackModifier: 5,
    attack: {
      name: 'Serrated Dagger',
      range: 'Close',
      damage: '2d10+2 phy',
    },
    experience: 'Command +3, Intrusion +3',
    features: [
      {
        name: 'Won’t See It Coming - Passive',
        description: 'The Assassin deals direct damage while they’re Hidden.',
      },
      {
        name: 'Strike as One - Action',
        description:
          'Mark a Stress to spotlight a number of other Assassins equal to the Assassin’s unmarked Stress.',
      },
      {
        name: 'The Subtle Blade - Reaction',
        description:
          'When the Assassin successfully makes a standard attack against a Vulnerable target, you can spend a Fear to deal Severe damage instead of their standard damage.',
      },
      {
        name: 'Momentum - Reaction',
        description: 'When the Assassin makes a successful attack against a PC, you gain a Fear.',
      },
    ],
  },
  {
    id: 'merchant-baron',
    name: 'Merchant Baron',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Social',
    description: 'An accomplished merchant with a large operation under their command.',
    motivesAndTactics: 'Abusive power, gather resources, mobilize minions',
    difficulty: 15,
    thresholds: {
      major: 9,
      severe: 19,
    },
    hitPoints: 5,
    stress: 3,
    attackModifier: 2,
    attack: {
      name: 'Rapier',
      range: 'Melee',
      damage: '1d6+2 phy',
    },
    experience: 'Nobility +2, Trade +2',
    features: [
      {
        name: 'Everyone Has a Price - Action',
        description:
          'Spend a Fear to offer a target a dangerous bargain for something they want or need. If used on a PC, they must make a Presence Reaction Roll (17). On a failure, they must mark 2 Stress or take the deal.',
      },
      {
        name: 'The Best Muscle Money Can Buy - Action',
        description:
          'Once per scene, mark a Stress to summon 1d4+1 Tier 1 adversaries, who appear at Far range, to enforce the Baron’s will.',
      },
    ],
  },
  {
    id: 'minotaur-wrecker',
    name: 'Minotaur Wrecker',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Bruiser',
    description: 'A massive bull-headed hybrid with a quick temper.',
    motivesAndTactics: 'Consume, gore, navigate, overpower, pursue',
    difficulty: 16,
    thresholds: {
      major: 14,
      severe: 27,
    },
    hitPoints: 7,
    stress: 5,
    attackModifier: 2,
    attack: {
      name: 'Battleaxe',
      range: 'Very Close',
      damage: '2d8+5 phy',
    },
    experience: 'Navigation +2',
    features: [
      {
        name: 'Ramp Up - Passive',
        description:
          'You must spend a Fear to spotlight the Minotaur. While spotlighted, they can make their standard attack against all targets within range.',
      },
      {
        name: 'Charging Bull - Action',
        description:
          'Mark a Stress to charge through a group within Close range and make an attack against all targets in the Minotaur’s path. Targets the Minotaur succeeds against take 2d6+8 physical damage and are knocked back to Very Far range. If a target is knocked into a solid object or another creature, they take an extra 1d6 damage (combine their damage).',
      },
      {
        name: 'Gore - Action',
        description:
          'Make an attack against a target within Very Close range, moving the Minotaur into Melee range of them. On a success, deal 2d8 direct physical damage.',
      },
    ],
  },
  {
    id: 'mortal-hunter',
    name: 'Mortal Hunter',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Leader',
    description:
      'An undead figure wearing a heavy leather coat, with searching eyes and a cruelly cut demeanor.',
    motivesAndTactics: 'Devour, hunt, track',
    difficulty: 16,
    thresholds: {
      major: 15,
      severe: 27,
    },
    hitPoints: 6,
    stress: 4,
    attackModifier: 5,
    attack: {
      name: 'Tear at Flesh',
      range: 'Very Close',
      damage: '2d12+1 phy',
    },
    experience: 'Bloodhound +3',
    features: [
      {
        name: 'Terrifying - Passive',
        description:
          'When the Hunter makes a successful attack, all PCs within Far range lose a Hope and you gain a Fear.',
      },
      {
        name: 'Deathlock - Action',
        description:
          'Spend a Fear to curse a target within Very Close range with a necrotic Deathlock until the end of the scene. Attacks made by the Hunter against a Deathlocked target deal direct damage. The Hunter can only maintain one Deathlock at a time.',
      },
      {
        name: 'Inevitable Death - Action',
        description:
          'Mark a Stress to spotlight 1d4 allies. Attacks they make while spotlighted in this way deal half damage.',
      },
      {
        name: 'Rampage - Reaction',
        description:
          'Countdown (Loop 1d6). When the Hunter is in the spotlight for the first time, activate the countdown. When it triggers, move the Hunter in a straight line to a point within Far range and make an attack against all targets in their path. Targets the Hunter succeeds against take 2d8+2 physical damage.',
      },
    ],
  },
  {
    id: 'royal-advisor',
    name: 'Royal Advisor',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Social',
    description: 'A high-ranking courtier with the ear of the local nobility.',
    motivesAndTactics: 'Curry favor, manufacture evidence, scheme',
    difficulty: 14,
    thresholds: {
      major: 8,
      severe: 15,
    },
    hitPoints: 3,
    stress: 3,
    attackModifier: -3,
    attack: {
      name: 'Wand',
      range: 'Far',
      damage: '1d4+3 phy',
    },
    experience: 'Administration +3, Courtier +3',
    features: [
      {
        name: 'Devastating Retort - Passive',
        description:
          'A PC who rolls less than 17 on an action roll targeting the Advisor must mark a Stress.',
      },
      {
        name: 'Bend Ears - Action',
        description:
          'Mark a Stress to influence an NPC within Melee range with whispered words. That target’s opinion on one matter shifts toward the Advisor’s preference unless it is in direct opposition to the target’s motives.',
      },
      {
        name: 'Scapegoat - Action',
        description:
          'Spend a Fear to convince a crowd or notable individual that one person or group is responsible for some problem facing the target. The target becomes hostile to the scapegoat until convinced of their innocence with a successful Presence Roll (17).',
      },
    ],
  },
  {
    id: 'secret-keeper',
    name: 'Secret-Keeper',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Leader',
    description: 'A clandestine leader with a direct channel to the Fallen Gods.',
    motivesAndTactics: 'Amass great power, plot, take command',
    difficulty: 16,
    thresholds: {
      major: 13,
      severe: 26,
    },
    hitPoints: 7,
    stress: 4,
    attackModifier: 3,
    attack: {
      name: 'Sigil-Laden Staff',
      range: 'Far',
      damage: '2d12 mag',
    },
    experience: 'Coercion +2, Fallen Lore +2',
    features: [
      {
        name: 'Seize Your Moment - Action',
        description:
          'Spend 2 Fear to spotlight 1d4 allies. Attacks they make while spotlighted in this way deal half damage.',
      },
      {
        name: 'Our Master’s Will - Reaction',
        description: 'When you spotlight an ally within Far range, mark a Stress to gain a Fear.',
      },
      {
        name: 'Summoning Ritual - Reaction',
        description:
          'Countdown (6). When the Secret-Keeper is in the spotlight for the first time, activate the countdown. When they mark HP, tick down this countdown by the number of HP marked. When it triggers, summon a Minor Demon who appears at Close range.',
      },
      {
        name: 'Fallen Hounds - Reaction',
        description:
          'Once per scene, when the Secret-Keeper marks 2 or more HP, you can mark a Stress to summon a Demonic Hound Pack, which appears at Close range and is immediately spotlighted.',
      },
    ],
  },
  {
    id: 'shark',
    name: 'Shark',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Bruiser',
    description: 'A large aquatic predator, always on the move.',
    motivesAndTactics: 'Find the blood, isolate prey, target the weak',
    difficulty: 14,
    thresholds: {
      major: 14,
      severe: 28,
    },
    hitPoints: 7,
    stress: 3,
    attackModifier: 2,
    attack: {
      name: 'Toothy Maw',
      range: 'Very Close',
      damage: '2d12+1 phy',
    },
    experience: 'Sense of Smell +3',
    features: [
      {
        name: 'Terrifying - Passive',
        description:
          'When the Shark makes a successful attack, all PCs within Far range lose a Hope and you gain a Fear.',
      },
      {
        name: 'Rending Bite - Passive',
        description:
          'When the Shark makes a successful attack, the target must mark an Armor Slot without receiving its benefits (they can still use armor to reduce the damage). If they can’t mark an Armor Slot, they must mark an additional HP.',
      },
      {
        name: 'Blood in the Water - Reaction',
        description:
          'When a creature within Close range of the Shark marks HP from another creature’s attack, you can mark a Stress to immediately spotlight the Shark, moving them into Melee range of the target and making a standard attack.',
      },
    ],
  },
  {
    id: 'siren',
    name: 'Siren',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Skulk',
    description: 'A half fish person with shimmering scales and an irresistible voice.',
    motivesAndTactics: 'Consume, lure prey, subdue with song',
    difficulty: 14,
    thresholds: {
      major: 9,
      severe: 18,
    },
    hitPoints: 5,
    stress: 3,
    attackModifier: 2,
    attack: {
      name: 'Distended Jaw Bite',
      range: 'Melee',
      damage: '2d6+3 phy',
    },
    experience: 'Song Repertoire +3',
    features: [
      {
        name: 'Captive Audience - Passive',
        description:
          'If the Siren makes a standard attack against a target Entranced by their song, the attack deals 2d10+1 damage instead of their standard damage.',
      },
      {
        name: 'Enchanting Song - Action',
        description:
          'Spend a Fear to sing a song that affects all targets within Close range. Targets must succeed on an Instinct Reaction Roll or become Entranced until they mark 2 Stress. Other Sirens within Close range of the target can mark a Stress to each add a +1 bonus to the Difficulty of the reaction roll. While Entranced, a target can’t act and is Vulnerable.',
      },
    ],
  },
  {
    id: 'spectral-archer',
    name: 'Spectral Archer',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Ranged',
    description:
      'A ghostly fighter with an ethereal bow, unable to move on while their charge is vulnerable.',
    motivesAndTactics: 'Move through solid objects, stay out of the fray, rehash old battles',
    difficulty: 13,
    thresholds: {
      major: 6,
      severe: 14,
    },
    hitPoints: 3,
    stress: 3,
    attackModifier: 3,
    attack: {
      name: 'Longbow',
      range: 'Far',
      damage: '2d10+2 phy',
    },
    experience: 'Ancient Knowledge +2',
    features: [
      {
        name: 'Ghost - Passive',
        description:
          'The Archer has resistance to physical damage. Mark a Stress to move up to Close range through solid objects.',
      },
      {
        name: 'Pick Your Target - Action',
        description:
          'Spend a Fear to make an attack against a target within Very Close range of at least two other PCs. On a success, the target takes 2d8+12 physical damage.',
      },
    ],
  },
  {
    id: 'spectral-captain',
    name: 'Spectral Captain',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Leader',
    description: 'A ghostly commander leading their troops beyond death.',
    motivesAndTactics: 'Move through solid objects, rally troops, rehash old battles',
    difficulty: 16,
    thresholds: {
      major: 13,
      severe: 26,
    },
    hitPoints: 6,
    stress: 4,
    attackModifier: 3,
    attack: {
      name: 'Longbow',
      range: 'Far',
      damage: '2d10+3 phy',
    },
    experience: 'Ancient Knowledge +3',
    features: [
      {
        name: 'Ghost - Passive',
        description:
          'The Captain has resistance to physical damage. Mark a Stress to move up to Close range through solid objects.',
      },
      {
        name: 'Unending Battle - Action',
        description:
          'Spend 2 Fear to return up to 1d4+1 defeated Spectral allies to the battle at the points where they first appeared (with no marked HP or Stress).',
      },
      {
        name: 'Hold Fast - Reaction',
        description:
          'When the Captain’s Spectral allies are forced to make a reaction roll, you can mark a Stress to give those allies a +2 bonus to the roll.',
      },
      {
        name: 'Momentum - Reaction',
        description: 'When the Captain makes a successful attack against a PC, you gain a Fear.',
      },
    ],
  },
  {
    id: 'spectral-guardian',
    name: 'Spectral Guardian',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Standard',
    description: 'A ghostly fighter with spears and swords, anchored by duty.',
    motivesAndTactics: 'Move through solid objects, protect treasure, rehash old battles',
    difficulty: 15,
    thresholds: {
      major: 7,
      severe: 15,
    },
    hitPoints: 4,
    stress: 3,
    attackModifier: 1,
    attack: {
      name: 'Spear',
      range: 'Very Close',
      damage: '2d8+1 phy',
    },
    experience: 'Ancient Knowledge +2',
    features: [
      {
        name: 'Ghost - Passive',
        description:
          'The Guardian has resistance to physical damage. Mark a Stress to move up to Close range through solid objects.',
      },
      {
        name: 'Grave Blade - Action',
        description:
          'Spend a Fear to make an attack against a target within Very Close range. On a success, deal 2d10+6 physical damage and the target must mark a Stress.',
      },
    ],
  },
  {
    id: 'spy',
    name: 'Spy',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Social',
    description:
      'A skilled espionage agent with a knack for being in the right place to overhear secrets.',
    motivesAndTactics: 'Cut and run, disguise appearance, eavesdrop',
    difficulty: 15,
    thresholds: {
      major: 8,
      severe: 17,
    },
    hitPoints: 4,
    stress: 3,
    attackModifier: -2,
    attack: {
      name: 'Dagger',
      range: 'Melee',
      damage: '2d6+3 phy',
    },
    experience: 'Espionage +3',
    features: [
      {
        name: 'Gathering Secrets - Action',
        description: 'Spend a Fear to describe how the Spy knows a secret about a PC in the scene.',
      },
      {
        name: 'Fly on the Wall - Reaction',
        description:
          'When a PC or group is discussing something sensitive, you can mark a Stress to reveal that the Spy is present in the scene, observing them. If the Spy escapes the scene to report their findings, you gain 1d4 Fear.',
      },
    ],
  },
  {
    id: 'stonewraith',
    name: 'Stonewraith',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Skulk',
    description: 'A prowling hunter, like a slinking mountain lion, with a slate-gray stone body.',
    motivesAndTactics: 'Defend territory, isolate prey, stalk',
    difficulty: 13,
    thresholds: {
      major: 11,
      severe: 22,
    },
    hitPoints: 6,
    stress: 3,
    attackModifier: 3,
    attack: {
      name: 'Bite and Claws',
      range: 'Melee',
      damage: '2d8+6 phy',
    },
    experience: 'Stonesense +3',
    features: [
      {
        name: 'Stonestrider - Passive',
        description:
          'The Stonewraith can move through stone and earth as easily as air. While within stone or earth, they are Hidden and immune to all damage.',
      },
      {
        name: 'Rocky Ambush - Action',
        description:
          'While Hidden, mark a Stress to leap into Melee range with a target within Very Close range. The target must succeed on an Agility or Instinct Reaction Roll (15) or take 2d8 physical damage and become temporarily Restrained.',
      },
      {
        name: 'Avalanche Roar - Action',
        description:
          'Spend a Fear to roar while within a cave and cause a cave-in. All targets within Close range must succeed on an Agility Reaction Roll (14) or take 2d10 physical damage. The rubble can be cleared with a Progress Countdown (8).',
      },
      {
        name: 'Momentum - Reaction',
        description:
          'When the Stonewraith makes a successful attack against a PC, you gain a Fear.',
      },
    ],
  },
  {
    id: 'war-wizard',
    name: 'War Wizard',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 2,
    role: 'Ranged',
    description: 'A battle-hardened mage trained in destructive magic.',
    motivesAndTactics: 'Develop new spells, seek power, conquer',
    difficulty: 16,
    thresholds: {
      major: 11,
      severe: 23,
    },
    hitPoints: 5,
    stress: 6,
    attackModifier: 4,
    attack: {
      name: 'Staff',
      range: 'Far',
      damage: '2d10+4 mag',
    },
    experience: 'Magical Knowledge +2, Strategize +2',
    features: [
      {
        name: 'Battle Teleport - Passive',
        description:
          'Before or after making a standard attack, you can mark a Stress to teleport to a location within Far range.',
      },
      {
        name: 'Refresh Warding Sphere - Action',
        description: 'Mark a Stress to refresh the Wizard’s “Warding Sphere” reaction.',
      },
      {
        name: 'Eruption - Action',
        description:
          'Spend a Fear and choose a point within Far range. A Very Close area around that point erupts into impassable terrain. All targets within that area must make an Agility Reaction Roll (14). Targets who fail take 2d10 physical damage and are thrown out of the area. Targets who succeed take half damage and aren’t moved.',
      },
      {
        name: 'Arcane Artillery - Action',
        description:
          'Spend a Fear to unleash a precise hail of magical blasts. All targets in the scene must make an Agility Reaction Roll. Targets who fail take 2d12 magic damage. Targets who succeed take half damage.',
      },
      {
        name: 'Warding Sphere - Reaction',
        description:
          'When the Wizard takes damage from an attack within Close range, deal 2d6 magic damage to the attacker. This reaction can’t be used again until the Wizard refreshes it with their “Refresh Warding Sphere” action.',
      },
    ],
  },
];
