// GENERATED by scripts/encode-daggerheart-adversaries.mjs from
// Batres3/daggerheart-srd (Daggerheart SRD 1.0, DPCGL — see
// docs/srd-sources.md). Regenerate per the script header.

import { DaggerheartAdversary } from '../../../../types/daggerheart';

export const daggerheartTier4Adversaries: DaggerheartAdversary[] = [
  {
    id: 'arch-necromancer',
    name: 'Arch-Necromancer',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Leader',
    description: 'A decaying mage adorned in dark, tattered robes.',
    motivesAndTactics: 'Corrupt, decay, flee to fight another day, resurrect',
    difficulty: 21,
    thresholds: {
      major: 33,
      severe: 66,
    },
    hitPoints: 9,
    stress: 8,
    attackModifier: 6,
    attack: {
      name: 'Necrotic Blast',
      range: 'Far',
      damage: '4d12+8 mag',
    },
    experience: 'Forbidden Knowledge +3, Wisdom of Centuries +3',
    features: [
      {
        name: 'Dance of Death - Action',
        description:
          'Mark a Stress to spotlight 1d4 allies. Attacks they make while spotlighted in this way deal half damage, or full damage if you spend a Fear.',
      },
      {
        name: 'Beam of Decay - Action',
        description:
          'Mark 2 Stress to cause all targets within Far range to make a Strength Reaction Roll. Targets who fail take 2d20+12 magic damage and you gain a Fear. Targets who succeed take half damage. A target who marks 2 or more HP must also mark 2 Stress and becomes Vulnerable until they roll with Hope.',
      },
      {
        name: 'Open the Gates of Death - Action',
        description:
          'Spend a Fear to summon a Zombie Legion, which appears at Close range and immediately takes the spotlight.',
      },
      {
        name: 'Not Today, My Dears - Reaction',
        description:
          'When the Necromancer has marked 7 or more of their HP, you can spend a Fear to have them teleport away to a safe location to recover. A PC who succeeds on an Instinct Roll can trace the teleportation magic to their destination.',
      },
      {
        name: 'Your Demise is Near - Reaction',
        description:
          'Countdown (2d6). When the Necromancer has marked 6 or more of their HP, activate the countdown. When it triggers, deal 2d10+6 direct magic damage to a target within Close range. The Necromancer then clears a number of Stress or HP equal to the number of HP marked by the target from this attack.',
      },
    ],
  },
  {
    id: 'fallen-shock-troop',
    name: 'Fallen Shock Troop',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Minion',
    description: 'A cursed soul bound to the Fallen’s will.',
    motivesAndTactics: 'Crush, dominate, earn relief, punish',
    difficulty: 18,
    hitPoints: 1,
    stress: 1,
    attackModifier: 2,
    attack: {
      name: 'Cursed Axe',
      range: 'Very Close',
      damage: '12 phy',
    },
    features: [
      {
        name: 'Minion (12) - Passive',
        description:
          'The Shock Troop is defeated when they take any damage. For every 12 damage a PC deals to the Shock Troop, defeat an additional Minion within range the attack would succeed against.',
      },
      {
        name: 'Aura of Doom - Passive',
        description: 'When a PC marks HP from an attack by the Shock Troop, they lose a Hope.',
      },
      {
        name: 'Group Attack - Action',
        description:
          'Spend a Fear to choose a target and spotlight all Fallen Shock Troops within Close range of them. Those Minions move into Melee range of the target and make one shared attack roll. On a success, they deal 12 physical damage each. Combine this damage.',
      },
    ],
  },
  {
    id: 'fallen-sorcerer',
    name: 'Fallen Sorcerer',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Support',
    description: 'Warped mage bound by the bargains they made in life.',
    motivesAndTactics: 'Acquire, dishearten, dominate, torment',
    difficulty: 19,
    thresholds: {
      major: 26,
      severe: 42,
    },
    hitPoints: 6,
    stress: 5,
    attackModifier: 4,
    attack: {
      name: 'Corrupted Staff',
      range: 'Far',
      damage: '4d6+10 mag',
    },
    experience: 'Ancient Knowledge +2',
    features: [
      {
        name: 'Conflagration - Action',
        description:
          'Spend a Fear to unleash an all-consuming firestorm and make an attack against all targets within Close range. Targets the Sorcerer succeeds against take 2d10+6 direct magic damage.',
      },
      {
        name: 'Nightmare Tableau - Action',
        description:
          'Mark a Stress to trap a target within Far range in a powerful illusion of their worst fears. While trapped, the target is Restrained and Vulnerable until they break free, ending both conditions, with a successful Instinct Roll.',
      },
      {
        name: 'Slippery - Reaction',
        description:
          'When the Sorcerer takes damage from an attack, they can teleport up to Far range.',
      },
      {
        name: 'Shackles of Guilt - Reaction',
        description:
          'Countdown (Loop 2d6). When the Sorcerer is in the spotlight for the first time, activate the countdown. When it triggers, all targets within Far range become Vulnerable and must mark a Stress as they relive their greatest regrets. A target can break free from their regret with a successful Presence or Strength Roll. When a PC fails to break free, they lose a Hope.',
      },
    ],
  },
  {
    id: 'fallen-warlord-realm-breaker',
    name: 'Fallen Warlord: Realm-Breaker',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Solo',
    description:
      'A fallen God, wreathed in rage and resentment, bearing millennia of experience in breaking heroes’ spirits.',
    motivesAndTactics: 'Corrupt, dominate, punish, break the weak',
    difficulty: 20,
    thresholds: {
      major: 36,
      severe: 66,
    },
    hitPoints: 8,
    stress: 5,
    attackModifier: 7,
    attack: {
      name: 'Barbed Whip',
      range: 'Close',
      damage: '4d8+7 phy',
    },
    experience: 'Conquest +3, History +2, Intimidation +3',
    features: [
      {
        name: 'Relentless (2) - Passive',
        description:
          'The Realm-Breaker can be spotlighted up to two times per GM turn. Spend Fear as usual to spotlight them.',
      },
      {
        name: 'Firespite Plate Armor - Passive',
        description: 'When the Realm-Breaker takes damage, reduce it by 2d10.',
      },
      {
        name: 'Tormenting Lash - Action',
        description:
          'Mark a Stress to make a standard attack against all targets within Very Close range. When a target uses armor to reduce damage from this attack, they must mark 2 Armor Slots.',
      },
      {
        name: 'All-Consuming Rage - Reaction',
        description:
          'Countdown (Decreasing 8). When the Realm-Breaker is in the spotlight for the first time, activate the countdown. When it triggers, create a torrent of incarnate rage that rends flesh from bone. All targets within Far range must make a Presence Reaction Roll. Targets who fail take 2d6+10 direct magic damage. Targets who succeed take half damage. For each HP marked from this damage, summon a Fallen Shock Troop within Very Close range of the target who marked that HP. If the countdown ever decreases its maximum value to 0, the Realm-Breaker marks their remaining HP and all targets within Far range must mark all remaining HP and make a death move.',
      },
      {
        name: 'Doombringer - Reaction',
        description:
          'When a target marks HP from an attack by the Realm-Breaker, all PCs within Far range of the target must lose a Hope.',
      },
      {
        name: 'I Have Never Known Defeat (Phase Change) - Reaction',
        description:
          'When the Realm-Breaker marks their last HP, replace them with the Undefeated Champion and immediately spotlight them.',
      },
    ],
  },
  {
    id: 'fallen-warlord-undefeated-champion',
    name: 'Fallen Warlord: Undefeated Champion',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Solo',
    description: 'That which only the most feared have a chance to fear.',
    motivesAndTactics: 'Dispatch merciless death, punish the defiant, secure victory at any cost',
    difficulty: 18,
    thresholds: {
      major: 35,
      severe: 58,
    },
    hitPoints: 11,
    stress: 5,
    attackModifier: 8,
    attack: {
      name: 'Heart-Shattering Sword',
      range: 'Very Close',
      damage: '4d12+13 phy',
    },
    experience: 'Conquest +3, History +2, Intimidation +3',
    features: [
      {
        name: 'Relentless (3) - Passive',
        description:
          'The Undefeated Champion can be spotlighted up to three times per GM turn. Spend Fear as usual to spotlight them.',
      },
      {
        name: 'Faltering Armor - Passive',
        description: 'When the Undefeated Champion takes damage, reduce it by 1d10.',
      },
      {
        name: 'Shattering Strike - Action',
        description:
          'Mark a Stress to make a standard attack against all targets within Very Close range. PCs the Champion succeeds against lose a number of Hope equal to the HP they marked from this attack.',
      },
      {
        name: 'Endless Legions - Action',
        description:
          'Spend a Fear to summon a number of Fallen Shock Troops equal to twice the number of PCs. The Shock Troops appear at Far range.',
      },
      {
        name: 'Circle of Defilement - Reaction',
        description:
          'Countdown (1d8). When the Undefeated Champion is in the spotlight for the first time, activate the countdown. When it triggers, activate a magical circle covering an area within Far range of the Champion. A target within that area is Vulnerable until they leave the circle. The circle can be removed by dealing Severe damage to the Undefeated Champion.',
      },
      {
        name: 'Doombringer - Reaction',
        description:
          'When the Undefeated Champion makes a successful attack against a PC, you gain a Fear.',
      },
      {
        name: 'Doombringer - Reaction',
        description:
          'When a target marks HP from an attack by the Undefeated Champion, all PCs within Far range of the target lose a Hope.',
      },
    ],
  },
  {
    id: 'hallowed-archer',
    name: 'Hallowed Archer',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Ranged',
    description: 'Spirit soldiers with sanctified bows.',
    motivesAndTactics: 'Focus fire, obey, retribution, volley',
    difficulty: 19,
    thresholds: {
      major: 25,
      severe: 45,
    },
    hitPoints: 3,
    stress: 2,
    attackModifier: 4,
    attack: {
      name: 'Sanctified Longbow',
      range: 'Far',
      damage: '4d8+8 phy',
    },
    features: [
      {
        name: 'Punish the Guilty - Passive',
        description: 'The Archer deals double damage to targets marked Guilty by a High Seraph.',
      },
      {
        name: 'Divine Volley - Action',
        description: 'Mark a Stress to make a standard attack against up to three targets.',
      },
    ],
  },
  {
    id: 'hallowed-soldier',
    name: 'Hallowed Soldier',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Minion',
    description: 'Souls of the faithful, lifted up with divine weaponry.',
    motivesAndTactics: 'Obey, outmaneuver, punish, swarm',
    difficulty: 18,
    hitPoints: 1,
    stress: 2,
    attackModifier: 2,
    attack: {
      name: 'Sword and Shield',
      range: 'Melee',
      damage: '10 phy',
    },
    features: [
      {
        name: 'Minion (13) - Passive',
        description:
          'The Soldier is defeated when they take any damage. For every 13 damage a PC deals to the Soldier, defeat an additional Minion within range the attack would succeed against.',
      },
      {
        name: 'Divine Flight - Passive',
        description:
          'While the Soldier is flying, spend a Fear to move up to Far range instead of Close range before taking an action.',
      },
      {
        name: 'Group Attack - Action',
        description:
          'Spend a Fear to choose a target and spotlight all Hallowed Soldiers within Close range of them. Those Minions move into Melee range of the target and make one shared attack roll. On a success, they deal 10 physical damage each. Combine this damage.',
      },
    ],
  },
  {
    id: 'high-seraph',
    name: 'High Seraph',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Leader',
    description:
      'A divine champion, head of a hallowed host of warriors who enforce their god’s will.',
    motivesAndTactics: 'Enforce dogma, fly, pronounce judgment, smite',
    difficulty: 20,
    thresholds: {
      major: 37,
      severe: 70,
    },
    hitPoints: 7,
    stress: 5,
    attackModifier: 8,
    attack: {
      name: 'Holy Sword',
      range: 'Very Close',
      damage: '4d10+10 phy',
    },
    experience: 'Divine Knowledge +3',
    features: [
      {
        name: 'Relentless (2) - Passive',
        description:
          'The Seraph can be spotlighted up to three times per GM turn. Spend Fear as usual to spotlight them.',
      },
      {
        name: 'Divine Flight - Passive',
        description:
          'While the Seraph is flying, spend a Fear to move up to Far range instead of Close range before taking an action.',
      },
      {
        name: 'Judgment - Action',
        description:
          'Spend a Fear to make a target Guilty in the eyes of the Seraph’s god until the Seraph is defeated. While Guilty, the target doesn’t gain Hope on a result with Hope. When the Seraph succeeds on a standard attack against a Guilty target, they deal Severe damage instead of their standard damage. The Seraph can only mark one target at a time.',
      },
      {
        name: 'God Rays - Action',
        description:
          'Mark a Stress to reflect a sliver of divinity as a searing beam of light that hits up to twenty targets within Very Far range. Targets must make a Presence Reaction Roll, with disadvantage if they are marked Guilty. Targets who fail take 4d6+12 magic damage. Targets who succeed take half damage.',
      },
      {
        name: 'We Are One - Action',
        description:
          'Once per scene, spend a Fear to spotlight all other adversaries within Far range. Attacks they make while spotlighted in this way deal half damage.',
      },
    ],
  },
  {
    id: 'kraken',
    name: 'Kraken',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Solo',
    description:
      'A legendary beast of the sea, bigger than the largest galleon, with sucker-laden tentacles and a terrifying maw.',
    motivesAndTactics: 'Consume, crush, drown, grapple',
    difficulty: 20,
    thresholds: {
      major: 35,
      severe: 70,
    },
    hitPoints: 11,
    stress: 8,
    attackModifier: 7,
    attack: {
      name: 'Tentacles',
      range: 'Close',
      damage: '4d12+10 phy',
    },
    experience: 'Swimming +3',
    features: [
      {
        name: 'Relentless (3) - Passive',
        description:
          'The Kraken can be spotlighted up to three times per GM turn. Spend Fear as usual to spotlight them.',
      },
      {
        name: 'Many Tentacles - Passive',
        description:
          'While the Kraken has 7 or fewer marked HP, they can make their standard attack against two targets within range.',
      },
      {
        name: 'Grapple and Drown - Action',
        description:
          'Make an attack roll against a target within Close range. On a success, mark a Stress to grab them with a tentacle and drag them beneath the water. The target is Restrained and Vulnerable until they break free with a successful Strength Roll or the Kraken takes Major or greater damage. While Restrained and Vulnerable in this way, a target must mark a Stress when they make an action roll.',
      },
      {
        name: 'Boiling Blast - Action',
        description:
          'Spend a Fear to spew a line of boiling water at any number of targets in a line up to Far range. All targets must succeed on an Agility Reaction Roll or take 4d6+9 physical damage. If a target marks an Armor Slot to reduce the damage, they must also mark a Stress.',
      },
      {
        name: 'Momentum - Reaction',
        description: 'When the Kraken makes a successful attack against a PC, you gain a Fear.',
      },
    ],
  },
  {
    id: 'oracle-of-doom',
    name: 'Oracle of Doom',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Solo',
    description: 'A towering immortal and incarnation of fate, cursed to only see bad outcomes.',
    motivesAndTactics: 'Change environment, condemn, dishearten, toss aside',
    difficulty: 20,
    thresholds: {
      major: 38,
      severe: 68,
    },
    hitPoints: 11,
    stress: 10,
    attackModifier: 8,
    attack: {
      name: 'Psychic Attack',
      range: 'Far',
      damage: '4d8+9 mag',
    },
    experience: 'Boundless Knowledge +4',
    features: [
      {
        name: 'Terrifying - Passive',
        description:
          'When the Oracle makes a successful attack, all PCs within Far range lose a Hope and you gain a Fear.',
      },
      {
        name: 'Walls Closing In - Passive',
        description:
          'When a creature rolls a failure while within Very Far range of the Oracle, they must mark a Stress.',
      },
      {
        name: 'Pronounce Fate - Action',
        description:
          'Spend a Fear to present a target within Far range with a vision of their personal nightmare. The target must make a Knowledge Reaction Roll. On a failure, they lose all Hope and take 2d10+4 direct magic damage. On a success, they take half damage and lose a Hope.',
      },
      {
        name: 'Summon Tormentors - Action',
        description:
          'Once per day, spend 2 Fear to summon 2d4 Tier 2 or below Minions relevant to one of the PC’s personal nightmares. They appear at Close range relative to that PC.',
      },
      {
        name: 'Ominous Knowledge - Reaction',
        description:
          'When the Oracle sees a mortal creature, they instantly know one of their personal nightmares.',
      },
      {
        name: 'Vengeful Fate - Reaction',
        description:
          'When the Oracle marks HP from an attack within Very Close range, you can mark a Stress to knock the attacker back to Far range and deal 2d10+4 physical damage.',
      },
    ],
  },
  {
    id: 'outer-realms-abomination',
    name: 'Outer Realms Abomination',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Bruiser',
    description: 'A chaotic mockery of life, constantly in flux.',
    motivesAndTactics: 'Confuse, demolish, devour, undermine',
    difficulty: 19,
    thresholds: {
      major: 35,
      severe: 71,
    },
    hitPoints: 7,
    stress: 5,
    attackModifier: 0,
    attackBonusDice: {
      count: 2,
      die: 4,
    },
    attack: {
      name: 'Massive Pseudopod',
      range: 'Very Close',
      damage: '4d6+13 mag',
    },
    features: [
      {
        name: 'Chaotic Form - Passive',
        description:
          'When the Abomination attacks, roll 2d4 and use the result as their attack modifier.',
      },
      {
        name: 'Disorienting Presence - Passive',
        description:
          'When a target takes damage from the Abomination, they must make an Instinct Reaction Roll. On a failure, they gain disadvantage on their next action roll and you gain a Fear.',
      },
      {
        name: 'Reality Quake - Action',
        description:
          'Spend a Fear to rattle the edges of reality within Far range of the Abomination. All targets within that area must succeed on a Knowledge Reaction Roll or become Unstuck from reality until the end of the scene. When an Unstuck target spends Hope or marks Armor Slots, HP, or Stress, they must double the amount spent or marked.',
      },
      {
        name: 'Fungal Form - Reaction',
        description:
          'When the Abomination takes damage, reduce it by 1d20. If the Abomination marks 1 or fewer Hit Points from a successful attack against them, you gain a Fear.',
      },
    ],
  },
  {
    id: 'outer-realms-corrupter',
    name: 'Outer Realms Corrupter',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Support',
    description: 'A shifting, formless mass seemingly made of chromatic light.',
    motivesAndTactics: 'Confuse, distract, overwhelm',
    difficulty: 19,
    thresholds: {
      major: 27,
      severe: 47,
    },
    hitPoints: 4,
    stress: 3,
    attackModifier: 7,
    attack: {
      name: 'Corroding Pseudopod',
      range: 'Very Close',
      damage: '4d8+5 mag',
    },
    features: [
      {
        name: 'Will-Shattering Touch - Passive',
        description: 'When a PC takes damage from the Corrupter, they lose a Hope.',
      },
      {
        name: 'Disgorge Reality Flotsam - Action',
        description:
          'Mark a Stress to spew partially digested portions of consumed realities at all targets within Close range. Targets must succeed on a Knowledge Reaction Roll or mark 2 Stress.',
      },
    ],
  },
  {
    id: 'outer-realms-thrall',
    name: 'Outer Realms Thrall',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Minion',
    description: 'A vaguely humanoid form stripped of memory and identity.',
    motivesAndTactics: 'Destroy, disgust, disorient, intimidate',
    difficulty: 17,
    hitPoints: 1,
    stress: 1,
    attackModifier: 3,
    attack: {
      name: 'Claws and Teeth',
      range: 'Very Close',
      damage: '11 phy',
    },
    features: [
      {
        name: 'Minion (13) - Passive',
        description:
          'The Thrall is defeated when they take any damage. For every 13 damage a PC deals to the Thrall, defeat an additional Minion within range the attack would succeed against.',
      },
      {
        name: 'Group Attack - Action',
        description:
          'Spend a Fear to choose a target and spotlight all Outer Realm Thralls within Close range of them. Those Minions move into Melee range of the target and make one shared attack roll. On a success, they deal 11 physical damage each. Combine this damage.',
      },
    ],
  },
  {
    id: 'perfected-zombie',
    name: 'Perfected Zombie',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Bruiser',
    description: 'A towering, muscular zombie with magically infused strength and skill.',
    motivesAndTactics: 'Consume, hound, maim, terrify',
    difficulty: 20,
    thresholds: {
      major: 40,
      severe: 70,
    },
    hitPoints: 9,
    stress: 4,
    attackModifier: 4,
    attack: {
      name: 'Greataxe',
      range: 'Very Close',
      damage: '4d12+15 phy',
    },
    features: [
      {
        name: 'Terrifying - Passive',
        description: 'On successful attack, all PCs in Far range lose Hope and you gain Fear.',
      },
      {
        name: 'Fearsome Presence - Passive',
        description: 'PCs can’t spend Hope to use features against the Zombie.',
      },
      {
        name: 'Perfect Strike - Action',
        description:
          'Mark a Stress to attack all targets within Very Close range; on success, targets are Vulnerable until next rest.',
      },
      {
        name: 'Skilled Opportunist - Reaction',
        description:
          "When another adversary deals damage to target within Very Close range of Zombie, spend a Fear to add Zombie's standard attack damage to the damage roll.",
      },
    ],
  },
  {
    id: 'volcanic-dragon-ashen-tyrant',
    name: 'Volcanic Dragon: Ashen Tyrant',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Solo',
    description:
      'A legendary, lava-hardened dragon. No enemy has ever had the insolence to wound the dragon so.',
    motivesAndTactics: 'Choke, fly, intimidate, kill or be killed',
    difficulty: 18,
    thresholds: {
      major: 29,
      severe: 55,
    },
    hitPoints: 8,
    stress: 5,
    attackModifier: 10,
    attack: {
      name: 'Claws and Teeth',
      range: 'Close',
      damage: '4d12+15 phy',
    },
    experience: 'Hunt from Above +5',
    features: [
      {
        name: 'Relentless (4) - Passive',
        description:
          'The Ashen Tyrant can be spotlighted up to four times per GM turn. Spend Fear as usual to spotlight them.',
      },
      {
        name: 'Cornered - Passive',
        description: 'Mark a Stress instead of spending a Fear to spotlight the Ashen Tyrant.',
      },
      {
        name: 'Ashes to Ashes - Passive',
        description:
          'When a PC rolls a failure while within Close range of the Ashen Tyrant, they lose a Hope and you gain a Fear. If the PC can’t lose a Hope, they must mark a HP.',
      },
      {
        name: 'Desperate Rampage - Action',
        description:
          'Mark 3 Stress to make an attack against all targets within Close range. Targets the Ashen Tyrant succeeds against take 2d20+2 physical damage, are knocked back to Close range of where they were, and must mark a Stress.',
      },
      {
        name: 'Ashen Cloud - Action',
        description:
          'Spend a Fear to smash the ground beneath an adversary within Far range. While within the ash cloud, a target has disadvantage on action rolls. The ash cloud clears the next time an adversary is spotlighted.',
      },
      {
        name: 'Apocalyptic Thrashing - Action',
        description:
          'Countdown (1d12). Spend a Fear to activate it. It ticks down when a PC rolls with Fear. When it reaches 0, the Ashen Tyrant thrashes about, causing environmental damage (such as an earthquake, avalanche, or collapsing walls). All targets within Far range must make a Strength Reaction Roll. Targets who fail take 2d10+10 physical damage and are Restrained by the rubble until they break free with a successful Strength Roll. Targets who succeed take half damage. If the Ashen Tyrant is defeated while this countdown is active, trigger the countdown immediately as the destruction caused by their death throes.',
      },
    ],
  },
  {
    id: 'volcanic-dragon-molten-scourge',
    name: 'Volcanic Dragon: Molten Scourge',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Solo',
    description: 'Engaged by their wounds, the dragon bursts into molten lava.',
    motivesAndTactics: 'Douse with lava, incinerate, repel invaders, respawn',
    difficulty: 20,
    thresholds: {
      major: 30,
      severe: 58,
    },
    hitPoints: 7,
    stress: 5,
    attackModifier: 9,
    attack: {
      name: 'Lava-Coated Claws',
      range: 'Close',
      damage: '4d12+4 phy',
    },
    experience: 'Hunt from Above +5',
    features: [
      {
        name: 'Relentless (3) - Passive',
        description:
          'Can be spotlighted up to three times per GM turn. Spend Fear as usual to spotlight them.',
      },
      {
        name: 'Cracked Scales - Passive',
        description:
          'When the Molten Scourge takes damage, roll a number of d6s equal to HP marked. For each result of 4 or higher, you gain a Fear.',
      },
      {
        name: 'Shattering Might - Action',
        description:
          'Mark a Stress to make an attack against a target within Very Close range. On a success, target takes 4d8+14 physical damage, loses a Hope, and is knocked back to Close range. The Scourge clears a Stress.',
      },
      {
        name: 'Eruption - Action',
        description:
          'Spend a Fear to erupt lava from beneath the Scourge’s scales, filling area within Very Close range with lava. All targets must make Agility Reaction Roll or take 4d6+6 physical damage and be knocked back to Close range. The area remains lava (6 HP damage on entry or action).',
      },
      {
        name: 'Volcanic Breath - Reaction',
        description:
          'When the Scourge takes Major damage, roll d10. On 8+, erupt lava in Very Close range: Agility Reaction Roll or take 2d10+4 physical damage, mark 1d4 Stress, and are Vulnerable until clearing a Stress; success = half damage + mark a Stress.;Lava Splash - Reaction;When the Scourge takes Severe damage from attack within Very Close, molten blood deals 2d10+4 direct physical damage to attacker.;Ashen Vengeance (Phase Change) - Reaction;When the Scourge marks last HP, replace with Ashen Tyrant and immediately spotlight.',
      },
    ],
  },
  {
    id: 'volcanic-dragon-obsidian-predator',
    name: 'Volcanic Dragon: Obsidian Predator',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Solo',
    description: 'A massive winged creature with obsidian scales and impossibly sharp claws.',
    motivesAndTactics: 'Defend lair, dive-bomb, fly, hunt, intimidate',
    difficulty: 19,
    thresholds: {
      major: 33,
      severe: 65,
    },
    hitPoints: 6,
    stress: 5,
    attackModifier: 8,
    attack: {
      name: 'Obsidian Claws',
      range: 'Close',
      damage: '4d10+4 phy',
    },
    experience: 'Hunt from Above +5',
    features: [
      {
        name: 'Relentless (2) - Passive',
        description:
          'Can be spotlighted up to two times per GM turn. Spend Fear as usual to spotlight.',
      },
      {
        name: 'Flying - Passive',
        description: 'While flying, gains +3 Difficulty.',
      },
      {
        name: 'Obsidian Scales - Passive',
        description: 'Resistant to physical damage.',
      },
      {
        name: 'Obsidian Tail - Action',
        description:
          'Mark a Stress to make attack against all targets within Close range. Success: 4d6+4 physical damage, knocked to Far range and Vulnerable until next roll with Hope.',
      },
      {
        name: 'Dive-Bomb - Action',
        description:
          'If flying, mark a Stress to choose point within Far range, move there, attack all targets within Very Close range; on success, 2d10+6 physical, mark a Stress, lose a Hope.',
      },
      {
        name: 'Erupting Rage (Phase Change) - Reaction',
        description: 'When marks last HP, replace with Molten Scourge and immediately spotlight.',
      },
    ],
  },
  {
    id: 'zombie-legion',
    name: 'Zombie Legion',
    system: 'daggerheart',
    source: 'SRD 1.0',
    tier: 4,
    role: 'Horde',
    roleDetail: '(3/HP)',
    description: 'A large pack of undead, still powerful despite their rotting flesh.',
    motivesAndTactics: 'Consume brain, shred flesh, surround',
    difficulty: 17,
    thresholds: {
      major: 25,
      severe: 45,
    },
    hitPoints: 8,
    stress: 5,
    attackModifier: 2,
    attack: {
      name: 'Tentacles',
      range: 'Close',
      damage: '4d6+10 phy',
    },
    features: [
      {
        name: 'Horde (2d6+5) - Passive',
        description:
          'When Legion has half or more HP marked, standard attack deals 2d6+5 physical damage instead.',
      },
      {
        name: 'Unyielding - Passive',
        description: 'Legion has resistance to physical damage.',
      },
      {
        name: 'Relentless (2) - Passive',
        description:
          'Legion can be spotlighted up to two times per GM turn. Spend Fear as usual to spotlight.',
      },
      {
        name: 'Overwhelm - Reaction',
        description:
          'When Legion takes Minor damage from attack within Melee, mark a Stress to make standard attack with advantage against the attacker.',
      },
    ],
  },
];
