// GENERATED by scripts/encode-35e-monsters.mjs: olimot/srd-v3.5-md core
// name list intersected with Rughalt/D35E bestiary.db structured data (both
// OGL — see docs/srd-sources.md). Regenerate with:
// node scripts/encode-35e-monsters.mjs

import { Monster } from '../../../../types/creatures/monsters';

export const srdCr01Monsters35e: Monster[] = [
  {
    id: 'rat-35e-monster',
    name: 'Rat',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'tiny',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.125,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 1,
      die: 'd8',
      modifier: -1,
      notation: '1d8-1',
    },
    speed: {
      walk: 15,
      swim: 15,
      climb: 15,
    },
    abilities: {
      str: 2,
      dex: 15,
      con: 10,
      int: 2,
      wis: 12,
      cha: 2,
    },
    d20Saves: {
      fort: 2,
      ref: 4,
      will: 1,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: -2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd3',
              notation: '1d3-4',
              modifier: -4,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'donkey-35e-monster',
    name: 'Donkey',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.166,
    experiencePoints: 0,
    armorClass: 13,
    hitPoints: {
      count: 2,
      die: 'd8',
      modifier: 2,
      notation: '2d8+2',
    },
    speed: {
      walk: 30,
    },
    abilities: {
      str: 10,
      dex: 13,
      con: 12,
      int: 2,
      wis: 11,
      cha: 4,
    },
    d20Saves: {
      fort: 4,
      ref: 4,
      will: 0,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 1,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd2',
              notation: '1d2',
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'lizard-35e-monster',
    name: 'Lizard',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'tiny',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.166,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 1,
      die: 'd8',
      modifier: -1,
      notation: '1d8-1',
    },
    speed: {
      walk: 20,
      climb: 20,
    },
    abilities: {
      str: 3,
      dex: 15,
      con: 10,
      int: 1,
      wis: 12,
      cha: 2,
    },
    d20Saves: {
      fort: 2,
      ref: 4,
      will: 1,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: -2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4-4',
              modifier: -4,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'monkey-35e-monster',
    name: 'Monkey',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'tiny',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.166,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 1,
      die: 'd8',
      modifier: -1,
      notation: '1d8-1',
    },
    speed: {
      walk: 30,
      climb: 30,
    },
    abilities: {
      str: 3,
      dex: 15,
      con: 10,
      int: 2,
      wis: 12,
      cha: 5,
    },
    d20Saves: {
      fort: 2,
      ref: 4,
      will: 1,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: -2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd3',
              notation: '1d3-4',
              modifier: -4,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'raven-35e-monster',
    name: 'Raven',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'tiny',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.166,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 1,
      die: 'd8',
      modifier: -1,
      notation: '1d8-1',
    },
    speed: {
      walk: 10,
      fly: 40,
    },
    abilities: {
      str: 1,
      dex: 15,
      con: 10,
      int: 2,
      wis: 14,
      cha: 6,
    },
    d20Saves: {
      fort: 2,
      ref: 4,
      will: 2,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Claw',
        description:
          'The creature rips with a sharp appendage, dealing piercing and slashing damage.',
        attackBonus: -3,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd2',
              notation: '1d2-5',
              modifier: -5,
            },
            type: 'slashing',
          },
        ],
      },
    ],
  },
  {
    id: 'cat-35e-monster',
    name: 'Cat',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'tiny',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.25,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 1,
      die: 'd8',
      modifier: -1,
      notation: '1d8-1',
    },
    speed: {
      walk: 30,
    },
    abilities: {
      str: 3,
      dex: 15,
      con: 10,
      int: 2,
      wis: 12,
      cha: 7,
    },
    d20Saves: {
      fort: 2,
      ref: 4,
      will: 1,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: -2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd3',
              notation: '1d3-4',
              modifier: -4,
            },
            type: 'piercing',
          },
        ],
      },
      {
        name: 'Claw',
        description:
          'The creature rips with a sharp appendage, dealing piercing and slashing damage.',
        attackBonus: -2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd2',
              notation: '1d2-4',
              modifier: -4,
            },
            type: 'slashing',
          },
        ],
      },
    ],
  },
  {
    id: 'owl-35e-monster',
    name: 'Owl',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'tiny',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.25,
    experiencePoints: 0,
    armorClass: 17,
    hitPoints: {
      count: 1,
      die: 'd8',
      modifier: -1,
      notation: '1d8-1',
    },
    speed: {
      walk: 10,
      fly: 40,
    },
    abilities: {
      str: 4,
      dex: 17,
      con: 10,
      int: 2,
      wis: 14,
      cha: 4,
    },
    d20Saves: {
      fort: 2,
      ref: 5,
      will: 2,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Talon',
        description:
          'The creature rips with a sharp appendage, dealing piercing and slashing damage.',
        attackBonus: -1,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4-3',
              modifier: -3,
            },
            type: 'slashing',
          },
        ],
      },
    ],
  },
  {
    id: 'pony-35e-monster',
    name: 'Pony',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.25,
    experiencePoints: 0,
    armorClass: 13,
    hitPoints: {
      count: 2,
      die: 'd8',
      modifier: 2,
      notation: '2d8+2',
    },
    speed: {
      walk: 40,
    },
    abilities: {
      str: 13,
      dex: 13,
      con: 12,
      int: 2,
      wis: 11,
      cha: 4,
    },
    d20Saves: {
      fort: 4,
      ref: 4,
      will: 0,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Hoof',
        description: 'The creature attacks with its hoof, dealing bludgeoning damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd3',
              notation: '1d3+1',
              modifier: 1,
            },
            type: 'bludgeoning',
          },
        ],
      },
    ],
  },
  {
    id: 'weasel-35e-monster',
    name: 'Weasel',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'tiny',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.25,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 1,
      die: 'd8',
      modifier: -1,
      notation: '1d8-1',
    },
    speed: {
      walk: 20,
      climb: 20,
    },
    abilities: {
      str: 3,
      dex: 15,
      con: 10,
      int: 2,
      wis: 12,
      cha: 5,
    },
    d20Saves: {
      fort: 2,
      ref: 4,
      will: 1,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: -2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd3',
              notation: '1d3-4',
              modifier: -4,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'dog-35e-monster',
    name: 'Dog',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'small',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.33,
    experiencePoints: 0,
    armorClass: 15,
    hitPoints: {
      count: 1,
      die: 'd8',
      modifier: 1,
      notation: '1d8+1',
    },
    speed: {
      walk: 40,
    },
    abilities: {
      str: 13,
      dex: 17,
      con: 15,
      int: 2,
      wis: 12,
      cha: 6,
    },
    d20Saves: {
      fort: 4,
      ref: 5,
      will: 1,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4+1',
              modifier: 1,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'giant-fire-beetle-35e-monster',
    name: 'Giant Fire Beetle',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'small',
    type: 'vermin',
    alignment: 'unaligned',
    challengeRating: 0.33,
    experiencePoints: 0,
    armorClass: 16,
    hitPoints: {
      count: 1,
      die: 'd8',
      modifier: -1,
      notation: '1d8-1',
    },
    speed: {
      walk: 30,
    },
    abilities: {
      str: 10,
      dex: 11,
      con: 11,
      int: 0,
      wis: 10,
      cha: 7,
    },
    d20Saves: {
      fort: 2,
      ref: 0,
      will: 0,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 1,
        damage: [
          {
            dice: {
              count: 2,
              die: 'd4',
              notation: '2d4',
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'hawk-35e-monster',
    name: 'Hawk',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'tiny',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.33,
    experiencePoints: 0,
    armorClass: 17,
    hitPoints: {
      count: 1,
      die: 'd8',
      modifier: -1,
      notation: '1d8-1',
    },
    speed: {
      walk: 10,
      fly: 60,
    },
    abilities: {
      str: 6,
      dex: 17,
      con: 10,
      int: 2,
      wis: 14,
      cha: 6,
    },
    d20Saves: {
      fort: 2,
      ref: 5,
      will: 2,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Talon',
        description:
          'The creature rips with a sharp appendage, dealing piercing and slashing damage.',
        attackBonus: 0,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4-2',
              modifier: -2,
            },
            type: 'slashing',
          },
        ],
      },
    ],
  },
  {
    id: 'baboon-35e-monster',
    name: 'Baboon',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.5,
    experiencePoints: 0,
    armorClass: 13,
    hitPoints: {
      count: 1,
      die: 'd8',
      notation: '1d8',
    },
    speed: {
      walk: 40,
      climb: 30,
    },
    abilities: {
      str: 15,
      dex: 14,
      con: 12,
      int: 2,
      wis: 12,
      cha: 4,
    },
    d20Saves: {
      fort: 3,
      ref: 4,
      will: 1,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6+2',
              modifier: 2,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'badger-35e-monster',
    name: 'Badger',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'small',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.5,
    experiencePoints: 0,
    armorClass: 15,
    hitPoints: {
      count: 1,
      die: 'd8',
      modifier: 1,
      notation: '1d8+1',
    },
    speed: {
      walk: 30,
    },
    abilities: {
      str: 8,
      dex: 17,
      con: 15,
      int: 2,
      wis: 12,
      cha: 6,
    },
    d20Saves: {
      fort: 4,
      ref: 5,
      will: 1,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 0,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd3',
              notation: '1d3-1',
              modifier: -1,
            },
            type: 'piercing',
          },
        ],
      },
      {
        name: 'Claw',
        description:
          'The creature rips with a sharp appendage, dealing piercing and slashing damage.',
        attackBonus: 0,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd2',
              notation: '1d2-1',
              modifier: -1,
            },
            type: 'slashing',
          },
        ],
      },
    ],
  },
  {
    id: 'eagle-35e-monster',
    name: 'Eagle',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'small',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.5,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 1,
      die: 'd8',
      notation: '1d8',
    },
    speed: {
      walk: 10,
      fly: 80,
    },
    abilities: {
      str: 10,
      dex: 15,
      con: 12,
      int: 2,
      wis: 14,
      cha: 6,
    },
    d20Saves: {
      fort: 3,
      ref: 4,
      will: 2,
    },
    baseAttackBonus: 0,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Talon',
        description:
          'The creature rips with a sharp appendage, dealing piercing and slashing damage.',
        attackBonus: 1,
      },
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 1,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4',
            },
            type: 'piercing',
          },
        ],
      },
      {
        name: 'Talon',
        description:
          'The creature rips with a sharp appendage, dealing piercing and slashing damage.',
        attackBonus: 1,
      },
    ],
  },
  {
    id: 'locathah-35e-monster',
    name: 'Locathah',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'humanoid',
    alignment: 'true neutral',
    challengeRating: 0.5,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 2,
      die: 'd8',
      notation: '2d8',
    },
    speed: {
      walk: 10,
      swim: 60,
    },
    abilities: {
      str: 10,
      dex: 12,
      con: 10,
      int: 10,
      wis: 13,
      cha: 11,
    },
    d20Saves: {
      fort: 0,
      ref: 4,
      will: 1,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Light Crossbow',
        description:
          'You draw a light crossbow back by pulling a lever. Loading a light crossbow is a move action that provokes attacks of opportunity. Normally, operating a light crossbow requires two hands. However, you can shoot, but not load, a light crossbow with one hand at a –2 penalty on attack rolls. You can sh',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd8',
              notation: '1d8',
            },
            type: 'piercing',
          },
        ],
      },
      {
        name: 'Longspear',
        description:
          'A longspear has reach. You can strike opponents 10 feet away with it, but you can’t use it against an adjacent foe. If you use a ready action to set a longspear against a charge, you deal double damage on a successful hit against a charging character.',
        attackBonus: 1,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd8',
              notation: '1d8',
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'pony-war-35e-monster',
    name: 'Pony, War',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.5,
    experiencePoints: 0,
    armorClass: 13,
    hitPoints: {
      count: 2,
      die: 'd8',
      modifier: 4,
      notation: '2d8+4',
    },
    speed: {
      walk: 40,
    },
    abilities: {
      str: 15,
      dex: 13,
      con: 14,
      int: 2,
      wis: 11,
      cha: 4,
    },
    d20Saves: {
      fort: 5,
      ref: 4,
      will: 0,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Hoof',
        description: 'The creature attacks with its hoof, dealing bludgeoning damage.',
        attackBonus: 3,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd3',
              notation: '1d3+2',
              modifier: 2,
            },
            type: 'bludgeoning',
          },
        ],
      },
    ],
  },
  {
    id: 'porpoise-35e-monster',
    name: 'Porpoise',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 0.5,
    experiencePoints: 0,
    armorClass: 15,
    hitPoints: {
      count: 2,
      die: 'd8',
      modifier: 2,
      notation: '2d8+2',
    },
    speed: {
      walk: 80,
    },
    abilities: {
      str: 11,
      dex: 17,
      con: 13,
      int: 2,
      wis: 12,
      cha: 6,
    },
    d20Saves: {
      fort: 4,
      ref: 6,
      will: 1,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Slam',
        description:
          'The creature batters opponents with an appendage, dealing bludgeoning damage.',
        attackBonus: 1,
        damage: [
          {
            dice: {
              count: 2,
              die: 'd4',
              notation: '2d4',
            },
            type: 'bludgeoning',
          },
        ],
      },
    ],
  },
  {
    id: 'stirge-35e-monster',
    name: 'Stirge',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'tiny',
    type: 'magical-beast',
    alignment: 'true neutral',
    challengeRating: 0.5,
    experiencePoints: 0,
    armorClass: 16,
    hitPoints: {
      count: 1,
      die: 'd10',
      modifier: -1,
      notation: '1d10-1',
    },
    speed: {
      walk: 10,
      fly: 40,
    },
    abilities: {
      str: 3,
      dex: 19,
      con: 10,
      int: 1,
      wis: 12,
      cha: 6,
    },
    d20Saves: {
      fort: 2,
      ref: 6,
      will: 1,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [],
  },
  {
    id: 'camel-35e-monster',
    name: 'Camel',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'large',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 13,
    hitPoints: {
      count: 3,
      die: 'd8',
      modifier: 5,
      notation: '3d8+5',
    },
    speed: {
      walk: 50,
    },
    abilities: {
      str: 18,
      dex: 16,
      con: 14,
      int: 2,
      wis: 11,
      cha: 4,
    },
    d20Saves: {
      fort: 5,
      ref: 6,
      will: 1,
    },
    baseAttackBonus: 2,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 5,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4+4',
              modifier: 4,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'darkmantle-35e-monster',
    name: 'Darkmantle',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'small',
    type: 'magical-beast',
    alignment: 'true neutral',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 17,
    hitPoints: {
      count: 1,
      die: 'd10',
      notation: '1d10',
    },
    speed: {
      walk: 20,
      fly: 30,
    },
    abilities: {
      str: 16,
      dex: 10,
      con: 13,
      int: 2,
      wis: 10,
      cha: 10,
    },
    d20Saves: {
      fort: 3,
      ref: 2,
      will: 0,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Constrict',
        description:
          'A creature with this special attack can crush an opponent, dealing bludgeoning damage, after making a successful grapple check. The amount of damage is given in the creature s entry. If the creature also has the improved grab ability it deals constriction damage in addition to damage dealt by the we',
        attackBonus: 5,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4+3',
              modifier: 3,
            },
            type: 'bludgeoning',
          },
        ],
      },
      {
        name: 'Slam',
        description:
          'The creature batters opponents with an appendage, dealing bludgeoning damage.',
        attackBonus: 5,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4+3',
              modifier: 3,
            },
            type: 'bludgeoning',
          },
        ],
      },
    ],
  },
  {
    id: 'dog-riding-35e-monster',
    name: 'Dog, Riding',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 16,
    hitPoints: {
      count: 2,
      die: 'd8',
      modifier: 4,
      notation: '2d8+4',
    },
    speed: {
      walk: 40,
    },
    abilities: {
      str: 15,
      dex: 15,
      con: 15,
      int: 2,
      wis: 12,
      cha: 6,
    },
    d20Saves: {
      fort: 5,
      ref: 5,
      will: 1,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 3,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6+2',
              modifier: 2,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'ghoul-35e-monster',
    name: 'Ghoul',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'undead',
    alignment: 'chaotic evil',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 2,
      die: 'd12',
      notation: '2d12',
    },
    speed: {
      walk: 30,
    },
    abilities: {
      str: 13,
      dex: 15,
      con: 0,
      int: 13,
      wis: 14,
      cha: 12,
    },
    d20Saves: {
      fort: 1,
      ref: 2,
      will: 5,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6+1',
              modifier: 1,
            },
            type: 'piercing',
          },
        ],
      },
      {
        name: 'Claw',
        description:
          'The creature rips with a sharp appendage, dealing piercing and slashing damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd3',
              notation: '1d3+1',
              modifier: 1,
            },
            type: 'slashing',
          },
        ],
      },
    ],
  },
  {
    id: 'giant-bee-35e-monster',
    name: 'Giant Bee',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'vermin',
    alignment: 'unaligned',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 3,
      die: 'd8',
      modifier: -1,
      notation: '3d8-1',
    },
    speed: {
      walk: 20,
      fly: 80,
    },
    abilities: {
      str: 11,
      dex: 14,
      con: 11,
      int: 0,
      wis: 12,
      cha: 9,
    },
    d20Saves: {
      fort: 3,
      ref: 3,
      will: 2,
    },
    baseAttackBonus: 2,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Sting',
        description:
          'The creature stabs with a stinger, dealing piercing damage. Sting attacks usually deal damage from poison in addition to hit point damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4',
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'gnoll-35e-monster',
    name: 'Gnoll',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'humanoid',
    alignment: 'chaotic evil',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 11,
    hitPoints: {
      count: 2,
      die: 'd8',
      modifier: 2,
      notation: '2d8+2',
    },
    speed: {
      walk: 30,
    },
    abilities: {
      str: 15,
      dex: 10,
      con: 13,
      int: 8,
      wis: 11,
      cha: 8,
    },
    d20Saves: {
      fort: 1,
      ref: 3,
      will: 0,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Shortbow',
        description:
          'You need at least two hands to use a bow, regardless of its size. You can use a shortbow while mounted. If you have a penalty for low Strength, apply it to damage rolls when you use a shortbow. If you have a bonus for high Strength, you can apply it to damage rolls when you use a composite shortbow ',
        attackBonus: 1,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6+2',
              modifier: 2,
            },
            type: 'piercing',
          },
        ],
      },
      {
        name: 'Battleaxe',
        description: 'The battleaxe is the most common melee weapon among dwarves.',
        attackBonus: 3,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd8',
              notation: '1d8+2',
              modifier: 2,
            },
            type: 'slashing',
          },
        ],
      },
    ],
  },
  {
    id: 'grimlock-35e-monster',
    name: 'Grimlock',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'monstrous-humanoid',
    alignment: 'neutral evil',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 15,
    hitPoints: {
      count: 2,
      die: 'd8',
      modifier: 2,
      notation: '2d8+2',
    },
    speed: {
      walk: 30,
    },
    abilities: {
      str: 15,
      dex: 13,
      con: 13,
      int: 10,
      wis: 8,
      cha: 6,
    },
    d20Saves: {
      fort: 1,
      ref: 4,
      will: 2,
    },
    baseAttackBonus: 2,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Battleaxe',
        description: 'The battleaxe is the most common melee weapon among dwarves.',
        attackBonus: 4,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd8',
              notation: '1d8+2',
              modifier: 2,
            },
            type: 'slashing',
          },
        ],
      },
    ],
  },
  {
    id: 'homunculus-35e-monster',
    name: 'Homunculus',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'tiny',
    type: 'construct',
    alignment: 'any',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 2,
      die: 'd10',
      notation: '2d10',
    },
    speed: {
      walk: 20,
      fly: 50,
    },
    abilities: {
      str: 8,
      dex: 15,
      con: 0,
      int: 10,
      wis: 12,
      cha: 7,
    },
    d20Saves: {
      fort: 0,
      ref: 4,
      will: 1,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4-1',
              modifier: -1,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'hyena-35e-monster',
    name: 'Hyena',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 2,
      die: 'd8',
      modifier: 4,
      notation: '2d8+4',
    },
    speed: {
      walk: 50,
    },
    abilities: {
      str: 14,
      dex: 15,
      con: 15,
      int: 2,
      wis: 13,
      cha: 6,
    },
    d20Saves: {
      fort: 5,
      ref: 5,
      will: 1,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 3,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6+2',
              modifier: 2,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'krenshar-35e-monster',
    name: 'Krenshar',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'magical-beast',
    alignment: 'true neutral',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 15,
    hitPoints: {
      count: 2,
      die: 'd10',
      notation: '2d10',
    },
    speed: {
      walk: 40,
    },
    abilities: {
      str: 11,
      dex: 14,
      con: 11,
      int: 6,
      wis: 12,
      cha: 13,
    },
    d20Saves: {
      fort: 3,
      ref: 5,
      will: 1,
    },
    baseAttackBonus: 2,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6',
            },
            type: 'piercing',
          },
        ],
      },
      {
        name: 'Claw',
        description:
          'The creature rips with a sharp appendage, dealing piercing and slashing damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4',
            },
            type: 'slashing',
          },
        ],
      },
    ],
  },
  {
    id: 'lizardfolk-35e-monster',
    name: 'Lizardfolk',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'humanoid',
    alignment: 'true neutral',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 15,
    hitPoints: {
      count: 2,
      die: 'd8',
      modifier: 2,
      notation: '2d8+2',
    },
    speed: {
      walk: 30,
    },
    abilities: {
      str: 13,
      dex: 10,
      con: 13,
      int: 9,
      wis: 10,
      cha: 10,
    },
    d20Saves: {
      fort: 1,
      ref: 3,
      will: 0,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Javelin',
        description:
          'This weapon is a light, flexible spear intended for throwing. You can use it in melee, but not well. Since it is not designed for melee, you are treated as nonproficient with it and take a –4 penalty on attack rolls if you use a javelin as a melee weapon.',
        attackBonus: 1,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6+1',
              modifier: 1,
            },
            type: 'piercing',
          },
        ],
      },
      {
        name: 'Club',
        description: 'A wooden club is so easy to find and fashion that it has no cost.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6+1',
              modifier: 1,
            },
            type: 'bludgeoning',
          },
        ],
      },
      {
        name: 'Claw',
        description:
          'The creature rips with a sharp appendage, dealing piercing and slashing damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4+1',
              modifier: 1,
            },
            type: 'slashing',
          },
        ],
      },
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4+1',
              modifier: 1,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'manta-ray-35e-monster',
    name: 'Manta Ray',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'large',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 12,
    hitPoints: {
      count: 4,
      die: 'd8',
      notation: '4d8',
    },
    speed: {
      walk: 30,
    },
    abilities: {
      str: 15,
      dex: 11,
      con: 10,
      int: 1,
      wis: 12,
      cha: 2,
    },
    d20Saves: {
      fort: 4,
      ref: 4,
      will: 2,
    },
    baseAttackBonus: 3,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Ram',
        description: 'Ram attack (melee).',
        attackBonus: 4,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6+2',
              modifier: 2,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'mule-35e-monster',
    name: 'Mule',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'large',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 13,
    hitPoints: {
      count: 3,
      die: 'd8',
      modifier: 8,
      notation: '3d8+8',
    },
    speed: {
      walk: 30,
    },
    abilities: {
      str: 16,
      dex: 13,
      con: 17,
      int: 2,
      wis: 11,
      cha: 6,
    },
    d20Saves: {
      fort: 6,
      ref: 4,
      will: 1,
    },
    baseAttackBonus: 2,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Hoof',
        description: 'The creature attacks with its hoof, dealing bludgeoning damage.',
        attackBonus: 4,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4+3',
              modifier: 3,
            },
            type: 'bludgeoning',
          },
        ],
      },
    ],
  },
  {
    id: 'octopus-35e-monster',
    name: 'Octopus',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'small',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 16,
    hitPoints: {
      count: 2,
      die: 'd8',
      notation: '2d8',
    },
    speed: {
      walk: 20,
      swim: 30,
    },
    abilities: {
      str: 12,
      dex: 17,
      con: 11,
      int: 2,
      wis: 12,
      cha: 3,
    },
    d20Saves: {
      fort: 3,
      ref: 6,
      will: 1,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 3,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd3',
              notation: '1d3+1',
              modifier: 1,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'pseudodragon-35e-monster',
    name: 'Pseudodragon',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'tiny',
    type: 'dragon',
    alignment: 'neutral good',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 18,
    hitPoints: {
      count: 2,
      die: 'd12',
      modifier: 2,
      notation: '2d12+2',
    },
    speed: {
      walk: 15,
      fly: 60,
    },
    abilities: {
      str: 6,
      dex: 15,
      con: 13,
      int: 10,
      wis: 12,
      cha: 10,
    },
    d20Saves: {
      fort: 4,
      ref: 5,
      will: 4,
    },
    baseAttackBonus: 2,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 2,
      },
      {
        name: 'Sting',
        description:
          'The creature stabs with a stinger, dealing piercing damage. Sting attacks usually deal damage from poison in addition to hit point damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd3',
              notation: '1d3-2',
              modifier: -2,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'squid-35e-monster',
    name: 'Squid',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 16,
    hitPoints: {
      count: 3,
      die: 'd8',
      modifier: -1,
      notation: '3d8-1',
    },
    speed: {
      walk: 60,
    },
    abilities: {
      str: 14,
      dex: 17,
      con: 11,
      int: 1,
      wis: 12,
      cha: 2,
    },
    d20Saves: {
      fort: 3,
      ref: 6,
      will: 2,
    },
    baseAttackBonus: 2,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 4,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6+2',
              modifier: 2,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'troglodyte-35e-monster',
    name: 'Troglodyte',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'humanoid',
    alignment: 'chaotic evil',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 15,
    hitPoints: {
      count: 2,
      die: 'd8',
      modifier: 4,
      notation: '2d8+4',
    },
    speed: {
      walk: 30,
    },
    abilities: {
      str: 10,
      dex: 9,
      con: 14,
      int: 8,
      wis: 10,
      cha: 10,
    },
    d20Saves: {
      fort: 2,
      ref: 2,
      will: 0,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Javelin',
        description:
          'This weapon is a light, flexible spear intended for throwing. You can use it in melee, but not well. Since it is not designed for melee, you are treated as nonproficient with it and take a –4 penalty on attack rolls if you use a javelin as a melee weapon.',
        attackBonus: 0,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6',
            },
            type: 'piercing',
          },
        ],
      },
      {
        name: 'Club',
        description: 'A wooden club is so easy to find and fashion that it has no cost.',
        attackBonus: 1,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6',
            },
            type: 'bludgeoning',
          },
        ],
      },
      {
        name: 'Claw',
        description:
          'The creature rips with a sharp appendage, dealing piercing and slashing damage.',
        attackBonus: 1,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4',
            },
            type: 'slashing',
          },
        ],
      },
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 1,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd4',
              notation: '1d4',
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
  {
    id: 'wolf-35e-monster',
    name: 'Wolf',
    system: 'dnd-3.5e',
    source: 'SRD 3.5',
    size: 'medium',
    type: 'animal',
    alignment: 'unaligned',
    challengeRating: 1,
    experiencePoints: 0,
    armorClass: 14,
    hitPoints: {
      count: 2,
      die: 'd8',
      modifier: 4,
      notation: '2d8+4',
    },
    speed: {
      walk: 50,
    },
    abilities: {
      str: 13,
      dex: 15,
      con: 15,
      int: 2,
      wis: 12,
      cha: 6,
    },
    d20Saves: {
      fort: 5,
      ref: 5,
      will: 1,
    },
    baseAttackBonus: 1,
    senses: [],
    languages: [],
    actions: [
      {
        name: 'Bite',
        description:
          'The creature attacks with its mouth, dealing piercing, slashing, and bludgeoning damage.',
        attackBonus: 2,
        damage: [
          {
            dice: {
              count: 1,
              die: 'd6',
              notation: '1d6+1',
              modifier: 1,
            },
            type: 'piercing',
          },
        ],
      },
    ],
  },
];
