/**
 * Compute register (Denominator B) for Daggerheart, cited against the
 * Daggerheart SRD 1.0. Derived math: src/rules/daggerheartDerived.ts.
 * Triggered/narrative card effects and Hope/Fear narrative resolution are
 * accepted manual boundaries (see docs/srd-manifest/_exclusions.ts) and are not
 * counted here.
 */

import type { SystemComputeRegister } from './types';

const SRD = 'Daggerheart SRD 1.0';
const T = 'src/__tests__/daggerheartEngineMath.test.ts';
// Generic derivation test — one describe(spec.id) block per declared standing
// quantity in src/systems/daggerheart/derivedQuantities.ts.
const D = 'src/__tests__/derivation/daggerheartDerivedQuantities.test.ts';

export const daggerheartComputeRegister: SystemComputeRegister = {
  systemId: 'daggerheart',
  srdVersion: SRD,
  entries: [
    {
      id: 'daggerheart.L1.tier',
      layer: 'L1',
      quantity: 'Tier by level',
      formula: 'tier 1 (L1), 2 (L2-4), 3 (L5-7), 4 (L8+)',
      inputs: ['level'],
      edgeCases: ['tier boundaries 2/5/8'],
      source: `${SRD}: Leveling Up`,
      status: 'verified',
      testRef: `${D} :: daggerheart.L1.tier`,
    },
    {
      id: 'daggerheart.L1.proficiency',
      layer: 'L1',
      quantity: 'Proficiency (= tier; weapon damage-dice multiplier)',
      formula: 'proficiency = tier(level)',
      inputs: ['level'],
      edgeCases: ['multiplies number of weapon damage dice'],
      source: `${SRD}: Proficiency`,
      status: 'verified',
      testRef: `${D} :: daggerheart.L1.proficiency`,
    },
    {
      id: 'daggerheart.L1.ancestry-adjustments',
      layer: 'L1',
      quantity: 'Ancestry adjustments (evasion/HP/stress)',
      formula: 'per-ancestry adjustment table; zero default',
      inputs: ['ancestry'],
      edgeCases: ['unknown ancestry → zero'],
      source: `${SRD}: Ancestries`,
      status: 'verified',
      testRef: `${T} :: Daggerheart ancestry adjustments`,
    },
    {
      id: 'daggerheart.L2.evasion',
      layer: 'L2',
      quantity: 'Evasion',
      formula: 'class starting evasion + ancestry adjustment + passive bonuses (else stored value)',
      inputs: ['class', 'ancestry', 'passive bonuses'],
      edgeCases: ['falls back to stored evasion when no class'],
      source: `${SRD}: Evasion`,
      status: 'verified',
      testRef: `${T} :: L2 Daggerheart derived stats (unarmored)`,
    },
    {
      id: 'daggerheart.L2.armor-score',
      layer: 'L2',
      quantity: 'Armor score (capped 0–12)',
      formula: 'clamp(0, 12, armor base + passive armor bonus)',
      inputs: ['armor', 'passive bonuses'],
      edgeCases: ['unarmored = 0', 'cap at 12'],
      source: `${SRD}: Armor`,
      status: 'verified',
      testRef: `${T} :: L2 Daggerheart derived stats (unarmored)`,
    },
    {
      id: 'daggerheart.L2.major-threshold',
      layer: 'L2',
      quantity: 'Major damage threshold',
      formula: 'armor baseMajor + level (unarmored: level) + passive bonus',
      inputs: ['armor', 'level', 'passive bonus'],
      edgeCases: ['unarmored = level'],
      source: `${SRD}: Damage Thresholds`,
      status: 'verified',
      testRef: `${D} :: daggerheart.L2.major-threshold`,
    },
    {
      id: 'daggerheart.L2.severe-threshold',
      layer: 'L2',
      quantity: 'Severe damage threshold',
      formula: 'armor baseSevere + level (unarmored: level × 2) + passive bonus',
      inputs: ['armor', 'level', 'passive bonus'],
      edgeCases: ['unarmored = level × 2'],
      source: `${SRD}: Damage Thresholds`,
      status: 'verified',
      testRef: `${D} :: daggerheart.L2.severe-threshold`,
    },
    {
      id: 'daggerheart.L2.passive-bonuses',
      layer: 'L2',
      quantity: 'Passive bonus aggregation (weapon/armor/passive cards/inventory)',
      formula: 'sum of passive bonuses from equipped + active-passive sources',
      inputs: ['weapons', 'armor', 'passive domain cards', 'inventory'],
      edgeCases: ['only passive-mode cards; conditional passives'],
      source: `${SRD}: Equipment; Domain Cards`,
      status: 'verified',
      testRef: `${T} :: L2 Daggerheart passive bonus aggregation`,
    },
    {
      id: 'daggerheart.L7.tracks',
      layer: 'L7',
      quantity: 'HP / Stress / Armor track clamping + damage/heal/armor-absorption',
      formula:
        'current clamped to max; physical damage absorbed by armor then HP; stress fills the stress track (bypasses armor); heal restores up to max',
      inputs: ['HP/Stress/Armor tracks', 'damage amount', 'damage type'],
      edgeCases: [
        'armor absorbs before HP',
        'stress bypasses armor',
        'heal caps at max',
        'clamp current ≤ max',
      ],
      source: `${SRD}: Hit Points, Stress, Armor`,
      status: 'verified',
      testRef:
        'src/__tests__/daggerheartEngineMath.test.ts :: L8 Daggerheart damage / heal / armor',
    },
    {
      id: 'daggerheart.L3.attack-vs-difficulty',
      layer: 'L3',
      quantity: 'Attack roll vs Difficulty + damage',
      formula: 'trait + bonuses vs Difficulty; damage = (proficiency × weapon dice) + bonuses',
      inputs: ['trait', 'proficiency', 'weapon'],
      edgeCases: ['Hope/Fear outcome (narrative — excluded)'],
      source: `${SRD}: Attack Rolls; Damage`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: Daggerheart weapon damage dice',
    },
    {
      id: 'daggerheart.L8.hp-marked',
      layer: 'L8',
      quantity: 'HP marked by incoming damage (threshold bands)',
      formula: 'damage ≤ 0 → 0; < major → 1; < severe → 2; ≥ severe → 3',
      inputs: ['damage', 'major threshold', 'severe threshold'],
      edgeCases: ['zero damage', 'exactly at major', 'exactly at severe'],
      source: `${SRD}: Damage Thresholds`,
      status: 'verified',
      testRef: `${T} :: L8 Daggerheart damage thresholds → HP marked`,
    },
    {
      id: 'daggerheart.L8.duality-outcome',
      layer: 'L8',
      quantity: 'Duality (Hope/Fear/crit) mechanical resolution',
      formula: 'hope > fear → Hope; fear > hope → Fear; equal → critical',
      inputs: ['Hope die', 'Fear die'],
      edgeCases: ['matched dice = critical'],
      source: `${SRD}: Duality Dice`,
      status: 'verified',
      testRef: `${T} :: L8 Daggerheart duality resolution`,
      note: 'Only the numeric outcome is computed; narrative Hope/Fear consequences remain an accepted manual boundary (_exclusions.ts).',
    },
    {
      id: 'daggerheart.L1.effective-attribute',
      layer: 'L1',
      quantity: 'Effective attribute (base trait + passive bonuses)',
      formula: 'trait value + sum of equipped-gear/passive attribute bonuses',
      inputs: ['attribute', 'passive bonuses'],
      edgeCases: ['negative armor attribute penalties'],
      source: `${SRD}: Traits; Equipment`,
      status: 'verified',
      testRef: `${T} :: L2 Daggerheart passive bonus aggregation`,
    },
    {
      id: 'daggerheart.L8.massive-damage',
      layer: 'L8',
      quantity: 'Massive Damage optional rule (mark 4 HP)',
      formula: 'damage ≥ 2 × Severe threshold → mark 4 HP (when the optional rule is enabled)',
      inputs: ['damage', 'severe threshold', 'optional rule flag'],
      edgeCases: ['only when enabled', 'exactly at 2× severe'],
      source: `${SRD}: Hit Points & Damage Thresholds (optional rule)`,
      status: 'verified',
      testRef: `${T} :: L8 Daggerheart massive damage (optional rule)`,
    },
    {
      id: 'daggerheart.L3.critical-damage',
      layer: 'L3',
      quantity: 'Critical damage bonus',
      formula: 'rolled damage + (damage dice count × die size); modifier is not multiplied',
      inputs: ['rolled damage', 'dice count', 'die size'],
      edgeCases: ['adds max of dice only', 'modifier excluded'],
      source: `${SRD}: Attacking — Critical Damage`,
      status: 'verified',
      testRef: `${T} :: L3 Daggerheart damage rolls`,
    },
    {
      id: 'daggerheart.L3.spellcast-damage-dice',
      layer: 'L3',
      quantity: 'Spellcast damage dice count',
      formula: 'number of dice = Spellcast trait; 0 if trait ≤ 0',
      inputs: ['Spellcast trait'],
      edgeCases: ['+0 or lower rolls nothing'],
      source: `${SRD}: Attacking — Damage Rolls`,
      status: 'verified',
      testRef: `${T} :: L3 Daggerheart damage rolls`,
    },
    {
      id: 'daggerheart.L8.resistance-immunity',
      layer: 'L8',
      quantity: 'Resistance / immunity damage reduction',
      formula: 'immune → 0; resistant → ⌊damage/2⌋; applied before thresholds and Armor Slots',
      inputs: ['damage', 'resistant?', 'immune?'],
      edgeCases: [
        'resistance applied before armor',
        'multiple same-type resistances do not stack',
        'halving rounds down by convention',
      ],
      source: `${SRD}: Attacking — Resistance, Immunity, and Direct Damage`,
      status: 'verified',
      testRef: `${T} :: L8 Daggerheart damage reduction`,
    },
    {
      id: 'daggerheart.L8.armor-slot-reduction',
      layer: 'L8',
      quantity: 'Armor Slot HP-marked reduction',
      formula: 'HP marked −1 per Armor Slot marked (floor 0); none if Armor Score 0',
      inputs: ['base HP marked', 'armor slots marked', 'armor score'],
      edgeCases: ['no reduction when Armor Score 0', 'direct damage marks 0 slots', 'floors at 0'],
      source: `${SRD}: Armor — Reducing Incoming Damage`,
      status: 'verified',
      testRef: `${T} :: L8 Daggerheart damage reduction`,
    },
    {
      id: 'daggerheart.L1.experience-bonus',
      layer: 'L1',
      quantity: 'Experience bonus',
      formula: '+2 base, +1 per "increase your Experience" advancement',
      inputs: ['increase advancements taken'],
      edgeCases: ['gained at creation and levels 2/5/8'],
      source: `${SRD}: Leveling Up — Experiences`,
      status: 'verified',
      testRef: `${T} :: L7 Daggerheart progression and recovery`,
    },
    {
      id: 'daggerheart.L1.starting-trait-array',
      layer: 'L1',
      quantity: 'Character-creation trait array',
      formula: 'assign +2, +1, +1, +0, +0, −1 across the six traits (sum +3)',
      inputs: ['—'],
      edgeCases: ['assigned in any order', 'six traits'],
      source: `${SRD}: Character Creation — Assign Character Traits`,
      status: 'verified',
      testRef: `${T} :: L7 Daggerheart progression and recovery`,
    },
    {
      id: 'daggerheart.L7.starting-hope',
      layer: 'L7',
      quantity: 'Starting Hope',
      formula: 'all PCs start a campaign with 2 Hope',
      inputs: ['—'],
      edgeCases: ['metacurrency baseline'],
      source: `${SRD}: Character Creation`,
      status: 'verified',
      testRef: `${T} :: L7 Daggerheart progression and recovery`,
    },
    {
      id: 'daggerheart.L10.gold-denominations',
      layer: 'L10',
      quantity: 'Gold value across denominations',
      formula: 'value (handfuls) = handfuls + 10 × bags + 100 × chests',
      inputs: ['handfuls', 'bags', 'chests'],
      edgeCases: ['10 handfuls → 1 bag; 10 bags → 1 chest', 'max 1 chest'],
      source: `${SRD}: Gold`,
      status: 'verified',
      testRef: `${T} :: L10 Daggerheart gold and L6 ranges`,
    },
    {
      id: 'daggerheart.L6.range-squares',
      layer: 'L6',
      quantity: 'Range bands in battle-map squares (Defined Ranges)',
      formula: 'Melee 1, Very Close 3, Close 6, Far 12, Very Far 13+ (1 square ≈ 5 ft)',
      inputs: ['range band'],
      edgeCases: ['optional Defined Ranges rule', 'Very Far is a 13+ lower bound'],
      source: `${SRD}: Maps, Range, and Movement`,
      status: 'verified',
      testRef: `${T} :: L10 Daggerheart gold and L6 ranges`,
    },
    {
      id: 'daggerheart.L7.short-rest-recovery',
      layer: 'L7',
      quantity: 'Short-rest downtime recovery (HP/Stress/Armor)',
      formula: 'cleared = 1d4 + Tier (Tend to Wounds / Clear Stress / Repair Armor)',
      inputs: ['d4 roll', 'tier'],
      edgeCases: ['long rest clears the track fully'],
      source: `${SRD}: Downtime`,
      status: 'verified',
      testRef: `${T} :: L7 Daggerheart progression and recovery`,
    },
    {
      id: 'daggerheart.L7.stress-vulnerable',
      layer: 'L7',
      quantity: 'Vulnerable on full Stress + Stress overflow to HP',
      formula: 'current Stress ≥ max → Vulnerable; must mark Stress while full → mark 1 HP instead',
      inputs: ['current stress', 'max stress', 'stress to mark'],
      edgeCases: ['overflow marks 1 HP', 'clears when ≥1 Stress cleared'],
      source: `${SRD}: Stress`,
      status: 'verified',
      testRef: `${T} :: L7 Daggerheart progression and recovery`,
    },
    {
      id: 'daggerheart.L8.death-moves',
      layer: 'L8',
      quantity: 'Death moves (Risk It All, Avoid Death scar)',
      formula:
        'Risk It All: Hope>Fear → survive, clear = Hope Die; Fear>Hope → death; match (critical) → survive, clear ALL marked HP and Stress. Avoid Death: Hope Die ≤ level → scar',
      inputs: ['Hope die', 'Fear die', 'level'],
      edgeCases: [
        'matched dice are a critical success: survive and clear all marked HP/Stress',
        'scar threshold at level',
      ],
      source: `${SRD}: Death`,
      status: 'verified',
      testRef: `${T} :: L8 Daggerheart death moves`,
    },
    {
      id: 'daggerheart.L4.trait-roll-total',
      layer: 'L4',
      quantity: 'Action / trait roll total',
      formula: 'total = Hope d12 + Fear d12 + effective trait modifier (+ any declared modifiers), compared to a Difficulty',
      inputs: ['Hope die', 'Fear die', 'trait', 'passive bonuses (gear, carried relics, active loadout cards)'],
      edgeCases: ['matched duality dice are a critical success at any value', 'no fumble result exists in the system', 'carried-relic and passive loadout-card trait bonuses are folded into the modifier', 'an unknown check id falls back to the raw stored attribute'],
      stacking: 'Every effect except conditions and advantage/disadvantage stacks (SRD 1.0: Additional Rules — Stacking Effects); modifiers must be declared before the roll.',
      source: 'Daggerheart SRD 1.0: Making Moves & Taking Action — Action Rolls; Special Rolls: Trait Rolls',
      status: 'verified',
      testRef: 'src/__tests__/engines/daggerheart-engine.test.ts :: rollCheck',
      note: 'Covers the total only. The Difficulty comparison is a separate row (daggerheart.L4.action-roll-outcome, missing); the Hope/Fear label is already daggerheart.L8.duality-outcome. A negative (−1) trait modifier is NOT exercised by the cited describe.',
    },
    {
      id: 'daggerheart.L4.action-roll-outcome',
      layer: 'L4',
      quantity: 'Action roll outcome (success/failure × Hope/Fear) and the Hope/Fear award',
      formula: 'total ≥ Difficulty → success, else failure; Hope die > Fear die → \'with Hope\' (acting PC gains 1 Hope); Fear die > Hope die → \'with Fear\' (GM gains 1 Fear); matched dice → critical success',
      inputs: ['roll total', 'Difficulty', 'Hope die', 'Fear die'],
      edgeCases: ['total exactly equal to Difficulty is a success (\'meets or beats\')', 'failure with Hope still gains the PC a Hope', 'Hope capped at 6, GM Fear capped at 12'],
      source: 'Daggerheart SRD 1.0: Making Moves & Taking Action — Action Rolls; Hope & Fear',
      status: 'missing',
      note: 'The attack-roll specialization (total vs Evasion) IS computed in src/rules/resolver/daggerheartResolution.ts:97 and is registered as daggerheart.L3.attack-vs-difficulty; this row is the general non-attack action roll.',
    },
    {
      id: 'daggerheart.L4.advantage-disadvantage',
      layer: 'L4',
      quantity: 'Advantage / disadvantage die on an action or reaction roll',
      formula: 'total + 1d6 per advantage die, − 1d6 per disadvantage die; advantage and disadvantage dice cancel one-for-one before rolling, so one pool never rolls both',
      inputs: ['advantage sources', 'disadvantage sources', 'd6 roll'],
      edgeCases: ['equal advantage and disadvantage cancel entirely (no die rolled)', 'dice that do not affect your own pool (e.g. an ally\'s Help an Ally die) are NOT cancelled and stack with your rolled result', 'applies to reaction rolls as well as action rolls'],
      stacking: 'Advantage/disadvantage explicitly do NOT stack — they cancel one-for-one (SRD 1.0: Additional Rules — Stacking Effects; Advantage & Disadvantage).',
      source: 'Daggerheart SRD 1.0: Making Moves & Taking Action — Advantage & Disadvantage',
      status: 'missing',
    },
    {
      id: 'daggerheart.L4.help-an-ally-die',
      layer: 'L4',
      quantity: 'Help an Ally advantage die contributed to another PC\'s roll',
      formula: 'helper spends 1 Hope and rolls a d6 advantage die; the acting player adds only the HIGHEST helper die to their total',
      inputs: ['helper Hope pool', 'number of helpers', 'd6 rolls'],
      edgeCases: ['multiple helpers each spend 1 Hope but only the single highest die is added', 'cannot be used on a reaction roll', 'gated on the helper actually having 1 Hope'],
      source: 'Daggerheart SRD 1.0: Making Moves & Taking Action — Hope & Fear (Help an Ally)',
      status: 'missing',
    },
    {
      id: 'daggerheart.L4.utilize-experience',
      layer: 'L4',
      quantity: 'Experience modifier applied to an action or reaction roll',
      formula: 'spend 1 Hope per Experience; total += that Experience\'s modifier (+2 base, +1 per \'increase your Experience\' advancement); multiple Hope may be spent to utilize multiple Experiences on one roll',
      inputs: ['Hope pool', 'Experience modifier', 'GM ruling on relevance'],
      edgeCases: ['must be declared before the roll', 'several Experiences can be applied to one roll, each costing 1 Hope', 'applies to reaction rolls too'],
      source: 'Daggerheart SRD 1.0: Making Moves & Taking Action — Hope & Fear (Utilize an Experience); Character Creation — Step 7: Create Your Experiences',
      status: 'missing',
      note: 'Whether an Experience is RELEVANT is an accepted manual boundary (legalActions.ts:176 marks it manualBoundary). Only the numeric application is proposed as in-scope.',
    },
    {
      id: 'daggerheart.L4.group-action-roll',
      layer: 'L4',
      quantity: 'Group action roll — leader\'s modifier from allies\' reaction rolls',
      formula: 'lead action roll modifier = +1 per ally reaction roll that succeeded, −1 per ally reaction roll that failed',
      inputs: ['number of successful ally reaction rolls', 'number of failed ally reaction rolls'],
      edgeCases: ['allies roll reaction rolls with traits chosen per-ally', 'a net-zero mix of successes and failures leaves the lead roll unmodified', 'reaction rolls in the group generate no Hope/Fear'],
      source: 'Daggerheart SRD 1.0: Making Moves & Taking Action — Special Rolls: Group Action Rolls',
      status: 'missing',
    },
    {
      id: 'daggerheart.L4.reaction-roll',
      layer: 'L4',
      quantity: 'Reaction roll total and outcome',
      formula: 'resolved exactly like an action roll (duality dice + trait vs Difficulty) but generates no Hope and no Fear, triggers no additional GM move, and cannot be aided by Help an Ally; a critical success clears no Stress and gains no Hope but ignores the effects a success would have avoided',
      inputs: ['Hope die', 'Fear die', 'trait', 'Difficulty'],
      edgeCases: ['critical success negates the incoming effect without the usual Hope/Stress benefit', 'no Hope/Fear metacurrency movement on any result', 'Help an Ally is disallowed; advantage/disadvantage still apply'],
      source: 'Daggerheart SRD 1.0: Making Moves & Taking Action — Special Rolls: Reaction Rolls',
      status: 'missing',
    },
    {
      id: 'daggerheart.L4.tag-team-roll',
      layer: 'L4',
      quantity: 'Tag Team roll (cost, chosen result, combined damage)',
      formula: 'spend 3 Hope, once per session per initiator; both PCs make separate action rolls and one roll is chosen to apply to both actions; on a roll with Hope every involved PC gains 1 Hope, on a roll with Fear the GM gains 1 Fear per involved PC; on a successful Tag Team ATTACK both players roll damage and the totals are summed, resolved as a single source',
      inputs: ['Hope pool', 'both PCs\' action rolls', 'both damage rolls', 'damage types'],
      edgeCases: ['counts as ONE action roll for countdowns/features that track action rolls', 'a PC may be involved in multiple Tag Teams but may only initiate one per session', 'mixed damage types: the players choose which type the combined total deals'],
      source: 'Daggerheart SRD 1.0: Making Moves & Taking Action — Special Rolls: Tag Team Rolls; Hope & Fear',
      status: 'missing',
    },
    {
      id: 'daggerheart.L5.spellcast-trait-modifier',
      layer: 'L5',
      quantity: 'Spellcast roll modifier',
      formula: 'Spellcast modifier = effective value of the trait named by the character\'s SUBCLASS Spellcast trait (base trait + passive attribute bonuses) + passive spellcast bonuses; a multiclassed PC whose two foundation cards name different Spellcast traits chooses which applies',
      inputs: ['subclass Spellcast trait', 'trait values', 'passive attribute bonuses', 'passive spellcast bonuses', 'multiclass foundation cards'],
      edgeCases: ['a subclass with no Spellcast trait cannot make Spellcast rolls at all', 'a Spellcast Roll that can damage a target also counts as an attack roll', 'features affecting the underlying trait roll also affect the Spellcast roll', 'multiclass: player chooses between two Spellcast traits'],
      source: 'Daggerheart SRD 1.0: Making Moves & Taking Action — Special Rolls: Spellcast Rolls; Multiclassing',
      status: 'missing',
      note: 'The hardcoded \'knowledge\' substitution in daggerheartCombatant.ts:81 is a real RAW divergence for every subclass whose Spellcast trait is not Knowledge (e.g. Presence-based subclasses); it should be closed when this row is implemented.',
    },
    {
      id: 'daggerheart.L5.recall-cost',
      layer: 'L5',
      quantity: 'Recall Cost — Stress marked to move a vault card into the loadout',
      formula: 'Stress marked = the vaulted card\'s Recall Cost, when moving it vault → loadout at any time other than the start of a rest; free at the start of a rest and for a card gained at level-up; if the loadout is full, a card must first move loadout → vault, which always costs nothing',
      inputs: ['card recallCost', 'loadout occupancy', 'rest/level-up context', 'current Stress'],
      edgeCases: ['free during downtime / at the start of a rest', 'free for the newly acquired card at level-up', 'loadout → vault direction is always free', 'marking Stress while the Stress track is full instead marks 1 HP (daggerheart.L7.stress-vulnerable)'],
      source: 'Daggerheart SRD 1.0: Classes — Domain Card Anatomy (Recall Cost); Classes — Loadout & Vault; Downtime',
      status: 'missing',
    },
    {
      id: 'daggerheart.L9.level-range',
      layer: 'L9',
      quantity: 'Legal character level range',
      formula: '1 ≤ level ≤ 10, integer',
      inputs: ['level'],
      edgeCases: ['level 0 / 11 / non-integer are illegal', 'reported as a recoverable warning, never a blocking error'],
      source: 'Daggerheart SRD 1.0: Leveling Up (10 PC levels across 4 tiers)',
      status: 'verified',
      testRef: 'src/__tests__/daggerheartValidation.test.ts :: reports unknown class, heritage, community, subclass, equipment, and level as warnings only',
    },
    {
      id: 'daggerheart.L9.creation-trait-array-legality',
      layer: 'L9',
      quantity: 'Level-1 trait spread legality',
      formula: 'at level 1 the six assigned trait modifiers, sorted, must equal [+2, +1, +1, +0, +0, −1]; assignment order is free',
      inputs: ['six trait modifiers', 'level'],
      edgeCases: ['all-zero traits = an unassigned default sheet, not an illegal spread', 'the check does not apply from level 2 on, because advancements legally raise traits', 'non-integer trait values are flagged separately'],
      source: 'Daggerheart SRD 1.0: Character Creation — Assign Character Traits',
      status: 'verified',
      testRef: 'src/__tests__/daggerheartValidation.test.ts :: warns when level-1 traits deviate from the +2/+1/+1/+0/+0/-1 creation array',
      note: 'Deliberately paired with the existing daggerheart.L1.starting-trait-array row: that row defines the array as a creation quantity, this one is the build-legality gate over a stored document.',
    },
    {
      id: 'daggerheart.L9.domain-card-domain-legality',
      layer: 'L9',
      quantity: 'Domain-card domain legality',
      formula: 'every owned domain card\'s domain must be one of the character\'s class\'s two domains',
      inputs: ['class domains', 'card domain'],
      edgeCases: ['cards that resolve to no catalog entry are kept as manual/homebrew warnings, never errors', 'subclass / ancestry / community cards are not domain cards and are exempt', 'multiclass grants access to one domain of the additional class (not modelled)'],
      source: 'Daggerheart SRD 1.0: Character Creation — Step 8: Choose Domain Cards; Classes — Domain Card Anatomy (Domain)',
      status: 'verified',
      testRef: 'src/__tests__/daggerheartValidation.test.ts :: warns on out-of-domain cards but accepts in-domain cards',
    },
    {
      id: 'daggerheart.L9.domain-card-level-legality',
      layer: 'L9',
      quantity: 'Domain-card level legality',
      formula: 'card.level ≤ character level for cards taken from the class\'s own domains',
      inputs: ['card level', 'character level'],
      edgeCases: ['equal level is legal', 'cards taken from a MULTICLASS domain are instead capped at ⌈level / 2⌉ (not modelled)', 'skipped when the character level is itself out of range'],
      source: 'Daggerheart SRD 1.0: Classes — Domain Card Anatomy (Level); Leveling Up — Step Four: Domain Cards',
      status: 'verified',
      testRef: 'src/__tests__/daggerheartValidation.test.ts :: warns when a card is above the character level',
    },
    {
      id: 'daggerheart.L9.loadout-limit',
      layer: 'L9',
      quantity: 'Loadout size cap (5 cards)',
      formula: 'count of owned domain cards with location ≠ \'vault\' ≤ 5; every further card sits in the vault and is inactive',
      inputs: ['owned domain cards', 'card location'],
      edgeCases: ['vault cards are excluded from the count and contribute no passive bonuses', 'subclass / ancestry / community cards never count toward loadout or vault', 'a full loadout blocks adding or recalling a card until one is vaulted', 'documents importing >5 loadout cards spill the excess to the vault in stable order'],
      source: 'Daggerheart SRD 1.0: Classes — Loadout & Vault',
      status: 'verified',
      testRef: 'src/__tests__/daggerheartValidation.test.ts :: warns when the loadout exceeds the 5-card limit, counting only non-vault cards',
    },
    {
      id: 'daggerheart.L9.weapon-burden',
      layer: 'L9',
      quantity: 'Equipped weapon burden budget (2 hands)',
      formula: 'primary.burden + secondary.burden ≤ 2; available secondary burden = 2 − primary.burden',
      inputs: ['primary weapon burden', 'secondary weapon burden'],
      edgeCases: ['a burden-2 (two-handed) primary leaves no room for a secondary', 'a two-handed primary with an empty secondary slot is legal', 'unresolved weapon ids contribute 0 burden'],
      source: 'Daggerheart SRD 1.0: Weapons — Burden (\'your character\'s maximum burden is 2 hands\')',
      status: 'verified',
      testRef: 'src/__tests__/daggerheartValidation.test.ts :: warns on an over-burden weapon loadout (two-handed primary plus secondary)',
    },
    {
      id: 'daggerheart.L9.weapon-category-slots',
      layer: 'L9',
      quantity: 'One equipped weapon per category',
      formula: 'the primary slot may hold only a category:\'primary\' weapon and the secondary slot only a category:\'secondary\' weapon — at most one of each equipped at a time',
      inputs: ['weapon category', 'slot'],
      edgeCases: ['a secondary weapon placed in the primary slot is illegal', 'empty slots are always legal'],
      source: 'Daggerheart SRD 1.0: Weapons — Category (\'your character can only equip up to one weapon of each category at a time\')',
      status: 'verified',
      testRef: 'src/__tests__/daggerheartValidation.test.ts :: warns when a secondary weapon sits in the primary slot',
    },
    {
      id: 'daggerheart.L9.consumable-quantity-cap',
      layer: 'L9',
      quantity: 'Consumable carry cap (5 of each)',
      formula: 'quantity of any single consumable ≤ 5; loot has no cap',
      inputs: ['item category', 'quantity'],
      edgeCases: ['cap is per consumable TYPE, not a total', 'loot entries are uncapped', 'custom / non-catalog gear is annotated (info) rather than capped', 'prepareData clamps a persisted over-max quantity down to 5'],
      source: 'Daggerheart SRD 1.0: Consumables (\'you can hold up to five of each consumable at a time\')',
      status: 'verified',
      testRef: 'src/__tests__/daggerheartValidation.test.ts :: annotates custom inventory as info and warns on over-max consumables',
    },
    {
      id: 'daggerheart.L9.inventory-weapon-limit',
      layer: 'L9',
      quantity: 'Stowed (inventory) weapon cap',
      formula: 'stowed weapons ≤ 2 in addition to the equipped primary/secondary; swapping a stowed weapon for an active one costs 1 Stress outside a rest or moment of calm',
      inputs: ['weapons.inventoryIds'],
      edgeCases: ['equipped weapons do not count toward the 2', 'the Stress cost of an out-of-rest swap is not modelled', 'free during a rest or moment of calm'],
      source: 'Daggerheart SRD 1.0: Equipment (\'PCs can carry up to two additional weapons in the Inventory Weapon area\')',
      status: 'implemented',
      note: 'The validator message calls this \'the sheet\'s 2-weapon inventory limit\'; it is in fact RAW (SRD 1.0: Equipment), so the message and this row should carry the citation. The 1-Stress out-of-rest swap is a separate unmodelled quantity.',
    },
    {
      id: 'daggerheart.L9.equipment-tier-gate',
      layer: 'L9',
      quantity: 'Equip-tier gate on weapons and armor',
      formula: 'an item may be equipped only when item.tier ≤ tier(character level), with tier = 1 (L1), 2 (L2–4), 3 (L5–7), 4 (L8–10)',
      inputs: ['item tier', 'character level → tier'],
      edgeCases: ['applies to armor as well as both weapon slots', 'crossing a tier boundary (levels 2/5/8) widens the legal set', 'an ALREADY-equipped over-tier item (e.g. from import or a level rollback) is not flagged anywhere'],
      source: 'Daggerheart SRD 1.0: Equipment (\'you can\'t equip weapons or armor with a higher tier than you\'); Character Creation — Step 5 (Tier 1 tables at creation)',
      status: 'implemented',
    },
    {
      id: 'daggerheart.L9.domain-cards-owned',
      layer: 'L9',
      quantity: 'Domain cards owned budget',
      formula: 'baseline owned cards = 2 at level 1 and +1 per level-up ⇒ 1 + level; plus 1 per \'take an additional domain card\' advancement selected',
      inputs: ['level', 'advancements taken'],
      edgeCases: ['the two creation cards must both be level 1', 'a level-up card may be at or below the character\'s level', 'one previously acquired card may be exchanged at level-up for another of the same level or lower (count unchanged)', 'multiclass-domain cards are capped at ⌈level / 2⌉'],
      source: 'Daggerheart SRD 1.0: Classes — Domain Cards (\'PCs acquire two 1st-level domain cards at character creation and an additional domain card at or below their level each time they level up\'); Leveling Up — Step Four; Character Creation — Step 8',
      status: 'missing',
    },
    {
      id: 'daggerheart.L9.advancement-slots',
      layer: 'L9',
      quantity: 'Level-up advancement budget',
      formula: 'exactly 2 advancement selections per level-up, chosen from options of the character\'s tier or below that still have an unmarked slot; each selection marks one slot; the \'increase Proficiency\' and \'multiclass\' options each consume BOTH selections (their slots are black-boxed)',
      inputs: ['level', 'tier', 'already-marked advancement slots'],
      edgeCases: ['a multi-slot option may be chosen more than once, once per slot', 'options above the character\'s tier are unavailable', 'taking the upgraded-subclass option crosses out that tier\'s multiclass option, and vice versa', 'a two-slot option consumes the entire level-up'],
      source: 'Daggerheart SRD 1.0: Leveling Up — Step Two: Advancements',
      status: 'missing',
      note: 'Because no advancements are tracked, engine Proficiency (= tier) and Evasion cannot reflect the \'increase Proficiency\' / \'increase Evasion\' advancements; that is the practical cost of this row being missing.',
    },
    {
      id: 'daggerheart.L9.trait-advancement-marks',
      layer: 'L9',
      quantity: 'Trait-increase advancement legality (marked traits)',
      formula: 'the \'increase two unmarked character traits\' advancement grants +1 to two traits and MARKS them; a marked trait cannot be increased again until the marks are cleared by the tier achievement at level 5 or level 8',
      inputs: ['trait marks', 'level', 'advancements taken'],
      edgeCases: ['marks clear at levels 5 and 8 only (the level-2 achievement does NOT clear marks)', 'both traits chosen must be unmarked at the time of selection', 'interacts with the level-1 creation-array gate, which stops applying from level 2'],
      source: 'Daggerheart SRD 1.0: Leveling Up — Step Two: Advancements; Step One: Tier Achievements',
      status: 'missing',
    },
    {
      id: 'daggerheart.L9.experience-count',
      layer: 'L9',
      quantity: 'Experience count budget',
      formula: 'Experiences = 2 at character creation + 1 per tier achievement (levels 2, 5, 8) ⇒ tier(level) + 1',
      inputs: ['level → tier'],
      edgeCases: ['each new Experience arrives at +2', 'the \'increase your Experience\' advancement raises two EXISTING Experiences by +1 each; it grants no new Experience', 'an Experience may not be so broad it applies to any roll (GM adjudicated)'],
      source: 'Daggerheart SRD 1.0: Character Creation — Step 7: Create Your Experiences; Leveling Up — Step One: Tier Achievements',
      status: 'missing',
      note: 'Pairs with the existing daggerheart.L1.experience-bonus row (the +2/+1 magnitude); this row is the count budget. Note the SRD wording that \'increase your Experience\' bumps TWO Experiences by +1 — worth reconciling with that row\'s \'per increase advancement\' phrasing.',
    },
    {
      id: 'daggerheart.L9.multiclass-legality',
      layer: 'L9',
      quantity: 'Multiclass legality and its card-level cap',
      formula: 'multiclass is selectable only at level 5+; it consumes both of that level-up\'s advancement selections; it grants one domain of the additional class plus its class feature and one foundation subclass card; cards taken from the multiclass domain are capped at level ≤ ⌈current level / 2⌉',
      inputs: ['level', 'advancement selections', 'chosen multiclass domain', 'card level'],
      edgeCases: ['taking multiclass crosses out that tier\'s upgraded-subclass option and all other multiclass options', 'half-level cap rounds UP (SRD 1.0: Additional Rules — Rounding Up)', 'if the two foundation cards name different Spellcast traits, the player chooses which applies'],
      source: 'Daggerheart SRD 1.0: Multiclassing; Leveling Up — Step Two: Advancements',
      status: 'missing',
    },
    {
      id: 'daggerheart.L9.magic-damage-wield-gate',
      layer: 'L9',
      quantity: 'Magic-damage weapon wield gate',
      formula: 'a weapon whose damage type is magic may only be wielded by a character who has a Spellcast trait (i.e. whose subclass grants one)',
      inputs: ['weapon damageType', 'subclass Spellcast trait'],
      edgeCases: ['\'physical-or-magic\' weapons are not gated', 'a subclass with no Spellcast trait cannot equip a magic-damage weapon', 'multiclass foundation cards can supply the Spellcast trait'],
      source: 'Daggerheart SRD 1.0: Weapons — Damage Type (\'weapons that deal magic damage can only be wielded by characters with a Spellcast trait\')',
      status: 'missing',
      note: 'Filed under L9 as an equipment-legality gate; it is the one build rule that depends on the L5 Spellcast-trait row, so the two should be implemented together.',
    },
  ],
};

export default daggerheartComputeRegister;
