/**
 * Compute register (Denominator B) for D&D 3.5e, cited against SRD 3.5.
 * Engine: src/systems/dnd35e/engine.ts; shared: src/systems/shared/d20-helpers.ts,
 * src/utils/armorClass.ts.
 */

import type { SystemComputeRegister } from './types';

const SRD = 'SRD 3.5';
const T = 'src/__tests__/d20LegacyEngineMath.test.ts';

export const dnd35eComputeRegister: SystemComputeRegister = {
  systemId: 'dnd-3.5e',
  srdVersion: SRD,
  entries: [
    {
      id: 'dnd35e.L1.ability-mod',
      layer: 'L1',
      quantity: 'Ability modifier',
      formula: 'floor((score - 10) / 2)',
      inputs: ['ability score'],
      edgeCases: ['negative scores'],
      source: `${SRD}: Abilities`,
      status: 'implemented',
    },
    {
      id: 'dnd35e.L1.bab-track',
      layer: 'L1',
      quantity: 'BAB progression track (full / three-quarter / half)',
      formula: 'full=level; three-quarter=floor(level*3/4); half=floor(level/2)',
      inputs: ['class level', 'progression'],
      edgeCases: ['rounding at each track', 'level 1 vs 20'],
      source: `${SRD}: Classes — Base Attack Bonus`,
      status: 'verified',
      testRef: `${T} :: L1/L3 BAB progression tracks`,
    },
    {
      id: 'dnd35e.L1.save-progression',
      layer: 'L1',
      quantity: 'Good/poor base save progression',
      formula: 'good=2+floor(level/2); poor=floor(level/3)',
      inputs: ['class level', 'save quality'],
      edgeCases: ['level 1 good=2 vs poor=0', 'level 20'],
      source: `${SRD}: Classes — Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L1 d20 base save progressions`,
    },
    {
      id: 'dnd35e.L2.ac',
      layer: 'L2',
      quantity: 'AC — total, touch, flat-footed (with size + Dex cap)',
      formula:
        'total=10+armor+shield+min(Dex,cap)+size; touch=10+Dex+size; flatFooted=10+armor+shield+size',
      inputs: ['Dex', 'size', 'armor', 'shield'],
      edgeCases: ['touch ignores armor/shield', 'flat-footed ignores Dex', 'size +/-', 'Dex cap'],
      source: `${SRD}: Combat — Armor Class`,
      status: 'verified',
      testRef: `${T} :: L2 d20-legacy AC (touch / flat-footed / size)`,
    },
    {
      id: 'dnd35e.L2.saves-total',
      layer: 'L2',
      quantity: 'Saving throw totals (Fort/Ref/Will)',
      formula: 'base (summed across classes) + ability mod + misc',
      inputs: ['class levels', 'Con/Dex/Wis', 'misc'],
      edgeCases: ['multiclass base sum', 'ability mapping per save'],
      source: `${SRD}: Combat — Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L3 D&D 3.5e BAB, saves, HP, grapple`,
    },
    {
      id: 'dnd35e.L3.bab-sum',
      layer: 'L3',
      quantity: 'Total BAB (multiclass sum)',
      formula: 'sum(classBAB(level, track)) across class levels',
      inputs: ['class levels'],
      edgeCases: ['multiclass full + half'],
      source: `${SRD}: Combat — Attack Bonus`,
      status: 'verified',
      testRef: `${T} :: L3 D&D 3.5e BAB, saves, HP, grapple`,
    },
    {
      id: 'dnd35e.L3.grapple',
      layer: 'L3',
      quantity: 'Grapple modifier',
      formula: 'BAB + Str mod + special grapple size modifier',
      inputs: ['BAB', 'Str', 'size'],
      edgeCases: ['size steps are larger and opposite-signed vs AC', 'large +4'],
      stacking: 'grapple size modifier differs from AC size modifier',
      source: `${SRD}: Combat — Grapple`,
      status: 'verified',
      testRef: `${T} :: L3 D&D 3.5e BAB, saves, HP, grapple`,
    },
    {
      id: 'dnd35e.L3.attack-roll',
      layer: 'L3',
      quantity: 'Attack roll modifier',
      formula: 'BAB + Str mod (melee)',
      inputs: ['BAB', 'Str'],
      edgeCases: ['melee vs ranged ability'],
      source: `${SRD}: Combat — Attack Roll`,
      status: 'verified',
      testRef: `${T} :: L3/L4 D&D 3.5e check resolution`,
    },
    {
      id: 'dnd35e.L3.iterative-attacks',
      layer: 'L3',
      quantity: 'Iterative attacks',
      formula: 'extra attacks at BAB +6/+11/+16, each at -5 cumulative',
      inputs: ['BAB'],
      edgeCases: ['full attack action only'],
      source: `${SRD}: Combat — Attacks of Opportunity / Full Attack`,
      status: 'missing',
    },
    {
      id: 'dnd35e.L4.skill-ranks',
      layer: 'L4',
      quantity: 'Skill check modifier (ranks + ability)',
      formula: 'ability mod + ranks',
      inputs: ['ability', 'ranks'],
      edgeCases: ['cross-class half ranks'],
      source: `${SRD}: Skills`,
      status: 'verified',
      testRef: `${T} :: L3/L4 D&D 3.5e check resolution`,
    },
    {
      id: 'dnd35e.L4.skill-synergy',
      layer: 'L4',
      quantity: 'Skill synergy (+2 at 5 ranks in a related skill)',
      formula: '+2 to target skill when 5+ ranks in the synergy skill',
      inputs: ['ranks in related skill'],
      edgeCases: ['exactly 5 ranks threshold'],
      source: `${SRD}: Skills — Synergy`,
      status: 'missing',
    },
    {
      id: 'dnd35e.L4.max-rank-cap',
      layer: 'L4',
      quantity: 'Max skill ranks (class level+3; cross-class half)',
      formula: 'class skills: level + 3; cross-class: (level + 3) / 2',
      inputs: ['level', 'class skill?'],
      edgeCases: ['cross-class half cap'],
      source: `${SRD}: Skills — Ranks`,
      status: 'missing',
    },
    {
      id: 'dnd35e.L4.initiative',
      layer: 'L4',
      quantity: 'Initiative',
      formula: 'Dex mod (+ Improved Initiative via misc)',
      inputs: ['Dex'],
      edgeCases: ['Improved Initiative +4 via misc'],
      source: `${SRD}: Combat — Initiative`,
      status: 'verified',
      testRef: `${T} :: L3/L4 D&D 3.5e check resolution`,
    },
    {
      id: 'dnd35e.L5.vancian-slots',
      layer: 'L5',
      quantity: 'Spells per day (Vancian slot totals + bonus spells)',
      formula: 'class table by level + bonus spells from high ability',
      inputs: ['class levels', 'casting ability'],
      edgeCases: ['domain slots', 'specialist slots'],
      source: `${SRD}: Magic — Spells Per Day`,
      status: 'implemented',
    },
    {
      id: 'dnd35e.L5.spell-save-dc',
      layer: 'L5',
      quantity: 'Spell save DC',
      formula: '10 + spell level + casting ability mod',
      inputs: ['spell level', 'casting ability'],
      edgeCases: ['per spell level'],
      source: `${SRD}: Magic — Saving Throws`,
      status: 'missing',
    },
    {
      id: 'dnd35e.L7.max-hp',
      layer: 'L7',
      quantity: 'Maximum hit points',
      formula: 'sum(max(1, hit-die roll + Con mod)), min 1',
      inputs: ['hit-die rolls', 'Con'],
      edgeCases: ['min 1 per die'],
      source: `${SRD}: Combat — Hit Points`,
      status: 'verified',
      testRef: `${T} :: L3 D&D 3.5e BAB, saves, HP, grapple`,
    },
    {
      id: 'dnd35e.L8.apply-damage',
      layer: 'L8',
      quantity: 'Damage application (temp HP, floor at 0)',
      formula: 'temp absorbs first; current floors at 0; healing capped at max',
      inputs: ['current/temp/max HP', 'damage'],
      edgeCases: ['temp absorb', 'overkill floors at 0'],
      source: `${SRD}: Combat — Injury and Death`,
      status: 'verified',
      testRef: `${T} :: L8 d20-legacy damage application`,
    },
  ],
};

export default dnd35eComputeRegister;
