/**
 * Compute register (Denominator B) for D&D 3.5e, cited against SRD 3.5.
 * Engine: src/systems/dnd35e/engine.ts; shared: src/systems/shared/d20-helpers.ts,
 * src/rules/compile/defense.ts.
 */

import type { SystemComputeRegister } from './types';

const SRD = 'SRD 3.5';
const T = 'src/__tests__/d20LegacyEngineMath.test.ts';

export const dnd35eComputeRegister: SystemComputeRegister = {
  systemId: 'dnd-3.5e',
  srdVersion: SRD,
  entries: [
    {
      id: 'dnd35e.L1.ability-mod',
      layer: 'L1',
      quantity: 'Ability modifier',
      formula: 'floor((score - 10) / 2)',
      inputs: ['ability score'],
      edgeCases: ['negative scores'],
      source: `${SRD}: Abilities`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: shared ability modifier',
    },
    {
      id: 'dnd35e.L1.bab-track',
      layer: 'L1',
      quantity: 'BAB progression track (full / three-quarter / half)',
      formula: 'full=level; three-quarter=floor(level*3/4); half=floor(level/2)',
      inputs: ['class level', 'progression'],
      edgeCases: ['rounding at each track', 'level 1 vs 20'],
      source: `${SRD}: Classes — Base Attack Bonus`,
      status: 'verified',
      testRef: `${T} :: L1/L3 BAB progression tracks`,
    },
    {
      id: 'dnd35e.L1.save-progression',
      layer: 'L1',
      quantity: 'Good/poor base save progression',
      formula: 'good=2+floor(level/2); poor=floor(level/3)',
      inputs: ['class level', 'save quality'],
      edgeCases: ['level 1 good=2 vs poor=0', 'level 20'],
      source: `${SRD}: Classes — Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L1 d20 base save progressions`,
    },
    {
      id: 'dnd35e.L2.ac',
      layer: 'L2',
      quantity: 'AC — total, touch, flat-footed (with size + Dex cap)',
      formula:
        'total=10+armor+shield+min(Dex,cap)+size; touch=10+Dex+size; flatFooted=10+armor+shield+size',
      inputs: ['Dex', 'size', 'armor', 'shield'],
      edgeCases: ['touch ignores armor/shield', 'flat-footed ignores Dex', 'size +/-', 'Dex cap'],
      note: 'Migrated to the declarative derivation layer (DND35E_DERIVED_QUANTITIES). The anchored `total` is dnd35e.L2.ac.total, whose faithful compute folds the shared base (computeD20LegacyAC(...).total) through the resolver so it equals data.armorClass.total; a no-gear case reduces to the anchored `const total = 10 + armor + shield + Dex + size` (defense.ts), keeping the dnd35e.L2.ac mutation live. touch/flat-footed are pure display-bearing scalars (ac.touch / ac.flat-footed) with no register row.',
      source: `${SRD}: Combat — Armor Class`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/dnd35eDerivedQuantities.test.ts :: dnd35e.L2.ac.total',
    },
    {
      id: 'dnd35e.L2.saves-total',
      layer: 'L2',
      quantity: 'Saving throw totals (Fort/Ref/Will)',
      formula: 'base (summed across classes) + ability mod + misc',
      inputs: ['class levels', 'Con/Dex/Wis', 'misc'],
      edgeCases: ['multiclass base sum', 'ability mapping per save'],
      source: `${SRD}: Combat — Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L3 D&D 3.5e BAB, saves, HP, grapple`,
    },
    {
      id: 'dnd35e.L3.bab-sum',
      layer: 'L3',
      quantity: 'Total BAB (multiclass sum)',
      formula: 'sum(classBAB(level, track)) across class levels',
      inputs: ['class levels'],
      edgeCases: ['multiclass full + half'],
      source: `${SRD}: Combat — Attack Bonus`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/dnd35eDerivedQuantities.test.ts :: dnd35e.L3.bab-sum',
    },
    {
      id: 'dnd35e.L3.grapple',
      layer: 'L3',
      quantity: 'Grapple modifier',
      formula: 'BAB + Str mod + special grapple size modifier',
      inputs: ['BAB', 'Str', 'size'],
      edgeCases: ['size steps are larger and opposite-signed vs AC', 'large +4'],
      stacking: 'grapple size modifier differs from AC size modifier',
      source: `${SRD}: Combat — Grapple`,
      status: 'verified',
      testRef: `${T} :: L3 D&D 3.5e BAB, saves, HP, grapple`,
    },
    {
      id: 'dnd35e.L3.attack-roll',
      layer: 'L3',
      quantity: 'Attack roll modifier',
      formula: 'BAB + Str mod (melee)',
      inputs: ['BAB', 'Str'],
      edgeCases: ['melee vs ranged ability'],
      source: `${SRD}: Combat — Attack Roll`,
      status: 'verified',
      testRef: `${T} :: L3/L4 D&D 3.5e check resolution`,
    },
    {
      id: 'dnd35e.L3.iterative-attacks',
      layer: 'L3',
      quantity: 'Iterative attacks',
      formula: 'extra attacks at BAB +6/+11/+16, each at -5 cumulative',
      inputs: ['BAB'],
      edgeCases: ['full attack action only'],
      note: 'Scene-wired: buildCharacterCombatant derives attacksPerRound/iterativePenaltyStep from BAB and the tactical executor applies the cumulative -5 (src/__tests__/rules/characterCombatant.test.ts :: legacy-d20 iterative attacks).',
      source: `${SRD}: Combat — Attacks of Opportunity / Full Attack`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: d20 iterative attacks',
    },
    {
      id: 'dnd35e.L3.crit-confirmation',
      layer: 'L3',
      quantity: 'Critical hit confirmation and multiplier',
      formula:
        'a natural threat confirms on a second attack roll (same bonus) vs AC; confirmed damage = normal damage × the weapon crit multiplier (×2 default), extra dice not multiplied',
      inputs: ['threat', 'attack bonus', 'AC', 'critical multiplier'],
      edgeCases: ['unconfirmed threat = ordinary hit', 'extra dice (sneak attack) not multiplied'],
      note: 'Scene-wired: resolveAttack rolls the confirmation d20 from the same seeded stream and applies d20CriticalDamage when critModel is "confirm-multiply" — selected for 3.5e/PF1e by sceneCombat (replacing the 5e double-dice default).',
      source: `${SRD}: Combat — Critical Hits`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/attackResolution.test.ts :: a confirmed threat multiplies normal damage by the weapon multiplier',
    },
    {
      id: 'dnd35e.L4.skill-ranks',
      layer: 'L4',
      quantity: 'Skill check modifier (ranks + ability)',
      formula: 'ability mod + ranks',
      inputs: ['ability', 'ranks'],
      edgeCases: ['cross-class half ranks'],
      source: `${SRD}: Skills`,
      status: 'verified',
      testRef: `${T} :: L3/L4 D&D 3.5e check resolution`,
    },
    {
      id: 'dnd35e.L4.skill-synergy',
      layer: 'L4',
      quantity: 'Skill synergy (+2 at 5 ranks in a related skill)',
      formula: '+2 to target skill when 5+ ranks in the synergy skill',
      inputs: ['ranks in related skill'],
      edgeCases: ['exactly 5 ranks threshold'],
      source: `${SRD}: Skills — Synergy`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: 3.5e skill synergy and max ranks',
    },
    {
      id: 'dnd35e.L4.max-rank-cap',
      layer: 'L4',
      quantity: 'Max skill ranks (class level+3; cross-class half)',
      formula: 'class skills: level + 3; cross-class: (level + 3) / 2',
      inputs: ['level', 'class skill?'],
      edgeCases: ['cross-class half cap'],
      source: `${SRD}: Skills — Ranks`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/dnd35eDerivedQuantities.test.ts :: dnd35e.L4.max-rank-cap',
    },
    {
      id: 'dnd35e.L4.initiative',
      layer: 'L4',
      quantity: 'Initiative',
      formula: 'Dex mod (+ Improved Initiative via misc)',
      inputs: ['Dex'],
      edgeCases: ['Improved Initiative +4 via misc'],
      source: `${SRD}: Combat — Initiative`,
      status: 'verified',
      testRef: `${T} :: L3/L4 D&D 3.5e check resolution`,
    },
    {
      id: 'dnd35e.L5.vancian-slots',
      layer: 'L5',
      quantity: 'Spells per day (Vancian slot totals + bonus spells)',
      formula: 'class table by level + bonus spells from high ability',
      inputs: ['class levels', 'casting ability'],
      edgeCases: ['domain slots', 'specialist slots'],
      source: `${SRD}: Magic — Spells Per Day`,
      status: 'verified',
      testRef: 'src/__tests__/d20LegacyEngineMath.test.ts :: L5 d20 Vancian spell-slot totals',
    },
    {
      id: 'dnd35e.L5.spell-save-dc',
      layer: 'L5',
      quantity: 'Spell save DC',
      formula: '10 + spell level + casting ability mod',
      inputs: ['spell level', 'casting ability'],
      edgeCases: ['per spell level'],
      source: `${SRD}: Magic — Saving Throws`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: d20 legacy spell save DC',
    },
    {
      id: 'dnd35e.L5.bonus-spells',
      layer: 'L5',
      quantity: 'Bonus spells per day from casting ability',
      formula: 'spell level ≥ 1 and mod ≥ level → floor((mod − level) / 4) + 1; else 0',
      inputs: ['casting ability mod', 'spell level'],
      edgeCases: ['no bonus cantrips', 'mod must reach the spell level'],
      source: `${SRD}: Magic — Bonus Spells`,
      status: 'verified',
      testRef: `${T} :: L5 d20 bonus spells from a high casting ability`,
    },
    {
      id: 'dnd35e.L6.carrying-capacity',
      layer: 'L6',
      quantity: 'Carrying capacity (light/medium/heavy thresholds)',
      formula:
        'heavy = Str table (x4 per +10 Str above 19); light = ⌊heavy/3⌋; medium = ⌊2·heavy/3⌋',
      inputs: ['Strength'],
      edgeCases: ['x4 doubling above Str 19', 'Str 0 = 0 lbs', '1/3 and 2/3 splits'],
      source: `${SRD}: Carrying Capacity`,
      status: 'verified',
      testRef: `${T} :: L6 d20-legacy carrying capacity`,
    },
    {
      id: 'dnd35e.L6.encumbrance',
      layer: 'L6',
      quantity: 'Load category + encumbrance penalties (max Dex / check / run)',
      formula: 'category by thresholds; light: none/0/x4; medium: +3/-3/x4; heavy: +1/-6/x3',
      inputs: ['Strength', 'carried weight'],
      edgeCases: ['load → max Dex cap', 'run multiplier drops to x3 when heavy'],
      source: `${SRD}: Carrying Capacity — Encumbrance`,
      status: 'verified',
      testRef: `${T} :: L6 d20-legacy carrying capacity`,
    },
    {
      id: 'dnd35e.L6.lift-drag',
      layer: 'L6',
      quantity: 'Lift/drag limits',
      formula: 'over head = max load; off ground = 2× max; push/drag = 5× max',
      inputs: ['Strength'],
      edgeCases: ['off-ground = stagger only'],
      source: `${SRD}: Carrying Capacity — Lifting and Dragging`,
      status: 'verified',
      testRef: `${T} :: L6 d20-legacy carrying capacity`,
    },
    {
      id: 'dnd35e.L7.max-hp',
      layer: 'L7',
      quantity: 'Maximum hit points',
      formula: 'sum(max(1, hit-die roll + Con mod)), min 1',
      inputs: ['hit-die rolls', 'Con'],
      edgeCases: ['min 1 per die'],
      source: `${SRD}: Combat — Hit Points`,
      status: 'verified',
      testRef: `${T} :: L3 D&D 3.5e BAB, saves, HP, grapple`,
    },
    {
      id: 'dnd35e.L8.apply-damage',
      layer: 'L8',
      quantity: 'Damage application (temp HP, floor at 0)',
      formula: 'temp absorbs first; current floors at 0; healing capped at max',
      inputs: ['current/temp/max HP', 'damage'],
      edgeCases: ['temp absorb', 'overkill floors at 0'],
      source: `${SRD}: Combat — Injury and Death`,
      status: 'verified',
      testRef: `${T} :: L8 d20-legacy damage application`,
    },
    {
      id: 'dnd35e.L5.concentration-dc',
      layer: 'L5',
      quantity: 'Concentration check DCs (defensive / damage)',
      formula: 'defensive = 15 + spell level; while damaged = 10 + damage + spell level',
      inputs: ['spell level', 'damage taken'],
      edgeCases: ['Concentration is a skill check (d20 + ranks + Con)'],
      source: `${SRD}: Skills — Concentration`,
      status: 'verified',
      testRef: `${T} :: L5/L7 D&D 3.5e concentration, feats, and ability increases`,
    },
    {
      id: 'dnd35e.L7.feats-from-level',
      layer: 'L7',
      quantity: 'Feats gained from level',
      formula: 'one at 1st level and every third level = 1 + floor(level / 3)',
      inputs: ['level'],
      edgeCases: ['racial/class bonus feats added separately'],
      source: `${SRD}: Character Advancement`,
      status: 'verified',
      testRef:
        'src/__tests__/derivation/dnd35eDerivedQuantities.test.ts :: dnd35e.L7.feats-from-level',
    },
    {
      id: 'dnd35e.L7.ability-increases',
      layer: 'L7',
      quantity: 'Ability score increases from level',
      formula: '+1 to an ability every fourth level = floor(level / 4)',
      inputs: ['level'],
      edgeCases: ['at 4th/8th/12th/16th/20th'],
      source: `${SRD}: Character Advancement`,
      status: 'verified',
      testRef:
        'src/__tests__/derivation/dnd35eDerivedQuantities.test.ts :: dnd35e.L7.ability-increases',
    },
    {
      id: 'dnd35e.L1.xp-to-level',
      layer: 'L1',
      quantity: 'XP required to attain a character level',
      formula: '500 × level × (level − 1) (1000 × triangular(level − 1)); level 1 = 0',
      inputs: ['character level'],
      edgeCases: ['L2 = 1000', 'L20 = 190000'],
      source: `${SRD}: Character Advancement`,
      status: 'verified',
      testRef: `${T} :: L1 D&D 3.5e XP-to-level table`,
    },
    {
      id: 'dnd35e.L8.massive-damage',
      layer: 'L8',
      quantity: 'Massive damage save trigger',
      formula: 'single hit ≥ 50 damage → DC 15 Fortitude save or die',
      inputs: ['single-hit damage'],
      edgeCases: ['threshold at exactly 50', 'death on failed save regardless of HP'],
      source: `${SRD}: Combat — Massive Damage`,
      status: 'verified',
      testRef: `${T} :: L8 D&D 3.5e massive damage and HP state`,
    },
    {
      id: 'dnd35e.L8.hp-state-track',
      layer: 'L8',
      quantity: 'Disabled / dying / dead HP track',
      formula: '> 0 healthy; = 0 disabled; −1..−9 dying (unconscious); ≤ −10 dead',
      inputs: ['current HP'],
      edgeCases: ['0 = disabled', '−10 boundary = dead'],
      source: `${SRD}: Combat — Injury and Death`,
      status: 'verified',
      testRef: `${T} :: L8 D&D 3.5e massive damage and HP state`,
    },
    {
      id: 'dnd35e.L9.skill-max-ranks',
      layer: 'L9',
      quantity: 'Max skill ranks (class = level+3, cross-class = ⌊(level+3)/2⌋)',
      formula:
        "flag when a skill's ranks exceed its maximum (class skill = level+3; cross-class = ⌊(level+3)/2⌋)",
      inputs: ['skillRanks', 'classSkills', 'level'],
      edgeCases: ['exactly at limit legal', 'over limit flagged'],
      source: `${SRD}: Skills — Maximum Ranks`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/dnd35eLegality.test.ts :: dnd35e flags skill ranks above the class-skill maximum',
    },
    {
      id: 'dnd35e.L9.class-level-sum',
      layer: 'L9',
      quantity: 'Class levels sum to character level',
      formula: 'flag when Σ classLevels.level exceeds character level',
      inputs: ['classLevels', 'level'],
      edgeCases: ['exactly at limit legal', 'over limit flagged'],
      source: `${SRD}: Advancement`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/dnd35eLegality.test.ts :: dnd35e flags class levels exceeding character level',
    },
    {
      id: 'dnd35e.L4.skill-check-penalty',
      layer: 'L4',
      quantity: 'Skill check penalty (encumbrance load + equipped armor/shield) on physical skills',
      formula:
        'affected physical skill: encumbrance load check penalty (light 0 / medium −3 / heavy −6) + Σ equipped armor/shield armor-check-penalty; 0 for unaffected skills',
      inputs: ['Strength', 'carried weight', 'equipped armor/shield ACP', 'skillId'],
      edgeCases: [
        'unaffected skill → 0',
        'unequipped armor contributes 0',
        'load penalty and armor ACP stack',
        '3.5e affected-skill list (Balance/Hide/Tumble/…) is its own set',
      ],
      stacking: 'the encumbrance (load) penalty and the equipped armor/shield check penalty add',
      source: `${SRD}: Carrying Capacity — Encumbrance; Equipment — Armor Check Penalty`,
      status: 'verified',
      testRef: `${T} :: applies the check penalty (load) per the system affected-skill list`,
      note: 'Wired into Dnd35eEngine.rollCheck for physical skills via d20SkillCheckPenalty (src/systems/shared/d20-helpers.ts); the armor-ACP composition is separately proven by "adds the equipped armor/shield check penalty to the load penalty" in the same suite.',
    },
    {
      id: 'dnd35e.L8.condition-check-penalty',
      layer: 'L8',
      quantity: 'Fear/sickened flat penalty on saves and checks',
      formula:
        'fear family (shaken / frightened / panicked) contributes a single −2 (escalating states of one track, not stacked) + sickened −2 (separate, stacks) on every save, skill, and ability check',
      inputs: ['active condition ids'],
      edgeCases: [
        'fear states do not stack with each other (one −2 from the family)',
        'sickened stacks with fear',
        'attack-only riders (dazzled/entangled/prone/blinded/stunned) contribute 0 to the check penalty',
      ],
      stacking: 'fear track dedups to a single −2; sickened adds on top',
      source: `${SRD}: Conditions`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/d20LegacyConditionFold.test.ts :: rollCheck modifier is baseline minus the check penalty for every condition/check',
      note: "Dnd35eEngine.rollCheck folds fear/sickened through resolveCharacterEffects(...).bonus('check'), pinned byte-identical to the closed-form d20LegacyCheckPenalty for every catalog condition and combination.",
    },
  ],
};

export default dnd35eComputeRegister;
