/**
 * Compute register (Denominator B) for D&D 5e (2014), cited against SRD 5.1.
 *
 * Status legend (see ./types.ts):
 *   verified    — formula + edge cases pinned by a test (testRef).
 *   implemented — engine computes it, not yet edge-pinned to this register.
 *   missing     — the rules define it; the engine does not compute it yet.
 *
 * Engine sources: src/systems/dnd5e/shared/engine.ts, src/systems/dnd5e/engine.ts,
 * src/utils/armorClass.ts, src/utils/math.ts, src/utils/spellSlots.ts.
 */

import type { SystemComputeRegister } from './types';

const SRD = 'SRD 5.1';
const T = 'src/__tests__/dnd5e2014EngineMath.test.ts';

export const dnd5e2014ComputeRegister: SystemComputeRegister = {
  systemId: 'dnd-5e-2014',
  srdVersion: SRD,
  entries: [
    // ── L1 ability & proficiency foundation ──
    {
      id: 'dnd5e2014.L1.ability-mod',
      layer: 'L1',
      quantity: 'Ability modifier',
      formula: 'floor((score - 10) / 2)',
      inputs: ['ability score'],
      edgeCases: ['score 1 → -5', 'score 7 → -2 (negative rounding)', 'score 20 → +5'],
      source: `${SRD}: Using Ability Scores`,
      status: 'verified',
      testRef: `${T} :: L1 ability modifier`,
    },
    {
      id: 'dnd5e2014.L1.proficiency-bonus',
      layer: 'L1',
      quantity: 'Proficiency bonus by level',
      formula: 'ceil(level / 4) + 1',
      inputs: ['total character level'],
      edgeCases: ['tier boundaries 4→5, 8→9, 12→13, 16→17', 'capped at +6 by level 20'],
      source: `${SRD}: Beyond 1st Level`,
      status: 'verified',
      testRef: `${T} :: L1 proficiency bonus by level`,
    },

    // ── L2 defenses ──
    {
      id: 'dnd5e2014.L2.ac.unarmored',
      layer: 'L2',
      quantity: 'AC — unarmored',
      formula: '10 + Dex mod (+ shield)',
      inputs: ['Dex score', 'shield'],
      edgeCases: ['negative Dex', 'with shield +2'],
      source: `${SRD}: Armor Class`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.light',
      layer: 'L2',
      quantity: 'AC — light armor',
      formula: 'armor base + full Dex mod (+ shield)',
      inputs: ['armor base', 'Dex score', 'shield'],
      edgeCases: ['full Dex applies (no cap)'],
      source: `${SRD}: Armor`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.medium',
      layer: 'L2',
      quantity: 'AC — medium armor',
      formula: 'armor base + min(Dex mod, 2)',
      inputs: ['armor base', 'Dex score', 'dexBonusMax'],
      edgeCases: [
        'Dex above cap clamps to +2',
        'Dex below cap applies fully',
        'explicit dexBonusMax override',
      ],
      source: `${SRD}: Armor`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.heavy',
      layer: 'L2',
      quantity: 'AC — heavy armor',
      formula: 'armor base (no Dex) (+ shield)',
      inputs: ['armor base', 'shield'],
      edgeCases: ['Dex contributes nothing', 'shield still adds'],
      source: `${SRD}: Armor`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.defense-style',
      layer: 'L2',
      quantity: 'AC — Defense fighting style (+1 while armored)',
      formula: 'AC + 1 if wearing armor and Defense style active',
      inputs: ['fighting style', 'armor worn'],
      edgeCases: ['no bonus while unarmored'],
      stacking: 'adds on top of armor AC',
      source: `${SRD}: Fighting Style (Defense)`,
      status: 'verified',
      testRef: `${T} :: L2 Defense fighting style`,
    },
    {
      id: 'dnd5e2014.L2.ac.unarmored-defense-barbarian',
      layer: 'L2',
      quantity: 'AC — Unarmored Defense (Barbarian)',
      formula: 'max(default AC, 10 + Dex mod + Con mod) (+ shield)',
      inputs: ['Dex score', 'Con score', 'shield', 'unarmored-defense-barbarian feature'],
      edgeCases: ['only while no armor worn', 'shield still applies', 'takes the higher formula'],
      source: `${SRD}: Barbarian — Unarmored Defense`,
      status: 'verified',
      testRef: 'src/__tests__/engines/dnd5e-engine.test.ts :: unarmored defense (engine-wired)',
    },
    {
      id: 'dnd5e2014.L2.ac.unarmored-defense-monk',
      layer: 'L2',
      quantity: 'AC — Unarmored Defense (Monk)',
      formula: 'max(default AC, 10 + Dex mod + Wis mod)',
      inputs: ['Dex score', 'Wis score', 'unarmored-defense-monk feature'],
      edgeCases: ['no armor and no shield', 'takes the higher formula'],
      source: `${SRD}: Monk — Unarmored Defense`,
      status: 'verified',
      testRef: 'src/__tests__/engines/dnd5e-engine.test.ts :: unarmored defense (engine-wired)',
    },
    {
      id: 'dnd5e2014.L2.saving-throw',
      layer: 'L2',
      quantity: 'Saving throw modifier',
      formula: 'ability mod + (proficiency bonus if proficient)',
      inputs: ['ability score', 'save proficiency', 'level'],
      edgeCases: [
        'proficient vs not',
        'auto-fail Str/Dex while paralyzed/petrified/stunned/unconscious',
      ],
      source: `${SRD}: Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L2/L4 rollCheck modifiers`,
    },
    {
      id: 'dnd5e2014.L2.spell-save-dc',
      layer: 'L2',
      quantity: 'Spell save DC',
      formula: '8 + proficiency bonus + spellcasting ability mod',
      inputs: ['level', 'spellcasting ability'],
      edgeCases: ['per spellcasting class'],
      source: `${SRD}: Spellcasting — Spell save DC`,
      status: 'missing',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: 5e spell save DC and attack',
      note: 'Canonical helper (derivedCasterMath.ts) is test-pinned but not consumed by any engine or sheet; per the legend, unwired quantities are missing.',
    },
    {
      id: 'dnd5e2014.L2.spell-attack',
      layer: 'L2',
      quantity: 'Spell attack bonus',
      formula: 'proficiency bonus + spellcasting ability mod',
      inputs: ['level', 'spellcasting ability'],
      edgeCases: ['per spellcasting class'],
      source: `${SRD}: Spellcasting — Spell attack modifier`,
      status: 'missing',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: 5e spell save DC and attack',
      note: 'Canonical helper (derivedCasterMath.ts) is test-pinned but not consumed by any engine or sheet; per the legend, unwired quantities are missing.',
    },

    // ── L3 offense ──
    {
      id: 'dnd5e2014.L3.extra-attack-count',
      layer: 'L3',
      quantity: 'Attacks per Attack action (Extra Attack)',
      formula: '1 + count of extra-attack features',
      inputs: ['features'],
      edgeCases: ['Fighter 11 with extra-attack + extra-attack-2 → 3 attacks'],
      source: `${SRD}: Fighter — Extra Attack`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/characterCombatant.test.ts :: Extra Attack scales attacksPerRound',
    },
    {
      id: 'dnd5e2014.L3.rage-damage',
      layer: 'L3',
      quantity: 'Rage damage bonus',
      formula: '+2 (level 1), +3 (level 9), +4 (level 16)',
      inputs: ['barbarian level', 'rage toggle', 'rage feature'],
      edgeCases: ['barbarian 9 → +3', 'toggle without feature → no effect'],
      source: `${SRD}: Barbarian — Rage`,
      status: 'verified',
      testRef: 'src/__tests__/rules/characterCombatant.test.ts :: 5e rider toggles in scene combat',
      note: 'Manual boundary: melee Strength attacks only (rider note travels with the effect).',
    },
    {
      id: 'dnd5e2014.L3.gwm-tradeoff',
      layer: 'L3',
      quantity: 'Great Weapon Master -5/+10',
      formula: 'attack -5, damage +10 while toggled',
      inputs: ['gwm feat', 'toggle'],
      edgeCases: ['feat-gated: toggle without feat → no effect'],
      source: `${SRD}: Feats — Great Weapon Master`,
      status: 'verified',
      testRef: 'src/__tests__/rules/characterCombatant.test.ts :: 5e rider toggles in scene combat',
      note: 'Manual boundary: heavy melee weapons only.',
    },
    {
      id: 'dnd5e2014.L3.sharpshooter-tradeoff',
      layer: 'L3',
      quantity: 'Sharpshooter -5/+10',
      formula: 'attack -5, damage +10 while toggled',
      inputs: ['sharpshooter feat', 'toggle'],
      edgeCases: ['feat-gated: toggle without feat → no effect'],
      source: `${SRD}: Feats — Sharpshooter`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/characterCombatant.test.ts :: collectDnd5eRiderEffects: Sharpshooter and Divine Smite',
      note: 'Manual boundary: ranged weapons with proficiency only.',
    },
    {
      id: 'dnd5e2014.L3.sneak-attack-dice',
      layer: 'L3',
      quantity: 'Sneak Attack dice',
      formula: 'ceil(rogue level / 2) d6',
      inputs: ['rogue level', 'sneak-attack feature', 'toggle'],
      edgeCases: ['rogue 1 → 1d6', 'rogue 20 → 10d6'],
      source: `${SRD}: Rogue — Sneak Attack`,
      status: 'verified',
      testRef: 'src/__tests__/rules/characterCombatant.test.ts :: 5e rider toggles in scene combat',
      note: 'Manual boundary: once per turn, advantage or adjacent-ally positioning asserted by the toggle.',
    },
    {
      id: 'dnd5e2014.L3.divine-smite-base',
      layer: 'L3',
      quantity: 'Divine Smite base damage',
      formula: '2d8 radiant (1st-level slot)',
      inputs: ['divine-smite feature', 'toggle'],
      edgeCases: ['feature-gated: toggle without feature → no effect'],
      source: `${SRD}: Paladin — Divine Smite`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/characterCombatant.test.ts :: collectDnd5eRiderEffects: Sharpshooter and Divine Smite',
      note: 'Manual boundary: slot expenditure and per-slot/undead scaling are manual calls.',
    },

    // ── L4 skills & derived checks ──
    {
      id: 'dnd5e2014.L4.skill-check',
      layer: 'L4',
      quantity: 'Skill check modifier',
      formula: 'ability mod + {0 | prof | 2×prof (expertise) | ½prof (Jack of All Trades)}',
      inputs: ['ability score', 'skill proficiency level', 'level'],
      edgeCases: ['expertise doubles', 'half (round down)', 'no proficiency'],
      source: `${SRD}: Using Each Ability; Expertise`,
      status: 'verified',
      testRef: `${T} :: L2/L4 rollCheck modifiers`,
    },
    {
      id: 'dnd5e2014.L4.initiative',
      layer: 'L4',
      quantity: 'Initiative',
      formula: 'Dex mod (+ feat modifiers)',
      inputs: ['Dex score'],
      edgeCases: ['base case = Dex mod'],
      source: `${SRD}: Initiative`,
      status: 'verified',
      testRef: `${T} :: L2/L4 prepareData derives AC and initiative`,
    },
    {
      id: 'dnd5e2014.L4.passive-perception',
      layer: 'L4',
      quantity: 'Passive Perception',
      formula: '10 + Wis(Perception) modifier (± 5 advantage/disadvantage)',
      inputs: ['Wis score', 'Perception proficiency'],
      edgeCases: ['advantage +5', 'disadvantage -5'],
      source: `${SRD}: Passive Checks`,
      status: 'missing',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: 5e passive Perception',
      note: 'Canonical helper (derivedCasterMath.ts) is test-pinned but not consumed by any engine or sheet; per the legend, unwired quantities are missing.',
    },
    {
      id: 'dnd5e2014.L4.d20-modes',
      layer: 'L4',
      quantity: 'Advantage / disadvantage roll resolution',
      formula: 'advantage = max(2d20); disadvantage = min(2d20)',
      inputs: ['roll mode'],
      edgeCases: ['advantage keeps higher', 'disadvantage keeps lower'],
      source: `${SRD}: Advantage and Disadvantage`,
      status: 'verified',
      testRef: `${T} :: L4 d20 roll modes`,
    },

    // ── L5 spellcasting economy ──
    {
      id: 'dnd5e2014.L5.multiclass-spell-slots',
      layer: 'L5',
      quantity: 'Spell slots (single-class tables + multiclass combined-level table)',
      formula:
        'single casting class → class table (half = ceil(level/2) from level 2; third = ceil(level/3) from level 3); 2+ casting classes → floored combined caster level → SRD multiclass slot table',
      inputs: ['class levels', 'caster type per class', 'number of casting classes'],
      edgeCases: [
        'single-class Paladin/Ranger odd levels round up (Paladin 3 → 3 slots)',
        'single-class EK/AT use their class table (EK 7 → 4/2)',
        'multiclass floors per the SRD rule',
        'preserve used counts',
      ],
      source: `${SRD}: Multiclassing — Spellcasting; Paladin/Ranger/EK tables`,
      status: 'verified',
      testRef: `${T} :: L5 spell slots (class tables + multiclass)`,
    },
    {
      id: 'dnd5e2014.L5.pact-magic',
      layer: 'L5',
      quantity: 'Warlock Pact Magic slots',
      formula:
        'slots: 1 at L1, 2 at L2, 3 at L11, 4 at L17; slot level = min(5, ceil(min(level, 9) / 2)); recover on short rest; never feeds the multiclass table',
      inputs: ['warlock class levels'],
      edgeCases: ['levels 1/2/5/11/17 thresholds', 'slot level caps at 5', 'short-rest recovery'],
      source: `${SRD}: Warlock — Pact Magic`,
      status: 'verified',
      testRef: 'src/__tests__/utils/spellSlots.test.ts :: computePactMagicSlots',
    },
    {
      id: 'dnd5e2014.L5.cantrip-scaling',
      layer: 'L5',
      quantity: 'Cantrip damage scaling by level',
      formula: 'damage dice step at levels 5/11/17',
      inputs: ['character level'],
      edgeCases: ['per-cantrip dice progression'],
      source: `${SRD}: Cantrips`,
      status: 'missing',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: 5e cantrip scaling tier',
      note: 'Canonical helper (derivedCasterMath.ts) is test-pinned but not consumed by any engine or sheet; per the legend, unwired quantities are missing.',
    },

    // ── L7 resources & progression ──
    {
      id: 'dnd5e2014.L7.max-hp',
      layer: 'L7',
      quantity: 'Maximum hit points',
      formula: 'sum(max(1, hit die or roll + Con mod) per level) — the min-1 clamp is per level',
      inputs: ['class levels', 'hit-die rolls', 'Con score'],
      edgeCases: [
        'multiclass',
        'first-level max die',
        'explicit rolls',
        'per-level min 1 with mixed positive/negative levels',
      ],
      source: `${SRD}: Hit Points`,
      status: 'verified',
      testRef: `${T} :: L7 max HP from class hit dice`,
    },
    {
      id: 'dnd5e2014.L7.hit-dice-pool',
      layer: 'L7',
      quantity: 'Hit-dice pool tracking',
      formula: 'per class: total = class level; remaining preserved across level-up',
      inputs: ['class levels', 'previous hit dice'],
      edgeCases: ['level-up gains', 'die-size change resets'],
      source: `${SRD}: Hit Dice; Resting`,
      status: 'verified',
      testRef: `${T} :: L7 hit-dice pool tracking`,
    },

    // ── L8 active-play state ──
    {
      id: 'dnd5e2014.L8.exhaustion-max-hp',
      layer: 'L8',
      quantity: 'Exhaustion — max HP halved at level 4 (2014)',
      formula:
        'hitPoints.max = max(1, floor(baseMaxHP / 2)) when exhaustion ≥ 4; the unhalved base is kept in baseMaxHP so re-preparing a persisted document never re-halves',
      inputs: ['exhaustion level', 'baseMaxHP'],
      edgeCases: ['exactly level 4', 'min 1', 'idempotent across repeated prepareData'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion (2014)`,
    },
    {
      id: 'dnd5e2014.L8.exhaustion-lethal',
      layer: 'L8',
      quantity: 'Exhaustion — death at level 6 (2014)',
      formula: 'current = 0, deathSaves.failures = 3 when exhaustion ≥ 6',
      inputs: ['exhaustion level'],
      edgeCases: ['exactly level 6'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion (2014)`,
    },
    {
      id: 'dnd5e2014.L8.exhaustion-clamp',
      layer: 'L8',
      quantity: 'Exhaustion level clamp [0, 6]',
      formula: 'clamp(floor(level), 0, 6)',
      inputs: ['raw exhaustion level'],
      edgeCases: ['negative', 'above 6', 'non-finite → 0'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion (2014)`,
    },
    {
      id: 'dnd5e2014.L8.exhaustion-disadvantage',
      layer: 'L8',
      quantity: 'Exhaustion — disadvantage on ability checks (≥1) and saves (≥3)',
      formula: 'roll mode = disadvantage under threshold conditions',
      inputs: ['exhaustion level', 'check type'],
      edgeCases: ['ability check ≥1', 'save ≥3'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion disadvantage (2014)`,
    },
    {
      id: 'dnd5e2014.L8.apply-damage',
      layer: 'L8',
      quantity: 'Damage application (temp HP, floor, death saves)',
      formula:
        'temp absorbs first; current floors at 0; damage at 0 HP adds a death-save failure; healing resets',
      inputs: ['current/temp/max HP', 'damage amount'],
      edgeCases: [
        'temp partial/full absorb',
        'overkill floors at 0',
        'damage while at 0',
        'healing resets death saves',
      ],
      source: `${SRD}: Damage and Healing; Temporary Hit Points`,
      status: 'verified',
      testRef: `${T} :: L8 applyDamage`,
    },
    {
      id: 'dnd5e2014.L8.death-save-normalize',
      layer: 'L8',
      quantity: 'Death-save normalization [0, 3]',
      formula: 'clamp(successes, 0, 3); clamp(failures, 0, 3)',
      inputs: ['death saves'],
      edgeCases: ['above 3', 'negative'],
      source: `${SRD}: Death Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L8 death-save normalization`,
    },
    {
      id: 'dnd5e2014.L8.condition-poisoned',
      layer: 'L8',
      quantity: 'Condition effects (poisoned disadvantage; auto-fail Str/Dex saves)',
      formula:
        'poisoned → disadvantage on attacks/ability checks; paralyzed/petrified/stunned/unconscious → auto-fail Str/Dex saves',
      inputs: ['active conditions', 'check type'],
      edgeCases: ['poisoned', 'incapacitating conditions auto-fail'],
      source: `${SRD}: Conditions`,
      status: 'verified',
      testRef: `${T} :: L8 poisoned condition`,
    },
    {
      id: 'dnd5e2014.L8.concentration-dc',
      layer: 'L8',
      quantity: 'Concentration save DC',
      formula: 'max(10, floor(damage / 2))',
      inputs: ['damage taken'],
      edgeCases: ['low damage floors at 10'],
      source: `${SRD}: Concentration`,
      status: 'missing',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: 5e concentration DC',
      note: 'Canonical helper (derivedCasterMath.ts) is test-pinned but not consumed by any engine or sheet; per the legend, unwired quantities are missing.',
    },
  ],
};

export default dnd5e2014ComputeRegister;
