/**
 * Compute register (Denominator B) for D&D 5e (2014), cited against SRD 5.1.
 *
 * Status legend (see ./types.ts):
 *   verified    — formula + edge cases pinned by a test (testRef).
 *   implemented — engine computes it, not yet edge-pinned to this register.
 *   missing     — the rules define it; the engine does not compute it yet.
 *
 * Engine sources: src/systems/dnd5e/shared/engine.ts, src/systems/dnd5e/engine.ts,
 * src/utils/armorClass.ts, src/utils/math.ts, src/utils/spellSlots.ts.
 */

import type { SystemComputeRegister } from './types';

const SRD = 'SRD 5.1';
const T = 'src/__tests__/dnd5e2014EngineMath.test.ts';

export const dnd5e2014ComputeRegister: SystemComputeRegister = {
  systemId: 'dnd-5e-2014',
  srdVersion: SRD,
  entries: [
    // ── L1 ability & proficiency foundation ──
    {
      id: 'dnd5e2014.L1.ability-mod',
      layer: 'L1',
      quantity: 'Ability modifier',
      formula: 'floor((score - 10) / 2)',
      inputs: ['ability score'],
      edgeCases: ['score 1 → -5', 'score 7 → -2 (negative rounding)', 'score 20 → +5'],
      source: `${SRD}: Using Ability Scores`,
      status: 'verified',
      testRef: `${T} :: L1 ability modifier`,
    },
    {
      id: 'dnd5e2014.L1.proficiency-bonus',
      layer: 'L1',
      quantity: 'Proficiency bonus by level',
      formula: 'ceil(level / 4) + 1',
      inputs: ['total character level'],
      edgeCases: ['tier boundaries 4→5, 8→9, 12→13, 16→17', 'capped at +6 by level 20'],
      source: `${SRD}: Beyond 1st Level`,
      status: 'verified',
      testRef: `${T} :: L1 proficiency bonus by level`,
    },

    // ── L2 defenses ──
    {
      id: 'dnd5e2014.L2.ac.unarmored',
      layer: 'L2',
      quantity: 'AC — unarmored',
      formula: '10 + Dex mod (+ shield)',
      inputs: ['Dex score', 'shield'],
      edgeCases: ['negative Dex', 'with shield +2'],
      source: `${SRD}: Armor Class`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.light',
      layer: 'L2',
      quantity: 'AC — light armor',
      formula: 'armor base + full Dex mod (+ shield)',
      inputs: ['armor base', 'Dex score', 'shield'],
      edgeCases: ['full Dex applies (no cap)'],
      source: `${SRD}: Armor`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.medium',
      layer: 'L2',
      quantity: 'AC — medium armor',
      formula: 'armor base + min(Dex mod, 2)',
      inputs: ['armor base', 'Dex score', 'dexBonusMax'],
      edgeCases: [
        'Dex above cap clamps to +2',
        'Dex below cap applies fully',
        'explicit dexBonusMax override',
      ],
      source: `${SRD}: Armor`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.heavy',
      layer: 'L2',
      quantity: 'AC — heavy armor',
      formula: 'armor base (no Dex) (+ shield)',
      inputs: ['armor base', 'shield'],
      edgeCases: ['Dex contributes nothing', 'shield still adds'],
      source: `${SRD}: Armor`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.defense-style',
      layer: 'L2',
      quantity: 'AC — Defense fighting style (+1 while armored)',
      formula: 'AC + 1 if wearing armor and Defense style active',
      inputs: ['fighting style', 'armor worn'],
      edgeCases: ['no bonus while unarmored'],
      stacking: 'adds on top of armor AC',
      source: `${SRD}: Fighting Style (Defense)`,
      status: 'implemented',
    },
    {
      id: 'dnd5e2014.L2.ac.unarmored-defense-barbarian',
      layer: 'L2',
      quantity: 'AC — Unarmored Defense (Barbarian)',
      formula: '10 + Dex mod + Con mod (+ shield)',
      inputs: ['Dex score', 'Con score', 'shield'],
      edgeCases: ['only while no armor worn'],
      source: `${SRD}: Barbarian — Unarmored Defense`,
      status: 'missing',
      note: 'compute5eAC uses 10 + Dex only; class-conditional unarmored defense not derived in the base engine path.',
    },
    {
      id: 'dnd5e2014.L2.ac.unarmored-defense-monk',
      layer: 'L2',
      quantity: 'AC — Unarmored Defense (Monk)',
      formula: '10 + Dex mod + Wis mod',
      inputs: ['Dex score', 'Wis score'],
      edgeCases: ['no armor and no shield'],
      source: `${SRD}: Monk — Unarmored Defense`,
      status: 'missing',
      note: 'Not derived in the base engine path.',
    },
    {
      id: 'dnd5e2014.L2.saving-throw',
      layer: 'L2',
      quantity: 'Saving throw modifier',
      formula: 'ability mod + (proficiency bonus if proficient)',
      inputs: ['ability score', 'save proficiency', 'level'],
      edgeCases: [
        'proficient vs not',
        'auto-fail Str/Dex while paralyzed/petrified/stunned/unconscious',
      ],
      source: `${SRD}: Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L2/L4 rollCheck modifiers`,
    },
    {
      id: 'dnd5e2014.L2.spell-save-dc',
      layer: 'L2',
      quantity: 'Spell save DC',
      formula: '8 + proficiency bonus + spellcasting ability mod',
      inputs: ['level', 'spellcasting ability'],
      edgeCases: ['per spellcasting class'],
      source: `${SRD}: Spellcasting — Spell save DC`,
      status: 'missing',
      note: 'Not computed in any engine (confirmed by compute-layer audit).',
    },
    {
      id: 'dnd5e2014.L2.spell-attack',
      layer: 'L2',
      quantity: 'Spell attack bonus',
      formula: 'proficiency bonus + spellcasting ability mod',
      inputs: ['level', 'spellcasting ability'],
      edgeCases: ['per spellcasting class'],
      source: `${SRD}: Spellcasting — Spell attack modifier`,
      status: 'missing',
    },

    // ── L4 skills & derived checks ──
    {
      id: 'dnd5e2014.L4.skill-check',
      layer: 'L4',
      quantity: 'Skill check modifier',
      formula: 'ability mod + {0 | prof | 2×prof (expertise) | ½prof (Jack of All Trades)}',
      inputs: ['ability score', 'skill proficiency level', 'level'],
      edgeCases: ['expertise doubles', 'half (round down)', 'no proficiency'],
      source: `${SRD}: Using Each Ability; Expertise`,
      status: 'verified',
      testRef: `${T} :: L2/L4 rollCheck modifiers`,
    },
    {
      id: 'dnd5e2014.L4.initiative',
      layer: 'L4',
      quantity: 'Initiative',
      formula: 'Dex mod (+ feat modifiers)',
      inputs: ['Dex score'],
      edgeCases: ['base case = Dex mod'],
      source: `${SRD}: Initiative`,
      status: 'verified',
      testRef: `${T} :: L2/L4 prepareData derives AC and initiative`,
    },
    {
      id: 'dnd5e2014.L4.passive-perception',
      layer: 'L4',
      quantity: 'Passive Perception',
      formula: '10 + Wis(Perception) modifier (± 5 advantage/disadvantage)',
      inputs: ['Wis score', 'Perception proficiency'],
      edgeCases: ['advantage +5', 'disadvantage -5'],
      source: `${SRD}: Passive Checks`,
      status: 'missing',
    },
    {
      id: 'dnd5e2014.L4.d20-modes',
      layer: 'L4',
      quantity: 'Advantage / disadvantage roll resolution',
      formula: 'advantage = max(2d20); disadvantage = min(2d20)',
      inputs: ['roll mode'],
      edgeCases: ['advantage keeps higher', 'disadvantage keeps lower'],
      source: `${SRD}: Advantage and Disadvantage`,
      status: 'verified',
      testRef: `${T} :: L4 d20 roll modes`,
    },

    // ── L5 spellcasting economy ──
    {
      id: 'dnd5e2014.L5.multiclass-spell-slots',
      layer: 'L5',
      quantity: 'Spell slots (incl. multiclass combined-level table)',
      formula: 'combined caster level → SRD multiclass slot table',
      inputs: ['class levels', 'caster type per class'],
      edgeCases: ['full vs half vs third casters', 'preserve used counts'],
      source: `${SRD}: Multiclassing — Spellcasting`,
      status: 'verified',
      testRef: `${T} :: L5 multiclass spell slots`,
    },
    {
      id: 'dnd5e2014.L5.cantrip-scaling',
      layer: 'L5',
      quantity: 'Cantrip damage scaling by level',
      formula: 'damage dice step at levels 5/11/17',
      inputs: ['character level'],
      edgeCases: ['per-cantrip dice progression'],
      source: `${SRD}: Cantrips`,
      status: 'missing',
    },

    // ── L7 resources & progression ──
    {
      id: 'dnd5e2014.L7.max-hp',
      layer: 'L7',
      quantity: 'Maximum hit points',
      formula: 'sum(hit die or roll + Con mod per level), min 1 per level',
      inputs: ['class levels', 'hit-die rolls', 'Con score'],
      edgeCases: ['multiclass', 'first-level max die', 'explicit rolls', 'min 1/level'],
      source: `${SRD}: Hit Points`,
      status: 'verified',
      testRef: `${T} :: L7 max HP from class hit dice`,
    },
    {
      id: 'dnd5e2014.L7.hit-dice-pool',
      layer: 'L7',
      quantity: 'Hit-dice pool tracking',
      formula: 'per class: total = class level; remaining preserved across level-up',
      inputs: ['class levels', 'previous hit dice'],
      edgeCases: ['level-up gains', 'die-size change resets'],
      source: `${SRD}: Hit Dice; Resting`,
      status: 'implemented',
    },

    // ── L8 active-play state ──
    {
      id: 'dnd5e2014.L8.exhaustion-max-hp',
      layer: 'L8',
      quantity: 'Exhaustion — max HP halved at level 4 (2014)',
      formula: 'maxHP = max(1, floor(maxHP / 2)) when exhaustion ≥ 4',
      inputs: ['exhaustion level', 'maxHP'],
      edgeCases: ['exactly level 4', 'min 1'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion (2014)`,
    },
    {
      id: 'dnd5e2014.L8.exhaustion-lethal',
      layer: 'L8',
      quantity: 'Exhaustion — death at level 6 (2014)',
      formula: 'current = 0, deathSaves.failures = 3 when exhaustion ≥ 6',
      inputs: ['exhaustion level'],
      edgeCases: ['exactly level 6'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion (2014)`,
    },
    {
      id: 'dnd5e2014.L8.exhaustion-clamp',
      layer: 'L8',
      quantity: 'Exhaustion level clamp [0, 6]',
      formula: 'clamp(floor(level), 0, 6)',
      inputs: ['raw exhaustion level'],
      edgeCases: ['negative', 'above 6', 'non-finite → 0'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion (2014)`,
    },
    {
      id: 'dnd5e2014.L8.exhaustion-disadvantage',
      layer: 'L8',
      quantity: 'Exhaustion — disadvantage on ability checks (≥1) and saves (≥3)',
      formula: 'roll mode = disadvantage under threshold conditions',
      inputs: ['exhaustion level', 'check type'],
      edgeCases: ['ability check ≥1', 'save ≥3'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion disadvantage (2014)`,
    },
    {
      id: 'dnd5e2014.L8.apply-damage',
      layer: 'L8',
      quantity: 'Damage application (temp HP, floor, death saves)',
      formula:
        'temp absorbs first; current floors at 0; damage at 0 HP adds a death-save failure; healing resets',
      inputs: ['current/temp/max HP', 'damage amount'],
      edgeCases: [
        'temp partial/full absorb',
        'overkill floors at 0',
        'damage while at 0',
        'healing resets death saves',
      ],
      source: `${SRD}: Damage and Healing; Temporary Hit Points`,
      status: 'verified',
      testRef: `${T} :: L8 applyDamage`,
    },
    {
      id: 'dnd5e2014.L8.death-save-normalize',
      layer: 'L8',
      quantity: 'Death-save normalization [0, 3]',
      formula: 'clamp(successes, 0, 3); clamp(failures, 0, 3)',
      inputs: ['death saves'],
      edgeCases: ['above 3', 'negative'],
      source: `${SRD}: Death Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L8 death-save normalization`,
    },
    {
      id: 'dnd5e2014.L8.condition-poisoned',
      layer: 'L8',
      quantity: 'Condition effects (poisoned disadvantage; auto-fail Str/Dex saves)',
      formula:
        'poisoned → disadvantage on attacks/ability checks; paralyzed/petrified/stunned/unconscious → auto-fail Str/Dex saves',
      inputs: ['active conditions', 'check type'],
      edgeCases: ['poisoned', 'incapacitating conditions auto-fail'],
      source: `${SRD}: Conditions`,
      status: 'implemented',
    },
    {
      id: 'dnd5e2014.L8.concentration-dc',
      layer: 'L8',
      quantity: 'Concentration save DC',
      formula: 'max(10, floor(damage / 2))',
      inputs: ['damage taken'],
      edgeCases: ['low damage floors at 10'],
      source: `${SRD}: Concentration`,
      status: 'missing',
    },
  ],
};

export default dnd5e2014ComputeRegister;
