/**
 * Compute register (Denominator B) for D&D 5e (2024), cited against SRD 5.2.
 *
 * The 2024 engine (src/systems/dnd5e-2024/engine.ts) extends the shared
 * Dnd5eEngineBase, so most quantities are the same code verified by the 2014
 * suite; 2024-specific deltas (Alert initiative, no HP halving, d20 exhaustion
 * penalty) are verified by the dedicated 2024 engine test.
 *
 * The 2024 exhaustion d20 penalty was previously implemented as -1 × level; it
 * has been corrected to the SRD 5.2 RAW -2 × level (Dnd5e2024Engine
 * .getExhaustionD20Penalty) and verified by test.
 */

import type { SystemComputeRegister } from './types';

const SRD = 'SRD 5.2';
const T14 = 'src/__tests__/dnd5e2014EngineMath.test.ts';
const T24 = 'src/__tests__/engines/dnd5e-2024-engine.test.ts';

export const dnd5e2024ComputeRegister: SystemComputeRegister = {
  systemId: 'dnd-5e-2024',
  srdVersion: SRD,
  entries: [
    {
      id: 'dnd5e2024.L1.ability-mod',
      layer: 'L1',
      quantity: 'Ability modifier',
      formula: 'floor((score - 10) / 2)',
      inputs: ['ability score'],
      edgeCases: ['negative scores'],
      source: `${SRD}: Ability Scores`,
      status: 'verified',
      testRef: `${T14} :: L1 ability modifier`,
    },
    {
      id: 'dnd5e2024.L1.proficiency-bonus',
      layer: 'L1',
      quantity: 'Proficiency bonus by level',
      formula: 'ceil(level / 4) + 1',
      inputs: ['level'],
      edgeCases: ['tier boundaries'],
      source: `${SRD}: Proficiency Bonus`,
      status: 'verified',
      testRef: `${T14} :: L1 proficiency bonus by level`,
    },
    {
      id: 'dnd5e2024.L2.ac-formula-set',
      layer: 'L2',
      quantity: 'AC formula set (unarmored/light/medium/heavy + shield)',
      formula: 'shared compute5eAC (Dex caps by armor type; shield adds)',
      inputs: ['Dex', 'armor', 'shield'],
      edgeCases: ['medium Dex cap', 'heavy ignores Dex'],
      source: `${SRD}: Armor Class`,
      status: 'verified',
      testRef: `${T14} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2024.L2.saving-throw',
      layer: 'L2',
      quantity: 'Saving throw modifier',
      formula: 'ability mod + (proficiency if proficient)',
      inputs: ['ability', 'proficiency', 'level'],
      edgeCases: ['proficient vs not'],
      source: `${SRD}: Saving Throws`,
      status: 'verified',
      testRef: `${T14} :: L2/L4 rollCheck modifiers`,
    },
    {
      id: 'dnd5e2024.L2.spell-save-dc',
      layer: 'L2',
      quantity: 'Spell save DC',
      formula: '8 + proficiency + spellcasting ability mod',
      inputs: ['level', 'spell ability'],
      edgeCases: ['per class'],
      source: `${SRD}: Spellcasting`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: 5e spell save DC and attack',
    },
    {
      id: 'dnd5e2024.L2.spell-attack',
      layer: 'L2',
      quantity: 'Spell attack bonus',
      formula: 'proficiency bonus + spellcasting ability mod',
      inputs: ['level', 'spellcasting ability'],
      edgeCases: ['per spellcasting class'],
      source: `${SRD}: Spellcasting — Spell attack modifier`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: 5e spell save DC and attack',
    },
    {
      id: 'dnd5e2024.L2.ac.unarmored-defense-barbarian',
      layer: 'L2',
      quantity: 'AC — Unarmored Defense (Barbarian)',
      formula: '10 + Dex mod + Con mod (+ shield)',
      inputs: ['Dex score', 'Con score', 'shield'],
      edgeCases: ['only while no armor worn'],
      source: `${SRD}: Barbarian — Unarmored Defense`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: 5e Unarmored Defense',
    },
    {
      id: 'dnd5e2024.L2.ac.unarmored-defense-monk',
      layer: 'L2',
      quantity: 'AC — Unarmored Defense (Monk)',
      formula: '10 + Dex mod + Wis mod',
      inputs: ['Dex score', 'Wis score'],
      edgeCases: ['only while no armor or shield'],
      source: `${SRD}: Monk — Unarmored Defense`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: 5e Unarmored Defense',
    },
    {
      id: 'dnd5e2024.L5.cantrip-scaling',
      layer: 'L5',
      quantity: 'Cantrip damage scaling by level',
      formula: 'damage dice step at levels 5/11/17',
      inputs: ['character level'],
      edgeCases: ['per-cantrip dice progression'],
      source: `${SRD}: Cantrips`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: 5e cantrip scaling tier',
    },
    {
      id: 'dnd5e2024.L6.carrying-capacity',
      layer: 'L6',
      quantity: 'Carrying capacity',
      formula: 'Strength score × 15 (lbs)',
      inputs: ['Strength score'],
      edgeCases: ['exceeding it (up to push/drag/lift) drops Speed to 5 ft'],
      source: `${SRD}: Carrying Capacity`,
      status: 'verified',
      testRef: 'src/__tests__/dnd5eMovement.test.ts :: 5e carrying capacity and push/drag/lift',
    },
    {
      id: 'dnd5e2024.L6.push-drag-lift',
      layer: 'L6',
      quantity: 'Push / drag / lift maximum',
      formula: 'Strength score × 30 (twice carrying capacity)',
      inputs: ['Strength score'],
      edgeCases: ['twice carrying capacity'],
      source: `${SRD}: Carrying Capacity — Push, Drag, or Lift`,
      status: 'verified',
      testRef: 'src/__tests__/dnd5eMovement.test.ts :: 5e carrying capacity and push/drag/lift',
    },
    {
      id: 'dnd5e2024.L6.jump-distances',
      layer: 'L6',
      quantity: 'Long jump / high jump distances',
      formula: 'long = Str score ft (half standing); high = 3 + Str mod ft (half standing)',
      inputs: ['Strength score', 'Strength mod', 'running start?'],
      edgeCases: ['standing jump halves (rounded down)', 'high jump floored at 0'],
      source: `${SRD}: Jumping`,
      status: 'verified',
      testRef: 'src/__tests__/dnd5eMovement.test.ts :: 5e jumping',
    },
    {
      id: 'dnd5e2024.L4.skill-check',
      layer: 'L4',
      quantity: 'Skill check modifier (expertise / half)',
      formula: 'ability mod + {prof | 2×prof | ½prof}',
      inputs: ['ability', 'proficiency level'],
      edgeCases: ['expertise', 'half'],
      source: `${SRD}: Skills`,
      status: 'verified',
      testRef: `${T14} :: L2/L4 rollCheck modifiers`,
    },
    {
      id: 'dnd5e2024.L4.initiative-alert',
      layer: 'L4',
      quantity: 'Initiative (2024 Alert feat: best of Dex/Int)',
      formula: 'Alert ? max(Dex mod, Int mod) : Dex mod',
      inputs: ['Dex', 'Int', 'Alert feat'],
      edgeCases: ['Alert swaps in Int when higher'],
      source: `${SRD}: Initiative; Alert feat`,
      status: 'verified',
      testRef: `${T24} :: uses INT for initiative when Alert feat outpaces DEX`,
    },
    {
      id: 'dnd5e2024.L4.d20-modes',
      layer: 'L4',
      quantity: 'Advantage / disadvantage resolution',
      formula: 'advantage = max(2d20); disadvantage = min(2d20)',
      inputs: ['roll mode'],
      edgeCases: ['advantage/disadvantage'],
      source: `${SRD}: Advantage and Disadvantage`,
      status: 'verified',
      testRef: `${T14} :: L4 d20 roll modes`,
    },
    {
      id: 'dnd5e2024.L4.passive-perception',
      layer: 'L4',
      quantity: 'Passive Perception',
      formula: '10 + Wis(Perception) modifier',
      inputs: ['Wis', 'proficiency'],
      edgeCases: ['advantage/disadvantage ±5'],
      source: `${SRD}: Passive Checks`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: 5e passive Perception',
    },
    {
      id: 'dnd5e2024.L5.multiclass-spell-slots',
      layer: 'L5',
      quantity: 'Multiclass spell slots',
      formula: 'combined caster level → SRD multiclass slot table',
      inputs: ['class levels'],
      edgeCases: ['full/half/third casters'],
      source: `${SRD}: Multiclassing`,
      status: 'verified',
      testRef: `${T14} :: L5 multiclass spell slots`,
    },
    {
      id: 'dnd5e2024.L7.max-hp',
      layer: 'L7',
      quantity: 'Maximum hit points (identical to 2014)',
      formula: 'sum(hit die or roll + Con mod), min 1/level',
      inputs: ['class levels', 'rolls', 'Con'],
      edgeCases: ['multiclass', 'explicit rolls'],
      source: `${SRD}: Hit Points`,
      status: 'verified',
      testRef: `${T24} :: calculates HP identically to 2014 rules`,
    },
    {
      id: 'dnd5e2024.L7.hit-dice-pool',
      layer: 'L7',
      quantity: 'Hit-dice pool tracking',
      formula: 'per class total; remaining preserved across prepareData',
      inputs: ['class levels', 'previous hit dice'],
      edgeCases: ['preserve spent'],
      source: `${SRD}: Resting`,
      status: 'verified',
      testRef: `${T24} :: preserves spent hit dice between prepareData calls`,
    },
    {
      id: 'dnd5e2024.L8.exhaustion-no-hp-halve',
      layer: 'L8',
      quantity: 'Exhaustion does NOT halve max HP (2024)',
      formula: 'maxHP unchanged by exhaustion level (2024 rules)',
      inputs: ['exhaustion level'],
      edgeCases: ['level 4 leaves HP intact'],
      source: `${SRD}: Exhaustion (2024)`,
      status: 'verified',
      testRef: `${T24} :: does not halve max HP at exhaustion level 4 (2024 rules)`,
    },
    {
      id: 'dnd5e2024.L8.exhaustion-d20-penalty',
      layer: 'L8',
      quantity: 'Exhaustion d20 penalty (2024)',
      formula: 'RAW: -2 × exhaustion level on d20 tests',
      inputs: ['exhaustion level'],
      edgeCases: ['scales per level'],
      source: `${SRD}: Exhaustion (2024)`,
      status: 'verified',
      testRef:
        'src/__tests__/engines/dnd5e-2024-engine.test.ts :: imposes a -2 per level penalty on d20 tests',
    },
    {
      id: 'dnd5e2024.L8.exhaustion-lethal',
      layer: 'L8',
      quantity: 'Exhaustion lethal at level 6',
      formula: 'death at exhaustion ≥ 6',
      inputs: ['exhaustion level'],
      edgeCases: ['level 6'],
      source: `${SRD}: Exhaustion (2024)`,
      status: 'verified',
      testRef:
        'src/__tests__/engines/dnd5e-2024-engine.test.ts :: is lethal at level 6 (current HP 0, three failed death saves)',
    },
    {
      id: 'dnd5e2024.L8.apply-damage',
      layer: 'L8',
      quantity: 'Damage application (temp HP, floor, healing/death saves)',
      formula: 'temp absorbs; current floors at 0; healing resets death saves',
      inputs: ['HP', 'damage'],
      edgeCases: ['temp absorb', 'healing from 0'],
      source: `${SRD}: Damage and Healing`,
      status: 'verified',
      testRef: `${T24} :: works identically to 2014 engine`,
    },
    {
      id: 'dnd5e2024.L8.condition-poisoned',
      layer: 'L8',
      quantity: 'Poisoned imposes disadvantage',
      formula: 'poisoned → disadvantage on attacks/ability checks',
      inputs: ['conditions'],
      edgeCases: ['ability check disadvantage'],
      source: `${SRD}: Conditions`,
      status: 'verified',
      testRef: `${T24} :: applies disadvantage on ability checks while poisoned`,
    },
    {
      id: 'dnd5e2024.L8.death-save-normalize',
      layer: 'L8',
      quantity: 'Death-save normalization [0,3]',
      formula: 'clamp successes/failures to [0,3]',
      inputs: ['death saves'],
      edgeCases: ['clamp'],
      source: `${SRD}: Death Saving Throws`,
      status: 'verified',
      testRef: `${T14} :: L8 death-save normalization`,
    },
    {
      id: 'dnd5e2024.L8.concentration-dc',
      layer: 'L8',
      quantity: 'Concentration save DC',
      formula: 'max(10, floor(damage / 2))',
      inputs: ['damage'],
      edgeCases: ['floors at 10'],
      source: `${SRD}: Concentration`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: 5e concentration DC',
    },
  ],
};

export default dnd5e2024ComputeRegister;
