/**
 * Compute register (Denominator B) for D&D 5e (2014), cited against SRD 5.1.
 *
 * Status legend (see ./types.ts):
 *   verified    — formula + edge cases pinned by a test (testRef).
 *   implemented — engine computes it, not yet edge-pinned to this register.
 *   missing     — the rules define it; the engine does not compute it yet.
 *
 * Engine sources: src/systems/dnd5e/shared/engine.ts, src/systems/dnd5e/engine.ts,
 * src/rules/compile/defense.ts, src/utils/math.ts, src/utils/spellSlots.ts.
 */

import type { SystemComputeRegister } from './types';

const SRD = 'SRD 5.1';
const T = 'src/__tests__/dnd5e2014EngineMath.test.ts';

export const dnd5e2014ComputeRegister: SystemComputeRegister = {
  systemId: 'dnd-5e-2014',
  srdVersion: SRD,
  entries: [
    // ── L1 ability & proficiency foundation ──
    {
      id: 'dnd5e2014.L1.ability-mod',
      layer: 'L1',
      quantity: 'Ability modifier',
      formula: 'floor((score - 10) / 2)',
      inputs: ['ability score'],
      edgeCases: ['score 1 → -5', 'score 7 → -2 (negative rounding)', 'score 20 → +5'],
      source: `${SRD}: Using Ability Scores`,
      status: 'verified',
      testRef: `${T} :: L1 ability modifier`,
    },
    {
      id: 'dnd5e2014.L1.proficiency-bonus',
      layer: 'L1',
      quantity: 'Proficiency bonus by level',
      formula: 'ceil(level / 4) + 1',
      inputs: ['total character level'],
      edgeCases: ['tier boundaries 4→5, 8→9, 12→13, 16→17', 'capped at +6 by level 20'],
      source: `${SRD}: Beyond 1st Level`,
      status: 'verified',
      testRef: `${T} :: L1 proficiency bonus by level`,
    },

    // ── L2 defenses ──
    {
      id: 'dnd5e2014.L2.ac.unarmored',
      layer: 'L2',
      quantity: 'AC — unarmored',
      formula: '10 + Dex mod (+ shield)',
      inputs: ['Dex score', 'shield'],
      edgeCases: ['negative Dex', 'with shield +2'],
      source: `${SRD}: Armor Class`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.light',
      layer: 'L2',
      quantity: 'AC — light armor',
      formula: 'armor base + full Dex mod (+ shield)',
      inputs: ['armor base', 'Dex score', 'shield'],
      edgeCases: ['full Dex applies (no cap)'],
      source: `${SRD}: Armor`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.medium',
      layer: 'L2',
      quantity: 'AC — medium armor',
      formula: 'armor base + min(Dex mod, 2)',
      inputs: ['armor base', 'Dex score', 'dexBonusMax'],
      edgeCases: [
        'Dex above cap clamps to +2',
        'Dex below cap applies fully',
        'explicit dexBonusMax override',
      ],
      source: `${SRD}: Armor`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.heavy',
      layer: 'L2',
      quantity: 'AC — heavy armor',
      formula: 'armor base (no Dex) (+ shield)',
      inputs: ['armor base', 'shield'],
      edgeCases: ['Dex contributes nothing', 'shield still adds'],
      source: `${SRD}: Armor`,
      status: 'verified',
      testRef: `${T} :: L2 AC formula set`,
    },
    {
      id: 'dnd5e2014.L2.ac.defense-style',
      layer: 'L2',
      quantity: 'AC — Defense fighting style (+1 while armored)',
      formula: 'AC + 1 if wearing armor and Defense style active',
      inputs: ['fighting style', 'armor worn'],
      edgeCases: ['no bonus while unarmored'],
      stacking: 'adds on top of armor AC',
      source: `${SRD}: Fighting Style (Defense)`,
      status: 'verified',
      testRef: `${T} :: L2 Defense fighting style`,
    },
    {
      id: 'dnd5e2014.L2.ac.unarmored-defense-barbarian',
      layer: 'L2',
      quantity: 'AC — Unarmored Defense (Barbarian)',
      formula: 'max(default AC, 10 + Dex mod + Con mod) (+ shield)',
      inputs: ['Dex score', 'Con score', 'shield', 'unarmored-defense-barbarian feature'],
      edgeCases: ['only while no armor worn', 'shield still applies', 'takes the higher formula'],
      source: `${SRD}: Barbarian — Unarmored Defense`,
      status: 'verified',
      testRef: 'src/__tests__/engines/dnd5e-engine.test.ts :: unarmored defense (engine-wired)',
    },
    {
      id: 'dnd5e2014.L2.ac.unarmored-defense-monk',
      layer: 'L2',
      quantity: 'AC — Unarmored Defense (Monk)',
      formula: 'max(default AC, 10 + Dex mod + Wis mod)',
      inputs: ['Dex score', 'Wis score', 'unarmored-defense-monk feature'],
      edgeCases: ['no armor and no shield', 'takes the higher formula'],
      source: `${SRD}: Monk — Unarmored Defense`,
      status: 'verified',
      testRef: 'src/__tests__/engines/dnd5e-engine.test.ts :: unarmored defense (engine-wired)',
    },
    {
      id: 'dnd5e2014.L2.saving-throw',
      layer: 'L2',
      quantity: 'Saving throw modifier',
      formula: 'ability mod + (proficiency bonus if proficient)',
      inputs: ['ability score', 'save proficiency', 'level'],
      edgeCases: [
        'proficient vs not',
        'auto-fail Str/Dex while paralyzed/petrified/stunned/unconscious',
      ],
      source: `${SRD}: Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L2/L4 rollCheck modifiers`,
    },
    {
      id: 'dnd5e2014.L2.spell-save-dc',
      layer: 'L2',
      quantity: 'Spell save DC',
      formula: '8 + proficiency bonus + spellcasting ability mod',
      inputs: ['level', 'spellcasting ability'],
      edgeCases: ['per spellcasting class'],
      source: `${SRD}: Spellcasting — Spell save DC`,
      status: 'verified',
      testRef:
        'src/__tests__/dnd5e2014EngineMath.test.ts :: L2 spell save DC and attack (engine-wired)',
      note: 'Wired in Dnd5eEngineBase.prepareData per spellcasting class (data.spellcasting.classes[].spellSaveDc / spellAttackBonus) via the derivedCasterMath helpers.',
    },
    {
      id: 'dnd5e2014.L2.spell-attack',
      layer: 'L2',
      quantity: 'Spell attack bonus',
      formula: 'proficiency bonus + spellcasting ability mod',
      inputs: ['level', 'spellcasting ability'],
      edgeCases: ['per spellcasting class'],
      source: `${SRD}: Spellcasting — Spell attack modifier`,
      status: 'verified',
      testRef:
        'src/__tests__/dnd5e2014EngineMath.test.ts :: L2 spell save DC and attack (engine-wired)',
      note: 'Wired in Dnd5eEngineBase.prepareData per spellcasting class (data.spellcasting.classes[].spellSaveDc / spellAttackBonus) via the derivedCasterMath helpers.',
    },

    // ── L3 offense ──
    {
      id: 'dnd5e2014.L3.extra-attack-count',
      layer: 'L3',
      quantity: 'Attacks per Attack action (Extra Attack)',
      formula: '1 + count of extra-attack features',
      inputs: ['features'],
      edgeCases: ['Fighter 11 with extra-attack + extra-attack-2 → 3 attacks'],
      source: `${SRD}: Fighter — Extra Attack`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/characterCombatant.test.ts :: 5e Extra Attack in scene combat (phase 4)',
    },
    {
      id: 'dnd5e2014.L3.rage-damage',
      layer: 'L3',
      quantity: 'Rage damage bonus',
      formula: '+2 (level 1), +3 (level 9), +4 (level 16)',
      inputs: ['barbarian level', 'rage toggle', 'rage feature'],
      edgeCases: ['barbarian 9 → +3', 'toggle without feature → no effect'],
      source: `${SRD}: Barbarian — Rage`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/characterCombatant.test.ts :: 5e rider toggles in scene combat (phase 4)',
      note: 'Manual boundary: melee Strength attacks only (rider note travels with the effect).',
    },
    {
      id: 'dnd5e2014.L3.gwm-tradeoff',
      layer: 'L3',
      quantity: 'Great Weapon Master -5/+10',
      formula: 'attack -5, damage +10 while toggled',
      inputs: ['gwm feat', 'toggle'],
      edgeCases: ['feat-gated: toggle without feat → no effect'],
      source: `${SRD}: Feats — Great Weapon Master`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/characterCombatant.test.ts :: 5e rider edition routing: 2014 keeps -5/+10, 2024 refuses it',
      note: 'Manual boundary: heavy melee weapons only. EDITION-SCOPED: this trade is SRD 5.1 only. SRD 5.2 does not open Great Weapon Master (see src/data/dnd/5e-2024/feats/), so collectDnd5eRiderEffects refuses it for dnd-5e-2024 characters; the routing is pinned by the same test.',
    },
    {
      id: 'dnd5e2014.L3.sharpshooter-tradeoff',
      layer: 'L3',
      quantity: 'Sharpshooter -5/+10',
      formula: 'attack -5, damage +10 while toggled',
      inputs: ['sharpshooter feat', 'toggle'],
      edgeCases: ['feat-gated: toggle without feat → no effect'],
      source: `${SRD}: Feats — Sharpshooter`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/characterCombatant.test.ts :: 5e rider edition routing: 2014 keeps -5/+10, 2024 refuses it',
      note: 'Manual boundary: ranged weapons with proficiency only. EDITION-SCOPED: this trade is SRD 5.1 only. SRD 5.2 does not open Sharpshooter (see src/data/dnd/5e-2024/feats/), so collectDnd5eRiderEffects refuses it for dnd-5e-2024 characters; the routing is pinned by the same test.',
    },
    {
      id: 'dnd5e2014.L3.sneak-attack-dice',
      layer: 'L3',
      quantity: 'Sneak Attack dice',
      formula: 'ceil(rogue level / 2) d6',
      inputs: ['rogue level', 'sneak-attack feature', 'toggle'],
      edgeCases: ['rogue 1 → 1d6', 'rogue 20 → 10d6'],
      source: `${SRD}: Rogue — Sneak Attack`,
      status: 'verified',
      testRef: 'src/__tests__/rules/characterCombatant.test.ts :: 5e sneak attack dice (phase 4)',
      note: 'Manual boundary: once per turn, advantage or adjacent-ally positioning asserted by the toggle.',
    },
    {
      id: 'dnd5e2014.L3.divine-smite-base',
      layer: 'L3',
      quantity: 'Divine Smite base damage',
      formula: '2d8 radiant (1st-level slot)',
      inputs: ['divine-smite feature', 'toggle'],
      edgeCases: ['feature-gated: toggle without feature → no effect'],
      source: `${SRD}: Paladin — Divine Smite`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/characterCombatant.test.ts :: collectDnd5eRiderEffects: Sharpshooter and Divine Smite',
      note: 'Manual boundary: slot expenditure and per-slot/undead scaling are manual calls.',
    },
    {
      id: 'dnd5e2014.L3.versatile-damage',
      layer: 'L3',
      quantity: 'Versatile weapon damage die',
      formula: 'larger (two-handed) die when wielded in two hands; base die otherwise',
      inputs: ['weapon dice', 'versatile die', 'off-hand occupancy'],
      edgeCases: ['off-hand occupied (shield/second weapon) → base die'],
      source: `${SRD}: Equipment — Weapon Properties (Versatile)`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/characterCombatant.test.ts :: 5e Versatile: rolls the larger die when wielded two-handed (empty off-hand)',
      note: 'Engine-wired (Denominator B): buildCharacterCombatant consumes the equipped main-hand weapon’s dice via dnd5eVersatileDamageDie. Populating EquippedItem.weaponDamage at equip time (a separate Denominator-A content step) shipped for 5e on 2026-07-14: toEquippedItem now converts the catalog Weapon.damage DiceRoll into the numeric {count, die} the combatant reads.',
    },
    {
      id: 'dnd5e2014.L3.two-weapon-offhand',
      layer: 'L3',
      quantity: 'Two-weapon off-hand attack damage',
      formula:
        'bonus attack with an off-hand light weapon; its damage omits the ability modifier unless the Two-Weapon Fighting style is active (a negative modifier still applies)',
      inputs: ['off-hand light weapon', 'ability mod', 'TWF style'],
      edgeCases: [
        'no off-hand light weapon → no bonus attack',
        'TWF style adds the ability mod',
        'negative modifier still applies',
      ],
      source: `${SRD}: Combat — Two-Weapon Fighting`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/characterCombatant.test.ts :: grants an off-hand attack whose damage omits the ability modifier',
      note: 'Engine-wired: buildCharacterCombatant builds the off-hand attack profile via dnd5eOffHandDamageMod and threads it to the tactical executor, which resolves it once after the Attack-action attacks. Populating EquippedItem.weaponDamage at equip time (a separate Denominator-A content step) shipped for 5e on 2026-07-14: toEquippedItem now converts the catalog Weapon.damage DiceRoll into the numeric {count, die} the combatant reads.',
    },

    // ── L4 skills & derived checks ──
    {
      id: 'dnd5e2014.L4.skill-check',
      layer: 'L4',
      quantity: 'Skill check modifier',
      formula: 'ability mod + {0 | prof | 2×prof (expertise) | ½prof (Jack of All Trades)}',
      inputs: ['ability score', 'skill proficiency level', 'level'],
      edgeCases: ['expertise doubles', 'half (round down)', 'no proficiency'],
      source: `${SRD}: Using Each Ability; Expertise`,
      status: 'verified',
      testRef: `${T} :: L2/L4 rollCheck modifiers`,
    },
    {
      id: 'dnd5e2014.L4.initiative',
      layer: 'L4',
      quantity: 'Initiative',
      formula: 'Dex mod (+ feat modifiers)',
      inputs: ['Dex score'],
      edgeCases: ['base case = Dex mod'],
      source: `${SRD}: Initiative`,
      status: 'verified',
      testRef: `${T} :: L2/L4 prepareData derives AC and initiative`,
    },
    {
      id: 'dnd5e2014.L4.passive-perception',
      layer: 'L4',
      quantity: 'Passive Perception',
      formula: '10 + Wis(Perception) modifier (± 5 advantage/disadvantage)',
      inputs: ['Wis score', 'Perception proficiency'],
      edgeCases: ['advantage +5', 'disadvantage -5'],
      source: `${SRD}: Passive Checks`,
      status: 'verified',
      testRef:
        'src/__tests__/derivation/dnd5eDerivedQuantities.test.ts :: dnd5e.L4.passive-perception',
    },
    {
      id: 'dnd5e2014.L6.speed-armored',
      layer: 'L6',
      quantity: 'Walking speed after heavy-armor Strength penalty',
      formula: 'base speed − 10 ft when armor Str requirement exceeds wearer Strength; else base',
      inputs: ['base speed', 'Strength score', 'worn armor Strength requirement'],
      edgeCases: [
        'no armor requirement → unchanged',
        'under the requirement → −10 ft',
        'meets the requirement → unchanged',
      ],
      source: `${SRD}: Armor — Heavy Armor (Strength requirement)`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/dnd5eDerivedQuantities.test.ts :: dnd5e.L6.speed-armored',
    },
    {
      id: 'dnd5e2014.L6.carrying-capacity',
      layer: 'L6',
      quantity: 'Carrying capacity',
      formula: 'Strength score × 15 (lbs)',
      inputs: ['Strength score'],
      edgeCases: ['Str 10 → 150 lb', 'Str 15 → 225 lb', 'Str 20 → 300 lb'],
      source: `${SRD}: Carrying Capacity`,
      status: 'verified',
      testRef:
        'src/__tests__/derivation/dnd5eDerivedQuantities.test.ts :: dnd5e.L6.carrying-capacity',
      note: 'Computed by the shared declarative derivation layer (DND5E_DERIVED_QUANTITIES → dnd5e.L6.carrying-capacity), applied in the shared Dnd5eEngineBase.prepareData that the 2014 engine runs; identical in SRD 5.1/5.2. Pinned by the generic derivation test.',
    },
    {
      id: 'dnd5e2014.L6.push-drag-lift',
      layer: 'L6',
      quantity: 'Push, drag, or lift maximum',
      formula: 'Strength score × 30 (lbs) — twice carrying capacity',
      inputs: ['Strength score'],
      edgeCases: ['Str 10 → 300 lb', 'Str 15 → 450 lb', 'Str 20 → 600 lb'],
      source: `${SRD}: Carrying Capacity — Push, Drag, or Lift`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/dnd5eDerivedQuantities.test.ts :: dnd5e.L6.push-drag-lift',
      note: 'Shared DND5E_DERIVED_QUANTITIES quantity applied in the shared prepareData the 2014 engine inherits; identical in SRD 5.1/5.2.',
    },
    {
      id: 'dnd5e2014.L6.long-jump',
      layer: 'L6',
      quantity: 'Long jump distance',
      formula: 'Str score ft with a running start (half, rounded down, standing)',
      inputs: ['Strength score', 'running start?'],
      edgeCases: ['standing jump halves (rounded down)', 'clamped at 0'],
      source: `${SRD}: Jumping — Long Jump`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/dnd5eDerivedQuantities.test.ts :: dnd5e.L6.long-jump',
      note: 'Shared DND5E_DERIVED_QUANTITIES quantity applied in the shared prepareData the 2014 engine inherits; identical in SRD 5.1/5.2.',
    },
    {
      id: 'dnd5e2014.L6.high-jump',
      layer: 'L6',
      quantity: 'High jump height',
      formula: '3 + Str mod ft with a running start (half, rounded down, standing), min 0',
      inputs: ['Strength mod', 'running start?'],
      edgeCases: ['standing jump halves (rounded down)', 'floored at 0'],
      source: `${SRD}: Jumping — High Jump`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/dnd5eDerivedQuantities.test.ts :: dnd5e.L6.high-jump',
      note: 'Shared DND5E_DERIVED_QUANTITIES quantity applied in the shared prepareData the 2014 engine inherits; identical in SRD 5.1/5.2.',
    },
    {
      id: 'dnd5e2014.L4.d20-modes',
      layer: 'L4',
      quantity: 'Advantage / disadvantage roll resolution',
      formula: 'advantage = max(2d20); disadvantage = min(2d20)',
      inputs: ['roll mode'],
      edgeCases: ['advantage keeps higher', 'disadvantage keeps lower'],
      source: `${SRD}: Advantage and Disadvantage`,
      status: 'verified',
      testRef: `${T} :: L4 d20 roll modes`,
    },

    // ── L5 spellcasting economy ──
    {
      id: 'dnd5e2014.L5.known-spell-limit',
      layer: 'L5',
      quantity: 'Known-spell count limit (known casters)',
      formula:
        'class table spellsKnown[level] + cantripsKnown[level] (clamped to the table); prepared casters exempt (no fixed cap)',
      inputs: ['class spellcasting progression', 'class level'],
      edgeCases: [
        'level clamps below 1 to the first row',
        'level past the table clamps to the last row',
        'prepared caster returns no cap',
        'overage reports count above the cap, 0 within',
      ],
      source: `${SRD}: Spellcasting — Spells Known of 1st Level and Higher`,
      status: 'verified',
      testRef: 'src/__tests__/dnd5eKnownSpells.test.ts :: dnd5e.L5.known-spell-limit',
      note: 'Enforced warn-not-block in createDnd5eValidator (validateKnownSpellCount) via the dnd5eKnownSpellLimit/Overage helpers this row anchors.',
    },
    {
      id: 'dnd5e2014.L5.multiclass-spell-slots',
      layer: 'L5',
      quantity: 'Spell slots (single-class tables + multiclass combined-level table)',
      formula:
        'single casting class → class table (half = ceil(level/2) from level 2; third = ceil(level/3) from level 3); 2+ casting classes → floored combined caster level → SRD multiclass slot table',
      inputs: ['class levels', 'caster type per class', 'number of casting classes'],
      edgeCases: [
        'single-class Paladin/Ranger odd levels round up (Paladin 3 → 3 slots)',
        'single-class EK/AT use their class table (EK 7 → 4/2)',
        'multiclass floors per the SRD rule',
        'preserve used counts',
      ],
      source: `${SRD}: Multiclassing — Spellcasting; Paladin/Ranger/EK tables`,
      status: 'verified',
      testRef: `${T} :: L5 spell slots (class tables + multiclass)`,
    },
    {
      id: 'dnd5e2014.L5.pact-magic',
      layer: 'L5',
      quantity: 'Warlock Pact Magic slots',
      formula:
        'slots: 1 at L1, 2 at L2, 3 at L11, 4 at L17; slot level = min(5, ceil(min(level, 9) / 2)); recover on short rest; never feeds the multiclass table',
      inputs: ['warlock class levels'],
      edgeCases: ['levels 1/2/5/11/17 thresholds', 'slot level caps at 5', 'short-rest recovery'],
      source: `${SRD}: Warlock — Pact Magic`,
      status: 'verified',
      testRef: 'src/__tests__/utils/spellSlots.test.ts :: computePactMagicSlots',
    },
    {
      id: 'dnd5e2014.L5.cantrip-scaling',
      layer: 'L5',
      quantity: 'Cantrip damage scaling by level',
      formula: 'damage dice step at levels 5/11/17',
      inputs: ['character level'],
      edgeCases: ['per-cantrip dice progression'],
      source: `${SRD}: Cantrips`,
      status: 'verified',
      testRef:
        'src/__tests__/derivation/dnd5eDerivedQuantities.test.ts :: dnd5e.L5.cantrip-scaling',
    },

    // ── L7 resources & progression ──
    {
      id: 'dnd5e2014.L7.max-hp',
      layer: 'L7',
      quantity: 'Maximum hit points',
      formula: 'sum(max(1, hit die or roll + Con mod) per level) — the min-1 clamp is per level',
      inputs: ['class levels', 'hit-die rolls', 'Con score'],
      edgeCases: [
        'multiclass',
        'first-level max die',
        'explicit rolls',
        'per-level min 1 with mixed positive/negative levels',
      ],
      source: `${SRD}: Hit Points`,
      status: 'verified',
      testRef: `${T} :: L7 max HP from class hit dice`,
    },
    {
      id: 'dnd5e2014.L7.hit-dice-pool',
      layer: 'L7',
      quantity: 'Hit-dice pool tracking',
      formula: 'per class: total = class level; remaining preserved across level-up',
      inputs: ['class levels', 'previous hit dice'],
      edgeCases: ['level-up gains', 'die-size change resets'],
      source: `${SRD}: Hit Dice; Resting`,
      status: 'verified',
      testRef: `${T} :: L7 hit-dice pool tracking`,
    },

    // ── L8 active-play state ──
    {
      id: 'dnd5e2014.L8.exhaustion-max-hp',
      layer: 'L8',
      quantity: 'Exhaustion — max HP halved at level 4 (2014)',
      formula:
        'hitPoints.max = max(1, floor(baseMaxHP / 2)) when exhaustion ≥ 4; the unhalved base is kept in baseMaxHP so re-preparing a persisted document never re-halves',
      inputs: ['exhaustion level', 'baseMaxHP'],
      edgeCases: ['exactly level 4', 'min 1', 'idempotent across repeated prepareData'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion (2014)`,
    },
    {
      id: 'dnd5e2014.L8.exhaustion-lethal',
      layer: 'L8',
      quantity: 'Exhaustion — death at level 6 (2014)',
      formula: 'current = 0, deathSaves.failures = 3 when exhaustion ≥ 6',
      inputs: ['exhaustion level'],
      edgeCases: ['exactly level 6'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion (2014)`,
    },
    {
      id: 'dnd5e2014.L8.exhaustion-clamp',
      layer: 'L8',
      quantity: 'Exhaustion level clamp [0, 6]',
      formula: 'clamp(floor(level), 0, 6)',
      inputs: ['raw exhaustion level'],
      edgeCases: ['negative', 'above 6', 'non-finite → 0'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion (2014)`,
    },
    {
      id: 'dnd5e2014.L8.exhaustion-disadvantage',
      layer: 'L8',
      quantity: 'Exhaustion — disadvantage on ability checks (≥1) and saves (≥3)',
      formula: 'roll mode = disadvantage under threshold conditions',
      inputs: ['exhaustion level', 'check type'],
      edgeCases: ['ability check ≥1', 'save ≥3'],
      source: `${SRD}: Exhaustion`,
      status: 'verified',
      testRef: `${T} :: L8 exhaustion disadvantage (2014)`,
    },
    {
      id: 'dnd5e2014.L8.apply-damage',
      layer: 'L8',
      quantity: 'Damage application (temp HP, floor, death saves)',
      formula:
        'temp absorbs first; current floors at 0; damage at 0 HP adds a death-save failure; healing resets',
      inputs: ['current/temp/max HP', 'damage amount'],
      edgeCases: [
        'temp partial/full absorb',
        'overkill floors at 0',
        'damage while at 0',
        'healing resets death saves',
      ],
      source: `${SRD}: Damage and Healing; Temporary Hit Points`,
      status: 'verified',
      testRef: `${T} :: L8 applyDamage`,
    },
    {
      id: 'dnd5e2014.L8.death-save-normalize',
      layer: 'L8',
      quantity: 'Death-save normalization [0, 3]',
      formula: 'clamp(successes, 0, 3); clamp(failures, 0, 3)',
      inputs: ['death saves'],
      edgeCases: ['above 3', 'negative'],
      source: `${SRD}: Death Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L8 death-save normalization`,
    },
    {
      id: 'dnd5e2014.L8.condition-poisoned',
      layer: 'L8',
      quantity: 'Condition effects (poisoned disadvantage; auto-fail Str/Dex saves)',
      formula:
        'poisoned → disadvantage on attacks/ability checks; paralyzed/petrified/stunned/unconscious → auto-fail Str/Dex saves',
      inputs: ['active conditions', 'check type'],
      edgeCases: ['poisoned', 'incapacitating conditions auto-fail'],
      source: `${SRD}: Conditions`,
      status: 'verified',
      testRef: `${T} :: L8 poisoned condition`,
    },
    {
      id: 'dnd5e2014.L8.concentration-dc',
      layer: 'L8',
      quantity: 'Concentration save DC',
      formula: 'max(10, floor(damage / 2))',
      inputs: ['damage taken'],
      edgeCases: ['low damage floors at 10'],
      source: `${SRD}: Concentration`,
      status: 'verified',
      testRef:
        'src/__tests__/derivation/dnd5eDerivedQuantities.test.ts :: dnd5e.L8.concentration-dc',
      note: 'Wired 2026-07-21 (helper-only → wired): surfaced as a derived-quantity card through the declarative derivation layer (DND5E_DERIVED_QUANTITIES → dnd5e.L8.concentration-dc), pinned by the generic derivation test. The DC scales with in-play damage, so the card shows the RAW min-10 floor with the damage-scaling rule in its hint.',
    },
    {
      id: 'dnd5e2014.L8.damage-mitigation-branch',
      layer: 'L8',
      quantity: 'Typed-damage mitigation branch (immune / resistant / vulnerable / none)',
      formula:
        'immunity wins outright; resistant ∧ vulnerable → halve then double → unchanged, reported as none; a type the profile does not declare, or no type at all, → none',
      inputs: ["target's snapshotted damage profile", 'damage type of the channel'],
      edgeCases: [
        'immunity beats a simultaneous resistance and vulnerability',
        'resistant and vulnerable together net to no change',
        'untyped damage is never mitigated',
        'absent profile takes everything at face value',
      ],
      stacking:
        'Non-cumulative: a second declaration of the same type changes nothing. Only two SRD sentences are encoded; the both-resistant-and-vulnerable case is DERIVED from the stated ordering rule (resistance and then vulnerability are applied after all other modifiers), not invented.',
      source: `${SRD}: Damage Resistance and Vulnerability`,
      status: 'verified',
      testRef: 'src/__tests__/rules/damageMitigation.test.ts :: resolveDamageMitigation',
      note: 'Implemented edition-agnostically in the shared rules layer (src/rules/resolver/damageMitigation.ts), applied at scene-event BUILD time by mitigateSceneDamage so RFC 006 replay stays byte-identical. Profiles are snapshotted onto the token at placement, so a scene never re-reads src/data/ at replay time. Only the two 5e registers carry these rows: snapshotDamageProfile is not system-gated, so a 3.5e/PF1e/PF2e token also gets the halve/double treatment, but that is the 5e rule — those systems print flat energy resistance instead and have no row here to claim.',
    },
    {
      id: 'dnd5e2014.L8.damage-mitigation-amount',
      layer: 'L8',
      quantity: 'Mitigated hit-point amount',
      formula: 'immune → 0; resistant → floor(damage / 2); vulnerable → damage × 2; none → damage',
      inputs: ['signed hit-point delta', 'mitigation branch'],
      edgeCases: [
        'odd damage halves rounding down',
        'immunity zeroes',
        'healing (negative amount) untouched under every branch',
        'zero and non-finite amounts left alone rather than invented',
      ],
      source: `${SRD}: Damage Resistance and Vulnerability`,
      status: 'verified',
      testRef: 'src/__tests__/rules/damageMitigation.test.ts :: applyDamageMitigation',
      note: 'Halving rounds down per the SRD general round-down instruction; doubling is exact. Scene damage carries a SIGNED amount where negative is healing, so the healing case is asserted directly — a fire-immune creature is not immune to being healed.',
    },
    {
      id: 'dnd5e2014.L8.damage-channels',
      layer: 'L8',
      quantity: 'Typed damage channels of one hit',
      formula:
        'one channel per damage.<type> effect target in first-seen declaration order; every non-typed target merges into ONE untyped channel; a channel resolving to ≤ 0 takes no part',
      inputs: ['resolved damage fold (byTarget totals)'],
      edgeCases: [
        'typed and untyped in the same hit stay separate',
        'two effects of the same type merge into one channel',
        'a channel that rolled 0 or less is dropped',
      ],
      source: `${SRD}: Damage Types; Damage Resistance and Vulnerability`,
      status: 'verified',
      testRef: 'src/__tests__/rules/damageChannelSplit.test.ts :: collectDamageChannels',
      note: "The untyped channel is kept whole and separate on purpose: untyped damage is never mitigated, so folding it into a typed bucket would let resistance eat points it has no claim to. First-seen order is what makes the split's declaration-order tie-break a stable property of the input rather than of object key enumeration.",
    },
    {
      id: 'dnd5e2014.L8.damage-channel-split',
      layer: 'L8',
      quantity: "Per-channel share of a multi-channel hit's total",
      formula:
        'largest-remainder (Hamilton): each channel takes floor(total × weight / Σweights), then the leftover units are handed out one at a time by descending fractional remainder. Parts sum EXACTLY to the total, asserted by the transform itself',
      inputs: ['damage total (post-crit)', 'channel weights (pre-crit resolved totals)'],
      edgeCases: [
        'a single channel takes the whole total',
        'total 0 gives every channel 0',
        'a zero-weight channel never collects a rounding unit',
        'all-zero weights fall back to an even split rather than dividing by zero',
        'negative total (healing) splits on its magnitude and is re-signed',
        'non-integer total throws rather than silently rounding',
        'a non-zero total across zero channels throws rather than destroying damage',
      ],
      source: `${SRD}: Damage Resistance and Vulnerability`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/damageChannelSplit.test.ts :: splitDamageAcrossChannels — the post-condition',
      note: 'THE APPORTIONMENT RULE IS NOT SRD TEXT — it is an engine decision (WORK_PLAN §3.2, decision B1) and is registered under the rule it SERVES. resolveAttack sums every damage channel into one scalar and crit math then multiplies that scalar as a whole, so the per-type breakdown has to be reconstructed before "damage of that type is halved" can be applied at all; before this landed, multi-channel attacks were left untyped and a flame tongue dealt full damage to a fire-immune creature. Hamilton is chosen over round-and-fix-up because it is symmetric (no channel is privileged by position) and over give-the-fraction-to-the-largest because that biases hard on small totals. Shared implementation in src/rules/resolver/damageChannelSplit.ts, reached from resolveAttack, resolveAreaEffect and the manual entry path (src/__tests__/rules/manualDamage.test.ts :: a total apportioned across weighted channels corroborates the manual caller).',
    },
    {
      id: 'dnd5e2014.L8.damage-channel-split-tiebreak',
      layer: 'L8',
      quantity: 'Leftover-unit order when channel remainders tie',
      formula:
        'rank by fractional remainder desc, then WEIGHT desc (the biggest channel absorbs the remainder), then declaration order — a total order over the input array',
      inputs: ['channel remainders', 'channel weights', 'declaration order'],
      edgeCases: [
        'equal remainders break toward the larger weight, wherever it is declared',
        'equal remainders AND equal weights break toward the earlier declared channel',
        'a larger remainder beats a larger weight — remainder is the primary key',
        'the result does not depend on object key enumeration',
      ],
      source: `${SRD}: Damage Resistance and Vulnerability`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/damageChannelSplit.test.ts :: splitDamageAcrossChannels — tie-breaking',
      note: 'Registered separately from the apportionment because it is what makes the split REPLAYABLE, not a detail of it: RFC 006 promises byte-identical replay, and a tie broken on key enumeration would let the same event log resolve to different numbers under a different engine or a re-ordered object. Like the apportionment itself this is decision B1, not SRD text.',
    },
    {
      id: 'dnd5e2014.L8.multi-channel-mitigation',
      layer: 'L8',
      quantity: 'Per-channel mitigation of a mixed-type hit',
      formula:
        'each channel is mitigated independently against the target profile; the recorded event carries amount, type, mitigation and raw per channel, and the HP delta is the sum of the mitigated channels',
      inputs: ['split channels', "target's snapshotted damage profile"],
      edgeCases: [
        'slashing 6 + fire 4 against fire-resistant → 8; immune → 6; vulnerable → 14',
        'typed + untyped mixed hit: the untyped points survive immunity',
        'a single-channel attack keeps the original one-entry event shape exactly',
        'the split always sums to the damage the resolver reports, across seeds and crits',
      ],
      source: `${SRD}: Damage Resistance and Vulnerability`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/damageChannelSplit.test.ts :: multi-channel damage reaching the grid',
      note: 'The composition of the three rows above, at the seam where damage actually reaches a token. Registered on its own because independence per channel is the RAW claim ("damage of that type"), and it is the one property none of the unit-level rows can show. The identical path is exercised from the manual entry surface by src/__tests__/rules/manualDamage.test.ts :: manual damage through the scene runtime.',
    },
    {
      id: 'dnd5e2014.L9.ability-score-cap',
      layer: 'L9',
      quantity: 'Ability score cap (base score ≤ 20)',
      formula: 'flag when any base ability score exceeds 20',
      inputs: ['baseAttributes'],
      edgeCases: ['exactly at limit legal', 'over limit flagged'],
      source: `${SRD}: Ability Scores and Modifiers (maximum 20)`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/dnd5eLegality.test.ts :: dnd5e 2014 flags a base ability score above 20',
    },
    {
      id: 'dnd5e2014.L9.class-level-sum',
      layer: 'L9',
      quantity: 'Class levels sum to character level',
      formula: 'flag when Σ classLevels.level exceeds character level',
      inputs: ['classLevels', 'level'],
      edgeCases: ['exactly at limit legal', 'over limit flagged'],
      source: `${SRD}: Multiclassing`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/dnd5eLegality.test.ts :: dnd5e 2014 flags class levels exceeding character level',
    },
    {
      id: 'dnd5e2014.L7.asi-feat-cadence',
      layer: 'L7',
      quantity: 'ASI/feat cadence (feats ≤ granted ASI slots)',
      formula:
        'granted ASI slots = Σ per class of count(class ASI levels ≤ class level); flag when feats taken exceed it',
      inputs: ['classLevels', 'feats'],
      edgeCases: [
        'Fighter/Rogue extra ASI levels counted',
        'feats within granted slots → legal',
        'feats over granted slots → flagged',
      ],
      source: `${SRD}: Class tables (Ability Score Improvement); Feats`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/dnd5eLegality.test.ts :: dnd5e 2014 flags more feats than granted ASI slots',
    },
    {
      id: 'dnd5e2014.L9.multiclass-prereq',
      layer: 'L9',
      quantity: 'Multiclass ability prerequisites',
      formula:
        'when 2+ classes, each class must meet its 13-minimum ability prerequisite (OR within a group, AND across groups)',
      inputs: ['classLevels', 'baseAttributes'],
      edgeCases: [
        'single class exempt',
        'meets every prerequisite → legal',
        'below a class minimum → flagged',
      ],
      source: `${SRD}: Multiclassing — Prerequisites`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/dnd5eLegality.test.ts :: dnd5e 2014 flags a multiclass build missing an ability prerequisite',
    },
    {
      id: 'dnd5e2014.L10.background-starting-gold',
      layer: 'L10',
      quantity: 'Background starting gold seeded on first background application',
      formula: 'currency.gold = background.gold, applied only when there is no previous background AND currency.gold === 0',
      inputs: ['selected background\'s starting gold', 'existing currency.gold', 'previous background id'],
      edgeCases: ['Acolyte (the only SRD 5.1 background) seeds 15 gp', 'an existing nonzero gold total is never overwritten', 'switching background later does not re-seed gold'],
      stacking: 'One-shot seeding, not an additive bonus — it never stacks with itself across background changes.',
      source: 'SRD 5.1: Backgrounds — Acolyte (Equipment: … a pouch containing 15 gp)',
      status: 'verified',
      testRef: 'src/__tests__/utils/backgroundTemplate.test.ts :: applies skills, feature, inventory, and starting gold for an initial background',
      note: 'The no-overwrite edge case has its own existing test, src/__tests__/utils/backgroundTemplate.test.ts :: does not auto-apply unresolved choice-based proficiencies or overwrite existing gold (:166, fixture seeds gold: 7 at :193), so both edge cases above are already pinned. Data anchor: src/data/dnd/5e-2014/backgrounds/acolyte.ts:26 (gold: 15). This is the ONLY currency quantity the 5e engine derives at all; everything else in the money economy is stored, not computed.',
    },
    {
      id: 'dnd5e2014.L10.coinage-exchange',
      layer: 'L10',
      quantity: 'Standard coin exchange rate',
      formula: '1 gp = 10 sp = 100 cp; 1 ep = 5 sp; 1 pp = 10 gp — i.e. value in cp = cp + 10·sp + 50·ep + 100·gp + 1000·pp',
      inputs: ['copper', 'silver', 'electrum', 'gold', 'platinum'],
      edgeCases: ['electrum\'s 5-sp rate is the one non-decimal step', 'round-tripping a mixed purse to cp and back must be lossless', 'a purchase priced in gp paid from a mixed purse needs the conversion the engine does not do'],
      stacking: 'Denominations convert, they do not stack — a total is one value expressed in a chosen denomination.',
      source: 'SRD 5.1: Equipment — Coinage (Standard Exchange Rates)',
      status: 'missing',
      note: 'The engine stores five independent, non-negative counters and never converts between them: the Currency shape is src/types/core/character.ts:305-310, defaulted at src/systems/dnd5e/data-model.ts:158, and the only editor (src/components/CurrencyEditor.tsx) writes each denomination in isolation with a Math.max(0, …) clamp and no cross-denomination arithmetic. A repo-wide search for conversion helpers (toCopper/convertCurrency/normalizeCurrency/gpValue/totalGold) returns nothing outside src/data/. Purchase affordability is therefore also uncomputed even though 718 encoded SRD 5.1 equipment entries carry costs in three denominations (669 gp, 25 cp, 24 sp).',
    },
    {
      id: 'dnd5e2014.L10.coin-weight',
      layer: 'L10',
      quantity: 'Weight of carried coinage',
      formula: 'weight (lb) = (cp + sp + ep + gp + pp) / 50 — fifty coins weigh a pound',
      inputs: ['total coin count across all five denominations'],
      edgeCases: ['fewer than 50 coins is a fractional pound, not zero', 'a large gp hoard can materially eat into the Str × 15 carrying capacity'],
      stacking: 'Adds to carried weight alongside inventory item weight; the two are a single load.',
      source: 'SRD 5.1: Equipment — Coinage (a coin weighs about a third of an ounce, so fifty coins weigh a pound)',
      status: 'missing',
      note: 'Closes the loop with the already-verified dnd5e2014.L6.carrying-capacity (Str × 15 lb): capacity is computed but the coin half of the load is not. The only weight sum in the app is item-only — src/components/InventoryManager.tsx:57 reduces over items\' weight × quantity and never touches document.system.currency — so coinage contributes nothing to encumbrance today.',
    },
    {
      id: 'dnd5e2014.L10.advancement-xp-threshold',
      layer: 'L10',
      quantity: 'Character level from accumulated experience points',
      formula: 'level = the highest Character Advancement row whose Experience Points requirement is ≤ experiencePoints; the table spans levels 1-20 and caps there',
      inputs: ['accumulated experience points'],
      edgeCases: ['0 XP resolves to level 1 (the table\'s first row)', 'XP at or beyond the level-20 row stays at level 20', 'XP one point below a row boundary must NOT advance', 'the inverse query (XP still needed for the next level) is the same table read backwards'],
      source: 'SRD 5.1: Beyond 1st Level — Character Advancement table',
      status: 'missing',
      note: 'Deliberately states the rule as a table lookup rather than transcribing the twenty XP thresholds, because the table is not present anywhere in this repo and transcribing remembered numbers would be exactly the fabrication mode docs/GAPS.md 18.7 records. The same SRD 5.1 section is already cited by the existing dnd5e2014.L1.proficiency-bonus row, whose proficiency column comes from this very table — so the section citation is corroborated by an entry already in the register. The engine stores experiencePoints (src/systems/dnd5e/data-model.ts:49) and level (:48) as INDEPENDENT authored fields and never derives one from the other; the XP field is a bare numeric input on the sheet header (src/systems/dnd5e/shared/components/Dnd5eHeaderSection.tsx:84-92). A repo-wide search for xpForLevel / levelFromXp / CHARACTER_ADVANCEMENT finds nothing. Layer note: XP awards are the encounter economy, which is why this sits in L10 alongside pf2e.L10.creature-xp; a reviewer could reasonably argue for L7 (progression) instead — either placement is defensible, but it should not be duplicated across both.',
    },
  ],
};

export default dnd5e2014ComputeRegister;
