/**
 * Compute register (Denominator B) for Mutants & Masterminds 3e, cited against
 * the Hero's Handbook (DHH open content). Engine: src/systems/mam3e/engine.ts,
 * src/systems/mam3e/powerMath.ts.
 */

import type { SystemComputeRegister } from './types';

const HH = "M&M 3e Hero's Handbook (DHH OGC)";
const T = 'src/__tests__/mam3eEngineMath.test.ts';

export const mam3eComputeRegister: SystemComputeRegister = {
  systemId: 'mam3e',
  srdVersion: HH,
  entries: [
    {
      id: 'mam3e.L1.initiative',
      layer: 'L1',
      quantity: 'Initiative bonus',
      formula: 'Agility + 4 × Improved Initiative rank',
      inputs: ['Agility', 'Improved Initiative advantage rank'],
      edgeCases: ['no advantage → Agility only', 'rank floored at 0'],
      source: `${HH}: Initiative`,
      status: 'verified',
      testRef: `${T} :: L1 initiative and L7 starting power points`,
    },
    {
      id: 'mam3e.L3.attack-dc',
      layer: 'L3',
      quantity: 'Attack check difficulty / hit resolution',
      formula: 'attack hits when d20 + attack bonus ≥ 10 + active defense (Dodge/Parry)',
      inputs: ['attack total', 'active defense'],
      edgeCases: ['meets DC = hit', 'misses by 1 = miss'],
      source: `${HH}: Action & Adventure — Attack Checks`,
      status: 'verified',
      testRef: `${T} :: L3 attack and resistance DCs`,
    },
    {
      id: 'mam3e.L3.damage-resistance-dc',
      layer: 'L3',
      quantity: 'Damage resistance DC (Toughness)',
      formula: 'DC = 15 + damage rank',
      inputs: ['damage effect rank'],
      edgeCases: ['rank 0 → DC 15'],
      source: `${HH}: Powers — Damage`,
      status: 'verified',
      testRef: `${T} :: L3 attack and resistance DCs`,
    },
    {
      id: 'mam3e.L3.affliction-dc',
      layer: 'L3',
      quantity: 'Affliction / general effect resistance DC',
      formula: 'DC = 10 + effect rank (Damage is the exception at 15 + rank)',
      inputs: ['effect rank'],
      edgeCases: ['general 10 + rank', 'resisted by Fortitude or Will'],
      source: `${HH}: Powers — Affliction`,
      status: 'verified',
      testRef: `${T} :: L3 attack and resistance DCs`,
    },
    {
      id: 'mam3e.L10.equipment-points',
      layer: 'L10',
      quantity: 'Equipment points from the Equipment advantage',
      formula: '5 EP per advantage rank (spent at 1 EP per power point)',
      inputs: ['Equipment advantage rank'],
      edgeCases: ['rank floored at 0'],
      source: `${HH}: Advantages — Equipment`,
      status: 'verified',
      testRef: `${T} :: L10 M&M equipment and hero points`,
    },
    {
      id: 'mam3e.L7.hero-points',
      layer: 'L7',
      quantity: 'Hero points available',
      formula: '1 at session start + 1 per activated complication',
      inputs: ['complications activated'],
      edgeCases: ['baseline 1 per session'],
      source: `${HH}: Hero Points`,
      status: 'verified',
      testRef: `${T} :: L10 M&M equipment and hero points`,
    },
    {
      id: 'mam3e.L3.degrees-of-success',
      layer: 'L3',
      quantity: 'Degrees of success / failure (universal check resolution)',
      formula:
        'success: 1 + floor((total − DC)/5); failure: −(1 + floor((DC − total)/5)); failure margin → 1-4 degree bands',
      inputs: ['check total', 'DC (or resistance margin)'],
      edgeCases: [
        'exact = 1 degree of success',
        'every full 5 = one further degree',
        'margin bands match the Toughness condition track',
      ],
      source: `${HH}: The Basics — Degrees of Success and Failure`,
      status: 'verified',
      testRef: `${T} :: M&M degrees of success and failure`,
    },
    {
      id: 'mam3e.L7.starting-power-points',
      layer: 'L7',
      quantity: 'Starting power-point budget',
      formula: 'powerPoints.total = 15 × power level',
      inputs: ['power level'],
      edgeCases: ['PL floored at 0'],
      source: `${HH}: Power Level`,
      status: 'verified',
      testRef: `${T} :: L1 initiative and L7 starting power points`,
    },
    {
      id: 'mam3e.L2.defense-totals',
      layer: 'L2',
      quantity: 'Defense totals (Dodge/Parry/Fortitude/Will/Toughness)',
      formula: 'Dodge=Agi+rank; Parry=Fgt+rank; Fort=Sta+rank; Will=Awe+rank; Toughness=Sta+rank',
      inputs: ['abilities', 'defense ranks'],
      edgeCases: ['ability mapping per defense'],
      source: `${HH}: Defenses`,
      status: 'verified',
      testRef: `${T} :: L2 defense totals`,
    },
    {
      id: 'mam3e.L2.toughness-power-bonus',
      layer: 'L2',
      quantity: 'Toughness from Protection/Force Field powers',
      formula:
        'Toughness += power rank for protection/force-field; enhanced-trait adds to named defense',
      inputs: ['powers', 'descriptors'],
      edgeCases: ['protection', 'force-field', 'enhanced-trait by descriptor'],
      stacking: 'power bonuses add to the ability+rank base',
      source: `${HH}: Powers — Protection`,
      status: 'verified',
      testRef: `${T} :: L2 defense totals`,
    },
    {
      id: 'mam3e.L4.skill-total',
      layer: 'L4',
      quantity: 'Skill total',
      formula: 'governing ability + purchased rank',
      inputs: ['abilities', 'skill ranks'],
      edgeCases: ['skill→ability mapping'],
      source: `${HH}: Skills`,
      status: 'verified',
      testRef: `${T} :: L4 skill totals`,
    },
    {
      id: 'mam3e.L8.toughness-failure-track',
      layer: 'L8',
      quantity: 'Toughness failure condition track',
      formula: '1-4 bruised; 5-9 +dazed; 10-14 +staggered; 15+ incapacitated',
      inputs: ['failure margin', 'current track'],
      edgeCases: ['dazed→staggered escalation', 'each margin band'],
      source: `${HH}: Action & Adventure — Damage`,
      status: 'verified',
      testRef: `${T} :: L8 toughness failure track`,
    },
    {
      id: 'mam3e.L9.cost-abilities',
      layer: 'L9',
      quantity: 'Ability cost (2 PP / rank)',
      formula: 'sum(ability ranks) × 2',
      inputs: ['abilities'],
      edgeCases: ['sum across all 8 abilities'],
      source: `${HH}: Abilities`,
      status: 'verified',
      testRef: `${T} :: L9 point-buy costs`,
    },
    {
      id: 'mam3e.L9.cost-defenses',
      layer: 'L9',
      quantity: 'Defense cost (1 PP / rank)',
      formula: 'sum(defense ranks)',
      inputs: ['defense ranks'],
      edgeCases: ['toughness rank charged too'],
      source: `${HH}: Defenses`,
      status: 'verified',
      testRef: `${T} :: L9 point-buy costs`,
    },
    {
      id: 'mam3e.L9.cost-skills',
      layer: 'L9',
      quantity: 'Skill cost (1 PP / 2 ranks)',
      formula: 'ceil(sum(skill ranks) / 2)',
      inputs: ['skill ranks'],
      edgeCases: ['rounds up'],
      source: `${HH}: Skills`,
      status: 'verified',
      testRef: `${T} :: L9 point-buy costs`,
    },
    {
      id: 'mam3e.L9.cost-advantages',
      layer: 'L9',
      quantity: 'Advantage cost (rank, min 1)',
      formula: 'sum(rank > 0 ? rank : 1)',
      inputs: ['advantages'],
      edgeCases: ['ranked vs unranked'],
      source: `${HH}: Advantages`,
      status: 'verified',
      testRef: `${T} :: L9 point-buy costs`,
    },
    {
      id: 'mam3e.L9.power-cost',
      layer: 'L9',
      quantity: 'Power cost formula',
      formula:
        'costPerRank × rank + flatCost, where costPerRank = base + Σ(modifier.costPerRank × modRank)',
      inputs: ['power baseCost', 'rank', 'extras', 'flaws', 'modifierRanks'],
      edgeCases: ['per-rank vs flat', 'rank floors at 1', 'clamped ≥ 0'],
      source: `${HH}: Powers — Power Cost`,
      status: 'verified',
      testRef: `${T} :: L9 calculatePowerPointCost`,
    },
    {
      id: 'mam3e.L9.pl-cap-dodge-toughness',
      layer: 'L9',
      quantity: 'PL cap — Dodge + Toughness ≤ 2×PL',
      formula: 'flag when dodge.total + toughness.total > 2 × powerLevel',
      inputs: ['dodge', 'toughness', 'powerLevel'],
      edgeCases: ['exactly at limit is legal', 'over limit flagged'],
      source: `${HH}: Power Level`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (PL10 → limit 20)`,
    },
    {
      id: 'mam3e.L9.pl-cap-fortitude-will',
      layer: 'L9',
      quantity: 'PL cap — Fortitude + Will ≤ 2×PL',
      formula: 'flag when fortitude.total + will.total > 2 × powerLevel',
      inputs: ['fortitude', 'will', 'powerLevel'],
      edgeCases: ['exactly at limit legal'],
      source: `${HH}: Power Level`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (PL10 → limit 20)`,
    },
    {
      id: 'mam3e.L9.pl-cap-parry-toughness',
      layer: 'L9',
      quantity: 'PL cap — Parry + Toughness ≤ 2×PL',
      formula: 'flag when parry.total + toughness.total > 2 × powerLevel',
      inputs: ['parry', 'toughness', 'powerLevel'],
      edgeCases: ['exactly at limit legal'],
      source: `${HH}: Power Level`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (parry/ranged/perception)`,
    },
    {
      id: 'mam3e.L9.pl-cap-close-attack',
      layer: 'L9',
      quantity: 'PL cap — Close attack bonus + effect rank ≤ 2×PL',
      formula: 'flag when (Fgt + close-combat rank) + close effect rank > 2 × powerLevel',
      inputs: ['Fgt', 'close-combat skill', 'attack powers'],
      edgeCases: ['only when a close attack power exists'],
      source: `${HH}: Power Level — Attack/Effect`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (PL10 → limit 20)`,
    },
    {
      id: 'mam3e.L9.pl-cap-ranged-attack',
      layer: 'L9',
      quantity: 'PL cap — Ranged attack bonus + effect rank ≤ 2×PL',
      formula: 'flag when (Dex + ranged-combat rank) + ranged effect rank > 2 × powerLevel',
      inputs: ['Dex', 'ranged-combat skill', 'attack powers'],
      edgeCases: ['only when a ranged attack power exists'],
      source: `${HH}: Power Level — Attack/Effect`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (parry/ranged/perception)`,
    },
    {
      id: 'mam3e.L9.pl-cap-perception',
      layer: 'L9',
      quantity: 'PL cap — Perception-ranged effect rank ≤ PL',
      formula: 'flag when perception attack effect rank > powerLevel',
      inputs: ['attack powers', 'powerLevel'],
      edgeCases: ['perception range only'],
      source: `${HH}: Power Level`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (parry/ranged/perception)`,
    },
    {
      id: 'mam3e.L9.pp-budget-conservation',
      layer: 'L9',
      quantity: 'PP budget conservation (spent == total)',
      formula: 'sum(spent.*) should equal powerPoints.total (= PL × 15 typical)',
      inputs: ['spent categories', 'total'],
      edgeCases: ['over/under spend'],
      source: `${HH}: Power Points`,
      status: 'verified',
      testRef: 'src/__tests__/mam3eEngineMath.test.ts :: L9 PP budget accounting',
    },
    {
      id: 'mam3e.L10.measurements-track',
      layer: 'L10',
      quantity: 'Measurements doubling track (mass/distance/time)',
      formula: 'measure = rank0Value × 2^rank (each rank doubles the measure)',
      inputs: ['rank-0 anchor (per measure)', 'rank'],
      edgeCases: ['doubling property f(r+1)=2·f(r)', 'per-measure anchor is data'],
      source: `${HH}: Measurements Table`,
      status: 'verified',
      testRef: `${T} :: L10 M&M measurements doubling track`,
    },
  ],
};

export default mam3eComputeRegister;
