/**
 * Compute register (Denominator B) for Mutants & Masterminds 3e, cited against
 * the Hero's Handbook (DHH open content). Engine: src/systems/mam3e/engine.ts,
 * src/systems/mam3e/powerMath.ts.
 */

import type { SystemComputeRegister } from './types';

const HH = "M&M 3e Hero's Handbook (DHH OGC)";
const T = 'src/__tests__/mam3eEngineMath.test.ts';

export const mam3eComputeRegister: SystemComputeRegister = {
  systemId: 'mam3e',
  srdVersion: HH,
  entries: [
    {
      id: 'mam3e.L1.initiative',
      layer: 'L1',
      quantity: 'Initiative bonus',
      formula: 'Agility + 4 × Improved Initiative rank',
      inputs: ['Agility', 'Improved Initiative advantage rank'],
      edgeCases: ['no advantage → Agility only', 'rank floored at 0'],
      source: `${HH}: Initiative`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/mam3eDerivedQuantities.test.ts :: mam3e.L1.initiative',
    },
    {
      id: 'mam3e.L3.attack-dc',
      layer: 'L3',
      quantity: 'Attack check difficulty / hit resolution',
      formula: 'attack hits when d20 + attack bonus ≥ 10 + active defense (Dodge/Parry)',
      inputs: ['attack total', 'active defense'],
      edgeCases: ['meets DC = hit', 'misses by 1 = miss'],
      source: `${HH}: Action & Adventure — Attack Checks`,
      status: 'verified',
      testRef: `${T} :: L3 attack and resistance DCs`,
    },
    {
      id: 'mam3e.L3.damage-resistance-dc',
      layer: 'L3',
      quantity: 'Damage resistance DC (Toughness)',
      formula: 'DC = 15 + damage rank',
      inputs: ['damage effect rank'],
      edgeCases: ['rank 0 → DC 15'],
      source: `${HH}: Powers — Damage`,
      status: 'verified',
      testRef: `${T} :: L3 attack and resistance DCs`,
    },
    {
      id: 'mam3e.L3.affliction-dc',
      layer: 'L3',
      quantity: 'Affliction / general effect resistance DC',
      formula: 'DC = 10 + effect rank (Damage is the exception at 15 + rank)',
      inputs: ['effect rank'],
      edgeCases: ['general 10 + rank', 'resisted by Fortitude or Will'],
      source: `${HH}: Powers — Affliction`,
      status: 'verified',
      testRef: `${T} :: L3 attack and resistance DCs`,
    },
    {
      id: 'mam3e.L3.critical-hit',
      layer: 'L3',
      quantity: 'Critical hit resistance-DC bonus',
      formula: 'natural 20 that hits → resistance DC + 5',
      inputs: ['base resistance DC'],
      edgeCases: ['applies to any effect DC'],
      source: `${HH}: Action & Adventure — Critical Hit`,
      status: 'verified',
      testRef: `${T} :: L3 attack and resistance DCs`,
    },
    {
      id: 'mam3e.L10.equipment-points',
      layer: 'L10',
      quantity: 'Equipment points from the Equipment advantage',
      formula: '5 EP per advantage rank (spent at 1 EP per power point)',
      inputs: ['Equipment advantage rank'],
      edgeCases: ['rank floored at 0'],
      source: `${HH}: Advantages — Equipment`,
      status: 'verified',
      testRef: `${T} :: L10 M&M equipment and hero points`,
    },
    {
      id: 'mam3e.L7.hero-points',
      layer: 'L7',
      quantity: 'Hero points available',
      formula: '1 at session start + 1 per activated complication',
      inputs: ['complications activated'],
      edgeCases: ['baseline 1 per session'],
      source: `${HH}: Hero Points`,
      status: 'verified',
      testRef: `${T} :: L10 M&M equipment and hero points`,
    },
    {
      id: 'mam3e.L3.degrees-of-success',
      layer: 'L3',
      quantity: 'Degrees of success / failure (universal check resolution)',
      formula:
        'success: 1 + floor((total − DC)/5); failure: −(1 + floor((DC − total)/5)); failure margin → 1-4 degree bands',
      inputs: ['check total', 'DC (or resistance margin)'],
      edgeCases: [
        'exact = 1 degree of success',
        'every full 5 = one further degree',
        'margin bands match the Toughness condition track',
      ],
      source: `${HH}: The Basics — Degrees of Success and Failure`,
      status: 'verified',
      testRef: `${T} :: M&M degrees of success and failure`,
    },
    {
      id: 'mam3e.L7.starting-power-points',
      layer: 'L7',
      quantity: 'Starting power-point budget',
      formula: 'powerPoints.total = 15 × power level',
      inputs: ['power level'],
      edgeCases: ['PL floored at 0'],
      source: `${HH}: Power Level`,
      status: 'verified',
      testRef:
        'src/__tests__/derivation/mam3eDerivedQuantities.test.ts :: mam3e.L7.starting-power-points',
    },
    {
      id: 'mam3e.L2.defense-totals',
      layer: 'L2',
      quantity: 'Defense totals (Dodge/Parry/Fortitude/Will/Toughness)',
      formula: 'Dodge=Agi+rank; Parry=Fgt+rank; Fort=Sta+rank; Will=Awe+rank; Toughness=Sta+rank',
      inputs: ['abilities', 'defense ranks'],
      edgeCases: ['ability mapping per defense'],
      source: `${HH}: Defenses`,
      status: 'verified',
      testRef: `${T} :: L2 defense totals`,
    },
    {
      id: 'mam3e.L2.toughness-power-bonus',
      layer: 'L2',
      quantity: 'Toughness from Protection/Force Field powers',
      formula:
        'Toughness += power rank for protection/force-field; enhanced-trait adds to named defense',
      inputs: ['powers', 'descriptors'],
      edgeCases: ['protection', 'force-field', 'enhanced-trait by descriptor'],
      stacking: 'power bonuses add to the ability+rank base',
      source: `${HH}: Powers — Protection`,
      status: 'verified',
      testRef: `${T} :: L2 defense totals`,
    },
    {
      id: 'mam3e.L4.skill-total',
      layer: 'L4',
      quantity: 'Skill total',
      formula: 'governing ability + purchased rank',
      inputs: ['abilities', 'skill ranks'],
      edgeCases: ['skill→ability mapping'],
      source: `${HH}: Skills`,
      status: 'verified',
      testRef: `${T} :: L4 skill totals`,
    },
    {
      id: 'mam3e.L8.toughness-failure-track',
      layer: 'L8',
      quantity: 'Toughness failure condition track',
      formula: '1-4 bruised; 5-9 +dazed; 10-14 +staggered; 15+ incapacitated',
      inputs: ['failure margin', 'current track'],
      edgeCases: ['dazed→staggered escalation', 'each margin band'],
      source: `${HH}: Action & Adventure — Damage`,
      status: 'verified',
      testRef: `${T} :: L8 toughness failure track`,
    },
    {
      id: 'mam3e.L9.cost-abilities',
      layer: 'L9',
      quantity: 'Ability cost (2 PP / rank)',
      formula: 'sum(ability ranks) × 2',
      inputs: ['abilities'],
      edgeCases: ['sum across all 8 abilities'],
      source: `${HH}: Abilities`,
      status: 'verified',
      testRef: `${T} :: L9 point-buy costs`,
    },
    {
      id: 'mam3e.L9.cost-defenses',
      layer: 'L9',
      quantity: 'Defense cost (1 PP / rank)',
      formula: 'sum(defense ranks)',
      inputs: ['defense ranks'],
      edgeCases: ['toughness rank charged too'],
      source: `${HH}: Defenses`,
      status: 'verified',
      testRef: `${T} :: L9 point-buy costs`,
    },
    {
      id: 'mam3e.L9.cost-skills',
      layer: 'L9',
      quantity: 'Skill cost (1 PP / 2 ranks)',
      formula: 'ceil(sum(skill ranks) / 2)',
      inputs: ['skill ranks'],
      edgeCases: ['rounds up'],
      source: `${HH}: Skills`,
      status: 'verified',
      testRef: `${T} :: L9 point-buy costs`,
    },
    {
      id: 'mam3e.L9.cost-advantages',
      layer: 'L9',
      quantity: 'Advantage cost (rank, min 1)',
      formula: 'sum(rank > 0 ? rank : 1)',
      inputs: ['advantages'],
      edgeCases: ['ranked vs unranked'],
      source: `${HH}: Advantages`,
      status: 'verified',
      testRef: `${T} :: L9 point-buy costs`,
    },
    {
      id: 'mam3e.L9.power-cost',
      layer: 'L9',
      quantity: 'Power cost formula',
      formula:
        'costPerRank × rank + flatCost, where costPerRank = base + Σ(modifier.costPerRank × modRank); minimum-cost rule: when costPerRank < 1, per-rank cost = ceil(rank / (2 − costPerRank)) — 1 point per 2 ranks, then per 3, …',
      inputs: ['power baseCost', 'rank', 'extras', 'flaws', 'modifierRanks'],
      edgeCases: [
        'per-rank vs flat',
        'rank floors at 1',
        'clamped ≥ 0',
        'costPerRank < 1 → 1 point per (2 − costPerRank) ranks, rounded up',
      ],
      source: `${HH}: Powers — Power Cost; Modifiers (minimum cost)`,
      status: 'verified',
      testRef: `${T} :: L9 calculatePowerPointCost`,
      note: 'Minimum-cost rule covered by "H2 minimum-cost rule for heavily flawed powers" in the same suite; no flawed power with rank > 0 costs 0 points.',
    },
    {
      id: 'mam3e.L9.pl-cap-dodge-toughness',
      layer: 'L9',
      quantity: 'PL cap — Dodge + Toughness ≤ 2×PL',
      formula: 'flag when dodge.total + toughness.total > 2 × powerLevel',
      inputs: ['dodge', 'toughness', 'powerLevel'],
      edgeCases: ['exactly at limit is legal', 'over limit flagged'],
      source: `${HH}: Power Level`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (PL10 → limit 20)`,
    },
    {
      id: 'mam3e.L9.pl-cap-fortitude-will',
      layer: 'L9',
      quantity: 'PL cap — Fortitude + Will ≤ 2×PL',
      formula: 'flag when fortitude.total + will.total > 2 × powerLevel',
      inputs: ['fortitude', 'will', 'powerLevel'],
      edgeCases: ['exactly at limit legal'],
      source: `${HH}: Power Level`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (PL10 → limit 20)`,
    },
    {
      id: 'mam3e.L9.pl-cap-parry-toughness',
      layer: 'L9',
      quantity: 'PL cap — Parry + Toughness ≤ 2×PL',
      formula: 'flag when parry.total + toughness.total > 2 × powerLevel',
      inputs: ['parry', 'toughness', 'powerLevel'],
      edgeCases: ['exactly at limit legal'],
      source: `${HH}: Power Level`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (parry/ranged/perception)`,
    },
    {
      id: 'mam3e.L9.pl-cap-close-attack',
      layer: 'L9',
      quantity: 'PL cap — Close attack bonus + effect rank ≤ 2×PL',
      formula: 'flag when (Fgt + close-combat rank) + close effect rank > 2 × powerLevel',
      inputs: ['Fgt', 'close-combat skill', 'attack powers'],
      edgeCases: ['only when a close attack power exists'],
      source: `${HH}: Power Level — Attack/Effect`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (PL10 → limit 20)`,
    },
    {
      id: 'mam3e.L9.pl-cap-ranged-attack',
      layer: 'L9',
      quantity: 'PL cap — Ranged attack bonus + effect rank ≤ 2×PL',
      formula: 'flag when (Dex + ranged-combat rank) + ranged effect rank > 2 × powerLevel',
      inputs: ['Dex', 'ranged-combat skill', 'attack powers'],
      edgeCases: ['only when a ranged attack power exists'],
      source: `${HH}: Power Level — Attack/Effect`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (parry/ranged/perception)`,
    },
    {
      id: 'mam3e.L9.pl-cap-perception',
      layer: 'L9',
      quantity: 'PL cap — Perception-ranged effect rank ≤ PL',
      formula: 'flag when perception attack effect rank > powerLevel',
      inputs: ['attack powers', 'powerLevel'],
      edgeCases: ['perception range only'],
      source: `${HH}: Power Level`,
      status: 'verified',
      testRef: `${T} :: L9 Power-Level caps (parry/ranged/perception)`,
    },
    {
      id: 'mam3e.L9.pp-budget-conservation',
      layer: 'L9',
      quantity: 'PP budget conservation (spent == total)',
      formula: 'sum(spent.*) should equal powerPoints.total (= PL × 15 typical)',
      inputs: ['spent categories', 'total'],
      edgeCases: ['over/under spend'],
      source: `${HH}: Power Points`,
      status: 'verified',
      testRef: 'src/__tests__/mam3eEngineMath.test.ts :: L9 PP budget accounting',
    },
    {
      id: 'mam3e.L10.measurements-track',
      layer: 'L10',
      quantity: 'Measurements doubling track (mass/distance/time)',
      formula: 'measure = rank0Value × 2^rank (each rank doubles the measure)',
      inputs: ['rank-0 anchor (per measure)', 'rank'],
      edgeCases: ['doubling property f(r+1)=2·f(r)', 'per-measure anchor is data'],
      source: `${HH}: Measurements Table`,
      status: 'verified',
      testRef: `${T} :: L10 M&M measurements doubling track`,
    },
    {
      id: 'mam3e.L6.move-action-distance',
      layer: 'L6',
      quantity: 'Distance moved with a move action (from speed rank)',
      formula: 'distance moved = Measurements Table DISTANCE entry at rank = the mode\'s speed rank; unmodified human ground speed rank = 0 = 30 ft. Two move actions in a turn move the speed-rank distance each time.',
      inputs: ['active movement mode\'s speed rank', 'Measurements Table distance column', 'number of move actions spent'],
      edgeCases: ['rank 0 (no Speed effect) → 30 ft per move action', 'rank 1 → 60 ft; rank 2 → 120 ft; rank 3 → 250 ft', 'two move actions → speed-rank distance twice, NOT rank+1', 'negative speed rank (Hindered at rank 0) → rank -1 = 15 ft'],
      stacking: 'Movement-effect ranks set a mode\'s speed rank; they do not add to each other across modes — each mode (ground/flight/swimming/burrowing) carries its own independent speed rank.',
      exceptions: ['The printed distance track is ROUNDED, not a pure power of two: rank 3 is 250 ft (not 30×2^3 = 240), rank 5 is 900 ft (not 960), rank 7 is 0.5 mile (not 3,840 ft). The mass track by contrast tracks 50×2^r closely. This means the existing mam3e.L10.measurements-track model (measure = rank0Value × 2^rank, src/systems/mam3e/powerMath.ts:49-51) is an IDEALIZATION that diverges from the real distance column at rank 3 and above — any L6 implementation must read the table, not multiply.'],
      source: 'M&M 3e Hero\'s Handbook (DHH OGC): Action & Adventure — Movement; Ranks and Measures — Measurements Table',
      status: 'missing',
      note: 'Rank-0 = 30 ft anchor independently confirmed twice: the Measurements Table distance column in the repo\'s sanctioned source (frnprt/mm3e-character-creator js/data.js, rank \'0\' → \'30 feet\', cited at docs/srd-sources.md:51) and the d20HeroSRD Action & Adventure movement text (\'normally this is rank 0 ground speed for most people, up to 30 feet\').',
    },
    {
      id: 'mam3e.L6.running-speed-boost',
      layer: 'L6',
      quantity: 'Running (all-out ground movement) speed-rank boost',
      formula: 'free-action Athletics check vs DC 15; success (one or more degrees) → ground speed rank +1 for one round',
      inputs: ['Athletics total (Strength + Athletics rank, per mam3e.L4.skill-total)', 'DC 15', 'degrees of success (mam3e.L3.degrees-of-success)'],
      edgeCases: ['failure → no boost', 'exactly 15 → 1 degree → +1 rank', 'boost expires after one round, so it must not persist into the next turn', '+1 speed rank roughly DOUBLES distance, e.g. rank 0 (30 ft) → rank 1 (60 ft)'],
      stacking: 'Applies to the GROUND speed rank only, and only for the round; it is a temporary rank shift, not a distance bonus, so it composes with mam3e.L6.move-action-distance by rank, not by feet.',
      source: 'M&M 3e Hero\'s Handbook (DHH OGC): Action & Adventure — Movement (Running); Skills — Athletics',
      status: 'missing',
      note: 'Whether more degrees grant more than +1 rank is NOT established by the open-content text I could retrieve — the wording is \'one or more degree of success increases your ground speed rank by +1\', which reads as a flat +1. An implementation must not invent degree scaling here without confirming against the Hero\'s Handbook directly.',
    },
    {
      id: 'mam3e.L6.lifting-capacity',
      layer: 'L6',
      quantity: 'Lifting capacity (mass rank a character can lift)',
      formula: 'mass rank liftable = Strength rank; convert via the Measurements Table MASS column (rank 0 = 50 lbs, each rank ≈ doubles)',
      inputs: ['Strength rank (abilities.str)', 'Measurements Table mass column'],
      edgeCases: ['Str 0 → mass rank 0 → 50 lbs', 'Str 3 → mass rank 3 → 400 lbs', 'Str 10 → mass rank 10 → 25 tons', 'negative Strength is legal in M&M and yields a negative mass rank (Str -1 → 25 lbs)'],
      stacking: 'Effective Strength for lifting can exceed the ability rank via limited Enhanced Strength; the lifting mass rank uses the EFFECTIVE Strength rank, not the raw ability.',
      exceptions: ['Power-Lifting (src/data/mutants-and-masterminds/3e/powers/core/general.ts:296-313) is Enhanced Strength Limited to Lifting: \'+1 effective Strength rank for lifting/carrying per rank\', applying only to lifting, carrying and breaking objects — so it raises this quantity without raising close-attack damage or any other Strength-derived value.', 'Insubstantial forms alter effective Strength entirely (gaseous/energy/incorporeal: \'no effective Strength\'), zeroing this quantity.'],
      source: 'M&M 3e Hero\'s Handbook (DHH OGC): Abilities — Strength (Lifting); Ranks and Measures — Measurements Table',
      status: 'missing',
      note: 'Anchor confirmed by two independent worked examples that both land exactly on the mass column of the sanctioned js/data.js table: Strength 3 lifts 400 lbs (table rank 3 = \'400 lbs\') and Strength 10 lifts 25 tons (table rank 10 = \'25 tons\'). Note the rank-0 mass anchor is 50 lbs, NOT 100 lbs — a plausible-looking wrong constant to guard against.',
    },
    {
      id: 'mam3e.L6.throwing-distance',
      layer: 'L6',
      quantity: 'Throwing distance rank for a lifted object',
      formula: 'thrown distance rank = Strength rank − the object\'s mass rank; convert the result via the Measurements Table DISTANCE column',
      inputs: ['Strength rank (effective, per lifting)', 'object\'s mass rank', 'Measurements Table distance column'],
      edgeCases: ['Str 10 throwing a mass-rank-8 object → distance rank 2 → 120 ft', 'result rank 0 → 30 ft', 'object mass rank equal to Strength rank → distance rank 0 (barely liftable, minimal throw)', 'object mass rank ABOVE Strength rank → cannot be lifted at all, so the quantity is undefined rather than negative'],
      stacking: 'Chains off the effective Strength rank used by mam3e.L6.lifting-capacity, so Power-Lifting raises throwing distance too.',
      source: 'M&M 3e Hero\'s Handbook (DHH OGC): Abilities — Strength (Throwing); Ranks and Measures — Measurements Table',
      status: 'missing',
      note: 'Verified against the SRD\'s own worked example, which round-trips exactly through the sanctioned table: Strength 10 (lifts 25 tons = mass rank 10) picks up a 10-ton truck (mass rank 8), 10 − 8 = 2, and distance rank 2 = 120 feet — matching js/data.js MEASUREMENT_TABLE[\'2\'].distance = \'120 feet\'.',
    },
    {
      id: 'mam3e.L6.jump-distance',
      layer: 'L6',
      quantity: 'Jump distance from an Athletics check (no Leaping effect)',
      formula: 'running long jump (ft) = the Athletics check RESULT; standing long jump = result ÷ 2; vertical jump = result ÷ 5; standing vertical jump = result ÷ 10. Routine (unpressured) result = Athletics bonus + 10.',
      inputs: ['Athletics total (Strength + Athletics rank)', 'jump kind (running/standing × horizontal/vertical)', 'check result, or bonus + 10 when routine'],
      edgeCases: ['Athletics bonus +10, routine → 20 ft running long jump, 10 ft standing, 4 ft vertical, 2 ft standing vertical', 'Athletics bonus +15, routine → 25 ft running long jump', 'routine checks are unavailable under pressure unless Skill Mastery applies', 'the divisors apply to the CHECK RESULT, not to the bonus'],
      stacking: 'Uses the same Athletics total as mam3e.L4.skill-total; no separate jump modifier exists in core.',
      exceptions: ['Characters with the Leaping effect use mam3e.L6.leaping-distance instead of (not in addition to) this Athletics-based distance.'],
      source: 'M&M 3e Hero\'s Handbook (DHH OGC): Skills — Athletics (Jumping)',
      status: 'missing',
      note: 'The divisor set (÷2 standing, ÷5 vertical, ÷10 standing vertical) and the \'bonus + 10\' routine baseline were retrieved twice from the d20HeroSRD Skills chapter and are self-consistent with its worked example (+10 bonus → 20 / 10 / 4 / 2 ft). The direct page 403s automated fetchers (as docs/srd-sources.md:17-19 already documents for publisher sites), so a human should confirm against the Hero\'s Handbook before this row is promoted past \'missing\'.',
    },
    {
      id: 'mam3e.L6.leaping-distance',
      layer: 'L6',
      quantity: 'Leap distance from the Leaping effect',
      formula: 'leap distance rank = Leaping rank − 2; convert via the Measurements Table DISTANCE column. No falling damage on landing within the maximum distance.',
      inputs: ['Leaping power rank', 'Measurements Table distance column'],
      edgeCases: ['Leaping rank 1 → distance rank -1 → 15 ft', 'Leaping rank 2 → distance rank 0 → 30 ft', 'Leaping rank 5 → distance rank 3 → 250 ft', 'Leaping rank 20 → distance rank 18 → 1,000 miles', 'landing within the maximum leap deals no falling damage — an explicit exemption, not a computed value'],
      stacking: 'Replaces the Athletics jump distance rather than adding to it; the Leaping effect is instant duration, so each leap is its own action.',
      source: 'M&M 3e Hero\'s Handbook (DHH OGC): Powers — Leaping (Movement effect)',
      status: 'missing',
      note: 'DATA DEFECT FOUND WHILE VERIFYING (report separately, outside this register): src/data/mutants-and-masterminds/3e/powers/core/movement.ts:81 claims \'Rank 10: 2 miles\' for Leaping. By the confirmed rank−2 rule, Leaping 10 → distance rank 8 = 1 MILE (js/data.js MEASUREMENT_TABLE[\'8\'].distance = \'1 mile\'; \'2 miles\' is rank 9). The file\'s other two anchors are correct (rank 1 → 15 ft, rank 5 → 250 ft), so line 81 is off by one rank. The identical \'Rank 10: 2 miles\' line on Teleport (same file:101) needs the same check. The rank−2 rule itself is triple-confirmed by the SRD\'s own examples: 15 ft at rank 1, 30 ft at rank 2, 1,000 miles at rank 20 — all three land exactly on the sanctioned table.',
    },
    {
      id: 'mam3e.L6.speed-rank-condition-modifiers',
      layer: 'L6',
      quantity: 'Speed rank modified by conditions (Hindered / Immobile)',
      formula: 'Hindered → speed rank −1 (half speed if already rank 0); Immobile → speed 0, cannot move. Conditions that include Hindered inherit the penalty.',
      inputs: ['active condition set', 'current speed rank per mode'],
      edgeCases: ['Hindered at rank 2 → rank 1', 'Hindered at rank 0 → half of 30 ft = 15 ft (the one place the rule leaves the rank track)', 'Immobile (2nd-degree Hindered) → speed 0', 'Staggered = Dazed + Hindered, so it carries the −1', 'Prone, Fatigued, Restrained and Exhausted all include Hindered and therefore all carry the −1', 'Blind includes Hindered'],
      stacking: 'Hindered does not stack with itself across multiple sources — the second degree is Immobile, not −2; the condition track escalates by degree rather than summing penalties.',
      source: 'M&M 3e Hero\'s Handbook (DHH OGC): Conditions — Hindered, Immobile',
      status: 'missing',
      note: 'Condition texts confirmed verbatim in the repo\'s sanctioned source js/data.js CONDITIONS: Hindered = \'Speed rank –1 (half speed if already 0).\', Immobile = \'Speed 0, cannot move (2nd degree Hindered).\', Staggered = \'Dazed and Hindered.\', Prone/Fatigued/Restrained include Hindered. This row is the natural second value-bearing axis for the existing mam3e conditions IR seam, which today folds only the Bruised Toughness penalty.',
    },
    {
      id: 'mam3e.L6.distance-over-time',
      layer: 'L6',
      quantity: 'Distance covered over an elapsed time (travel-time conversion)',
      formula: 'distance rank covered = speed rank + time rank; convert the resulting rank via the Measurements Table DISTANCE column',
      inputs: ['speed rank', 'time rank (Measurements Table time column)', 'Measurements Table distance column'],
      edgeCases: ['speed rank 0 + time rank 0 (6 seconds) → distance rank 0 = 30 ft, consistent with the move-action distance', 'speed rank 5 + time rank 9 (1 hour) → distance rank 14 = 60 miles', 'negative time ranks are legal (rank -2 = 1 second)', 'the rounded distance column means rank arithmetic is exact but the FEET are table lookups, never 30×2^rank'],
      stacking: 'Rank addition is the whole mechanism — this is the general rank-algebra rule that makes speed, time and distance interconvertible, and it is what makes the Measurements Table a compute input rather than flavor.',
      source: 'M&M 3e Hero\'s Handbook (DHH OGC): Ranks and Measures — Measurements Table (relating mass, distance, speed and time)',
      status: 'missing',
      note: 'Confirmed by the SRD\'s own statement of the rule: \'To determine the distance a hero covers in a given amount of time, add the rank of the time to the rank of the hero\'s speed, with normal human ground speed being rank 0.\' Implementing this row would also surface the rounding divergence noted on mam3e.L6.move-action-distance, since the existing L10 pure-2^rank model cannot reproduce the printed distance column.',
    },
  ],
};

export default mam3eComputeRegister;
