/**
 * Compute register (Denominator B) for Pathfinder 1e, cited against the Core
 * Rulebook (open game content). Engine: src/systems/pf1e/engine.ts; shared:
 * src/systems/shared/d20-helpers.ts, src/utils/armorClass.ts.
 */

import type { SystemComputeRegister } from './types';

const CRB = 'PF1e Core Rulebook (OGC)';
const T = 'src/__tests__/d20LegacyEngineMath.test.ts';

export const pf1eComputeRegister: SystemComputeRegister = {
  systemId: 'pf1e',
  srdVersion: CRB,
  entries: [
    {
      id: 'pf1e.L1.ability-mod',
      layer: 'L1',
      quantity: 'Ability modifier',
      formula: 'floor((score - 10) / 2)',
      inputs: ['ability score'],
      edgeCases: ['negative scores'],
      source: `${CRB}: Getting Started`,
      status: 'implemented',
    },
    {
      id: 'pf1e.L1.bab-track',
      layer: 'L1',
      quantity: 'BAB progression track (full / three-quarter / half)',
      formula: 'full=level; three-quarter=floor(level*3/4); half=floor(level/2)',
      inputs: ['class level', 'progression'],
      edgeCases: ['rounding at each track'],
      source: `${CRB}: Classes — Base Attack Bonus`,
      status: 'verified',
      testRef: `${T} :: L1/L3 BAB progression tracks`,
    },
    {
      id: 'pf1e.L1.save-progression',
      layer: 'L1',
      quantity: 'Good/poor base save progression',
      formula: 'good=2+floor(level/2); poor=floor(level/3)',
      inputs: ['class level', 'save quality'],
      edgeCases: ['level 1 good=2 vs poor=0'],
      source: `${CRB}: Classes — Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L1 d20 base save progressions`,
    },
    {
      id: 'pf1e.L2.ac',
      layer: 'L2',
      quantity: 'AC — total, touch, flat-footed (with size + Dex cap)',
      formula:
        'total=10+armor+shield+min(Dex,cap)+size; touch=10+Dex+size; flatFooted=10+armor+shield+size',
      inputs: ['Dex', 'size', 'armor', 'shield'],
      edgeCases: ['touch ignores armor/shield', 'flat-footed ignores Dex', 'Dex cap'],
      source: `${CRB}: Combat — Armor Class`,
      status: 'verified',
      testRef: `${T} :: L2 d20-legacy AC (touch / flat-footed / size)`,
    },
    {
      id: 'pf1e.L2.saves-total',
      layer: 'L2',
      quantity: 'Saving throw totals (Fort/Ref/Will)',
      formula: 'base (summed across classes) + ability mod + misc',
      inputs: ['class levels', 'Con/Dex/Wis', 'misc'],
      edgeCases: ['multiclass base sum'],
      source: `${CRB}: Combat — Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L3.bab-sum',
      layer: 'L3',
      quantity: 'Total BAB (multiclass sum)',
      formula: 'sum(classBAB(level, track))',
      inputs: ['class levels'],
      edgeCases: ['feeds CMB/CMD'],
      source: `${CRB}: Combat — Attack Bonus`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L3.cmb',
      layer: 'L3',
      quantity: 'Combat Maneuver Bonus (CMB)',
      formula: 'BAB + Str mod + special size modifier',
      inputs: ['BAB', 'Str', 'size'],
      edgeCases: ['size modifier sign opposite of AC', 'large +1'],
      stacking: 'CMB size modifier differs from AC size modifier',
      source: `${CRB}: Combat — Combat Maneuver Bonus`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L3.cmd',
      layer: 'L3',
      quantity: 'Combat Maneuver Defense (CMD)',
      formula: '10 + BAB + Str mod + Dex mod + special size modifier',
      inputs: ['BAB', 'Str', 'Dex', 'size'],
      edgeCases: ['includes both Str and Dex'],
      source: `${CRB}: Combat — Combat Maneuver Defense`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L3.attack-roll',
      layer: 'L3',
      quantity: 'Attack roll modifier',
      formula: 'BAB + Str mod (melee)',
      inputs: ['BAB', 'Str'],
      edgeCases: ['melee vs ranged'],
      source: `${CRB}: Combat — Attack Roll`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L3.iterative-attacks',
      layer: 'L3',
      quantity: 'Iterative attacks',
      formula: 'extra attacks at BAB +6/+11/+16, each at -5 cumulative',
      inputs: ['BAB'],
      edgeCases: ['full attack only'],
      source: `${CRB}: Combat — Full Attack`,
      status: 'missing',
    },
    {
      id: 'pf1e.L3.maneuver-types',
      layer: 'L3',
      quantity: 'Specific combat maneuvers (trip/disarm/grapple/etc.) vs CMD',
      formula: 'CMB check vs target CMD, per maneuver',
      inputs: ['CMB', 'target CMD'],
      edgeCases: ['per-maneuver modifiers'],
      source: `${CRB}: Combat — Combat Maneuvers`,
      status: 'missing',
    },
    {
      id: 'pf1e.L4.skill-ranks',
      layer: 'L4',
      quantity: 'Skill check modifier (ranks + ability + class-skill +3)',
      formula: 'ability mod + ranks + (3 if class skill and ranks ≥ 1)',
      inputs: ['ability', 'ranks', 'class skill?'],
      edgeCases: ['+3 only when trained', 'max ranks = level'],
      source: `${CRB}: Skills`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L4.initiative',
      layer: 'L4',
      quantity: 'Initiative',
      formula: 'Dex mod',
      inputs: ['Dex'],
      edgeCases: ['Improved Initiative +4 via misc'],
      source: `${CRB}: Combat — Initiative`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L5.vancian-slots',
      layer: 'L5',
      quantity: 'Spells per day (Vancian slot totals + bonus spells)',
      formula: 'class table by level + bonus spells from high ability',
      inputs: ['class levels', 'casting ability'],
      edgeCases: ['domain slots'],
      source: `${CRB}: Magic — Spells Per Day`,
      status: 'implemented',
    },
    {
      id: 'pf1e.L5.spell-save-dc',
      layer: 'L5',
      quantity: 'Spell save DC',
      formula: '10 + spell level + casting ability mod',
      inputs: ['spell level', 'casting ability'],
      edgeCases: ['per spell level'],
      source: `${CRB}: Magic — Saving Throws`,
      status: 'missing',
    },
    {
      id: 'pf1e.L7.max-hp',
      layer: 'L7',
      quantity: 'Maximum hit points',
      formula: 'sum(max(1, hit-die roll + Con mod)) (+ favored-class HP), min 1',
      inputs: ['hit-die rolls', 'Con', 'favored class'],
      edgeCases: ['min 1 per die'],
      source: `${CRB}: Combat — Hit Points`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L7.favored-class-hp',
      layer: 'L7',
      quantity: 'Favored-class HP bonus',
      formula: '+1 HP per level taken with the HP favored-class choice',
      inputs: ['favored-class choices'],
      edgeCases: ['HP vs skill choice'],
      source: `${CRB}: Classes — Favored Class`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L7.favored-class-skill',
      layer: 'L7',
      quantity: 'Favored-class skill bonus',
      formula: '+1 skill point per level taken with the skill favored-class choice',
      inputs: ['favored-class choices'],
      edgeCases: ['accumulates per level'],
      source: `${CRB}: Classes — Favored Class`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L8.apply-damage',
      layer: 'L8',
      quantity: 'Damage application (temp HP, floor at 0)',
      formula: 'temp absorbs first; current floors at 0; healing capped at max',
      inputs: ['current/temp/max HP', 'damage'],
      edgeCases: ['temp absorb', 'overkill floors at 0'],
      source: `${CRB}: Combat — Injury and Death`,
      status: 'verified',
      testRef: `${T} :: L8 d20-legacy damage application`,
    },
  ],
};

export default pf1eComputeRegister;
