/**
 * Compute register (Denominator B) for Pathfinder 1e, cited against the Core
 * Rulebook (open game content). Engine: src/systems/pf1e/engine.ts; shared:
 * src/systems/shared/d20-helpers.ts, src/rules/compile/defense.ts.
 */

import type { SystemComputeRegister } from './types';

const CRB = 'PF1e Core Rulebook (OGC)';
const T = 'src/__tests__/d20LegacyEngineMath.test.ts';

export const pf1eComputeRegister: SystemComputeRegister = {
  systemId: 'pf1e',
  srdVersion: CRB,
  entries: [
    {
      id: 'pf1e.L1.ability-mod',
      layer: 'L1',
      quantity: 'Ability modifier',
      formula: 'floor((score - 10) / 2)',
      inputs: ['ability score'],
      edgeCases: ['negative scores'],
      source: `${CRB}: Getting Started`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: shared ability modifier',
    },
    {
      id: 'pf1e.L1.bab-track',
      layer: 'L1',
      quantity: 'BAB progression track (full / three-quarter / half)',
      formula: 'full=level; three-quarter=floor(level*3/4); half=floor(level/2)',
      inputs: ['class level', 'progression'],
      edgeCases: ['rounding at each track'],
      source: `${CRB}: Classes — Base Attack Bonus`,
      status: 'verified',
      testRef: `${T} :: L1/L3 BAB progression tracks`,
    },
    {
      id: 'pf1e.L1.save-progression',
      layer: 'L1',
      quantity: 'Good/poor base save progression',
      formula: 'good=2+floor(level/2); poor=floor(level/3)',
      inputs: ['class level', 'save quality'],
      edgeCases: ['level 1 good=2 vs poor=0'],
      source: `${CRB}: Classes — Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L1 d20 base save progressions`,
    },
    {
      id: 'pf1e.L2.ac',
      layer: 'L2',
      quantity: 'AC — total, touch, flat-footed (with size + Dex cap)',
      formula:
        'total=10+armor+shield+min(Dex,cap)+size; touch=10+Dex+size; flatFooted=10+armor+shield+size',
      inputs: ['Dex', 'size', 'armor', 'shield'],
      edgeCases: ['touch ignores armor/shield', 'flat-footed ignores Dex', 'Dex cap'],
      note: 'Migrated to the declarative derivation layer (PF1E_DERIVED_QUANTITIES). The anchored `total` is pf1e.L2.ac.total, whose faithful compute folds the shared base (computeD20LegacyAC(...).total) through the resolver so it equals data.armorClass.total; a no-gear case reduces to the anchored `const total = 10 + armor + shield + Dex + size` (defense.ts, shared with 3.5e), keeping the pf1e.L2.ac mutation live. touch/flat-footed are pure display-bearing scalars (ac.touch / ac.flat-footed) with no register row.',
      source: `${CRB}: Combat — Armor Class`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf1eDerivedQuantities.test.ts :: pf1e.L2.ac.total',
    },
    {
      id: 'pf1e.L2.saves-total',
      layer: 'L2',
      quantity: 'Saving throw totals (Fort/Ref/Will)',
      formula: 'base (summed across classes) + ability mod + misc',
      inputs: ['class levels', 'Con/Dex/Wis', 'misc'],
      edgeCases: ['multiclass base sum'],
      source: `${CRB}: Combat — Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L3.bab-sum',
      layer: 'L3',
      quantity: 'Total BAB (multiclass sum)',
      formula: 'sum(classBAB(level, track))',
      inputs: ['class levels'],
      edgeCases: ['feeds CMB/CMD'],
      source: `${CRB}: Combat — Attack Bonus`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf1eDerivedQuantities.test.ts :: pf1e.L3.bab-sum',
    },
    {
      id: 'pf1e.L3.cmb',
      layer: 'L3',
      quantity: 'Combat Maneuver Bonus (CMB)',
      formula: 'BAB + Str mod + special size modifier',
      inputs: ['BAB', 'Str', 'size'],
      edgeCases: ['size modifier sign opposite of AC', 'large +1'],
      stacking: 'CMB size modifier differs from AC size modifier',
      source: `${CRB}: Combat — Combat Maneuver Bonus`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L3.cmd',
      layer: 'L3',
      quantity: 'Combat Maneuver Defense (CMD)',
      formula: '10 + BAB + Str mod + Dex mod + special size modifier',
      inputs: ['BAB', 'Str', 'Dex', 'size'],
      edgeCases: ['includes both Str and Dex'],
      source: `${CRB}: Combat — Combat Maneuver Defense`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L3.attack-roll',
      layer: 'L3',
      quantity: 'Attack roll modifier',
      formula: 'BAB + Str mod (melee)',
      inputs: ['BAB', 'Str'],
      edgeCases: ['melee vs ranged'],
      source: `${CRB}: Combat — Attack Roll`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L3.iterative-attacks',
      layer: 'L3',
      quantity: 'Iterative attacks',
      formula: 'extra attacks at BAB +6/+11/+16, each at -5 cumulative',
      inputs: ['BAB'],
      edgeCases: ['full attack only'],
      source: `${CRB}: Combat — Full Attack`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: d20 iterative attacks',
      note: 'Scene-wired: buildCharacterCombatant derives attacksPerRound/iterativePenaltyStep from BAB and the tactical executor applies the cumulative -5 (src/__tests__/rules/characterCombatant.test.ts :: legacy-d20 iterative attacks).',
    },
    {
      id: 'pf1e.L3.crit-confirmation',
      layer: 'L3',
      quantity: 'Critical hit confirmation and multiplier',
      formula:
        'a natural threat confirms on a second attack roll (same bonus) vs AC; confirmed damage = normal damage × the weapon crit multiplier (×2 default), extra dice not multiplied',
      inputs: ['threat', 'attack bonus', 'AC', 'critical multiplier'],
      edgeCases: ['unconfirmed threat = ordinary hit', 'extra dice (sneak attack) not multiplied'],
      source: `${CRB}: Combat — Critical Hits`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/attackResolution.test.ts :: a confirmed threat multiplies normal damage by the weapon multiplier',
      note: 'Scene-wired: resolveAttack rolls the confirmation d20 from the same seeded stream and applies d20CriticalDamage when critModel is "confirm-multiply" — selected for 3.5e/PF1e by sceneCombat (replacing the 5e double-dice default).',
    },
    {
      id: 'pf1e.L3.maneuver-types',
      layer: 'L3',
      quantity: 'Specific combat maneuvers (trip/disarm/grapple/etc.) vs CMD',
      formula: 'CMB check vs target CMD, per maneuver',
      inputs: ['CMB', 'target CMD'],
      edgeCases: ['per-maneuver modifiers'],
      source: `${CRB}: Combat — Combat Maneuvers`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: PF1e max ranks and maneuvers',
    },
    {
      id: 'pf1e.L4.skill-ranks',
      layer: 'L4',
      quantity: 'Skill check modifier (ranks + ability + class-skill +3)',
      formula: 'ability mod + ranks + (3 if class skill and ranks ≥ 1)',
      inputs: ['ability', 'ranks', 'class skill?'],
      edgeCases: ['+3 only when trained', 'max ranks = level'],
      source: `${CRB}: Skills`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L4.max-rank-cap',
      layer: 'L4',
      quantity: 'Max skill ranks per skill',
      formula:
        'max ranks in a skill = character level (class skills add +3 to the bonus, not the cap)',
      inputs: ['level'],
      edgeCases: ['cap is the character level, unlike 3.5e class/cross-class split'],
      source: `${CRB}: Skills — Ranks`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf1eDerivedQuantities.test.ts :: pf1e.L4.max-rank-cap',
    },
    {
      id: 'pf1e.L4.initiative',
      layer: 'L4',
      quantity: 'Initiative',
      formula: 'Dex mod',
      inputs: ['Dex'],
      edgeCases: ['Improved Initiative +4 via misc'],
      source: `${CRB}: Combat — Initiative`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L5.vancian-slots',
      layer: 'L5',
      quantity: 'Spells per day (Vancian slot totals + bonus spells)',
      formula: 'class table by level + bonus spells from high ability',
      inputs: ['class levels', 'casting ability'],
      edgeCases: ['domain slots'],
      source: `${CRB}: Magic — Spells Per Day`,
      status: 'verified',
      testRef: 'src/__tests__/d20LegacyEngineMath.test.ts :: L5 d20 Vancian spell-slot totals',
    },
    {
      id: 'pf1e.L5.spell-save-dc',
      layer: 'L5',
      quantity: 'Spell save DC',
      formula: '10 + spell level + casting ability mod',
      inputs: ['spell level', 'casting ability'],
      edgeCases: ['per spell level'],
      source: `${CRB}: Magic — Saving Throws`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: d20 legacy spell save DC',
    },
    {
      id: 'pf1e.L5.bonus-spells',
      layer: 'L5',
      quantity: 'Bonus spells per day from casting ability',
      formula: 'spell level ≥ 1 and mod ≥ level → floor((mod − level) / 4) + 1; else 0',
      inputs: ['casting ability mod', 'spell level'],
      edgeCases: ['no bonus cantrips', 'mod must reach the spell level'],
      source: `${CRB}: Magic — Bonus Spells`,
      status: 'verified',
      testRef: `${T} :: L5 d20 bonus spells from a high casting ability`,
    },
    {
      id: 'pf1e.L5.concentration-dc',
      layer: 'L5',
      quantity: 'Concentration check DCs (defensive / damage)',
      formula: 'defensive = 15 + 2 × spell level; while damaged = 10 + damage + spell level',
      inputs: ['spell level', 'damage taken'],
      edgeCases: ['check = d20 + caster level + casting mod'],
      source: `${CRB}: Magic — Concentration`,
      status: 'verified',
      testRef: `${T} :: L5/L8 Pathfinder 1e concentration, death, and feats`,
    },
    {
      id: 'pf1e.L8.hp-state-track',
      layer: 'L8',
      quantity: 'Disabled / dying / dead HP track (death at −Con)',
      formula: '> 0 healthy; = 0 disabled; below 0 dying; ≤ −Constitution dead',
      inputs: ['current HP', 'Constitution score'],
      edgeCases: ['death threshold scales with Con (unlike 3.5e −10)'],
      source: `${CRB}: Combat — Injury and Death`,
      status: 'verified',
      testRef: `${T} :: L5/L8 Pathfinder 1e concentration, death, and feats`,
    },
    {
      id: 'pf1e.L7.feats-from-level',
      layer: 'L7',
      quantity: 'Feats gained from level',
      formula: 'one at 1st level and every odd level thereafter = ceil(level / 2)',
      inputs: ['level'],
      edgeCases: ['racial/class bonus feats added separately'],
      source: `${CRB}: Character Advancement`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf1eDerivedQuantities.test.ts :: pf1e.L7.feats-from-level',
    },
    {
      id: 'pf1e.L6.carrying-capacity',
      layer: 'L6',
      quantity: 'Carrying capacity (light/medium/heavy thresholds)',
      formula:
        'heavy = Str table (x4 per +10 Str above 19); light = ⌊heavy/3⌋; medium = ⌊2·heavy/3⌋',
      inputs: ['Strength'],
      edgeCases: ['x4 doubling above Str 19', 'Str 0 = 0 lbs', '1/3 and 2/3 splits'],
      source: `${CRB}: Carrying Capacity`,
      status: 'verified',
      testRef: `${T} :: L6 d20-legacy carrying capacity`,
    },
    {
      id: 'pf1e.L6.encumbrance',
      layer: 'L6',
      quantity: 'Load category + encumbrance penalties (max Dex / check / run)',
      formula: 'category by thresholds; light: none/0/x4; medium: +3/-3/x4; heavy: +1/-6/x3',
      inputs: ['Strength', 'carried weight'],
      edgeCases: ['load → max Dex cap', 'run multiplier drops to x3 when heavy'],
      source: `${CRB}: Carrying Capacity — Encumbrance`,
      status: 'verified',
      testRef: `${T} :: L6 d20-legacy carrying capacity`,
    },
    {
      id: 'pf1e.L6.lift-drag',
      layer: 'L6',
      quantity: 'Lift/drag limits',
      formula: 'over head = max load; off ground = 2× max; push/drag = 5× max',
      inputs: ['Strength'],
      edgeCases: ['off-ground = stagger only'],
      source: `${CRB}: Carrying Capacity — Lifting and Dragging`,
      status: 'verified',
      testRef: `${T} :: L6 d20-legacy carrying capacity`,
    },
    {
      id: 'pf1e.L7.max-hp',
      layer: 'L7',
      quantity: 'Maximum hit points',
      formula: 'sum(max(1, hit-die roll + Con mod)) (+ favored-class HP), min 1',
      inputs: ['hit-die rolls', 'Con', 'favored class'],
      edgeCases: ['min 1 per die'],
      source: `${CRB}: Combat — Hit Points`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L7.favored-class-hp',
      layer: 'L7',
      quantity: 'Favored-class HP bonus',
      formula: '+1 HP per level taken with the HP favored-class choice',
      inputs: ['favored-class choices'],
      edgeCases: ['HP vs skill choice'],
      source: `${CRB}: Classes — Favored Class`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L7.favored-class-skill',
      layer: 'L7',
      quantity: 'Favored-class skill bonus',
      formula: '+1 skill point per level taken with the skill favored-class choice',
      inputs: ['favored-class choices'],
      edgeCases: ['accumulates per level'],
      source: `${CRB}: Classes — Favored Class`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L8.apply-damage',
      layer: 'L8',
      quantity: 'Damage application (temp HP, floor at 0)',
      formula: 'temp absorbs first; current floors at 0; healing capped at max',
      inputs: ['current/temp/max HP', 'damage'],
      edgeCases: ['temp absorb', 'overkill floors at 0'],
      source: `${CRB}: Combat — Injury and Death`,
      status: 'verified',
      testRef: `${T} :: L8 d20-legacy damage application`,
    },
    {
      id: 'pf1e.L9.skill-max-ranks',
      layer: 'L9',
      quantity: 'Max skill ranks per skill (≤ character level)',
      formula: "flag when a skill's ranks exceed the character level",
      inputs: ['skillRanks', 'level'],
      edgeCases: ['exactly at limit legal', 'over limit flagged'],
      source: `${CRB}: Skills — Ranks`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/pf1eLegality.test.ts :: pf1e flags skill ranks above the character level',
    },
    {
      id: 'pf1e.L9.class-level-sum',
      layer: 'L9',
      quantity: 'Class levels sum to character level',
      formula: 'flag when Σ classLevels.level exceeds character level',
      inputs: ['classLevels', 'level'],
      edgeCases: ['exactly at limit legal', 'over limit flagged'],
      source: `${CRB}: Character Advancement`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/pf1eLegality.test.ts :: pf1e flags class levels exceeding character level',
    },
  ],
};

export default pf1eComputeRegister;
