/**
 * Compute register (Denominator B) for Pathfinder 1e, cited against the Core
 * Rulebook (open game content). Engine: src/systems/pf1e/engine.ts; shared:
 * src/systems/shared/d20-helpers.ts, src/rules/compile/defense.ts.
 */

import type { SystemComputeRegister } from './types';

const CRB = 'PF1e Core Rulebook (OGC)';
const T = 'src/__tests__/d20LegacyEngineMath.test.ts';

export const pf1eComputeRegister: SystemComputeRegister = {
  systemId: 'pf1e',
  srdVersion: CRB,
  entries: [
    {
      id: 'pf1e.L1.ability-mod',
      layer: 'L1',
      quantity: 'Ability modifier',
      formula: 'floor((score - 10) / 2)',
      inputs: ['ability score'],
      edgeCases: ['negative scores'],
      source: `${CRB}: Getting Started`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: shared ability modifier',
    },
    {
      id: 'pf1e.L1.bab-track',
      layer: 'L1',
      quantity: 'BAB progression track (full / three-quarter / half)',
      formula: 'full=level; three-quarter=floor(level*3/4); half=floor(level/2)',
      inputs: ['class level', 'progression'],
      edgeCases: ['rounding at each track'],
      source: `${CRB}: Classes — Base Attack Bonus`,
      status: 'verified',
      testRef: `${T} :: L1/L3 BAB progression tracks`,
    },
    {
      id: 'pf1e.L1.save-progression',
      layer: 'L1',
      quantity: 'Good/poor base save progression',
      formula: 'good=2+floor(level/2); poor=floor(level/3)',
      inputs: ['class level', 'save quality'],
      edgeCases: ['level 1 good=2 vs poor=0'],
      source: `${CRB}: Classes — Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L1 d20 base save progressions`,
    },
    {
      id: 'pf1e.L2.ac',
      layer: 'L2',
      quantity: 'AC — total, touch, flat-footed (with size + Dex cap)',
      formula:
        'total=10+armor+shield+min(Dex,cap)+size; touch=10+Dex+size; flatFooted=10+armor+shield+size',
      inputs: ['Dex', 'size', 'armor', 'shield'],
      edgeCases: ['touch ignores armor/shield', 'flat-footed ignores Dex', 'Dex cap'],
      note: 'Migrated to the declarative derivation layer (PF1E_DERIVED_QUANTITIES). The anchored `total` is pf1e.L2.ac.total, whose faithful compute folds the shared base (computeD20LegacyAC(...).total) through the resolver so it equals data.armorClass.total; a no-gear case reduces to the anchored `const total = 10 + armor + shield + Dex + size` (defense.ts, shared with 3.5e), keeping the pf1e.L2.ac mutation live. touch/flat-footed are pure display-bearing scalars (ac.touch / ac.flat-footed) with no register row.',
      source: `${CRB}: Combat — Armor Class`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf1eDerivedQuantities.test.ts :: pf1e.L2.ac.total',
    },
    {
      id: 'pf1e.L2.saves-total',
      layer: 'L2',
      quantity: 'Saving throw totals (Fort/Ref/Will)',
      formula: 'base (summed across classes) + ability mod + misc',
      inputs: ['class levels', 'Con/Dex/Wis', 'misc'],
      edgeCases: ['multiclass base sum'],
      source: `${CRB}: Combat — Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L3.bab-sum',
      layer: 'L3',
      quantity: 'Total BAB (multiclass sum)',
      formula: 'sum(classBAB(level, track))',
      inputs: ['class levels'],
      edgeCases: ['feeds CMB/CMD'],
      source: `${CRB}: Combat — Attack Bonus`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf1eDerivedQuantities.test.ts :: pf1e.L3.bab-sum',
    },
    {
      id: 'pf1e.L10.wealth-by-level',
      layer: 'L10',
      quantity: 'Expected character wealth (gp) by level',
      formula: 'CRB "Character Wealth by Level" table (index = level − 1)',
      inputs: ['character level'],
      edgeCases: [
        'level 1 → 0 (class starting wealth, not on the table)',
        'mid table (level 5 → 10,500)',
        'clamps past 20 to the 20th-level figure',
      ],
      source: `${CRB}: Character Wealth by Level`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf1eDerivedQuantities.test.ts :: pf1e.L10.wealth-by-level',
    },
    {
      id: 'pf1e.L10.average-party-level',
      layer: 'L10',
      quantity: 'Average Party Level (APL)',
      formula:
        'round(mean(party levels)); +1 when the party is six or more; −1 when three or fewer; floored at 1',
      inputs: ['party levels'],
      edgeCases: [
        'rounds to the NEAREST whole number (avg 4.5 → APL 5), not down',
        'six level-4 characters → APL 5',
        'three level-4 characters → APL 3',
        'clamped to a minimum of 1',
        'empty party → no APL (budget short-circuits to 0)',
      ],
      exceptions: [
        'The party-size ±1 adjustment is PF1e-only — the 3.5e sibling (dnd35eEncounterBudget, src/scene/encounterDraft.ts:245) deliberately has no party-size term.',
        'Rounding to nearest is an explicit exception to the d20 round-down default, called out in the engine comment at src/scene/encounterDraft.ts:103-111.',
      ],
      source: `${CRB}: Gamemastering — Designing Encounters (Average Party Level)`,
      status: 'verified',
      testRef:
        'src/__tests__/scene/encounterDraft.test.ts :: target CR = APL + difficulty offset, XP from the awards table',
      note: 'Computed inside pf1eEncounterXpBudget (src/scene/encounterDraft.ts:117-121). Registered separately from the budget because APL is its own named CRB quantity and carries the two PF1e divergences above; the budget row pins the CR/award stage that consumes it.',
    },
    {
      id: 'pf1e.L10.encounter-xp-budget',
      layer: 'L10',
      quantity: 'Encounter XP budget (target CR from APL + difficulty band)',
      formula:
        'targetCR = min(25, APL + {easy −1, average 0, challenging +1}); budget = the Total XP award for targetCR, with targetCR ≤ 0 floored to CR 1/2',
      inputs: ['APL', 'difficulty band'],
      edgeCases: [
        'APL 4 → easy CR 3 = 800 XP, average CR 4 = 1,200 XP, challenging CR 5 = 1,600 XP',
        'CRB floor: easy at APL 1 → CR 1/2 = 200 XP, not CR 0',
        'target CR clamps at 25 (the last row of the awards table)',
        'a target CR absent from the table yields 0 rather than a guessed award',
        'empty party → 0',
      ],
      exceptions: [
        'PF1e sizes a fight by ONE target CR\'s printed award, not by a summed per-character budget (5e, partyXpBudget at src/scene/encounterDraft.ts:62) nor a party-of-four base + per-character table (PF2e, :139).',
      ],
      source: `${CRB}: Gamemastering — Designing Encounters (Table: Encounter Design) and Table: Experience Point Awards`,
      status: 'verified',
      testRef:
        'src/__tests__/scene/encounterDraft.test.ts :: target CR = APL + difficulty offset, XP from the awards table',
      note: 'Shipped as pf1eEncounterXpBudget (src/scene/encounterDraft.ts:112) and wired to the runtime: encounterPartyBudget feeds the drafter, the encounter-spec validator (src/scene/encounterSpec.ts:88), and the scene Encounter panel (src/components/scene/useSceneEncounter.ts:240). It lives in src/scene/ rather than src/systems/pf1e/ because it is party-scoped GM math the layer boundary keeps out of the system module — the same placement pf2e.L10.encounter-budget documents.',
    },
    {
      id: 'pf1e.L10.encounter-spend',
      layer: 'L10',
      quantity: "One monster's cost against the encounter budget",
      formula: "the monster's own printed Total XP award (monster.experiencePoints)",
      inputs: ['monster XP award'],
      edgeCases: [
        'a 700-XP monster costs 700 whatever the party levels are',
        'the cost is party-independent, so the same monster prices identically in every PF1e draft',
      ],
      exceptions: [
        'PF1e (like 5e) spends the printed award; PF2e rescales by creature-level-minus-party-level (src/scene/encounterDraft.ts:165) and 3.5e prices off its derived EL-value scale (:230). PF1e takes the fall-through return at :332.',
      ],
      source: `${CRB}: Gamemastering — Table: Experience Point Awards`,
      status: 'verified',
      testRef:
        'src/__tests__/scene/encounterSpec.test.ts :: monsterEncounterCost uses XP for 5e/PF1e, party-relative for PF2e, EL-value for 3.5e',
      note: 'monsterEncounterCost is shared by the drafter and the validator so the spend math cannot diverge between drafting and validation.',
    },
    {
      id: 'pf1e.L10.budget-dispatch',
      layer: 'L10',
      quantity: 'PF1e routing of the shared party-budget dispatch',
      formula:
        "encounterPartyBudget('pf1e', partyLevels, difficulty) = pf1eEncounterXpBudget(partyLevels, difficulty)",
      inputs: ['systemId', 'party levels', 'difficulty band'],
      edgeCases: [
        "systemId 'pf1e' resolves to the CRB awards table, never the 5e per-character sum",
        'the drafter and the encounter-spec validator therefore read one identical budget',
      ],
      source: `${CRB}: Gamemastering — Designing Encounters`,
      status: 'verified',
      testRef:
        'src/__tests__/scene/encounterSpec.test.ts :: encounterPartyBudget dispatches to each system table',
      note: 'Pins the ROUTING, not a second formula — the arithmetic belongs to pf1e.L10.encounter-xp-budget and is not re-counted here. Registered on its own because the `case \'pf1e\'` arm (src/scene/encounterDraft.ts:300-301) is the single point where a refactor could silently send PF1e to partyXpBudget, and its mutation anchor perturbs the arm itself rather than the formula.',
    },
    {
      id: 'pf1e.L3.cmb',
      layer: 'L3',
      quantity: 'Combat Maneuver Bonus (CMB)',
      formula: 'BAB + Str mod + special size modifier',
      inputs: ['BAB', 'Str', 'size'],
      edgeCases: ['size modifier sign opposite of AC', 'large +1'],
      stacking: 'CMB size modifier differs from AC size modifier',
      source: `${CRB}: Combat — Combat Maneuver Bonus`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L3.cmd',
      layer: 'L3',
      quantity: 'Combat Maneuver Defense (CMD)',
      formula: '10 + BAB + Str mod + Dex mod + special size modifier',
      inputs: ['BAB', 'Str', 'Dex', 'size'],
      edgeCases: ['includes both Str and Dex'],
      source: `${CRB}: Combat — Combat Maneuver Defense`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L3.attack-roll',
      layer: 'L3',
      quantity: 'Attack roll modifier',
      formula: 'BAB + Str mod (melee)',
      inputs: ['BAB', 'Str'],
      edgeCases: ['melee vs ranged'],
      source: `${CRB}: Combat — Attack Roll`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L3.iterative-attacks',
      layer: 'L3',
      quantity: 'Iterative attacks',
      formula: 'extra attacks at BAB +6/+11/+16, each at -5 cumulative',
      inputs: ['BAB'],
      edgeCases: ['full attack only'],
      source: `${CRB}: Combat — Full Attack`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: d20 iterative attacks',
      note: 'Scene-wired: buildCharacterCombatant derives attacksPerRound/iterativePenaltyStep from BAB and the tactical executor applies the cumulative -5 (src/__tests__/rules/characterCombatant.test.ts :: legacy-d20 iterative attacks).',
    },
    {
      id: 'pf1e.L3.crit-confirmation',
      layer: 'L3',
      quantity: 'Critical hit confirmation and multiplier',
      formula:
        'a natural threat confirms on a second attack roll (same bonus) vs AC; confirmed damage = normal damage × the weapon crit multiplier (×2 default), extra dice not multiplied',
      inputs: ['threat', 'attack bonus', 'AC', 'critical multiplier'],
      edgeCases: ['unconfirmed threat = ordinary hit', 'extra dice (sneak attack) not multiplied'],
      source: `${CRB}: Combat — Critical Hits`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/attackResolution.test.ts :: a confirmed threat multiplies normal damage by the weapon multiplier',
      note: 'Scene-wired: resolveAttack rolls the confirmation d20 from the same seeded stream and applies d20CriticalDamage when critModel is "confirm-multiply" — selected for 3.5e/PF1e by sceneCombat (replacing the 5e double-dice default).',
    },
    {
      id: 'pf1e.L3.maneuver-types',
      layer: 'L3',
      quantity: 'Specific combat maneuvers (trip/disarm/grapple/etc.) vs CMD',
      formula: 'CMB check vs target CMD, per maneuver',
      inputs: ['CMB', 'target CMD'],
      edgeCases: ['per-maneuver modifiers'],
      source: `${CRB}: Combat — Combat Maneuvers`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: PF1e max ranks and maneuvers',
    },
    {
      id: 'pf1e.L4.skill-ranks',
      layer: 'L4',
      quantity: 'Skill check modifier (ranks + ability + class-skill +3)',
      formula: 'ability mod + ranks + (3 if class skill and ranks ≥ 1)',
      inputs: ['ability', 'ranks', 'class skill?'],
      edgeCases: ['+3 only when trained', 'max ranks = level'],
      source: `${CRB}: Skills`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L4.max-rank-cap',
      layer: 'L4',
      quantity: 'Max skill ranks per skill',
      formula:
        'max ranks in a skill = character level (class skills add +3 to the bonus, not the cap)',
      inputs: ['level'],
      edgeCases: ['cap is the character level, unlike 3.5e class/cross-class split'],
      source: `${CRB}: Skills — Ranks`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf1eDerivedQuantities.test.ts :: pf1e.L4.max-rank-cap',
    },
    {
      id: 'pf1e.L4.initiative',
      layer: 'L4',
      quantity: 'Initiative',
      formula: 'Dex mod',
      inputs: ['Dex'],
      edgeCases: ['Improved Initiative +4 via misc'],
      source: `${CRB}: Combat — Initiative`,
      status: 'verified',
      testRef: `${T} :: L2/L4 Pathfinder 1e check resolution`,
    },
    {
      id: 'pf1e.L5.vancian-slots',
      layer: 'L5',
      quantity: 'Spells per day (Vancian slot totals + bonus spells)',
      formula: 'class table by level + bonus spells from high ability',
      inputs: ['class levels', 'casting ability'],
      edgeCases: ['domain slots'],
      source: `${CRB}: Magic — Spells Per Day`,
      status: 'verified',
      testRef: 'src/__tests__/d20LegacyEngineMath.test.ts :: L5 d20 Vancian spell-slot totals',
    },
    {
      id: 'pf1e.L5.spell-save-dc',
      layer: 'L5',
      quantity: 'Spell save DC',
      formula: '10 + spell level + casting ability mod',
      inputs: ['spell level', 'casting ability'],
      edgeCases: ['per spell level'],
      source: `${CRB}: Magic — Saving Throws`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCasterMath.test.ts :: d20 legacy spell save DC',
    },
    {
      id: 'pf1e.L5.bonus-spells',
      layer: 'L5',
      quantity: 'Bonus spells per day from casting ability',
      formula: 'spell level ≥ 1 and mod ≥ level → floor((mod − level) / 4) + 1; else 0',
      inputs: ['casting ability mod', 'spell level'],
      edgeCases: ['no bonus cantrips', 'mod must reach the spell level'],
      source: `${CRB}: Magic — Bonus Spells`,
      status: 'verified',
      testRef: `${T} :: L5 d20 bonus spells from a high casting ability`,
    },
    {
      id: 'pf1e.L5.concentration-dc',
      layer: 'L5',
      quantity: 'Concentration check DCs (defensive / damage)',
      formula: 'defensive = 15 + 2 × spell level; while damaged = 10 + damage + spell level',
      inputs: ['spell level', 'damage taken'],
      edgeCases: ['check = d20 + caster level + casting mod'],
      source: `${CRB}: Magic — Concentration`,
      status: 'verified',
      testRef: `${T} :: L5/L8 Pathfinder 1e concentration, death, and feats`,
    },
    {
      id: 'pf1e.L8.hp-state-track',
      layer: 'L8',
      quantity: 'Disabled / dying / dead HP track (death at −Con)',
      formula: '> 0 healthy; = 0 disabled; below 0 dying; ≤ −Constitution dead',
      inputs: ['current HP', 'Constitution score'],
      edgeCases: ['death threshold scales with Con (unlike 3.5e −10)'],
      source: `${CRB}: Combat — Injury and Death`,
      status: 'verified',
      testRef: `${T} :: L5/L8 Pathfinder 1e concentration, death, and feats`,
    },
    {
      id: 'pf1e.L7.feats-from-level',
      layer: 'L7',
      quantity: 'Feats gained from level',
      formula: 'one at 1st level and every odd level thereafter = ceil(level / 2)',
      inputs: ['level'],
      edgeCases: ['racial/class bonus feats added separately'],
      source: `${CRB}: Character Advancement`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf1eDerivedQuantities.test.ts :: pf1e.L7.feats-from-level',
    },
    {
      id: 'pf1e.L6.carrying-capacity',
      layer: 'L6',
      quantity: 'Carrying capacity (light/medium/heavy thresholds)',
      formula:
        'heavy = Str table (x4 per +10 Str above 19); light = ⌊heavy/3⌋; medium = ⌊2·heavy/3⌋',
      inputs: ['Strength'],
      edgeCases: ['x4 doubling above Str 19', 'Str 0 = 0 lbs', '1/3 and 2/3 splits'],
      source: `${CRB}: Carrying Capacity`,
      status: 'verified',
      testRef: `${T} :: L6 d20-legacy carrying capacity`,
    },
    {
      id: 'pf1e.L6.encumbrance',
      layer: 'L6',
      quantity: 'Load category + encumbrance penalties (max Dex / check / run)',
      formula: 'category by thresholds; light: none/0/x4; medium: +3/-3/x4; heavy: +1/-6/x3',
      inputs: ['Strength', 'carried weight'],
      edgeCases: ['load → max Dex cap', 'run multiplier drops to x3 when heavy'],
      source: `${CRB}: Carrying Capacity — Encumbrance`,
      status: 'verified',
      testRef: `${T} :: L6 d20-legacy carrying capacity`,
    },
    {
      id: 'pf1e.L6.lift-drag',
      layer: 'L6',
      quantity: 'Lift/drag limits',
      formula: 'over head = max load; off ground = 2× max; push/drag = 5× max',
      inputs: ['Strength'],
      edgeCases: ['off-ground = stagger only'],
      source: `${CRB}: Carrying Capacity — Lifting and Dragging`,
      status: 'verified',
      testRef: `${T} :: L6 d20-legacy carrying capacity`,
    },
    {
      id: 'pf1e.L7.max-hp',
      layer: 'L7',
      quantity: 'Maximum hit points',
      formula: 'sum(max(1, hit-die roll + Con mod)) (+ favored-class HP), min 1',
      inputs: ['hit-die rolls', 'Con', 'favored class'],
      edgeCases: ['min 1 per die'],
      source: `${CRB}: Combat — Hit Points`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L7.favored-class-hp',
      layer: 'L7',
      quantity: 'Favored-class HP bonus',
      formula: '+1 HP per level taken with the HP favored-class choice',
      inputs: ['favored-class choices'],
      edgeCases: ['HP vs skill choice'],
      source: `${CRB}: Classes — Favored Class`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L7.favored-class-skill',
      layer: 'L7',
      quantity: 'Favored-class skill bonus',
      formula: '+1 skill point per level taken with the skill favored-class choice',
      inputs: ['favored-class choices'],
      edgeCases: ['accumulates per level'],
      source: `${CRB}: Classes — Favored Class`,
      status: 'verified',
      testRef: `${T} :: L3 Pathfinder 1e CMB / CMD and favored-class HP`,
    },
    {
      id: 'pf1e.L8.apply-damage',
      layer: 'L8',
      quantity: 'Damage application (temp HP, floor at 0)',
      formula: 'temp absorbs first; current floors at 0; healing capped at max',
      inputs: ['current/temp/max HP', 'damage'],
      edgeCases: ['temp absorb', 'overkill floors at 0'],
      source: `${CRB}: Combat — Injury and Death`,
      status: 'verified',
      testRef: `${T} :: L8 d20-legacy damage application`,
    },
    {
      id: 'pf1e.L9.skill-max-ranks',
      layer: 'L9',
      quantity: 'Max skill ranks per skill (≤ character level)',
      formula: "flag when a skill's ranks exceed the character level",
      inputs: ['skillRanks', 'level'],
      edgeCases: ['exactly at limit legal', 'over limit flagged'],
      source: `${CRB}: Skills — Ranks`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/pf1eLegality.test.ts :: pf1e flags skill ranks above the character level',
    },
    {
      id: 'pf1e.L9.class-level-sum',
      layer: 'L9',
      quantity: 'Class levels sum to character level',
      formula: 'flag when Σ classLevels.level exceeds character level',
      inputs: ['classLevels', 'level'],
      edgeCases: ['exactly at limit legal', 'over limit flagged'],
      source: `${CRB}: Character Advancement`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/pf1eLegality.test.ts :: pf1e flags class levels exceeding character level',
    },
    {
      id: 'pf1e.L4.skill-check-penalty',
      layer: 'L4',
      quantity: 'Skill check penalty (encumbrance load + equipped armor/shield) on physical skills',
      formula:
        'affected physical skill: encumbrance load check penalty (light 0 / medium −3 / heavy −6) + Σ equipped armor/shield armor-check-penalty; 0 for unaffected skills',
      inputs: ['Strength', 'carried weight', 'equipped armor/shield ACP', 'skillId'],
      edgeCases: [
        'unaffected skill → 0',
        'unequipped armor contributes 0',
        'load penalty and armor ACP stack',
        'PF1e affected-skill list (Acrobatics/Climb/Fly/Stealth/Swim/…) differs from 3.5e',
      ],
      stacking: 'the encumbrance (load) penalty and the equipped armor/shield check penalty add',
      source: `${CRB}: Carrying Capacity — Encumbrance; Armor — Armor Check Penalty`,
      status: 'verified',
      testRef: `${T} :: applies the check penalty (load) per the system affected-skill list`,
      note: 'Wired into Pf1eEngine.rollCheck for physical skills via d20SkillCheckPenalty (src/systems/shared/d20-helpers.ts); the armor-ACP composition is separately proven by "adds the equipped armor/shield check penalty to the load penalty" in the same suite.',
    },
    {
      id: 'pf1e.L8.condition-check-penalty',
      layer: 'L8',
      quantity: 'Fear/sickened flat penalty on saves and checks',
      formula:
        'fear family (shaken / frightened / panicked) contributes a single −2 (escalating states of one track, not stacked) + sickened −2 (separate, stacks) on every save, skill, and ability check',
      inputs: ['active condition ids'],
      edgeCases: [
        'fear states do not stack with each other (one −2 from the family)',
        'sickened stacks with fear',
        'attack-only riders (dazzled/entangled/prone/blinded/stunned) contribute 0 to the check penalty',
      ],
      stacking: 'fear track dedups to a single −2; sickened adds on top',
      source: `${CRB}: Conditions`,
      status: 'verified',
      testRef:
        'src/__tests__/rules/d20LegacyConditionFold.test.ts :: rollCheck modifier is baseline minus the check penalty for every condition/check',
      note: "Pf1eEngine.rollCheck folds fear/sickened through resolveCharacterEffects(...).bonus('check'), pinned byte-identical to the closed-form d20LegacyCheckPenalty for every catalog condition and combination.",
    },
  ],
};

export default pf1eComputeRegister;
