/**
 * Compute register (Denominator B) for Pathfinder 2e, cited against the Core
 * Rulebook (OGC). Engine: src/systems/pf2e/engine.ts, src/systems/pf2e/data-model.ts.
 */

import type { SystemComputeRegister } from './types';

const CRB = 'PF2e Core Rulebook (OGC)';
const T = 'src/__tests__/pf2eEngineMath.test.ts';

export const pf2eComputeRegister: SystemComputeRegister = {
  systemId: 'pf2e',
  srdVersion: CRB,
  entries: [
    {
      id: 'pf2e.L1.proficiency',
      layer: 'L1',
      quantity: 'Proficiency = level + tier (0 if untrained)',
      formula: 'untrained=0; trained=level+2; expert=level+4; master=level+6; legendary=level+8',
      inputs: ['level', 'proficiency tier'],
      edgeCases: ['untrained adds no level', 'each tier bonus', 'recomputed at current level'],
      source: `${CRB}: Proficiency`,
      status: 'verified',
      testRef: `${T} :: L1 proficiency (rank + level)`,
    },
    {
      id: 'pf2e.L1.ability-mod',
      layer: 'L1',
      quantity: 'Ability modifier',
      formula: 'floor((score - 10) / 2)',
      inputs: ['ability score'],
      edgeCases: ['negative scores'],
      source: `${CRB}: Ability Scores`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: shared ability modifier',
    },
    {
      id: 'pf2e.L2.ac',
      layer: 'L2',
      quantity: 'AC = 10 + Dex mod + armor proficiency + armor item bonus',
      formula: '10 + Dex mod (capped) + armor proficiency total + armor item bonus (+ shield)',
      inputs: ['Dex', 'armor proficiency', 'armor'],
      edgeCases: ['unarmored trained', 'Dex cap by armor', 'full AC incl. magic/feat bonuses'],
      note: 'Migrated to the declarative derivation layer (PF2E_DERIVED_QUANTITIES pf2e.L2.ac): a single display-bearing scalar whose compute reproduces the resolver fold (base + magic/feat AC bonuses) minus the worst Dex status penalty, so it equals data.armorClass. The unarmored case reduces to the anchored base `ac = 10 + dexMod + proficiencyBonus` (defense.ts), keeping the pf2e.L2.ac mutation live.',
      source: `${CRB}: Armor Class`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf2eDerivedQuantities.test.ts :: pf2e.L2.ac',
    },
    {
      id: 'pf2e.L2.ac-clumsy',
      layer: 'L2',
      quantity: 'Clumsy reduces effective Dex before AC',
      formula: 'effectiveDex = max(1, Dex score − clumsy × 2)',
      inputs: ['Dex', 'clumsy value'],
      edgeCases: ['clumsy lowers AC', 'floors at Dex 1'],
      stacking: 'condition value feeds back into the AC computation',
      source: `${CRB}: Conditions — Clumsy`,
      status: 'verified',
      testRef: `${T} :: L2 PF2e AC`,
    },
    {
      id: 'pf2e.L2.saves',
      layer: 'L2',
      quantity: 'Saving throw proficiency totals',
      formula: 'profTotal(level, save tier); ability mod added at roll time',
      inputs: ['level', 'save tier'],
      edgeCases: ['untrained save = 0', 'expert/master scaling'],
      source: `${CRB}: Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L1 proficiency (rank + level)`,
    },
    {
      id: 'pf2e.L2.perception',
      layer: 'L2',
      quantity: 'Perception total',
      formula: 'Wis mod + profTotal(level, perception tier)',
      inputs: ['Wis', 'level', 'perception tier'],
      edgeCases: ['its own proficiency, not a skill'],
      source: `${CRB}: Perception`,
      status: 'verified',
      testRef: `${T} :: L2/L8 PF2e perception and damage`,
    },
    {
      id: 'pf2e.L2.class-spell-dc',
      layer: 'L2',
      quantity: 'Class DC',
      formula: '10 + key ability modifier + profTotal(level, class DC tier)',
      inputs: ['level', 'key ability', 'class DC tier'],
      edgeCases: [
        'untrained class-DC proficiency contributes 0',
        'no key ability selected → +0',
        'tier scaling',
      ],
      source: `${CRB}: Class DC`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf2eDerivedQuantities.test.ts :: pf2e.L2.class-spell-dc',
    },
    {
      id: 'pf2e.L4.skill-check',
      layer: 'L4',
      quantity: 'Skill check modifier',
      formula: 'ability mod + profTotal(level, tier) − status penalties',
      inputs: ['ability', 'skill tier', 'conditions'],
      edgeCases: ['item/circumstance/status bonuses'],
      source: `${CRB}: Skills`,
      status: 'verified',
      testRef: `${T} :: L4 PF2e skill check`,
    },
    {
      id: 'pf2e.L7.hp',
      layer: 'L7',
      quantity: 'Maximum hit points',
      formula: 'ancestry HP + level × (class hit die + Con mod), min level',
      inputs: ['ancestry HP', 'level', 'class hit die', 'Con'],
      edgeCases: ['no class → d8 default', 'Con scaling per level'],
      source: `${CRB}: Hit Points`,
      status: 'verified',
      testRef: `${T} :: L7 PF2e HP`,
    },
    {
      id: 'pf2e.L8.degrees-of-success',
      layer: 'L8',
      quantity: 'Degrees of success',
      formula:
        'crit-success if total ≥ DC+10; success ≥ DC; crit-fail ≤ DC−10; nat 20 +1 step, nat 1 −1 step',
      inputs: ['total', 'DC', 'natural d20'],
      edgeCases: ['beat-by-10 boundary', 'nat 20 upgrade', 'nat 1 downgrade'],
      source: `${CRB}: Degrees of Success (p.445)`,
      status: 'verified',
      testRef: `${T} :: L8 degrees of success`,
    },
    {
      id: 'pf2e.L8.valued-conditions',
      layer: 'L8',
      quantity: 'Valued conditions as status penalties',
      formula:
        'frightened/sickened plus ability-mapped clumsy/enfeebled/drained/stupefied; highest status applies',
      inputs: ['conditions', 'ability'],
      edgeCases: ['only highest status penalty applies', 'ability-specific mapping'],
      source: `${CRB}: Conditions`,
      status: 'verified',
      testRef: `${T} :: L8 valued conditions`,
    },
    {
      id: 'pf2e.L8.apply-damage',
      layer: 'L8',
      quantity: 'Damage application (temp HP, floor at 0)',
      formula: 'temp absorbs first; current floors at 0',
      inputs: ['HP', 'damage'],
      edgeCases: ['temp absorb'],
      source: `${CRB}: Hit Points, Healing, and Dying`,
      status: 'verified',
      testRef: `${T} :: L2/L8 PF2e perception and damage`,
    },
    {
      id: 'pf2e.L5.spell-slots',
      layer: 'L5',
      quantity: 'Spell slots from class progression',
      formula: 'class spell-slot table at character level',
      inputs: ['class', 'level'],
      edgeCases: ['prepared vs spontaneous'],
      source: `${CRB}: Spellcasting`,
      status: 'verified',
      testRef: 'src/__tests__/utils/classSpellcasting.test.ts :: classSpellcasting helpers',
    },
    {
      id: 'pf2e.L5.focus-points',
      layer: 'L5',
      quantity: 'Focus points (max 3)',
      formula: 'class focus resource max formula',
      inputs: ['class resources'],
      edgeCases: ['cap at 3'],
      source: `${CRB}: Focus Spells`,
      status: 'verified',
      testRef: `${T} :: L5 PF2e focus points`,
    },
    {
      id: 'pf2e.L5.heightening',
      layer: 'L5',
      quantity: 'Auto-heighten spell rank',
      formula: 'auto-heighten rank = ceil(character level / 2)',
      inputs: ['character level'],
      edgeCases: ['level 1 → rank 1', 'half level rounded up'],
      source: `${CRB}: Heightening Spells`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf2eDerivedQuantities.test.ts :: pf2e.L5.heightening',
    },
    {
      id: 'pf2e.L3.map',
      layer: 'L3',
      quantity: 'Multiple attack penalty (MAP)',
      formula: '−5 / −10 (agile −4 / −8) on 2nd/3rd attacks',
      inputs: ['attack number', 'agile trait'],
      edgeCases: ['agile reduces penalty'],
      source: `${CRB}: Multiple Attack Penalty`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: PF2e MAP, striking, bulk, heightening',
    },
    {
      id: 'pf2e.L3.striking-runes',
      layer: 'L3',
      quantity: 'Striking rune weapon dice + specialization',
      formula: 'weapon dice × striking (2/3/4) + weapon specialization (+2/+3/+4 by prof)',
      inputs: ['striking rune', 'proficiency'],
      edgeCases: ['greater/major striking'],
      source: `${CRB}: Runes; Weapon Specialization`,
      status: 'verified',
      testRef: 'src/__tests__/derivedCombatMath.test.ts :: PF2e MAP, striking, bulk, heightening',
    },
    {
      id: 'pf2e.L6.bulk',
      layer: 'L6',
      quantity: 'Encumbered Bulk threshold',
      formula: 'Str mod + 5 Bulk',
      inputs: ['Str'],
      edgeCases: ['negative Str mod', 'encumbered threshold'],
      source: `${CRB}: Bulk`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf2eDerivedQuantities.test.ts :: pf2e.L6.bulk',
    },
    {
      id: 'pf2e.L6.bulk-max',
      layer: 'L6',
      quantity: 'Maximum Bulk',
      formula: 'Str mod + 10 Bulk',
      inputs: ['Str'],
      edgeCases: ['negative Str mod', 'max threshold'],
      source: `${CRB}: Bulk`,
      status: 'verified',
      testRef: 'src/__tests__/derivation/pf2eDerivedQuantities.test.ts :: pf2e.L6.bulk-max',
    },
    {
      id: 'pf2e.L3.attack-modifier',
      layer: 'L3',
      quantity: 'Strike / spell attack roll modifier',
      formula: 'ability mod + proficiency total (level + tier) + item bonus',
      inputs: ['ability mod', 'proficiency total', 'item bonus'],
      edgeCases: ['MAP applied separately', 'item/potency rune bonus'],
      source: `${CRB}: Attack Rolls; Spell Attacks`,
      status: 'verified',
      testRef: `${T} :: L3 PF2e attack rolls and shields`,
    },
    {
      id: 'pf2e.L8.shield-block',
      layer: 'L8',
      quantity: 'Shield Block damage reduction',
      formula: 'damage taken = max(0, damage − shield Hardness)',
      inputs: ['incoming damage', 'shield hardness'],
      edgeCases: ['fully blocked when hardness ≥ damage', 'shield takes remainder'],
      source: `${CRB}: Raise a Shield; Shield Block`,
      status: 'verified',
      testRef: `${T} :: L3 PF2e attack rolls and shields`,
    },
    {
      id: 'pf2e.L7.hero-points',
      layer: 'L7',
      quantity: 'Hero points (session start + cap)',
      formula: '1 at session start; maximum 3 held',
      inputs: ['—'],
      edgeCases: ['cap at 3', 'spend all to cheat death'],
      source: `${CRB}: Hero Points`,
      status: 'verified',
      testRef: `${T} :: L3 PF2e attack rolls and shields`,
    },
    {
      id: 'pf2e.L8.dying-on-knockout',
      layer: 'L8',
      quantity: 'Dying value gained on being knocked out',
      formula: '(critical hit ? 2 : 1) + current wounded value',
      inputs: ['from critical hit?', 'wounded value'],
      edgeCases: ['crit doubles base', 'wounded adds on each gain'],
      source: `${CRB}: Hit Points, Healing, and Dying — Dying`,
      status: 'verified',
      testRef: `${T} :: L8 PF2e dying and recovery`,
    },
    {
      id: 'pf2e.L8.dying-recovery',
      layer: 'L8',
      quantity: 'Recovery check DC + dying track + death threshold',
      formula:
        'recovery DC = 10 + dying; dying delta crit-success −2 / success −1 / failure +1 / crit-fail +2 (floor 0); dead at dying ≥ 4',
      inputs: ['dying value', 'recovery degree of success'],
      edgeCases: ['DC scales with dying', 'reaching 0 ends dying', 'death at dying max 4'],
      source: `${CRB}: Hit Points, Healing, and Dying — Dying/Recovery`,
      status: 'verified',
      testRef: `${T} :: L8 PF2e dying and recovery`,
    },
    {
      id: 'pf2e.L8.wounded-track',
      layer: 'L8',
      quantity: 'Wounded value after recovering from dying',
      formula: 'wounded += 1 each time the dying condition is removed',
      inputs: ['wounded value'],
      edgeCases: ['feeds back into the next dying gained'],
      source: `${CRB}: Hit Points, Healing, and Dying — Wounded`,
      status: 'verified',
      testRef: `${T} :: L8 PF2e dying and recovery`,
    },
    {
      id: 'pf2e.L10.creature-xp',
      layer: 'L10',
      quantity: 'Creature XP by level relative to party',
      formula: 'table −4..+4 → 10/15/20/30/40/60/80/120/160; below −4 = 0; clamps at +4',
      inputs: ['creature level − party level'],
      edgeCases: ['too-weak creatures count for 0', 'clamp above +4'],
      source: `${CRB}: Building Encounters — XP Awards`,
      status: 'verified',
      testRef: `${T} :: L10 PF2e encounter math`,
    },
    {
      id: 'pf2e.L10.encounter-budget',
      layer: 'L10',
      quantity: 'Encounter XP budget by threat and party size',
      formula:
        'budget = ⌊(partySize × 20) × {trivial .5, low .75, moderate 1, severe 1.5, extreme 2}⌋ (party of 4 = 40/60/80/120/160)',
      inputs: ['threat level', 'party size'],
      edgeCases: ['party-of-4 matches printed Table 10-1', '20 XP per character base'],
      source: `${CRB}: Building Encounters — Encounter Budget (Table 10-1)`,
      status: 'verified',
      testRef: `${T} :: L10 PF2e encounter math`,
    },
    {
      id: 'pf2e.L9.ability-score-cap',
      layer: 'L9',
      quantity: 'Ability score creation cap (≤ 18 at level 1)',
      formula: 'flag when a level-1 base ability score exceeds 18',
      inputs: ['baseAttributes', 'level'],
      edgeCases: ['exactly at limit legal', 'over limit flagged'],
      source: `${CRB}: Character Creation — Ability Scores`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/pf2eLegality.test.ts :: pf2e flags a level-1 ability score above 18',
    },
    {
      id: 'pf2e.L9.proficiency-budget',
      layer: 'L9',
      quantity: 'Proficiency total budget (≤ level + tier bonus)',
      formula:
        'flag when a proficiency total exceeds level + tier bonus (untrained budget is 0)',
      inputs: ['skillProficiencies', 'saveProficiencies', 'armorProficiencies', 'level'],
      edgeCases: ['exactly at limit legal', 'over limit flagged'],
      source: `${CRB}: Proficiency`,
      status: 'verified',
      testRef:
        'src/__tests__/legality/pf2eLegality.test.ts :: pf2e flags a proficiency total above the level-plus-tier budget',
    },
  ],
};

export default pf2eComputeRegister;
