/**
 * Compute register (Denominator B) for Pathfinder 2e, cited against the Core
 * Rulebook (OGC). Engine: src/systems/pf2e/engine.ts, src/systems/pf2e/data-model.ts.
 */

import type { SystemComputeRegister } from './types';

const CRB = 'PF2e Core Rulebook (OGC)';
const T = 'src/__tests__/pf2eEngineMath.test.ts';

export const pf2eComputeRegister: SystemComputeRegister = {
  systemId: 'pf2e',
  srdVersion: CRB,
  entries: [
    {
      id: 'pf2e.L1.proficiency',
      layer: 'L1',
      quantity: 'Proficiency = level + tier (0 if untrained)',
      formula: 'untrained=0; trained=level+2; expert=level+4; master=level+6; legendary=level+8',
      inputs: ['level', 'proficiency tier'],
      edgeCases: ['untrained adds no level', 'each tier bonus', 'recomputed at current level'],
      source: `${CRB}: Proficiency`,
      status: 'verified',
      testRef: `${T} :: L1 proficiency (rank + level)`,
    },
    {
      id: 'pf2e.L1.ability-mod',
      layer: 'L1',
      quantity: 'Ability modifier',
      formula: 'floor((score - 10) / 2)',
      inputs: ['ability score'],
      edgeCases: ['negative scores'],
      source: `${CRB}: Ability Scores`,
      status: 'implemented',
    },
    {
      id: 'pf2e.L2.ac',
      layer: 'L2',
      quantity: 'AC = 10 + Dex mod + armor proficiency + armor item bonus',
      formula: '10 + Dex mod (capped) + armor proficiency total + armor item bonus (+ shield)',
      inputs: ['Dex', 'armor proficiency', 'armor'],
      edgeCases: ['unarmored trained', 'Dex cap by armor'],
      source: `${CRB}: Armor Class`,
      status: 'verified',
      testRef: `${T} :: L2 PF2e AC`,
    },
    {
      id: 'pf2e.L2.ac-clumsy',
      layer: 'L2',
      quantity: 'Clumsy reduces effective Dex before AC',
      formula: 'effectiveDex = max(1, Dex score − clumsy × 2)',
      inputs: ['Dex', 'clumsy value'],
      edgeCases: ['clumsy lowers AC', 'floors at Dex 1'],
      stacking: 'condition value feeds back into the AC computation',
      source: `${CRB}: Conditions — Clumsy`,
      status: 'verified',
      testRef: `${T} :: L2 PF2e AC`,
    },
    {
      id: 'pf2e.L2.saves',
      layer: 'L2',
      quantity: 'Saving throw proficiency totals',
      formula: 'profTotal(level, save tier); ability mod added at roll time',
      inputs: ['level', 'save tier'],
      edgeCases: ['untrained save = 0', 'expert/master scaling'],
      source: `${CRB}: Saving Throws`,
      status: 'verified',
      testRef: `${T} :: L1 proficiency (rank + level)`,
    },
    {
      id: 'pf2e.L2.perception',
      layer: 'L2',
      quantity: 'Perception total',
      formula: 'Wis mod + profTotal(level, perception tier)',
      inputs: ['Wis', 'level', 'perception tier'],
      edgeCases: ['its own proficiency, not a skill'],
      source: `${CRB}: Perception`,
      status: 'verified',
      testRef: `${T} :: L2/L8 PF2e perception and damage`,
    },
    {
      id: 'pf2e.L2.class-spell-dc',
      layer: 'L2',
      quantity: 'Class DC / Spell DC',
      formula: '10 + ability mod + profTotal(level, tier)',
      inputs: ['level', 'key/spell ability', 'tier'],
      edgeCases: ['per tradition'],
      source: `${CRB}: Class DC; Spellcasting`,
      status: 'missing',
    },
    {
      id: 'pf2e.L4.skill-check',
      layer: 'L4',
      quantity: 'Skill check modifier',
      formula: 'ability mod + profTotal(level, tier) − status penalties',
      inputs: ['ability', 'skill tier', 'conditions'],
      edgeCases: ['item/circumstance/status bonuses'],
      source: `${CRB}: Skills`,
      status: 'implemented',
    },
    {
      id: 'pf2e.L7.hp',
      layer: 'L7',
      quantity: 'Maximum hit points',
      formula: 'ancestry HP + level × (class hit die + Con mod), min level',
      inputs: ['ancestry HP', 'level', 'class hit die', 'Con'],
      edgeCases: ['no class → d8 default', 'Con scaling per level'],
      source: `${CRB}: Hit Points`,
      status: 'verified',
      testRef: `${T} :: L7 PF2e HP`,
    },
    {
      id: 'pf2e.L8.degrees-of-success',
      layer: 'L8',
      quantity: 'Degrees of success',
      formula:
        'crit-success if total ≥ DC+10; success ≥ DC; crit-fail ≤ DC−10; nat 20 +1 step, nat 1 −1 step',
      inputs: ['total', 'DC', 'natural d20'],
      edgeCases: ['beat-by-10 boundary', 'nat 20 upgrade', 'nat 1 downgrade'],
      source: `${CRB}: Degrees of Success (p.445)`,
      status: 'verified',
      testRef: `${T} :: L8 degrees of success`,
    },
    {
      id: 'pf2e.L8.valued-conditions',
      layer: 'L8',
      quantity: 'Valued conditions as status penalties',
      formula:
        'frightened/sickened plus ability-mapped clumsy/enfeebled/drained/stupefied; highest status applies',
      inputs: ['conditions', 'ability'],
      edgeCases: ['only highest status penalty applies', 'ability-specific mapping'],
      source: `${CRB}: Conditions`,
      status: 'verified',
      testRef: `${T} :: L8 valued conditions`,
    },
    {
      id: 'pf2e.L8.apply-damage',
      layer: 'L8',
      quantity: 'Damage application (temp HP, floor at 0)',
      formula: 'temp absorbs first; current floors at 0',
      inputs: ['HP', 'damage'],
      edgeCases: ['temp absorb'],
      source: `${CRB}: Hit Points, Healing, and Dying`,
      status: 'verified',
      testRef: `${T} :: L2/L8 PF2e perception and damage`,
    },
    {
      id: 'pf2e.L5.spell-slots',
      layer: 'L5',
      quantity: 'Spell slots from class progression',
      formula: 'class spell-slot table at character level',
      inputs: ['class', 'level'],
      edgeCases: ['prepared vs spontaneous'],
      source: `${CRB}: Spellcasting`,
      status: 'implemented',
    },
    {
      id: 'pf2e.L5.focus-points',
      layer: 'L5',
      quantity: 'Focus points (max 3)',
      formula: 'class focus resource max formula',
      inputs: ['class resources'],
      edgeCases: ['cap at 3'],
      source: `${CRB}: Focus Spells`,
      status: 'implemented',
    },
    {
      id: 'pf2e.L5.heightening',
      layer: 'L5',
      quantity: 'Spell heightening',
      formula: 'auto-heighten to half level rounded up; manual heighten by rank',
      inputs: ['spell', 'rank'],
      edgeCases: ['cantrip auto-heighten'],
      source: `${CRB}: Heightening Spells`,
      status: 'missing',
    },
    {
      id: 'pf2e.L3.map',
      layer: 'L3',
      quantity: 'Multiple attack penalty (MAP)',
      formula: '−5 / −10 (agile −4 / −8) on 2nd/3rd attacks',
      inputs: ['attack number', 'agile trait'],
      edgeCases: ['agile reduces penalty'],
      source: `${CRB}: Multiple Attack Penalty`,
      status: 'missing',
    },
    {
      id: 'pf2e.L3.striking-runes',
      layer: 'L3',
      quantity: 'Striking rune weapon dice + specialization',
      formula: 'weapon dice × striking (2/3/4) + weapon specialization (+2/+3/+4 by prof)',
      inputs: ['striking rune', 'proficiency'],
      edgeCases: ['greater/major striking'],
      source: `${CRB}: Runes; Weapon Specialization`,
      status: 'missing',
    },
    {
      id: 'pf2e.L6.bulk',
      layer: 'L6',
      quantity: 'Bulk / encumbrance',
      formula: 'encumbered at Str mod + 5 Bulk; max at Str mod + 10',
      inputs: ['Str', 'carried bulk'],
      edgeCases: ['encumbered threshold'],
      source: `${CRB}: Bulk`,
      status: 'missing',
    },
  ],
};

export default pf2eComputeRegister;
