// GENERATED by scripts/encode-5e-spells.mjs from 5e-bits/5e-database
// (SRD 5.1 spells, OGL 1.0a — see docs/srd-sources.md). Hand-written spells
// live in the non-srd-prefixed files and always win on name match;
// regenerate with: node scripts/encode-5e-spells.mjs

import { Spell } from '../../../../types/magic/spells';

export const srdLevel1Spells: Spell[] = [
  {
    id: 'find-familiar',
    name: 'Find Familiar',
    system: 'dnd-5e-2014',
    source: 'SRD 5.1',
    level: 1,
    school: 'conjuration',
    castingTime: {
      type: 'hour',
      hours: 1,
    },
    range: {
      type: 'ranged',
      feet: 10,
    },
    components: {
      verbal: true,
      somatic: true,
      material: true,
      materialDescription:
        '10gp worth of charcoal, incense, and herbs that must be consumed by fire in a brass brazier',
    },
    duration: {
      type: 'instant',
    },
    concentration: false,
    ritual: true,
    description:
      "You gain the service of a familiar, a spirit that takes an animal form you choose: bat, cat, crab, frog (toad), hawk, lizard, octopus, owl, poisonous snake, fish (quipper), rat, raven, sea horse, spider, or weasel. Appearing in an unoccupied space within range, the familiar has the statistics of the chosen form, though it is a celestial, fey, or fiend (your choice) instead of a beast.\n\nYour familiar acts independently of you, but it always obeys your commands. In combat, it rolls its own initiative and acts on its own turn. A familiar can't attack, but it can take other actions as normal.\n\nWhen the familiar drops to 0 hit points, it disappears, leaving behind no physical form. It reappears after you cast this spell again.\n\nWhile your familiar is within 100 feet of you, you can communicate with it telepathically. Additionally, as an action, you can see through your familiar's eyes and hear what it hears until the start of your next turn, gaining the benefits of any special senses that the familiar has. During this time, you are deaf and blind with regard to your own senses.\n\nAs an action, you can temporarily dismiss your familiar. It disappears into a pocket dimension where it awaits your summons. Alternatively, you can dismiss it forever. As an action while it is temporarily dismissed, you can cause it to reappear in any unoccupied space within 30 feet of you.\n\nYou can't have more than one familiar at a time. If you cast this spell while you already have a familiar, you instead cause it to adopt a new form. Choose one of the forms from the above list. Your familiar transforms into the chosen creature.\n\nFinally, when you cast a spell with a range of touch, your familiar can deliver the spell as if it had cast the spell. Your familiar must be within 100 feet of you, and it must use its reaction to deliver the spell when you cast it. If the spell requires an attack roll, you use your action modifier for the roll.",
    classes: ['wizard'],
  },
  {
    id: 'hellish-rebuke',
    name: 'Hellish Rebuke',
    system: 'dnd-5e-2014',
    source: 'SRD 5.1',
    level: 1,
    school: 'evocation',
    castingTime: {
      type: 'reaction',
      amount: 1,
    },
    range: {
      type: 'ranged',
      feet: 60,
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    duration: {
      type: 'instant',
    },
    savingThrow: {
      attribute: 'dex',
      success: 'half',
    },
    damage: {
      base: {
        count: 2,
        die: 'd10',
        notation: '2d10',
      },
      type: 'fire',
    },
    concentration: false,
    ritual: false,
    description:
      'You point your finger, and the creature that damaged you is momentarily surrounded by hellish flames. The creature must make a dexterity saving throw. It takes 2d10 fire damage on a failed save, or half as much damage on a successful one.',
    atHigherLevels:
      'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d10 for each slot level above 1st.',
    classes: ['warlock'],
  },
  {
    id: 'illusory-script',
    name: 'Illusory Script',
    system: 'dnd-5e-2014',
    source: 'SRD 5.1',
    level: 1,
    school: 'illusion',
    castingTime: {
      type: 'minutes',
      minutes: 1,
    },
    range: {
      type: 'touch',
    },
    components: {
      verbal: false,
      somatic: true,
      material: true,
      materialDescription: 'A lead-based ink worth at least 10gp, which this spell consumes',
    },
    duration: {
      type: 'special',
      description: '10 days',
    },
    concentration: false,
    ritual: true,
    description:
      'You write on parchment, paper, or some other suitable writing material and imbue it with a potent illusion that lasts for the duration.\n\nTo you and any creatures you designate when you cast the spell, the writing appears normal, written in your hand, and conveys whatever meaning you intended when you wrote the text. To all others, the writing appears as if it were written in an unknown or magical script that is unintelligible. Alternatively, you can cause the writing to appear to be an entirely different message, written in a different hand and language, though the language must be one you know.\n\nShould the spell be dispelled, the original script and the illusion both disappear.\n\nA creature with truesight can read the hidden message.',
    classes: ['bard', 'warlock', 'wizard'],
  },
];
