// GENERATED by scripts/encode-2024-spells.mjs from
// downfallx/dnd-5e-srd-markdown spells.md (SRD 5.2.1, CC-BY-4.0 — the same
// document the srd:coverage 2024 denominator parses). Hand-written spells
// always win on name match; regenerate with:
// node scripts/encode-2024-spells.mjs

import { Spell } from '../../../../types/magic/spells';

export const srd2024Level5Spells: Spell[] = [
  {
    id: 'antilife-shell',
    name: 'Antilife Shell',
    system: 'dnd-5e-2024',
    source: 'SRD 5.2',
    level: 5,
    school: 'abjuration',
    castingTime: {
      type: 'action',
      amount: 1,
    },
    range: {
      type: 'self',
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    duration: {
      type: 'concentration',
      maxDuration: 'concentration, up to 1 hour',
    },
    concentration: true,
    ritual: false,
    description:
      'An aura extends from you in a 10-foot Emanation for the duration. The aura prevents creatures other than Constructs and Undead from passing or reaching through it. An affected creature can cast spells or make attacks with Ranged or Reach weapons through the barrier.\n\nIf you move so that an affected creature is forced to pass through the barrier, the spell ends.',
    classes: ['druid'],
  },
  {
    id: 'arcane-hand',
    name: 'Arcane Hand',
    system: 'dnd-5e-2024',
    source: 'SRD 5.2',
    level: 5,
    school: 'evocation',
    castingTime: {
      type: 'action',
      amount: 1,
    },
    range: {
      type: 'ranged',
      feet: 120,
    },
    components: {
      verbal: true,
      somatic: true,
      material: true,
      materialDescription: 'an eggshell and a glove',
    },
    duration: {
      type: 'concentration',
      maxDuration: 'concentration, up to 1 minute',
    },
    concentration: true,
    ritual: false,
    description:
      "You create a Large hand of shimmering magical energy in an unoccupied space that you can see within range. The hand lasts for the duration, and it moves at your command, mimicking the movements of your own hand.\n\nThe hand is an object that has AC 20 and Hit Points equal to your Hit Point maximum. If it drops to 0 Hit Points, the spell ends. The hand doesn't occupy its space.\n\nWhen you cast the spell and as a Bonus Action on your later turns, you can move the hand up to 60 feet and then cause one of the following effects:\n\n**Clenched Fist.** The hand strikes a target within 5 feet of it. Make a melee spell attack. On a hit, the target takes 5d8 Force damage.\n\n**Forceful Hand.** The hand attempts to push a Huge or smaller creature within 5 feet of it. The target must succeed on a Strength saving throw, or the hand pushes the target up to 5 feet plus a number of feet equal to five times your spellcasting ability modifier. The hand moves with the target, remaining within 5 feet of it.\n\n**Grasping Hand.** The hand attempts to grapple a Huge or smaller creature within 5 feet of it. The target must succeed on a Dexterity saving throw, or the target has the Grappled condition, with an escape DC equal to your spell save DC. While the hand grapples the target, you can take a Bonus Action to cause the hand to crush it, dealing Bludgeoning damage to the target equal to 4d6 plus your spellcasting ability modifier.\n\n**Interposing Hand.** The hand grants you Half Cover against attacks and other effects that originate from its space or that pass through it. In addition, its space counts as Difficult Terrain for your enemies.",
    atHigherLevels:
      'The damage of the Clenched Fist increases by 2d8 and the damage of the Grasping Hand increases by 2d6 for each spell slot level above 5.',
    classes: ['sorcerer', 'wizard'],
  },
  {
    id: 'commune-with-nature',
    name: 'Commune with Nature',
    system: 'dnd-5e-2024',
    source: 'SRD 5.2',
    level: 5,
    school: 'divination',
    castingTime: {
      type: 'minutes',
      minutes: 1,
    },
    range: {
      type: 'self',
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    duration: {
      type: 'instant',
    },
    concentration: false,
    ritual: false,
    description:
      "You commune with nature spirits and gain knowledge of the surrounding area. In the outdoors, the spell gives you knowledge of the area within 3 miles of you. In caves and other natural underground settings, the radius is limited to 300 feet. The spell\ndoesn't function where nature has been replaced by construction, such as in castles and settlements.\n\nChoose three of the following facts; you learn those facts as they pertain to the spell's area:\n\n• Locations of settlements\n• Locations of portals to other planes of existence\n• Location of one Challenge Rating 10+ creature (GM's choice) that is a Celestial, an Elemental, a Fey, a Fiend, or an Undead\n• The most prevalent kind of plant, mineral, or Beast (you choose which to learn)\n• Locations of bodies of water\n\nFor example, you could determine the location of a powerful monster in the area, the locations of bodies of water, and the locations of any towns.",
    classes: ['druid', 'ranger'],
  },
  {
    id: 'modify-memory',
    name: 'Modify Memory',
    system: 'dnd-5e-2024',
    source: 'SRD 5.2',
    level: 5,
    school: 'enchantment',
    castingTime: {
      type: 'action',
      amount: 1,
    },
    range: {
      type: 'ranged',
      feet: 30,
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    duration: {
      type: 'concentration',
      maxDuration: 'concentration, up to 1 minute',
    },
    concentration: true,
    ritual: false,
    description:
      "You attempt to reshape another creature's memories. One creature that you can see within range makes a Wisdom saving throw. If you are fighting the creature, it has Advantage on the save. On a failed save, the target has the Charmed condition for the duration. While Charmed in this way, the target also has the Incapacitated condition and is unaware of its surroundings, though it can hear you. If it takes any damage or is targeted by another spell, this spell ends, and no memories are modified.\n\nWhile this charm lasts, you can affect the target's memory of an event that it experienced within the last 24 hours and that lasted no more than 10 minutes. You can permanently eliminate all memory of the event, allow the target to recall the event with perfect clarity, change its memory of the event's details, or create a memory of some other event.\n\nYou must speak to the target to describe how its memories are affected, and it must be able to understand your language for the modified memories to take root. Its mind fills in any gaps in the details of your description. If the spell ends before you finish describing the modified memories, the creature's memory isn't altered. Otherwise, the modified memories take hold when the spell ends.\n\nA modified memory doesn't necessarily affect how a creature behaves, particularly if the memory contradicts the creature's natural inclinations, alignment, or beliefs. An illogical modified memory, such as a false memory of how much the creature enjoyed swimming in acid, is dismissed as a bad dream. The GM might deem a modified memory too nonsensical to affect a creature.\n\nA _Remove Curse_ or _Greater Restoration_ spell cast on the target restores the creature's true memory.",
    atHigherLevels:
      "You can alter the target's memories of an event that took place up to 7 days ago (level 6 spell slot), 30 days ago (level 7 spell slot), 365 days ago (level 8 spell slot), or any time in the creature's past (level 9 spell slot).",
    classes: ['bard', 'wizard'],
  },
  {
    id: 'reincarnate',
    name: 'Reincarnate',
    system: 'dnd-5e-2024',
    source: 'SRD 5.2',
    level: 5,
    school: 'necromancy',
    castingTime: {
      type: 'hour',
      hours: 1,
    },
    range: {
      type: 'touch',
    },
    components: {
      verbal: true,
      somatic: true,
      material: true,
      materialDescription: 'rare oils worth 1,000+ GP, which the spell consumes',
    },
    duration: {
      type: 'instant',
    },
    concentration: false,
    ritual: false,
    description:
      "You touch a dead Humanoid or a piece of one. If the creature has been dead no longer than 10 days, the spell forms a new body for it and calls the soul to enter that body. Roll 1d10 and consult the table below to determine the body's species, or the GM chooses another playable species.\n\n<table>\n  <thead>\n    <tr>\n      <th>1d10</th>\n      <th>Species</th>\n      <th>1d10</th>\n      <th>Species</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>1</td>\n      <td>Roll again.</td>\n      <td>6</td>\n      <td>Goliath</td>\n    </tr>\n    <tr>\n      <td>2</td>\n      <td>Dragonborn</td>\n      <td>7</td>\n      <td>Halfling</td>\n    </tr>\n    <tr>\n      <td>3</td>\n      <td>Dwarf</td>\n      <td>8</td>\n      <td>Human</td>\n    </tr>\n    <tr>\n      <td>4</td>\n      <td>Elf</td>\n      <td>9</td>\n      <td>Orc</td>\n    </tr>\n    <tr>\n      <td>5</td>\n      <td>Gnome</td>\n      <td>10</td>\n      <td>Tiefling</td>\n    </tr>\n  </tbody>\n</table>\n\nThe reincarnated creature makes any choices that a species' description offers, and the creature recalls its former life. It retains the capabilities it had in its original form, except it loses the traits of its previous species and gains the traits of its new one.",
    classes: ['druid'],
  },
  {
    id: 'summon-dragon',
    name: 'Summon Dragon',
    system: 'dnd-5e-2024',
    source: 'SRD 5.2',
    level: 5,
    school: 'conjuration',
    castingTime: {
      type: 'action',
      amount: 1,
    },
    range: {
      type: 'ranged',
      feet: 60,
    },
    components: {
      verbal: true,
      somatic: true,
      material: true,
      materialDescription: 'an object with the image of a dragon engraved on it worth 500+ GP',
    },
    duration: {
      type: 'concentration',
      maxDuration: 'concentration, up to 1 hour',
    },
    concentration: true,
    ritual: false,
    description:
      "You call forth a Dragon spirit. It manifests in an unoccupied space that you can see within range and uses the Draconic Spirit stat block. The creature disappears when it drops to 0 Hit Points or when the spell ends.\n\nThe creature is an ally to you and your allies. In combat, the creature shares your Initiative count, but it takes its turn immediately after yours. It obeys your verbal commands (no action required by you). If you don't issue any, it takes the Dodge action and uses its movement to avoid danger.",
    atHigherLevels:
      "Use the spell slot's level for the spell's level in the stat block.\n\n## Draconic Spirit\n\n_Large Dragon, Neutral_\n\n**AC** 14 + the spell's level\n**HP** 50 + 10 for each spell level above 5\n**Speed** 30 ft., Fly 60 ft., Swim 30 ft.\n\n<table>\n  <tbody>\n    <tr>\n      <td>MOD</td>\n      <td>SAVE</td>\n      <td></td>\n      <td>MOD</td>\n      <td>SAVE</td>\n      <td></td>\n      <td>MOD</td>\n      <td>SAVE</td>\n      <td colspan=\"4\"></td>\n    </tr>\n    <tr>\n      <td>STR</td>\n      <td>19</td>\n      <td>+4</td>\n      <td>+4</td>\n      <td>DEX</td>\n      <td>14</td>\n      <td>+2</td>\n      <td>+2</td>\n      <td>CON</td>\n      <td>17</td>\n      <td>+3</td>\n      <td>+3</td>\n    </tr>\n    <tr>\n      <td>INT</td>\n      <td>10</td>\n      <td>+0</td>\n      <td>+0</td>\n      <td>WIS</td>\n      <td>14</td>\n      <td>+2</td>\n      <td>+2</td>\n      <td>CHA</td>\n      <td>14</td>\n      <td>+2</td>\n      <td>+2</td>\n    </tr>\n  </tbody>\n</table>\n\n**Resistances** Acid, Cold, Fire, Lightning, Poison\n**Immunities** Charmed, Frightened, Poisoned\n**Senses** Blindsight 30 ft., Darkvision 60 ft.; Passive Perception 12\n**Languages** Draconic, understands the languages you know\n**CR** None (XP 0; PB equals your Proficiency Bonus)",
    classes: ['wizard'],
  },
  {
    id: 'telepathic-bond',
    name: 'Telepathic Bond',
    system: 'dnd-5e-2024',
    source: 'SRD 5.2',
    level: 5,
    school: 'divination',
    castingTime: {
      type: 'action',
      amount: 1,
    },
    range: {
      type: 'ranged',
      feet: 30,
    },
    components: {
      verbal: true,
      somatic: true,
      material: true,
      materialDescription: 'two eggs',
    },
    duration: {
      type: 'hours',
      hours: 1,
    },
    concentration: false,
    ritual: false,
    description:
      "You forge a telepathic link among up to eight willing creatures of your choice within range, psychically linking each creature to all the others for the duration. Creatures that can't communicate in any languages aren't affected by this spell.\n\nUntil the spell ends, the targets can communicate telepathically through the bond whether or not they share a language. The communication is possible over any distance, though it can't extend to other planes of existence.",
    classes: ['bard', 'wizard'],
  },
  {
    id: 'tree-stride',
    name: 'Tree Stride',
    system: 'dnd-5e-2024',
    source: 'SRD 5.2',
    level: 5,
    school: 'conjuration',
    castingTime: {
      type: 'action',
      amount: 1,
    },
    range: {
      type: 'self',
    },
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    duration: {
      type: 'concentration',
      maxDuration: 'concentration, up to 1 minute',
    },
    concentration: true,
    ritual: false,
    description:
      "You gain the ability to enter a tree and move from inside it to inside another tree of the same kind within 500 feet. Both trees must be living and at least the same size as you. You must use 5 feet of movement to enter a tree. You instantly know the location of all other trees of the same kind within 500 feet and, as part of the move used to enter the tree, can either pass into one of those trees or step out of the tree you're in. You appear in a spot of your choice within 5 feet of the destination tree, using another 5 feet of movement. If you have no movement left, you appear within 5 feet of the tree you entered.\n\nYou can use this transportation ability only once on each of your turns. You must end each turn outside a tree.",
    classes: ['druid', 'ranger'],
  },
];
