// Pathfinder 2e Feats - Master Index (Core Rulebook Only)
// Fabricated magic-feats.ts removed (135 Array.from placeholders)

export * from './general';
export * from './skill';
export * from './ancestry';
export * from './class';
// Genuine CRB feats from Pf2eTools (source:"CRB"), filling the catalog beyond the
// hand-written core. Generated by scripts/encode-pf2e-feats.mjs; the hand-written
// feats above win on name match.
export * from './generated';
